Repository prebid/Prebid.js, pull requests merged in 2018-06, with the labels that each got.

#2610 AdKernel adapter GDPR support
  modules/adkernelBidAdapter.js
  test/spec/modules/adkernelBidAdapter_spec.js
Labels: LGTM, needs docs

#2671 Adding new Bidder Andbeyond
  modules/andbeyondBidAdapter.js
  modules/andbeyondBidAdapter.md
  test/spec/modules/andbeyondBidAdapter_spec.js
Labels: LGTM

#2667 convert appnexus bid.params.keywords to style needed for pbs
  modules/appnexusBidAdapter.js
  modules/prebidServerBidAdapter.js
  src/utils.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: needs review

#2419 AdSpirit Bid Adapter
  integrationExamples/gpt/hello_world.html
  integrationExamples/gpt/pbjs_ucfunnel_gpt.html
  modules/adspiritBidAdapter.js
  modules/adspiritBidAdapter.md
  test/spec/modules/adspiritBidAdapter_spec.js
Labels: needs update

#2592 Consistent targeting set
  src/targeting.js
  test/spec/unit/core/targeting_spec.js
  test/spec/unit/pbjs_api_spec.js
Labels: needs 2nd review

#2611 Passing GDPR flag without consent string for AOL adapter.
  modules/aolBidAdapter.js
  test/spec/modules/aolBidAdapter_spec.js
Labels: needs update

#2686 Sonobi - suppress user sync error
  modules/sonobiBidAdapter.js
  test/spec/modules/sonobiBidAdapter_spec.js
Labels: needs review

#2681 Native images bug fixed
  modules/quantumBidAdapter.js
Labels: LGTM

#2688 Refactoring Prebid Analytics by Roxot
  modules/roxotAnalyticsAdapter.js
  test/spec/modules/roxotAnalyticsAdapter_spec.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
Labels: needs review

#2673 Fix getTopWindowUrl
  src/utils.js
  test/spec/modules/audienceNetworkBidAdapter_spec.js
Labels: LGTM, needs 2nd review, needs review

#2606 Playground XYZ - new adapter
  modules/playgroundxyzBidAdapter.js
  modules/playgroundxyzBidAdapter.md
  package-lock.json
  test/spec/modules/playgroundxyzBidAdapter_spec.js
Labels: LGTM

#2665 Rubicon Bid Adapter - ordered auction query params
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: adapter support

#2694 New optional bid parameter
  modules/nanointeractiveBidAdapter.js
  modules/nanointeractiveBidAdapter.md
  test/spec/modules/nanointeractiveBidAdapter_spec.js
Labels: needs review

#2692 Adform adapter supports string type sizes
  modules/adformBidAdapter.js
  test/spec/modules/adformBidAdapter_spec.js
Labels: needs update

#2696 MANTIS bidder: support tracking viewability of ad
  modules/mantisBidAdapter.js
Labels: needs review

#2536 Update to XHB adapter
  modules/xhbBidAdapter.js
  modules/xhbBidAdapter.md
  test/spec/modules/xhbBidAdapter_spec.js
Labels: adapter support, needs update

#2479 Rubicon Adapter - SRA support legacy
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: adapter support, legacy

#2684 Support send multi request
  modules/gammaBidAdapter.js
  test/spec/modules/gammaBidAdapter_spec.js
Labels: LGTM

#2693 Just Premium: add format parameter (issue #2691)
  modules/justpremiumBidAdapter.js
  test/spec/modules/justpremiumBidAdapter_spec.js
Labels: LGTM

#2734 Fix GDPR consent required for Beachfront adapter
  modules/beachfrontBidAdapter.js
  test/spec/modules/beachfrontBidAdapter_spec.js
Labels: LGTM

#2699 Playground xyz - GDPR integration.
  modules/playgroundxyzBidAdapter.js
  modules/playgroundxyzBidAdapter.md
  test/spec/modules/playgroundxyzBidAdapter_spec.js
Labels: LGTM, needs docs

#2522 Add GDPR parameters in ad request
  modules/freewheelSSPBidAdapter.js
  test/spec/modules/freewheelSSPBidAdapter_spec.js
Labels: needs review, needs update

#2700 QuantumBidAdapter usersync bugfix
  modules/quantumBidAdapter.js
Labels: LGTM

#2499 updated logic for userSync - new field filterSettings
  src/adapters/bidderFactory.js
  src/userSync.js
  test/spec/userSync_spec.js
Labels: needs review

#2562 Allow user to override which gpt slots should be targeted at invocation
  src/prebid.js
  src/targeting.js
Labels: LGTM, needs 2nd review, needs docs

#2739 Gumgum Unit test fix
  modules/gumgumBidAdapter.js
Labels: LGTM

#2711 update some unit tests to clean-up consentManagement hooks
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/pubCommonId_spec.js
  test/spec/modules/smartadserverBidAdapter_spec.js
Labels: needs 2nd review

#2723 update consentManagement error logic/handling
  modules/consentManagement.js
Labels: needs 2nd review

#2724 enhance logWarn message
  src/utils.js
Labels: needs 2nd review

#2687 Debugging
  src/debugging.js
  src/hook.js
  src/prebid.js
  test/spec/debugging_spec.js
Labels: LGTM

#2743 Max origin concurrent auctions
  src/adaptermanager.js
  src/ajax.js
  src/auction.js
  test/spec/unit/pbjs_api_spec.js
Labels: needs docs

#2733 Add GDPR support for Quantcast adapter
  modules/quantcastBidAdapter.js
  modules/quantcastBidAdapter.md
  test/spec/modules/quantcastBidAdapter_spec.js
Labels: LGTM

#2729 ixBidAdapter.js: allow siteId param to be number
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: LGTM

#2657 Audience Network: add debug params to bid requests
  modules/audienceNetworkBidAdapter.js
  test/spec/modules/audienceNetworkBidAdapter_spec.js
Labels: LGTM

#2749 Update RELEASE_SCHEDULE to cover beta-vs-GA
  RELEASE_SCHEDULE.md
Labels: needs 2nd review

#2710 Weborama header bidding adapter 1.0.0
  integrationExamples/gpt/pbjs_example_gpt.html
  modules/weboramaBidAdapter.js
  modules/weboramaBidAdapter.md
  test/spec/modules/weboramaBidAdapter_spec.js
Labels: needs review

#2715 move logic to check if CMP is not found
  modules/consentManagement.js
  test/spec/modules/consentManagement_spec.js
Labels: LGTM

#2682 Add crs parameter to eplanning adapter
  modules/eplanningBidAdapter.js
  test/spec/modules/eplanningBidAdapter_spec.js
Labels: needs review

#2741 googleAnalyticsAdapter timeout bidder name
  modules/googleAnalyticsAdapter.js
Labels: needs 2nd review, needs review

#2738 Feature/normalize size
  src/adaptermanager.js
  test/spec/unit/core/adapterManager_spec.js
Labels: LGTM, needs 2nd review

#2762 Sharethrough - handle iframe bid param, safeframe support
  modules/sharethroughBidAdapter.js
  modules/sharethroughBidAdapter.md
  test/spec/modules/sharethroughBidAdapter_spec.js
Labels: LGTM

#2728 Integration of Realvu analytics in Somo adapter
  modules/somoaudienceBidAdapter.js
Labels: LGTM

#2758 Refactored URL query parameter passthrough for additional values, cha…
  modules/lkqdBidAdapter.js
  modules/lkqdBidAdapter.md
  test/spec/modules/lkqdBidAdapter_spec.js
Labels: LGTM

#2761 Add user sync to Beachfront adapter
  modules/beachfrontBidAdapter.js
  modules/beachfrontBidAdapter.md
  test/spec/modules/beachfrontBidAdapter_spec.js
Labels: LGTM

#2755 Add gdpr and targeting support for Yieldlab adapter
  modules/yieldlabBidAdapter.js
  modules/yieldlabBidAdapter.md
  test/spec/modules/yieldlabBidAdapter_spec.js
Labels: LGTM

#2753 sending information about prebid and adapter versions in request
  modules/justpremiumBidAdapter.js
  test/spec/modules/justpremiumBidAdapter_spec.js
Labels: LGTM

#2664 Kargo Adapter: Add request timestamp
  modules/kargoBidAdapter.js
  test/spec/modules/kargoBidAdapter_spec.js
Labels: LGTM

#2695 check if bidder exists before making request object
  src/adaptermanager.js
  test/spec/unit/core/adapterManager_spec.js
Labels: LGTM

#2683 allow outstream video, remove parsePosition method, simplify code
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: needs review

#2767 adding logInfo message to note the consentManagement module was activated
  modules/consentManagement.js
  test/spec/modules/consentManagement_spec.js
Labels: needs review

#2766 Bugfix: Set gdpr flag to 0 for prebidServerBidAdapter
  modules/prebidServerBidAdapter.js
Labels: needs 2nd review
