Repository prebid/Prebid.js, pull requests merged in 2018-09, with the labels that each got.

#2855 YieldNexus Bid Adapter v1
  modules/yieldNexusBidAdapter.js
  modules/yieldNexusBidAdapter.md
  test/spec/modules/yieldNexusBidAdapter_spec.js
Labels: needs update

#2930 upgrade to gulp 4
  .circleci/config.yml
  README.md
  gulpfile.js
  package-lock.json
  package.json
Labels: LGTM, needs 2nd review, needs review, on hold

#3031 Update gumgumBidAdapter.md
  modules/gumgumBidAdapter.md
Labels: needs update

#2636 Ability to statically pass consentData
  modules/consentManagement.js
  test/spec/modules/consentManagement_spec.js
Labels: needs update

#3048 Update dgadsBidAdapter
  modules/dgadsBidAdapter.js
  test/spec/modules/dgadsBidAdapter_spec.js
Labels: LGTM

#3062 Fix #3059 by returning both hb_deal and hb_deal_${bidder_code}
  src/targeting.js
  test/spec/unit/core/targeting_spec.js
Labels: LGTM

#3066 Fix the secure creative resizing
  src/secureCreatives.js
Labels: LGTM, needs 2nd review

#3068 AOL adapter - add defaults for currency and creative ID until fix issued server-side
  modules/aolBidAdapter.js
Labels: needs review

#3024 Fix for early auction close with video + done cb cleanup
  modules/prebidServerBidAdapter/index.js
  src/adaptermanager.js
  src/adapters/bidderFactory.js
  src/auction.js
  src/utils.js
  src/video.js
  test/spec/auctionmanager_spec.js
Labels: needs unit tests, needs update

#3067 Add referer detection module
  modules/appnexusBidAdapter.js
  src/adaptermanager.js
  src/refererDetection.js
  test/spec/modules/appnexusBidAdapter_spec.js
  test/spec/refererDetection_spec.js
Labels: LGTM

#3080 Wrap window.top reference with try/catch in aardvark adapter
  modules/aardvarkBidAdapter.js
Labels: needs review

#3078 fix for endpoint url
  modules/justpremiumBidAdapter.js
  test/spec/modules/justpremiumBidAdapter_spec.js
Labels: needs review

#3100 Audience Network (legacy): deprecate fullwidth format, prefer 300x250
  modules/audienceNetworkBidAdapter.js
  modules/audienceNetworkBidAdapter.md
  test/spec/modules/audienceNetworkBidAdapter_spec.js
Labels: legacy

#3074 Add new Adapter rdnBidAdapter
  modules/rdnBidAdapter.js
  modules/rdnBidAdapter.md
  test/spec/modules/rdnBidAdapter_spec.js
Labels: LGTM

#3084 33Across: add viewability
  modules/33acrossBidAdapter.js
  test/spec/modules/33acrossBidAdapter_spec.js
Labels: needs review

#3071 Add support for publisher common id user opt-out
  modules/pubCommonId.js
Labels: needs review

#3099 add user syncing for kargo
  modules/kargoBidAdapter.js
  test/spec/modules/kargoBidAdapter_spec.js
Labels: needs update

#3097 Freewheel-ssp BidAdapter improvements
  modules/freewheel-sspBidAdapter.js
  modules/freewheel-sspBidAdapter.md
  test/spec/modules/freewheel-sspBidAdapter_spec.js
Labels: LGTM

#3032 AOL adapter - switched to native Prebid user syncs support.
  modules/aolBidAdapter.js
  test/spec/modules/aolBidAdapter_spec.js
Labels: needs update

#3094 added sizes for rubicon
  modules/rubiconBidAdapter.js
Labels: needs review

#3064 Serverbid Bid Adapter: Add pubnx alias
  modules/serverbidBidAdapter.js
Labels: needs review

#2993 Trafficroots Bid Adapter Submission
  modules/trafficrootsBidAdapter.js
  modules/trafficrootsBidAdapter.md
  test/spec/modules/trafficrootsBidAdapter_spec.js
Labels: pinned

#3123 adding account to s2s bidder-sync request
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: needs 2nd review, needs review

#3125 Sonobi - Fix ref encoding
  modules/sonobiBidAdapter.js
  test/spec/modules/sonobiBidAdapter_spec.js
Labels: LGTM

#3121 Add video params to Beachfront adapter
  modules/beachfrontBidAdapter.js
  test/spec/modules/beachfrontBidAdapter_spec.js
Labels: LGTM

#3131 Fix for Issue 3130: passing new copy of adUnits object to every adapter
  src/adaptermanager.js
  test/spec/unit/core/adapterManager_spec.js
Labels: needs 2nd review

#3129 fixes #3128 YieldlabBidAdapter is not using bidRequest.params.adSize
  modules/yieldlabBidAdapter.js
  test/spec/modules/yieldlabBidAdapter_spec.js
Labels: needs review, needs unit tests
