Repository prebid/Prebid.js, pull requests merged in 2018-04, with the labels that each got.

#2053 Add CLICKFORCE Bid Adapter (updated to new spec)
  modules/clickforceBidAdapter.js
  modules/clickforceBidAdapter.md
Labels: needs review, needs update

#2279 Adding onTimeout function in Adapter Spec
  src/adaptermanager.js
  src/auction.js
  src/utils.js
  test/spec/utils_spec.js
Labels: LGTM, needs 2nd review

#2335 Log error returned by PBS
  modules/prebidServerBidAdapter.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: in progress, needs review

#2300 Legacy Rubicon Adapter add mediatypes support
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: in progress, legacy

#2311 Fixes #2276 - video.playerSize and Size Mapping not working together
  src/adaptermanager.js
  test/spec/unit/core/adapterManager_spec.js
Labels: LGTM, needs 2nd review

#2287 InSkin Bid Adapter: add user syncing
  modules/inskinBidAdapter.js
  test/spec/modules/inskinBidAdapter_spec.js
Labels: LGTM, question

#2286 InSkin Legacy Bid Adapter: Ignore referrer, add user syncing
  modules/inskinBidAdapter.js
  test/spec/modules/inskinBidAdapter_spec.js
Labels: LGTM, legacy, question

#2336 Fixes issue #2327 - getBidLandScapeTargeting not using adUnitCode argument
  src/targeting.js
  test/spec/unit/core/targeting_spec.js
Labels: LGTM, in progress, needs 2nd review

#2308 Fixes #2291 - user cust_params data lost with url option for dfpAdServerVideo module
  modules/dfpAdServerVideo.js
  test/spec/modules/dfpAdServerVideo_spec.js
Labels: LGTM, needs 2nd review

#2322 Add: vuble adapter handles dealId
  modules/vubleBidAdapter.js
  modules/vubleBidAdapter.md
  test/spec/modules/vubleBidAdapter_spec.js
Labels: not receiving bids

#2337 change utils.js unit tests to fix browserstack errors
  test/spec/utils_spec.js
Labels: in progress

#2338 change find method in adapatermanger.js to polyfill version
  src/adaptermanager.js
Labels: in progress

#2163 New adapter madvertise
  modules/madvertiseBidAdapter.js
  modules/madvertiseBidAdapter.md
  test/spec/modules/madvertiseBidAdapter_spec.js
Labels: needs update

#2290 Adkernel adapters compatibility issues
  modules/adkernelAdnAnalyticsAdapter.js
  modules/adkernelAdnBidAdapter.js
  modules/adkernelBidAdapter.js
  test/spec/modules/adkernelAdnAnalyticsAdapter_spec.js
  test/spec/modules/adkernelAdnBidAdapter_spec.js
  test/spec/modules/adkernelBidAdapter_spec.js
Labels: needs review

#2307 update rubicon video position default value for legacy version
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: needs review

#2349 Integrate browserstack with travis
  .travis.yml
  browsers.json
  gulpfile.js
  karma.conf.maker.js
  test/spec/modules/invibesBidAdapter_spec.js
Labels: in progress

#2358 run unit-tests for pr and non-pr
  .travis.yml
Labels: in progress

#2360 test for travis
  src/prebid.js
Labels: in progress

#2313 initial commit
  modules/realvuAnalyticsAdapter.js
  modules/realvuAnalyticsAdapter.md
  package-lock.json
  test/spec/modules/realvuAnalyticsAdapter_spec.js
Labels: LGTM

#2343 Update AdGeneration adapter
  modules/adgenerationBidAdapter.js
  test/spec/modules/adgenerationBidAdapter_spec.js
Labels: LGTM

#2340 Read and send the pv param on bid requests
  modules/gumgumBidAdapter.js
Labels: LGTM

#2310 Smart: User sync
  modules/smartadserverBidAdapter.js
  test/spec/modules/smartadserverBidAdapter_spec.js
Labels: needs review

#2328 Added bid pool and fixed getAllWinningBids function
  src/auction.js
  src/auctionManager.js
  src/prebid.js
  src/targeting.js
  test/fixtures/fixtures.js
  test/spec/unit/core/targeting_spec.js
  test/spec/unit/pbjs_api_spec.js
Labels: LGTM, in progress, needs 2nd review

#2347 Rubicon Adapter - Multiple media types bug fix
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: adapter support, bug, in progress

#2373 uppercase all keys for AST macros
  src/targeting.js
  test/spec/unit/pbjs_api_spec.js
Labels: LGTM, in progress, needs 2nd review

#2329 EngageBDR legacy bid adapter
  modules/ebdrBidAdapter.js
  modules/ebdrBidAdapter.md
  test/spec/modules/ebdrBidAdapter_spec.js
Labels: legacy, needs update

#2323 Create rtbdemandAdkBidAdapter.js
  modules/rtbdemandAdkBidAdapter.js
Labels: needs docs, needs update

#2375 applying AST macro fix to legacy
  src/targeting.js
  test/spec/unit/pbjs_api_spec.js
Labels: in progress, legacy, needs 2nd review

#2333 Added LKQD prebid adapter with associated documentation and tests
  modules/lkqdBidAdapter.js
  modules/lkqdBidAdapter.md
  test/spec/modules/lkqdBidAdapter_spec.js
Labels: LGTM

#2387 Fix lqpd unit test failure
  modules/lkqdBidAdapter.js
Labels: in progress

#2334 33Across: Complete user sync implementation
  modules/33acrossBidAdapter.js
  test/spec/modules/33acrossBidAdapter_spec.js
Labels: needs review

#2325 Smart: New parameters for in-app ads
  modules/smartadserverBidAdapter.js
  modules/smartadserverBidAdapter.md
  test/spec/modules/smartadserverBidAdapter_spec.js
Labels: needs docs, needs review

#2172 Add SARA-HB Bid Adapter
  modules/saraBidAdapter.js
  modules/saraBidAdapter.md
  test/spec/modules/saraBidAdapter_spec.js
Labels: not receiving bids

#2297 Sonobi Video Support
  modules/sonobiBidAdapter.js
  modules/sonobiBidAdapter.md
  test/spec/modules/sonobiBidAdapter_spec.js
Labels: needs docs, needs review

#2364 fix legacy sizes in prebidserverAdapter
  modules/prebidServerBidAdapter.js
Labels: needs review

#2363 fixes #2353 - not appending hb_uuid and hb_cache_id
  modules/dfpAdServerVideo.js
  src/utils.js
  test/spec/modules/dfpAdServerVideo_spec.js
Labels: in progress, needs 2nd review

#2331 Add: Vuble Analytics Adapter
  modules/vubleAnalyticsAdapter.js
  modules/vubleAnalyticsAdapter.md
  test/spec/modules/vubleAnalyticsAdapter_spec.js
Labels: LGTM

#2283 Widespace adapter
  modules/widespaceBidAdapter.js
  modules/widespaceBidAdapter.md
  test/spec/modules/widespaceBidAdapter_spec.js
Labels: LGTM

#2352 Create rtbdemandAdkBidAdapter_spec.js
  test/spec/modules/rtbdemandAdkBidAdapter_spec.js
Labels: needs update

#2365 add support for video bids to use an impression tracking URL
  modules/appnexusBidAdapter.js
  src/videoCache.js
  test/spec/modules/appnexusBidAdapter_spec.js
  test/spec/videoCache_spec.js
Labels: needs 2nd review

#2394 Smart: Add prebid version in the data payload
  modules/smartadserverBidAdapter.js
  modules/smartadserverBidAdapter.md
Labels: LGTM

#2326 Add Unruly Bid Adapter
  integrationExamples/gpt/unruly_example.html
  modules/unrulyBidAdapter.js
  modules/unrulyBidAdapter.md
  test/spec/modules/unrulyBidAdapter_spec.js
Labels: needs review

#2405 Fix widespace Unit test failures
  modules/widespaceBidAdapter.js
  test/spec/modules/widespaceBidAdapter_spec.js
Labels: in progress

#2391 deprecate loadScript and add loadExternalScript
  src/adloader.js
  src/prebid.js
Labels: LGTM, in progress, needs 2nd review

#2316 Add analytics adapter by Sigmoid
  modules/sigmoidAnalyticsAdapter.js
  modules/sigmoidAnalyticsAdapter.md
  test/spec/modules/sigmoidAnalyticsAdapter_spec.js
Labels: needs docs, needs update

#2385 convert AN bid params to underscore formatting for pbs
  modules/prebidServerBidAdapter.js
  src/utils.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/utils_spec.js
Labels: LGTM, needs 2nd review

#2351 send appnexus usePaymentRule info to prebid-server ortb request
  modules/prebidServerBidAdapter.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/unit/core/adapterManager_spec.js
Labels: LGTM, in progress

#2404 send travis-ci notifications to slack
  .travis.yml
Labels: LGTM, in progress

#2292 Make eslint aware of the custom import paths
  .eslintrc.js
  modules/sonobiBidAdapter.js
  src/adapters/bidderFactory.js
Labels: LGTM, needs 2nd review

#2409 Add user sync callback for OpenX adaptor
  modules/openxBidAdapter.js
  test/spec/modules/openxBidAdapter_spec.js
Labels: LGTM

#2398 add server response time to bids in prebid server
  modules/prebidServerBidAdapter.js
  modules/rubiconAnalyticsAdapter.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
Labels: LGTM, in progress

#2426 add gdpr support to rubicon video in rubiconBidAdapter
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: needs review

#2429 Add New Adapter dgadsBidAdapter
  modules/dgadsBidAdapter.js
  modules/dgadsBidAdapter.md
  test/spec/modules/dgadsBidAdapter_spec.js
Labels: LGTM

#2414 Size Bugfix
  modules/quantumBidAdapter.js
  test/spec/modules/quantumBidAdapter_spec.js
Labels: LGTM

#2406 Rubicon adapter GDPR support
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: LGTM, adapter support

#2422 IndexExchange Display Bid Adapter
  modules/ixBidAdapter.js
  modules/ixBidAdapter.md
  test/spec/modules/ixBidAdapter_spec.js
Labels: LGTM, adapter support

#2441 typo
  modules/sekindoUMBidAdapter.md
Labels: in progress

#2432 Media.net Adapter Improvements Legacy
  modules/medianetBidAdapter.js
  test/spec/modules/medianetBidAdapter_spec.js
Labels: legacy, needs review

#2388 add cleanup and proper stubbing for legacy analytics
  test/spec/modules/adkernelAdnAnalyticsAdapter_spec.js
  test/spec/modules/adomikAnalyticsAdapter_spec.js
  test/spec/modules/adxcgAnalyticsAdapter_spec.js
  test/spec/modules/pubwiseAnalyticsAdapter_spec.js
  test/spec/modules/roxotAnalyticsAdapter_spec.js
Labels: LGTM, in progress

#2456 Rubicon Adapter GDPR Update for gdprApplies flag
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: LGTM, adapter support, in progress

#2435 Beachfront adapter support for sizes defined in mediaTypes
  modules/beachfrontBidAdapter.js
  modules/beachfrontBidAdapter.md
  test/spec/modules/beachfrontBidAdapter_spec.js
Labels: needs review

#2416 Add Sigmoid Analytics Adapter files to Legacy branch
  modules/sigmoidAnalyticsAdapter.js
  modules/sigmoidAnalyticsAdapter.md
  test/spec/modules/sigmoidAnalyticsAdapter_spec.js
Labels: legacy

#2383 add getUserSyncs function in clickforceBidAdapter
  modules/clickforceBidAdapter.js
  modules/clickforceBidAdapter.md
  test/spec/modules/clickforceBidAdapter_spec.js
Labels: needs update

#2440 added missing dfpAdServerVideo.js dfp vast tag generation uri compone…
  modules/dfpAdServerVideo.js
  src/targeting.js
Labels: LGTM

#2469 GDPR Support for PubMaticBidAdapter
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: LGTM

#2463 Sonobi Adapter - Added debugging and analytics query params.
  modules/sonobiBidAdapter.js
  test/spec/modules/sonobiBidAdapter_spec.js
Labels: needs review

#2390 Add New Adapter admaticBidAdapter
  modules/admaticBidAdapter.js
  modules/admaticBidAdapter.md
Labels: LGTM

#2453 Getintent adapter: support multisize bids
  modules/getintentBidAdapter.js
  test/spec/modules/getintentBidAdapter_spec.js
Labels: LGTM

#2444 add feature to bridgewellBidAdapter
  modules/bridgewellBidAdapter.js
  modules/bridgewellBidAdapter.md
  test/spec/modules/bridgewellBidAdapter_spec.js
Labels: needs review
