Repository prebid/Prebid.js, pull requests merged in 2018-03, with the labels that each got.

#2135 Yieldbot Prebid.js 1.0 adapter
  modules/yieldbotBidAdapter.js
  modules/yieldbotBidAdapter.md
  test/spec/e2e/gpt-examples/gpt_yieldbot.html
  test/spec/modules/yieldbotBidAdapter_spec.js
Labels: in progress

#2168 Remove bracket and object spacing lint exceptions
  test/.eslintrc.js
  test/helpers/index_adapter_utils.js
  test/spec/auctionmanager_spec.js
  test/spec/modules/a4gBidAdapter_spec.js
  test/spec/modules/adformBidAdapter_spec.js
  test/spec/modules/appnexusBidAdapter_spec.js
  test/spec/modules/jcmBidAdapter_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/pulsepointBidAdapter_spec.js
  test/spec/modules/somoaudienceBidAdapter_spec.js
  test/spec/unit/core/bidderFactory_spec.js
  test/spec/unit/pbjs_api_spec.js
Labels: needs review

#2195 RTK official updates
  modules/aardvarkBidAdapter.js
Labels: LGTM, legacy

#2209 fix mediaType being overwritten by undefined in rubicon bid adapter
  modules/rubiconBidAdapter.js
Labels: in progress

#2155 Auctionmanager spec refactor pr
  src/auction.js
  test/spec/auctionmanager_spec.js
Labels: LGTM

#2203 Audience Network: allow native/fullwidth bids for non-IAB sizes
  modules/audienceNetworkBidAdapter.js
  test/spec/modules/audienceNetworkBidAdapter_spec.js
Labels: LGTM

#2080 Smartyads Adapter 1.x
  modules/smartyadsBidAdapter.js
  modules/smartyadsBidAdapter.md
  package.json
  test/spec/modules/smartyadsBidAdapter_spec.js
Labels: LGTM

#2117 Add banner support to Beachfront adapter
  modules/beachfrontBidAdapter.js
  modules/beachfrontBidAdapter.md
  test/spec/modules/beachfrontBidAdapter_spec.js
Labels: LGTM

#2147 FairTrade Bidder Adapter
  modules/fairtradeBidAdapter.js
  modules/fairtradeBidAdapter.md
  test/spec/modules/fairtradeBidAdapter_spec.js
Labels: LGTM

#2204 use b64EncodeUnicode to encode strings with unicode chars in them
  modules/sharethroughBidAdapter.js
  test/spec/modules/sharethroughBidAdapter_spec.js
Labels: LGTM

#2159 adding PR_REVIEW guideline
  PR_REVIEW.md
Labels: LGTM

#2193 33Across Bid Adapter: updated user sync endpoint
  modules/33acrossBidAdapter.js
  test/spec/modules/33acrossBidAdapter_spec.js
Labels: LGTM

#2192 Feature/stale bot
  .github/stale.yml
Labels: in progress

#2227 fix mediaType being overwritten by undefined in rubicon bid adapter
  modules/rubiconBidAdapter.js
Labels: LGTM, legacy

#2216 Gamma Support UserSync Endpoint
  modules/gammaBidAdapter.js
Labels: LGTM

#2217 InSkin Bid Adapter: remove referrer field from request body
  modules/inskinBidAdapter.js
Labels: LGTM

#2219 Fix video bids from multi-response array triggering callback early
  src/adapters/bidderFactory.js
  test/spec/auctionmanager_spec.js
Labels: LGTM

#2228 Fix cross-platform test failures
  modules/adyoulikeBidAdapter.js
  modules/nasmediaAdmixerBidAdapter.js
  modules/rtbhouseBidAdapter.js
  test/spec/modules/peak226BidAdapter_spec.js
  test/spec/modules/pubCommonId_spec.js
Labels: in progress

#2202 Add Invibes Adapter
  modules/invibesBidAdapter.js
  modules/invibesBidAdapter.md
  test/spec/modules/invibesBidAdapter_spec.js
Labels: LGTM

#2236 fixes #2229 - Edge cookie string form
  modules/yieldbotBidAdapter.js
Labels: LGTM

#2206 PBS adapter not sending app or device
  modules/prebidServerBidAdapter.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: LGTM

#2197 Update Lifestreet adapter to 1.0
  modules/lifestreetBidAdapter.js
  modules/lifestreetBidAdapter.md
  test/spec/modules/lifestreetBidAdapter_spec.js
Labels: LGTM

#2230 Update Platform.io Adapter
  modules/platformioBidAdapter.js
  modules/platformioBidAdapter.md
  test/spec/modules/platformioBidAdapter_spec.js
Labels: LGTM

#2255 create RELEASE_SCHEDULE.md
  RELEASE_SCHEDULE.md
Labels: in progress

#2207 Update Unruly Adapter to ensure Prebid.js 1.x compatibility
  integrationExamples/gpt/unruly_example.html
  modules/unrulyBidAdapter.js
  test/spec/modules/unrulyBidAdapter_spec.js
Labels: legacy

#2246 Add billing url (burl) support
  modules/prebidServerBidAdapter.js
  src/prebid.js
  src/utils.js
  test/spec/unit/pbjs_api_spec.js
Labels: needs docs

#2250 Added ad id to a4g bid
  modules/a4gBidAdapter.js
  test/spec/modules/a4gBidAdapter_spec.js
Labels: LGTM

#2240 Invibes Bid Adapter: adding to legacy branch
  modules/invibesBidAdapter.js
  modules/invibesBidAdapter.md
  test/spec/modules/invibesBidAdapter_spec.js
Labels: LGTM, legacy

#2261 Add vastUrl for Gamma Adapter Video
  modules/gammaBidAdapter.js
  modules/gammaBidAdapter.md
Labels: LGTM

#2211 Add e-planning analytics adapter
  modules/eplanningAnalyticsAdapter.js
  modules/eplanningAnalyticsAdapter.md
  test/spec/modules/eplanningAnalyticsAdapter_spec.js
Labels: LGTM

#2252 Audience Network: add 'cb' and 'pbv' query params
  modules/audienceNetworkBidAdapter.js
  test/spec/modules/audienceNetworkBidAdapter_spec.js
Labels: in progress

#2265 Ensure Unruly Renderer is placed in Prebid supply mode if necessary.
  modules/unrulyBidAdapter.js
  test/spec/modules/unrulyBidAdapter_spec.js
Labels: LGTM

#2277 Yieldbot impression image creation fix
  modules/yieldbotBidAdapter.js
Labels: LGTM

#2285 Message formatting in case number of user sync exceeded
  src/userSync.js
Labels: LGTM

#2181 Adapt Adomik Analytics for Prebid.js legacy
  modules/adomikAnalyticsAdapter.js
  test/spec/modules/adomikAnalyticsAdapter_spec.js
Labels: legacy

#2272 Update to Rubicon Adapter for mediaTypes support
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: in progress

#2241 Update for Media.net adapter legacy
  modules/medianetBidAdapter.js
  test/spec/modules/medianetBidAdapter_spec.js
Labels: LGTM, legacy

#2231 Update Yieldlab adapter and add official maintainer
  modules/yieldlabBidAdapter.js
  modules/yieldlabBidAdapter.md
  test/spec/modules/yieldlabBidAdapter_spec.js
Labels: LGTM

#2273 add hb_cache_id
  modules/dfpAdServerVideo.js
  test/spec/modules/dfpAdServerVideo_spec.js
Labels: needs docs

#2268 New Content Ignite adapter
  modules/contentigniteBidAdapter.js
  modules/contentigniteBidAdapter.md
  test/spec/modules/contentigniteBidAdapter_spec.js
Labels: LGTM

#2210 firing new adRenderFailed event when renderAd() fails
  src/AnalyticsAdapter.js
  src/constants.json
  src/prebid.js
  test/spec/AnalyticsAdapter_spec.js
Labels: LGTM

#2269 Add Oneplanetonly Bid Adapter
  modules/oneplanetonlyBidAdapter.js
  modules/oneplanetonlyBidAdapter.md
  test/spec/modules/oneplanetonlyBidAdapter_spec.js
Labels: LGTM

#2298 Fix travis on legacy branch
  test/spec/modules/adformBidAdapter_spec.js
Labels: in progress

#2301 Unit test fixes
  test/spec/modules/audienceNetworkBidAdapter_spec.js
  test/spec/modules/eplanningAnalyticsAdapter_spec.js
Labels: in progress

#2137 NEW adapter AdtelligentBidAdapter
  modules/adtelligentBidAdapter.js
  modules/adtelligentBidAdapter.md
  test/spec/modules/adtelligentBidAdapter_spec.js
Labels: LGTM

#2170 Smart Ad Server: Fix bug when multi bids
  modules/smartadserverBidAdapter.js
  test/spec/modules/smartadserverBidAdapter_spec.js
Labels: LGTM

#2293 Serverbid Bid Adapter: Added archon alias
  modules/serverbidBidAdapter.js
Labels: needs review

#2302 if cache markup is not enabled, set it to the default value 0
  modules/prebidServerBidAdapter.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: LGTM

#2294 Serverbid Legacy Bid Adapter: Added archon alias
  modules/serverbidBidAdapter.js
Labels: legacy, needs review

#2167 Enhance location detection within utils
  modules/sovrnBidAdapter.js
  src/url.js
  src/utils.js
  test/spec/modules/sovrnBidAdapter_spec.js
  test/spec/url_spec.js
  test/spec/utils_spec.js
Labels: LGTM, needs update

#2257 Support aliases in prebidServer
  modules/prebidServerBidAdapter.js
  src/adaptermanager.js
  src/adapters/bidderFactory.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: needs 2nd review, needs review

#2320 add feature to bridgewellBidAdapter
  modules/bridgewellBidAdapter.js
  modules/bridgewellBidAdapter.md
  test/spec/modules/bridgewellBidAdapter_spec.js
Labels: needs review

#2309 EngageBDR New Bid Adapter
  modules/ebdrBidAdapter.js
  modules/ebdrBidAdapter.md
  test/spec/modules/ebdrBidAdapter_spec.js
Labels: needs docs, needs update

#2321 Add video targeting to Beachfront adapter
  modules/beachfrontBidAdapter.js
  modules/beachfrontBidAdapter.md
  test/spec/modules/beachfrontBidAdapter_spec.js
Labels: LGTM

#2318 Platform.io video support
  integrationExamples/gpt/hello_world.html
  modules/platformioBidAdapter.js
  modules/platformioBidAdapter.md
  test/spec/modules/platformioBidAdapter_spec.js
Labels: LGTM

#2305 Fixes #2258 - cpm bucketing error
  src/cpmBucketManager.js
  test/spec/cpmBucketManager_spec.js
Labels: LGTM
