Repository prebid/Prebid.js, pull requests merged in 2018-05, with the labels that each got.

#2425 [legacy] Populate crid with values from demand if present
  modules/sovrnBidAdapter.js
  test/spec/modules/sovrnBidAdapter_spec.js
Labels: legacy, needs review

#2424 [1.x] Populate crid with values from demand if present
  modules/sovrnBidAdapter.js
  test/spec/modules/sovrnBidAdapter_spec.js
Labels: needs review

#2471 PulsePoint Adapter GDPR support
  modules/pulsepointBidAdapter.js
  test/spec/modules/pulsepointBidAdapter_spec.js
Labels: LGTM, needs docs

#2452 OpenX Adapter: Support out of order bids.
  modules/openxBidAdapter.js
  test/spec/modules/openxBidAdapter_spec.js
Labels: LGTM

#2213 GDPR consentManagement module
  integrationExamples/gpt/gdpr_hello_world.html
  modules/adformBidAdapter.js
  modules/aolBidAdapter.js
  modules/aolBidAdapter.md
  modules/appnexusBidAdapter.js
  modules/consentManagement.js
  modules/pre1api.js
  modules/prebidServerBidAdapter.js
  modules/pubmaticBidAdapter.js
  src/adaptermanager.js
  src/adapters/bidderFactory.js
  src/utils.js
  test/spec/modules/adformBidAdapter_spec.js
  test/spec/modules/aolBidAdapter_spec.js
  test/spec/modules/appnexusBidAdapter_spec.js
  test/spec/modules/consentManagement_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/pubmaticBidAdapter_spec.js
  test/spec/unit/core/adapterManager_spec.js
  test/spec/utils_spec.js
Labels: in progress

#2430 added whitelist for loading external JS + tests
  src/adloader.js
  test/spec/adloader_spec.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: LGTM, in progress, needs 2nd review

#2367 Add note about headerbid expert
  PR_REVIEW.md
Labels: stale

#2475 GDPR support for Sovrn Adapter
  modules/sovrnBidAdapter.js
  test/spec/modules/sovrnBidAdapter_spec.js
Labels: LGTM

#2480 add feature to bridgewellBidAdapter
  modules/bridgewellBidAdapter.js
  modules/bridgewellBidAdapter.md
  test/spec/modules/bridgewellBidAdapter_spec.js
Labels: LGTM, needs docs

#2468 Update Platformio Adapter
  modules/platformioBidAdapter.js
  modules/platformioBidAdapter.md
  test/spec/modules/platformioBidAdapter_spec.js
Labels: LGTM, needs docs

#2484 Only send OpenX BO beacon once per page load
  modules/openxBidAdapter.js
  test/spec/modules/openxBidAdapter_spec.js
Labels: LGTM

#2477 Add LockerDome bid adapter
  modules/lockerdomeBidAdapter.js
  modules/lockerdomeBidAdapter.md
  test/spec/modules/lockerdomeBidAdapter_spec.js
Labels: adapter support, needs review

#2485 Add LockerDome legacy bid adapter
  modules/lockerdomeBidAdapter.js
  modules/lockerdomeBidAdapter.md
  test/spec/modules/lockerdomeBidAdapter_spec.js
Labels: legacy, needs review

#2445 One Video Adapter
  modules/oneVideoBidAdapter.js
  modules/oneVideoBidAdapter.md
  test/spec/modules/oneVideoBidAdapter_spec.js
Labels: needs docs, needs review

#2447 Update babel plugins
  .babelrc
  package-lock.json
  package.json
  webpack.conf.js
Labels: in progress, needs 2nd review

#2474 Add GDPR support to Beachfront adapter
  modules/beachfrontBidAdapter.js
  test/spec/modules/beachfrontBidAdapter_spec.js
Labels: needs review

#2461 New Adapter onetagBidAdapter
  modules/onetagBidAdapter.js
  modules/onetagBidAdapter.md
  test/spec/modules/onetagBidAdapter_spec.js
Labels: LGTM

#2495 New optional parameter - subId
  modules/nanointeractiveBidAdapter.js
  modules/nanointeractiveBidAdapter.md
  test/spec/modules/nanointeractiveBidAdapter_spec.js
Labels: needs review

#2487 add support to handle native js pixels for AN adapter
  modules/appnexusBidAdapter.js
  src/native.js
  src/utils.js
  test/spec/native_spec.js
Labels: LGTM

#2501 A4G Adapter GDPR support
  modules/a4gBidAdapter.js
  test/spec/modules/a4gBidAdapter_spec.js
Labels: LGTM

#2502 support extra params
  modules/vidazooBidAdapter.js
  modules/vidazooBidAdapter.md
  test/spec/modules/vidazooBidAdapter_spec.js
Labels: LGTM

#2496 IndexExchange Display Bid Adapter + GDPR Support
  modules/ixBidAdapter.js
  modules/ixBidAdapter.md
  test/spec/modules/ixBidAdapter_spec.js
Labels: LGTM, adapter support, needs docs

#2503 Sharethrough: GDPR compliance + getUserSyncs
  modules/sharethroughBidAdapter.js
  test/spec/modules/sharethroughBidAdapter_spec.js
Labels: LGTM

#2497 Sonobi Adapter - Added referrer param. Fixed timeout error in userSync
  modules/sonobiBidAdapter.js
  test/spec/modules/sonobiBidAdapter_spec.js
Labels: needs review

#2508 add support for latLong in rubicon adapter
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: LGTM

#2504 OpenX Adapter: GDPR Support
  modules/openxBidAdapter.js
  test/spec/modules/openxBidAdapter_spec.js
Labels: LGTM

#2458 Add new Adapter brainyBidAdapter
  modules/brainyBidAdapter.js
  modules/brainyBidAdapter.md
  test/spec/modules/brainyBidAdapter_spec.js
Labels: needs review

#2459 Update ReadPeak adapter (legacy)
  modules/readpeakBidAdapter.js
  modules/readpeakBidAdapter.md
  test/spec/modules/readpeakBidAdapter_spec.js
Labels: LGTM

#2498 Sonobi Legacy - Add referrer param
  modules/sonobiBidAdapter.js
  test/spec/modules/sonobiBidAdapter_spec.js
Labels: legacy, needs review

#2514 Mocha reporter: Show only summary and errors
  karma.conf.maker.js
Labels: LGTM, reviewed

#2531 added gdpr support to userSync in rubicon adapter
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: LGTM, adapter support

#2537 Lifestreet: gdpr and consent string parameters
  modules/lifestreetBidAdapter.js
  test/spec/modules/lifestreetBidAdapter_spec.js
Labels: LGTM

#2540 GXOne Bid Adapter
  modules/gxoneBidAdapter.js
  modules/gxoneBidAdapter.md
  test/spec/modules/gxoneBidAdapter_spec.js
Labels: LGTM, adapter support

#2520 Bug fix to read all bids from seatBid array
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: LGTM

#2505 fix getPreparedBidForAuction to look for renderer on correct bid
  src/auction.js
  test/spec/auctionmanager_spec.js
Labels: LGTM, needs 2nd review

#2528 Smart: GDPR support
  modules/smartadserverBidAdapter.js
  test/spec/modules/smartadserverBidAdapter_spec.js
Labels: LGTM, needs docs

#2451 Added Release Process
  README.md
  RELEASE_SCHEDULE.md
Labels: needs review

#2534 Fix endpoint for brainy
  modules/brainyBidAdapter.js
  test/spec/modules/brainyBidAdapter_spec.js
Labels: LGTM

#2488 Changed invalid engine URL to a valid one, removed unnecessary params…
  modules/nanointeractiveBidAdapter.js
  modules/nanointeractiveBidAdapter.md
  test/spec/modules/nanointeractiveBidAdapter_spec.js
Labels: LGTM, legacy

#2518 feat(adyoulikeAdapter): adapt adapter to gdpr
  modules/adyoulikeBidAdapter.js
  test/spec/modules/adyoulikeBidAdapter_spec.js
Labels: LGTM

#2565 Update TrustX Bid Adapter to support gdpr
  modules/trustxBidAdapter.js
  test/spec/modules/trustxBidAdapter_spec.js
Labels: LGTM

#2555 execute bidsBackHandler when auction is canceled by consent module
  modules/consentManagement.js
  test/spec/modules/consentManagement_spec.js
Labels: needs 2nd review

#2581 GjirafaBidAdapter - Added GPRS support
  modules/gjirafaBidAdapter.js
  test/spec/modules/gjirafaBidAdapter_spec.js
Labels: LGTM, needs docs

#2588 Consent Management module bug fix.
  modules/consentManagement.js
  test/spec/modules/consentManagement_spec.js
Labels: LGTM, needs 2nd review

#2561 put server latency on bidder timeout event for NO_BIDs
  modules/prebidServerBidAdapter.js
  modules/rubiconAnalyticsAdapter.js
  src/utils.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
Labels: LGTM, needs 2nd review

#2563 Sharethrough GDPR updates
  modules/sharethroughBidAdapter.js
  test/spec/modules/sharethroughBidAdapter_spec.js
Labels: LGTM, needs docs

#2569 Updated GDPR feature for Onetag bidder adapter
  modules/onetagBidAdapter.js
  test/spec/modules/onetagBidAdapter_spec.js
Labels: LGTM

#2478 Rubicon Adapter - SRA support
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: adapter support

#2584 Sonobi Adapter creativeId support
  modules/sonobiBidAdapter.js
  test/spec/modules/sonobiBidAdapter_spec.js
Labels: needs update

#2575 added ccxAdapter
  modules/ccxBidAdapter.js
  modules/ccxBidAdapter.md
  test/spec/modules/ccxBidAdapter_spec.js
Labels: LGTM

#2370 Update Criteo bid adapter to Prebid 1.x
  modules/criteoBidAdapter.js
  modules/criteoBidAdapter.md
  test/spec/modules/criteoBidAdapter_spec.js
Labels: needs update, on hold

#2612 fix issue with GDPR module in concurrent auctions
  modules/consentManagement.js
Labels: LGTM

#2595 Add GDPR support to GumGum Adapter
  modules/gumgumBidAdapter.js
  test/spec/modules/gumgumBidAdapter_spec.js
Labels: needs update

#2626 ConsentManagement: detect __cmp in window.top
  modules/consentManagement.js
Labels: LGTM, needs 2nd review

#2641 rtbhouse adapter GDPR integration.
  modules/rtbhouseBidAdapter.js
  test/spec/modules/rtbhouseBidAdapter_spec.js
Labels: LGTM

#2492 New debugging functionality with bid overrides
  src/debugging.js
  src/hook.js
  src/prebid.js
  test/spec/debugging_spec.js
Labels: LGTM, needs 2nd review

#2643 Arteebee adapter GDPR integration
  modules/arteebeeBidAdapter.js
  test/spec/modules/arteebeeBidAdapter_spec.js
Labels: not receiving bids

#2644 fix cpm floor issue in price bucket formula
  src/cpmBucketManager.js
  test/fixtures/cpmInputsOutputs.json
  test/spec/cpmBucketManager_spec.js
Labels: LGTM, needs 2nd review
