Repository prebid/Prebid.js, pull requests merged in 2018-12, with the labels that each got.

#3343 update gulp packages to address vulnerability
  gulpfile.js
  package-lock.json
  package.json
Labels: LGTM, needs 2nd review

#3307 initial version of ozone adapter for review
  modules/ozoneBidAdapter.js
  modules/ozoneBidAdapter.md
  test/spec/modules/ozoneBidAdapter_spec.js
Labels: needs unit tests, needs update

#3317 adding additional bid request validity checks. updating how we grab sizes array
  modules/emx_digitalBidAdapter.js
  test/spec/modules/emx_digitalBidAdapter_spec.js
Labels: needs update

#3345 Update TTL to 30 mins
  modules/ucfunnelBidAdapter.js
Labels: needs update

#3347 Bidfluence Adapter update - Single call
  modules/bidfluenceBidAdapter.js
  test/spec/modules/bidfluenceBidAdapter_spec.js
Labels: LGTM

#3348 Adding native parameters: body2, rating, privacyLink
  modules/appnexusBidAdapter.js
  src/constants.json
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: LGTM

#3359 Add user sync pixel logic in Adtelligent adapter
  modules/adtelligentBidAdapter.js
  test/spec/modules/adtelligentBidAdapter_spec.js
Labels: LGTM

#3314 AppNexus debug auction via cookie
  modules/appnexusBidAdapter.js
  src/utils.js
Labels: needs 2nd review

#3360 Fix #2781 - syncsPerBidder set to 0
  src/userSync.js
  test/spec/userSync_spec.js
Labels: needs 2nd review

#3370 Add a new adapter for Appier bidder.
  modules/appierBidAdapter.js
  modules/appierBidAdapter.md
  test/spec/modules/appierBidAdapter_spec.js
Labels: needs review

#3351 Rivr thin adapter
  modules/rivrAnalyticsAdapter.js
  test/spec/modules/rivrAnalyticsAdapter_spec.js
Labels: LGTM
