Repository prebid/Prebid.js, pull requests merged in 2018-02, with the labels that each got.

#2092 Add adapter for GAMMA SSP
  modules/gammaBidAdapter.js
  modules/gammaBidAdapter.md
  test/spec/modules/gammaBidAdapter_spec.js
Labels: LGTM

#2129 Remove unneeded lint exceptions
  .eslintrc.js
  test/.eslintrc.js
Labels: LGTM

#2073 Option to use a configurable vendor preset for s2sConfig
  modules/prebidServerBidAdapter.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: in progress, reviewed

#2110 remote.html is being deprecated in AMP. Pointer to the Prebid Server …
  integrationExamples/gpt/amp/README.md
Labels: LGTM, in progress

#2130 Remove deprecated method reference
  CONTRIBUTING.md
Labels: needs review

#2141 AN Adapter fix bug with privateSizes
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: LGTM, in progress

#2086 added advertiserId and networkId for rubiconBidAdapter
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: needs update

#2014 Update test stack POC
  README.md
  browsers.json
  integrationExamples/gpt/hello_world.html
  karma.conf.maker.js
  package.json
  src/userSync.js
  src/utils.js
  test/spec/AnalyticsAdapter_spec.js
  test/spec/auctionmanager_spec.js
  test/spec/modules/33acrossBidAdapter_spec.js
  test/spec/modules/adkernelAdnAnalyticsAdapter_spec.js
  test/spec/modules/adkernelAdnBidAdapter_spec.js
  test/spec/modules/adkernelBidAdapter_spec.js
  test/spec/modules/adomikAnalyticsAdapter_spec.js
  test/spec/modules/adxcgAnalyticsAdapter_spec.js
  test/spec/modules/appnexusBidAdapter_spec.js
  test/spec/modules/eplanningBidAdapter_spec.js
  test/spec/modules/improvedigitalBidAdapter_spec.js
  test/spec/modules/kargoBidAdapter_spec.js
  test/spec/modules/nanointeractiveBidAdapter_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/pubwiseAnalyticsAdapter_spec.js
  test/spec/modules/roxotAnalyticsAdapter_spec.js
  test/spec/modules/rubiconBidAdapter_spec.js
  test/spec/modules/s2sTesting_spec.js
  test/spec/modules/serverbidServerBidAdapter_spec.js
  test/spec/modules/vidazooBidAdapter_spec.js
  test/spec/renderer_spec.js
  test/spec/sizeMapping_spec.js
  test/spec/unit/core/adapterManager_spec.js
  test/spec/unit/core/bidderFactory_spec.js
  test/spec/unit/core/targeting_spec.js
  test/spec/unit/pbjs_api_spec.js
  test/spec/userSync_spec.js
  test/spec/utils_spec.js
  test/test_index.js
  yarn.lock
Labels: needs review, needs update

#2131 Serverbid Legacy Bid Adapter: update to latest from master
  modules/serverbidBidAdapter.js
  test/spec/modules/serverbidBidAdapter_spec.js
Labels: LGTM, legacy

#2114 size mapping throws warning if mediaQuery missing
  src/sizeMapping.js
  test/spec/sizeMapping_spec.js
Labels: LGTM

#2144 added package-lock.json for node v9 builds
  package-lock.json
Labels: LGTM, in progress

#2125 AOL adapter: Fixed broken user matching in iframes
  modules/aolBidAdapter.js
  test/spec/modules/aolBidAdapter_spec.js
Labels: LGTM

#2127 AOL adapter: Fixed broken user matching in iframes (legacy)
  modules/aolBidAdapter.js
  test/spec/modules/aolBidAdapter_spec.js
Labels: LGTM, legacy

#2027 fix bug in UndertoneBidAdapter
  modules/undertoneBidAdapter.js
Labels: LGTM

#2149 Update to sovrn custom params as well as site object construction
  modules/sovrnBidAdapter.js
  test/spec/modules/sovrnBidAdapter_spec.js
Labels: LGTM

#2151 Update AdGeneration adapter
  modules/adgenerationBidAdapter.js
  modules/adgenerationBidAdapter.md
Labels: LGTM

#2087 consolidated referrer logic and added pageUrl support from config in …
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: LGTM

#2153 Fix stub syntax to work with test stack update
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: needs review

#2158 Add debug info to DOM for prebid creatives
  src/prebid.js
Labels: LGTM

#2108 Adding Orbitsoft module for Prebid 1.0
  modules/orbitsoftBidAdapter.js
  modules/orbitsoftBidAdapter.md
  test/spec/modules/orbitsoftBidAdapter_spec.js
Labels: LGTM

#2150 Add Publisher Common ID module
  modules/conversantBidAdapter.js
  modules/pubCommonId.js
  test/spec/modules/conversantBidAdapter_spec.js
  test/spec/modules/pubCommonId_spec.js
Labels: LGTM

#2134 added currency.defaultRates to use when currency file fails to load
  modules/currency.js
  test/spec/modules/currency_spec.js
Labels: LGTM, needs docs

#2157 [Edit BidAdapter] rxrtb adapter for Perbid.js 1.0 Update
  modules/rxrtbBidAdapter.js
Labels: LGTM

#2102 Add support for OpenRTB protocol and endpoint
  modules/prebidServerBidAdapter.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: needs review

#2175 legacy: fixing test file and removing yarn
  package-lock.json
  test/spec/AnalyticsAdapter_spec.js
  yarn.lock
Labels: in progress

#2051 Quantum Advertising Adapter
  modules/quantumBidAdapter.js
  modules/quantumBidAdapter.md
  test/spec/modules/quantumBidAdapter_spec.js
Labels: LGTM

#2143 only do video caching if we don't already have a videoCacheKey
  src/auction.js
Labels: LGTM

#2154 only count bid timeouts if bidder didn't call done. fixes #2146
  src/auction.js
Labels: LGTM

#2183 Change bidderCode for DAN Marketplace Bid Adapter
  modules/danmarketBidAdapter.js
  modules/danmarketBidAdapter.md
  test/spec/modules/danmarketBidAdapter_spec.js
Labels: LGTM

#2077 Update Adyoulike Adapter to prebid 1.0
  modules/adyoulikeBidAdapter.js
  modules/adyoulikeBidAdapter.md
  test/spec/modules/adyoulikeBidAdapter_spec.js
Labels: LGTM

#2180 Update Innity Adapter to Prebid.js v1.0
  modules/innityBidAdapter.js
  modules/innityBidAdapter.md
  test/spec/modules/innityBidAdapter_spec.js
Labels: LGTM

#2184 [NEW Adapter] RTBHouseBidAdapter
  modules/rtbhouseBidAdapter.js
  modules/rtbhouseBidAdapter.md
  test/spec/modules/rtbhouseBidAdapter_spec.js
Labels: LGTM

#2136 Add multiple bids request
  modules/vertamediaBidAdapter.js
  test/spec/modules/vertamediaBidAdapter_spec.js
Labels: needs review

#2104 Update Vertoz adapter for Prebid 1.0
  modules/vertozBidAdapter.js
  modules/vertozBidAdapter.md
  test/spec/modules/vertozBidAdapter_spec.js
Labels: LGTM

#2177 [RE-OPEN] Update to sovrn custom params as well as site object construction
  modules/sovrnBidAdapter.js
  test/spec/modules/sovrnBidAdapter_spec.js
Labels: LGTM, legacy
