Repository prebid/Prebid.js, pull requests merged in 2019-11, with the labels that each got.

#4355 Add function to remove item in LocalStorage
  src/utils.js
Labels: LGTM

#4396 Making originalCpm and originalCurrency fields in bid object always available
  modules/currency.js
  src/adapters/bidderFactory.js
  test/spec/unit/core/bidderFactory_spec.js
Labels: needs 2nd review

#4359 Fixes for Platform One Analytics Adapter
  modules/yieldoneAnalyticsAdapter.js
  test/spec/modules/yieldoneAnalyticsAdapter_spec.js
Labels: needs review

#4395 Added protocol to url
  modules/zedoBidAdapter.js
  test/spec/modules/zedoBidAdapter_spec.js
Labels: needs review, question

#4410 JustPremium: Update to Prebid 3.0
  modules/justpremiumBidAdapter.js
  modules/justpremiumBidAdapter.md
  test/spec/modules/justpremiumBidAdapter_spec.js
Labels: needs review, question

#4401 Update Consumable adapter for Prebid.js 3.0
  modules/consumableBidAdapter.js
  test/spec/modules/consumableBidAdapter_spec.js
Labels: needs review

#4247 Alter get highest cpm bids
  src/prebid.js
  test/spec/unit/pbjs_api_spec.js
Labels: Prebid 3.0, needs 2nd review

#4339 Create Mobsmart bidder adapter
  modules/mobsmartBidAdapter.js
  modules/mobsmartBidAdapter.md
  test/spec/modules/mobsmartBidAdapter_spec.js
Labels: LGTM

#4389 Adpod deal support
  modules/adpod.js
  modules/appnexusBidAdapter.js
  test/spec/modules/adpod_spec.js
  test/spec/modules/freeWheelAdserverVideo_spec.js
Labels: needs docs

#4428 RTBhouse Bid Adapter update for 3.0
  modules/rtbhouseBidAdapter.js
  modules/rtbhouseBidAdapter.md
  test/spec/modules/rtbhouseBidAdapter_spec.js
Labels: needs review

#4201 YIELDONE adapter - add viewable rendering format
  modules/yieldoneBidAdapter.js
Labels: needs review

#4219 Feature/adapter
  modules/deepintentBidAdapter.js
  modules/deepintentBidAdapter.md
  test/spec/modules/deepintentBidAdapter_spec.js
Labels: LGTM

#4433 PulsePoint Bid Adapter: Support for schain
  modules/pulsepointBidAdapter.js
  test/spec/modules/pulsepointBidAdapter_spec.js
Labels: needs review

#4426 Inventory id and schain support for display
  modules/oneVideoBidAdapter.js
  test/spec/modules/oneVideoBidAdapter_spec.js
Labels: needs review

#4431 PubMatic supporting updated Criteo User Id module
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: needs review

#4343 Brightcom Bid Adapter update for 3.0
  modules/brightcomBidAdapter.js
  modules/brightcomBidAdapter.md
  test/spec/modules/brightcomBidAdapter_spec.js
Labels: LGTM, adapter support

#4434 add support for min_height field in pbs native requests
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: needs 2nd review, needs review

#4365 New adapter Proxistore
  integrationExamples/gpt/hello_world.html
  integrationExamples/gpt/proxistore_example.html
  modules/proxistoreBidAdapter.js
  modules/proxistoreBidAdapter.md
  test/spec/modules/proxistoreBidAdapter_spec.js
Labels: needs review

#4334 Implementation of setBidderConfig and bidder-specific data
  src/adapterManager.js
  src/adapters/bidderFactory.js
  src/config.js
  src/prebid.js
  src/utils.js
  test/spec/unit/core/adapterManager_spec.js
  test/spec/unit/core/bidderFactory_spec.js
Labels: needs 2nd review

#4430 Conversant Bid Adapter checks pubcid directly
  modules/conversantBidAdapter.js
  test/spec/modules/conversantBidAdapter_spec.js
Labels: needs review

#4372 Staq Adapter: update with meta envelope
  modules/staqAnalyticsAdapter.js
  test/spec/modules/staqAnalyticsAdapter_spec.js
Labels: needs review

#4414 RhythmOne Adapter - schain support
  modules/rhythmoneBidAdapter.js
  test/spec/modules/rhythmoneBidAdapter_spec.js
Labels: LGTM

#4378 Media.net Adapter: Support Prebid 3.0
  modules/medianetBidAdapter.js
  test/spec/modules/medianetBidAdapter_spec.js
Labels: LGTM, Prebid 3.0

#4385 Sovrn adapter updates: schain, digitrust, pixel syncing, and 3.0 upgrades
  modules/sovrnBidAdapter.js
  test/spec/modules/sovrnBidAdapter_spec.js
Labels: needs update

#4424 IX Adapter Video Support
  modules/ixBidAdapter.js
  modules/ixBidAdapter.md
  test/spec/modules/ixBidAdapter_spec.js
Labels: needs review

#4452 Default size filter & KVP support
  modules/districtmDMXBidAdapter.js
  modules/districtmDmxBidAdapter.md
  test/spec/modules/districtmDmxBidAdapter_spec.js
Labels: needs review

#4367 Feature/smart video
  modules/smartadserverBidAdapter.js
  modules/smartadserverBidAdapter.md
  test/spec/modules/smartadserverBidAdapter_spec.js
Labels: needs update

#4439 add smms adapter
  modules/smmsBidAdapter.js
  modules/smmsBidAdapter.md
  test/spec/modules/smmsBidAdapter_spec.js
Labels: needs review

#4442 GumGum: adds schain param
  modules/gumgumBidAdapter.js
  test/spec/modules/gumgumBidAdapter_spec.js
Labels: LGTM

#4455 Create newborntownWeb adapter
  modules/newborntownWebBidAdapter.js
  modules/newborntownWebBidAdapter.md
  test/spec/modules/newborntownWebBidAdapter_spec.js
Labels: LGTM

#4338 ucfunnel adapter fix error message in debug mode
  modules/ucfunnelBidAdapter.js
  test/spec/modules/ucfunnelBidAdapter_spec.js
Labels: needs unit tests

#4467 Site id missing
  modules/oneVideoBidAdapter.js
  test/spec/modules/oneVideoBidAdapter_spec.js
Labels: needs update
