Repository prebid/Prebid.js, pull requests merged in 2019-05, with the labels that each got.

#3529 OpenX Adapter - support User ID module
  modules/openxBidAdapter.js
  test/spec/modules/openxBidAdapter_spec.js
Labels: LGTM, adapter support

#3792 add adUnitCodes as param for setTargetingForAst()
  src/prebid.js
  src/targeting.js
Labels: needs 2nd review, needs docs, needs unit tests

#3748 VI Bid Adapter Changes
  modules/viBidAdapter.js
  modules/viBidAdapter.md
  test/spec/modules/viBidAdapter_spec.js
Labels: LGTM

#3785 Add bucksense Adapter
  modules/bucksenseBidAdapter.js
  modules/bucksenseBidAdapter.md
  test/spec/modules/bucksenseBidAdapter_spec.js
Labels: LGTM

#3801 adpone: onBidWon implementation
  modules/adponeBidAdapter.js
Labels: needs review

#3804 Orbidder uses onSetTargeting callback
  modules/orbidderBidAdapter.js
  package-lock.json
  test/spec/modules/orbidderBidAdapter_spec.js
Labels: LGTM

#3765 Add Imonomy network BidAdapter
  modules/imonomyBidAdapter.js
  modules/imonomyBidAdapter.md
  test/spec/modules/imonomyBidAdapter_spec.js
Labels: LGTM

#3805 Rad 2751/specify ad units set targeting for ast
  src/targeting.js
  test/spec/unit/core/targeting_spec.js
Labels: needs update

#3793 RichAudience: Files name updated
  modules/richaudienceBidAdapter.js
  modules/richaudienceBidAdapter.md
  test/spec/modules/richaudienceBidAdapter_spec.js
Labels: LGTM

#3811 Improve Digital adapter: Endpoint update
  modules/improvedigitalBidAdapter.js
  test/spec/modules/improvedigitalBidAdapter_spec.js
Labels: LGTM

#3819 Support Prebid.js User ID module in Sharethrough bid adapter
  modules/sharethroughBidAdapter.js
  test/spec/modules/sharethroughBidAdapter_spec.js
Labels: LGTM

#3822 Cedato adapter - Added iframe user sync support
  modules/cedatoBidAdapter.js
Labels: LGTM

#3806 Gamoshi: Remove and update some bid response properties
  modules/gamoshiBidAdapter.js
  test/spec/modules/gamoshiBidAdapter_spec.js
Labels: needs review

#3814 update fun-hooks and use no-eval version for CSP
  package-lock.json
  package.json
  src/hook.js
Labels: needs 2nd review

#3774 mgid adapter: native support, minor changes
  modules/mgidBidAdapter.js
  test/spec/modules/mgidBidAdapter_spec.js
Labels: LGTM

#3829 Teads-Adapter: Update way to find referrer
  modules/teadsBidAdapter.js
  test/spec/modules/teadsBidAdapter_spec.js
Labels: question

#3835 Project Limelight bidder adapter
  modules/projectLimeLightBidAdapter.js
  modules/projectLimeLightBidAdapter.md
  test/spec/modules/projectLimeLightBidAdapter_spec.js
Labels: LGTM

#3834 PubMatic adapter support to read TTD Id from UserId module
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: needs review

#3809 Added 240x400 size
  modules/rubiconBidAdapter.js
Labels: needs review

#3820 CPMStar Bid Adapter
  modules/cpmstarBidAdapter.js
  modules/cpmstarBidAdapter.md
  test/spec/modules/cpmstarBidAdapter_spec.js
Labels: LGTM

#3831 Refactor UserId Module with external submodules
  modules/pubCommonIdSystem.js
  modules/unifiedIdSystem.js
  modules/userId.js
  modules/userId.md
  test/spec/modules/userId_spec.js
Labels: LGTM, needs 2nd review

#3828 updated ozone adapter from v1.4.4 -> v2.0.0
  modules/ozoneBidAdapter.js
  modules/ozoneBidAdapter.md
  test/spec/modules/ozoneBidAdapter_spec.js
Labels: LGTM

#3832 fix how native sizes are passed in AppNexus adapter
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: needs review

#3807 Cleanmedianet: Remove unnecessary bid response properties
  modules/cleanmedianetBidAdapter.js
Labels: needs review

#3821 change in Aardvark adapter to handle additional data
  modules/aardvarkBidAdapter.js
  test/spec/modules/aardvarkBidAdapter_spec.js
Labels: needs review

#3849 rename consentManagement setConfig function and update test page
  integrationExamples/gpt/gdpr_hello_world.html
  modules/consentManagement.js
  test/spec/modules/consentManagement_spec.js
Labels: LGTM

#3824 adxcgBidAdapter - added pubcid
  modules/adxcgBidAdapter.js
  test/spec/modules/adxcgBidAdapter_spec.js
Labels: LGTM
