Repository prebid/Prebid.js, pull requests merged in 2019-09, with the labels that each got.

#4050 Nobid Prebid Adapter commit
  modules/nobidBidAdapter.js
  modules/nobidBidAdapter.md
  test/spec/modules/nobidBidAdapter_spec.js
Labels: needs review

#4104 update outstream prod url
  modules/gridBidAdapter.js
  modules/trustxBidAdapter.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/trustxBidAdapter_spec.js
  test/spec/renderer_spec.js
Labels: needs 2nd review

#4143 JustPremium: support pubcid and uids
  modules/justpremiumBidAdapter.js
  test/spec/modules/justpremiumBidAdapter_spec.js
Labels: needs docs

#4155 Rubicon Video COPPA fix
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: bug

#4128 Datablocks bid/analytics adapter
  modules/datablocksAnalyticsAdapter.js
  modules/datablocksAnalyticsAdapter.md
  modules/datablocksBidAdapter.js
  modules/datablocksBidAdapter.md
  test/spec/modules/datablocksBidAdapter_spec.js
Labels: LGTM

#4065 update logic of ad_types field in appnexusBidAdapter
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: LGTM, needs 2nd review

#4163 Shorten SomoAudience to just Somo
  modules/somoBidAdapter.js
  modules/somoBidAdapter.md
  test/spec/modules/somoBidAdapter_spec.js
Labels: LGTM

#4142 One Video adding Rewarded Video Feature
  modules/oneVideoBidAdapter.js
  modules/oneVideoBidAdapter.md
  test/pages/video.html
  test/spec/modules/oneVideoBidAdapter_spec.js
Labels: LGTM

#4140 Module to pass User Ids to DFP
  modules/userIdTargeting.js
  modules/userIdTargeting.md
  test/spec/modules/shareUserIds_spec.js
  test/spec/unit/pbjs_api_spec.js
Labels: LGTM

#4154 fix several issues in appnexus video bids
  modules/appnexusBidAdapter.js
  src/video.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: LGTM

#4123 S2s testing disable client side
  .gitignore
  src/adapterManager.js
  test/fixtures/fixtures.js
  test/spec/unit/core/adapterManager_spec.js
Labels: feature, needs 2nd review

#4136 New option to Include deal KVPs when enableSendAllBids === false
  src/targeting.js
  test/spec/unit/core/targeting_spec.js
Labels: LGTM

#4165 if schain config is not defined then error should not be thrown
  modules/schain.js
  modules/schain.md
  test/spec/modules/schain_spec.js
Labels: LGTM

#4188 myTargetBidAdapter: support currency config
  modules/mytargetBidAdapter.js
  test/spec/modules/mytargetBidAdapter_spec.js
Labels: needs review

#4181 Added adxpremium prebid analytics adapter
  modules/adxpremiumAnalyticsAdapter.js
  modules/adxpremiumAnalyticsAdapter.md
Labels: LGTM

#4194 OpenX Adapter: Added support for schain non-rtb payload
  modules/openxBidAdapter.js
  test/spec/modules/openxBidAdapter_spec.js
Labels: LGTM

#4082 userId - Add support for refreshing the cached user id
  integrationExamples/gpt/userId_example.html
  modules/id5IdSystem.js
  modules/userId/index.js
  modules/userId/userId.md
  test/spec/modules/userId_spec.js
Labels: LGTM, needs 2nd review

#4174 Add video dimensions in request
  modules/emx_digitalBidAdapter.js
  test/spec/modules/emx_digitalBidAdapter_spec.js
Labels: needs update

#4183 Added keywords parameter support in TrustX Bid Adapter
  modules/trustxBidAdapter.js
  modules/trustxBidAdapter.md
  test/spec/modules/trustxBidAdapter_spec.js
Labels: LGTM

#4208 create stubs for localStorage in widespaceBidAdapter test file
  test/spec/modules/widespaceBidAdapter_spec.js
Labels: needs review

#4097 added adId property to adRenderFailed event
  src/prebid.js
Labels: needs 2nd review

#4182 OpenX Adapter: Forcing https requests and adding UserID module support for LiveRamp and TTD
  modules/openxBidAdapter.js
  test/spec/modules/openxBidAdapter_spec.js
Labels: LGTM, adapter support

#4191 PubMatic to support userId sub-modules
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: LGTM, adapter support

#4197 TripleLift support for UnifiedId and IdentityLink
  modules/tripleliftBidAdapter.js
  modules/tripleliftBidAdapter.md
  test/spec/modules/tripleliftBidAdapter_spec.js
Labels: LGTM, adapter support

#4195 Add Video Support for Datablocks Bid Adapter
  modules/datablocksBidAdapter.js
  modules/datablocksBidAdapter.md
  test/spec/modules/datablocksBidAdapter_spec.js
Labels: needs review

#4180 update adUnit, bidRequest and bidResponse object
  test/fixtures/fixtures.js
  test/spec/unit/core/adapterManager_spec.js
Labels: LGTM, needs 2nd review

#4209 3 display banner and video vast support for rads
  modules/radsBidAdapter.js
  modules/radsBidAdapter.md
  test/spec/modules/radsBidAdapter_spec.js
Labels: needs review

#3869 UserId - Add SameSite and server-side pubcid support
  modules/conversantBidAdapter.js
  modules/criteortusIdSystem.js
  modules/digiTrustIdSystem.js
  modules/id5IdSystem.js
  modules/identityLinkIdSystem.js
  modules/pubCommonId.js
  modules/userId/index.js
  modules/userId/pubCommonIdSystem.js
  modules/userId/unifiedIdSystem.js
  src/utils.js
  test/spec/modules/conversantBidAdapter_spec.js
  test/spec/modules/criteortusIdSystem_spec.js
  test/spec/modules/emoteevBidAdapter_spec.js
  test/spec/modules/pubCommonId_spec.js
  test/spec/modules/userId_spec.js
Labels: adapter support, needs update

#4229 added schain to appnexus bid adapter
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: LGTM

#4179 update doubleclick url
  modules/dfpAdServerVideo.js
  test/spec/modules/dfpAdServerVideo_spec.js
Labels: LGTM, needs 2nd review

#4226 Remove pbs depracated legacy url
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: 3.0 API Change, LGTM

#4088 videoNow bid adapter
  modules/videoNowBidAdapter.js
  modules/videoNowBidAdapter.md
  test/spec/modules/videoNowBidAdapter_spec.js
Labels: LGTM

#4192 djax new bidder adapter
  modules/djaxBidAdapter.js
  modules/djaxBidAdapter.md
  test/spec/modules/djaxBidAdapter_spec.js
Labels: LGTM

#4203 Added Turk Telekom Bid Adapter
  modules/turktelekomBidAdapter.js
  modules/turktelekomBidAdapter.md
  test/spec/modules/turktelekomBidAdapter_spec.js
Labels: LGTM

#4115 3952 delay auction for ids
  integrationExamples/gpt/userId_example.html
  modules/userId/index.js
  modules/userId/userId.md
  src/userSync.js
  test/spec/config_spec.js
  test/spec/modules/userId_spec.js
Labels: LGTM, needs 2nd review
