Repository prebid/Prebid.js, pull requests merged in 2019-08, with the labels that each got.

#4033 AdkernelAdn adapter minor update
  modules/adkernelAdnBidAdapter.js
  modules/adkernelAdnBidAdapter.md
  test/spec/modules/adkernelAdnBidAdapter_spec.js
Labels: needs review

#4038 Update karma to address vulnerabilities.
  .circleci/config.yml
  README.md
  gulpfile.js
  package-lock.json
  package.json
Labels: LGTM, needs 2nd review

#4051 adding supply chain Object feature
  modules/oneVideoBidAdapter.js
  modules/oneVideoBidAdapter.md
  test/spec/modules/oneVideoBidAdapter_spec.js
Labels: needs review, needs update

#4055 Adding new BidAdapter 'eywamedia'
  modules/eywamediaBidAdapter.js
  modules/eywamediaBidAdapter.md
  test/spec/modules/eywamediaBidAdapter_spec.js
Labels: needs review

#4056 Change Domain to videoreach.com
  modules/videoreachBidAdapter.js
  modules/videoreachBidAdapter.md
  test/spec/modules/videoreachBidAdapter_spec.js
Labels: needs review

#4037 Add instream & outstream video support to Criteo adapter
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: needs review

#3817 topRTBBidAdapter
  modules/topRTBBidAdapter.js
  modules/topRTBBidAdapter.md
  test/spec/modules/topRTBBidAdapter_spec.js
Labels: needs review

#4058 add check to see if adObject is present
  src/secureCreatives.js
Labels: LGTM, needs 2nd review

#4044 Consent String added to the HB request
  modules/nanointeractiveBidAdapter.js
  test/spec/modules/nanointeractiveBidAdapter_spec.js
Labels: needs update

#4049 Update URI for IdentityLink integration
  modules/identityLinkSystem.js
Labels: LGTM

#4043 adformOpenRTB adapter: parse seatbid bid responses
  modules/adformOpenRTBBidAdapter.js
  test/spec/modules/adformOpenRTBBidAdapter_spec.js
Labels: needs review

#4060 Fix Cedato adapter user sync logic
  modules/cedatoBidAdapter.js
Labels: LGTM

#4026 Improve Piximedia Adapter
  modules/piximediaBidAdapter.js
  test/spec/modules/piximediaBidAdapter_spec.js
Labels: LGTM

#4061 Rhythmone Adapter - deprecate direct usage of window objects.
  modules/rhythmoneBidAdapter.js
  test/spec/modules/rhythmoneBidAdapter_spec.js
Labels: LGTM

#4053 Fix removeAdUnit
  src/prebid.js
Labels: needs 2nd review

#4063 Fix for #4047
  modules/quantcastBidAdapter.js
  test/spec/modules/quantcastBidAdapter_spec.js
Labels: question

#4073 Criteo Adapter - Code cleaning & added missing tests to increase code coverage
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: LGTM

#4071 update to use dlv/index to fix webpack sourcemaps
  src/utils.js
Labels: needs 2nd review

#4041 Yieldmo unified id
  modules/yieldmoBidAdapter.js
  modules/yieldmoBidAdapter.md
  test/spec/modules/yieldmoBidAdapter_spec.js
Labels: LGTM

#4079 Add video support to LoopMe adapter
  modules/loopmeBidAdapter.js
  modules/loopmeBidAdapter.md
  test/spec/modules/loopmeBidAdapter_spec.js
Labels: needs review

#3960 Add bid adapter for Sublime
  modules/sublimeBidAdapter.js
  modules/sublimeBidAdapter.md
  test/spec/modules/sublimeBidAdapter_spec.js
Labels: on hold, question

#4077 Identity Link - Use ats library for retrieving envelope
  modules/identityLinkIdSystem.js
  test/spec/modules/userId_spec.js
Labels: needs review

#4096 New Adapter request : cosmos
  modules/cosmosBidAdapter.js
  modules/cosmosBidAdapter.md
  test/spec/modules/cosmosBidAdapter_spec.js
Labels: LGTM

#4092 Banner e2e
  test/pages/banner.html
  test/spec/e2e/banner/basic_banner_ad.spec.js
  test/spec/e2e/longform/basic_w_custom_adserver_translation.spec.js
  test/spec/e2e/longform/basic_w_requireExactDuration.spec.js
  test/spec/e2e/longform/basic_wo_brandCategoryExclusion.spec.js
  test/spec/e2e/longform/basic_wo_requireExactDuration.spec.js
  wdio.conf.js
Labels: needs 2nd review

#4094 Collect info about which ad units receive bids
  modules/livewrappedAnalyticsAdapter.js
  test/spec/modules/livewrappedAnalyticsAdapter_spec.js
Labels: LGTM

#3851 s2sTesting: random number moved to global
  modules/s2sTesting.js
  test/spec/modules/s2sTesting_spec.js
Labels: pinned, reviewed

#4087 consolidate logic around common chunk inclusions
  .eslintrc.js
  allowedModules.js
  webpack.conf.js
Labels: needs 2nd review

#4080 Updates to RDN Adapter
  modules/rdnBidAdapter.js
  test/spec/modules/rdnBidAdapter_spec.js
Labels: in progress, stale

#4084 SupplyChain object support in Prebid
  modules/prebidServerBidAdapter/index.js
  modules/pubmaticBidAdapter.js
  modules/schain.js
  modules/schain.md
  src/utils.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/pubmaticBidAdapter_spec.js
  test/spec/modules/schain_spec.js
Labels: LGTM
