Repository prebid/Prebid.js, pull requests merged in 2019-07, with the labels that each got.

#3956 Revert addition of video support to IX adapter as it is still in testing
  modules/ixBidAdapter.js
  modules/ixBidAdapter.md
  test/spec/modules/ixBidAdapter_spec.js
Labels: LGTM

#3928 Update emoteevBidAdapter.js
  integrationExamples/gpt/hello_world_emoteev.html
  modules/emoteevBidAdapter.js
  modules/emoteevBidAdapter.md
  test/spec/modules/emoteevBidAdapter_spec.js
Labels: needs review

#3924 Submodule system using hooks
  gulpHelpers.js
  modules/.submodules.json
  modules/adpod.js
  modules/digiTrustIdSystem.js
  modules/freeWheelAdserverVideo.js
  modules/id5IdSystem.js
  modules/userId/index.js
  modules/userId/pubCommonIdSystem.js
  modules/userId/unifiedIdSystem.js
  modules/userId/userId.md
  src/hook.js
  test/spec/modules/freeWheelAdserverVideo_spec.js
  test/spec/modules/userId_spec.js
  webpack.conf.js
Labels: needs 2nd review, on hold

#3949 Gamoshi: Add adasta new bidder alias
  modules/gamoshiBidAdapter.js
Labels: needs review

#3915 Added bid adapter for seedtag
  modules/seedtagBidAdapter.js
  modules/seedtagBidAdapter.md
  test/spec/modules/seedtagBidAdapter_spec.js
Labels: LGTM

#3944 33Across: Update GDPR handling
  modules/33acrossBidAdapter.js
  modules/33acrossBidAdapter.md
  test/spec/modules/33acrossBidAdapter_spec.js
Labels: LGTM

#3937 PulsePoint adapter - Video support + userId module support
  modules/pulsepointBidAdapter.js
  modules/pulsepointBidAdapter.md
  test/spec/modules/pulsepointBidAdapter_spec.js
Labels: needs review

#3930 Criteo real time user sync
  modules/.submodules.json
  modules/appnexusBidAdapter.js
  modules/criteortusIdSystem.js
  modules/userId/index.js
  test/spec/modules/appnexusBidAdapter_spec.js
  test/spec/modules/criteortusIdSystem_spec.js
Labels: needs docs, on hold

#3947 Rubicon add meta fields to bids
  modules/rubiconBidAdapter.js
Labels: needs review

#3938 Fix #3894 - update sizeConfig logic around multiformat bids
  src/sizeMapping.js
  test/spec/sizeMapping_spec.js
Labels: LGTM, needs 2nd review

#3976 add eslint plugin for checking imports
  .eslintrc.js
  modules/ixBidAdapter.js
  package.json
  plugins/eslint/package.json
  plugins/eslint/validateImports.js
  src/adapters/analytics/example2.js
Labels: needs 2nd review

#3885 Synacor media bidder updates: filter bad sizes & extra video parameters
  modules/synacormediaBidAdapter.js
  modules/synacormediaBidAdapter.md
  test/spec/modules/synacormediaBidAdapter_spec.js
Labels: LGTM, reviewed

#3889 Adding a method pbjs.getUserIds to share userIds in Prebid to external codes
  modules/userId/index.js
Labels: LGTM

#3881 restrict outstream w/o renderer to PBS
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: LGTM

#3986 Fix typo
  modules/admanBidAdapter.js
  test/spec/modules/admanBidAdapter_spec.js
Labels: LGTM

#3996 Fixing the issue introduced in #3845 for rubi analytics adapter
  modules/rubiconAnalyticsAdapter.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: LGTM, adapter support

#3966 update karma and webpack-stream packages to address vulnerabilities
  package-lock.json
  package.json
Labels: needs 2nd review

#3998 Kargo Adapter: fix extensible error
  modules/kargoBidAdapter.js
  test/spec/modules/kargoBidAdapter_spec.js
Labels: bug, needs review

#3992 make placementId optional
  modules/mgidBidAdapter.js
  test/spec/modules/mgidBidAdapter_spec.js
Labels: LGTM, adapter support

#3787 Google ad manager support for long-form video
  gulpHelpers.js
  modules/.submodules.json
  modules/adpod.js
  modules/categoryTranslation.js
  modules/dfpAdServerVideo.js
  modules/freeWheelAdserverVideo.js
  test/spec/modules/dfpAdServerVideo_spec.js
  test/spec/modules/freeWheelAdserverVideo_spec.js
Labels: needs docs

#3969 Added 'ceh' config property in Criteo bid adapter
  modules/criteoBidAdapter.js
  modules/criteoBidAdapter.md
  test/spec/modules/criteoBidAdapter_spec.js
Labels: LGTM

#3927 Rhythmone Adapter - Remove usersync, devicetype, and bad banners
  modules/rhythmoneBidAdapter.js
  test/spec/modules/rhythmoneBidAdapter_spec.js
Labels: needs 2nd review, needs update

#3984 update user sync to allow for multiple auction syncs
  src/userSync.js
  test/spec/userSync_spec.js
Labels: LGTM, needs 2nd review

#4002 Padsquad bid adapter
  modules/padsquadBidAdapter.js
  modules/padsquadBidAdapter.md
  test/spec/modules/padsquadBidAdapter_spec.js
Labels: LGTM, needs 2nd review

#4007 Debug update and remove setConfig hook
  src/config.js
  src/utils.js
  test/spec/debugging_spec.js
Labels: needs 2nd review

#4010 Add Logicad for Publishers bid adapter
  modules/logicadBidAdapter.js
  modules/logicadBidAdapter.md
  test/spec/modules/logicadBidAdapter_spec.js
Labels: question

#3918 DigiTrust Facade init GH Issue 3911
  modules/digiTrustIdSystem.js
  modules/digiTrustIdSystem.md
  test/spec/modules/digitrustIdSystem_spec.js
Labels: LGTM

#3965 Integrate id link system
  integrationExamples/gpt/userId_example.html
  modules/identityLinkSystem.js
  modules/userId/index.js
  modules/userId/userId.md
  test/spec/modules/userId_spec.js
Labels: LGTM, reviewed

#3990 Update rubicon analytics adapter with wrapper name
  modules/rubiconAnalyticsAdapter.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
  test/spec/modules/rubiconAnalyticsSchema.json
Labels: LGTM

#3972 TrustX Bid Adapter updating to use referrerInfo
  modules/trustxBidAdapter.js
  test/spec/modules/trustxBidAdapter_spec.js
Labels: LGTM

#4000 Adkernel adapter minor update
  modules/adkernelBidAdapter.js
  modules/adkernelBidAdapter.md
  src/utils.js
  test/spec/modules/adkernelBidAdapter_spec.js
  test/spec/utils_spec.js
Labels: needs unit tests

#3951 Add oRTB cur to PrebidServer Adapter
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: LGTM, adapter support

#4018 adformBidAdapter: currency module support
  modules/adformBidAdapter.js
  test/spec/modules/adformBidAdapter_spec.js
Labels: LGTM

#3963 Teads-adapter: Read placementId from response and add sync informations
  modules/teadsBidAdapter.js
  test/spec/modules/teadsBidAdapter_spec.js
Labels: LGTM

#3993 Deep libs and lint fix
  .eslintrc.js
  package-lock.json
  package.json
  plugins/eslint/validateImports.js
  src/utils.js
  test/spec/utils_spec.js
Labels: needs 2nd review

#4009 Update hello world example and remove other outdated GPT examples
  integrationExamples/gpt/gdpr_hello_world.html
  integrationExamples/gpt/gpt_aliasingBidder.html
  integrationExamples/gpt/hello_world.html
  integrationExamples/gpt/hello_world_emoteev.html
  integrationExamples/gpt/load_pbjs_before_dfp_example.html
  integrationExamples/gpt/load_pbjs_dfp_concurrently.html
  integrationExamples/gpt/pbjs_example_gpt.html
  integrationExamples/gpt/pbjs_innity_gpt.html
  integrationExamples/gpt/pbjs_partial_refresh_gpt.html
  integrationExamples/gpt/pbjs_yieldbot_gpt.html
  integrationExamples/gpt/pollux_example.html
  integrationExamples/gpt/unruly_example.html
Labels: needs 2nd review

#3145 Prebid server support for OpenRTB Native bids
  integrationExamples/gpt/prebidServer_native_example.html
  modules/prebidServerBidAdapter/index.js
  modules/rubiconAnalyticsAdapter.js
  src/utils.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: needs 2nd review, needs review, pinned

#4022 Appnexus native view tracker
  modules/appnexusBidAdapter.js
  src/native.js
  test/spec/modules/appnexusBidAdapter_spec.js
  test/spec/unit/pbjs_api_spec.js
Labels: LGTM

#4040 Fix referrer encoding in The Media Grid Bid Adapter
  modules/gridBidAdapter.js
  test/spec/modules/gridBidAdapter_spec.js
Labels: needs review

#3977 ucfunnel support tdid
  modules/ucfunnelBidAdapter.js
Labels: needs update
