Repository prebid/Prebid.js, pull requests merged in 2019-03, with the labels that each got.

#3586 Added LoopMe Adapter
  modules/loopmeBidAdapter.js
  modules/loopmeBidAdapter.md
  test/spec/modules/loopmeBidAdapter_spec.js
Labels: LGTM

#3589 Fix event firing on native click
  src/native.js
  src/secureCreatives.js
  test/spec/native_spec.js
Labels: needs 2nd review

#3588 Submit Advangelists Prebid Adapter
  modules/advangelistsBidAdapter.js
  modules/advangelistsBidAdapter.md
  test/spec/modules/advangelistsBidAdapter_spec.js
Labels: LGTM

#3605 fix two issues related to hb_uuid and hb_cache_id targeting keys
  modules/dfpAdServerVideo.js
  src/auction.js
  test/spec/modules/dfpAdServerVideo_spec.js
Labels: LGTM, needs 2nd review

#3608 Bug fix: Adding protocol to mapping file url
  modules/categoryTranslation.js
Labels: needs 2nd review

#3602 add default sizes value for appnexus native requests
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
  test/spec/unit/core/adapterManager_spec.js
Labels: LGTM, needs 2nd review

#3528 PBS Bid Adapter oRTB caching and video updates
  modules/prebidServerBidAdapter/index.js
  src/auction.js
  src/constants.json
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: LGTM

#3599 Added myTarget Adapter
  modules/mytargetBidAdapter.js
  modules/mytargetBidAdapter.md
  test/spec/modules/mytargetBidAdapter_spec.js
Labels: needs update

#3596 Add HTML5 video support param to bid requests
  modules/sharethroughBidAdapter.js
Labels: LGTM

#3504 update AJA adaptor: support native format
  modules/ajaBidAdapter.js
  modules/ajaBidAdapter.md
  test/spec/modules/ajaBidAdapter_spec.js
Labels: needs review, on hold

#3614 Submit Brightcom Bid Adapter
  modules/brightcomBidAdapter.js
  modules/brightcomBidAdapter.md
  test/spec/modules/brightcomBidAdapter_spec.js
Labels: LGTM

#3593 ozone adapter - fixup for gdpr and device objects
  modules/ozoneBidAdapter.js
  test/spec/modules/ozoneBidAdapter_spec.js
Labels: needs unit tests

#3601 New bid adapter for SmileWanted
  modules/smilewantedBidAdapter.js
  modules/smilewantedBidAdapter.md
  test/spec/modules/smilewantedBidAdapter_spec.js
Labels: LGTM, needs update

#3625 Update auction algorithm logic for long-form
  modules/adpod.js
  modules/freeWheelAdserverVideo.js
  src/utils.js
  test/spec/modules/adpod_spec.js
  test/spec/modules/freeWheelAdserverVideo_spec.js
Labels: needs 2nd review

#3623 update circleci test to not auto-fix lint errors
  .circleci/config.yml
  gulpfile.js
Labels: LGTM, needs 2nd review

#3578 Consumable Bid Adapter: Pass GDPR and Prebid version info. Pixel syncs.
  modules/consumableBidAdapter.js
  test/spec/modules/consumableBidAdapter_spec.js
Labels: needs review

#3630 Add brand ID to OpenX bid responses
  modules/openxBidAdapter.js
  test/spec/modules/openxBidAdapter_spec.js
Labels: LGTM

#3615 Sonobi - Analytics Adapter
  modules/sonobiAnalyticsAdapter.js
  modules/sonobiAnalyticsAdapter.md
  test/spec/modules/sonobiAnalyticsAdapter_spec.js
Labels: LGTM, adapter support

#3652 Add 'hb_cache_host' and 'hb_cache_path' targeting for video bids when cache is set
  src/auction.js
  src/constants.json
  test/spec/auctionmanager_spec.js
Labels: needs 2nd review

#3598 Adding Optimera/AppNexus workaround documentation
  modules/optimeraBidAdapter.md
Labels: stale

#3619 Add buyer data to Pubmatic bid responses
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: LGTM

#3575 modules: Implement SmartRTB adapter and spec.
  modules/smartrtbBidAdapter.js
  modules/smartrtbBidAdapter.md
  test/spec/modules/smartrtbBidAdapter_spec.js
Labels: LGTM

#3639 ADman Media new bidder adapter
  modules/admanBidAdapter.js
  modules/admanBidAdapter.md
  test/spec/modules/admanBidAdapter_spec.js
Labels: needs update, reviewed

#3648 Improve Digital adapter: use Prebid sizes param
  modules/improvedigitalBidAdapter.js
  test/spec/modules/improvedigitalBidAdapter_spec.js
Labels: LGTM

#3668 Add hb_uuid and hb_cache_id back to dfp module
  modules/dfpAdServerVideo.js
  test/spec/modules/dfpAdServerVideo_spec.js
Labels: needs 2nd review

#3679 fix spelling of 'country'
  modules/etargetBidAdapter.js
Labels: LGTM

#3672 Kargo migration to localstorage alternatives
  modules/kargoBidAdapter.js
  test/spec/modules/kargoBidAdapter_spec.js
Labels: LGTM

#3634 ReklamStore Bid Adapter
  modules/reklamstoreBidAdapter.js
  modules/reklamstoreBidAdapter.md
  test/spec/modules/reklamstoreBidAdapter_spec.js
Labels: needs update

#3675 support userId module
  modules/yieldmoBidAdapter.js
  test/spec/modules/yieldmoBidAdapter_spec.js
Labels: needs review

#3670 Rubicon Bid Adapter: custom price granularity fix
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: adapter support, bug

#3682 Added MediaFuse Lift alias to Orbitsoft adapter
  modules/orbitsoftBidAdapter.js
Labels: LGTM, adapter support

#3674 Ensure width and height are integers
  src/adapters/bidderFactory.js
Labels: needs 2nd review

#3680 update aja adaptor: forgot privacyLink for Native
  modules/ajaBidAdapter.js
  modules/ajaBidAdapter.md
  test/spec/modules/ajaBidAdapter_spec.js
Labels: LGTM

#3690 Finteza adapter: fix request params
  modules/fintezaAnalyticsAdapter.js
  modules/fintezaAnalyticsAdapter.md
  test/spec/modules/fintezaAnalyticsAdapter_spec.js
Labels: LGTM
