Repository prebid/Prebid.js, pull requests merged in 2019-06, with the labels that each got.

#3808 Bugfix add bid parameters if not present
  modules/orbidderBidAdapter.js
  test/spec/modules/orbidderBidAdapter_spec.js
Labels: question

#3874 Use actual global object name in log message
  modules/dfpAdServerVideo.js
  src/video.js
Labels: needs 2nd review

#3772 New STAQ analytics adapter
  modules/staqAnalyticsAdapter.js
  modules/staqAnalyticsAdapter.md
  test/spec/modules/staqAnalyticsAdapter_spec.js
Labels: needs docs

#3871 New Analytics Adapter: Implement Appier Analytics Adapter.
  modules/appierAnalyticsAdapter.js
  modules/appierAnalyticsAdapter.md
  test/spec/modules/appierAnalyticsAdapter_spec.js
Labels: LGTM

#3848 Adding aliases for adsparc and safereach to aardvark adapter
  modules/aardvarkBidAdapter.js
  modules/serverbidBidAdapter.js
Labels: needs update

#3880 Add SlimCut bid adapter
  modules/slimcutBidAdapter.js
  modules/slimcutBidAdapter.md
  test/spec/modules/slimcutBidAdapter_spec.js
Labels: LGTM

#3892 Aardvark adapter, add width & height params
  modules/aardvarkBidAdapter.js
  test/spec/modules/aardvarkBidAdapter_spec.js
Labels: needs docs

#3886 Add bidFloor to Yieldmo Adapter
  modules/yieldmoBidAdapter.js
  modules/yieldmoBidAdapter.md
  test/spec/modules/yieldmoBidAdapter_spec.js
Labels: needs docs

#3868 Add beachfront bidder params to set outstream player settings
  modules/beachfrontBidAdapter.js
  modules/beachfrontBidAdapter.md
  test/spec/modules/beachfrontBidAdapter_spec.js
Labels: LGTM

#3846 Adding Scaleable Analytics Adapter
  modules/scaleableAnalyticsAdapter.js
  modules/scaleableAnalyticsAdapter.md
  test/spec/modules/scaleableAnalyticsAdapter_spec.js
Labels: needs update

#3913 digiTrustIdSystem.js add the synchronous behavior to facade call of D…
  modules/digiTrustIdSystem.js
Labels: LGTM, feature

#3891 FeedAd bidder adapter
  modules/feedadBidAdapter.js
  modules/feedadBidAdapter.md
  test/spec/modules/feedadBidAdapter_spec.js
Labels: needs update

#3841 Fix #3813 move auctionEnd events so it always executes when auction completes
  src/auction.js
  test/spec/auctionmanager_spec.js
Labels: LGTM, needs 2nd review

#3921 Fix #3917 fix import paths for various adapters
  modules/advenueBidAdapter.js
  modules/bidphysicsBidAdapter.js
  modules/cedatoBidAdapter.js
  modules/digiTrustIdSystem.js
  modules/emx_digitalBidAdapter.js
  modules/imonomyBidAdapter.js
  modules/loopmeBidAdapter.js
  modules/mgidBidAdapter.js
  modules/microadBidAdapter.js
  modules/open8BidAdapter.js
  modules/otmBidAdapter.js
  modules/prebidmanagerAnalyticsAdapter.js
  modules/reklamstoreBidAdapter.js
  modules/slimcutBidAdapter.js
  modules/smartrtbBidAdapter.js
  modules/sortableAnalyticsAdapter.js
  modules/timBidAdapter.js
  modules/yieldoneBidAdapter.js
Labels: LGTM, needs 2nd review

#3914 add --analyze arg for webpack bundle analyzing
  package-lock.json
  package.json
  webpack.conf.js
Labels: needs review

#3935 Digitrust support in PBS bid adapter and Rubicon bid adapter
  modules/prebidServerBidAdapter/index.js
  modules/rubiconBidAdapter.js
  src/utils.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: needs 2nd review

#3798 ID5 userId submodule
  integrationExamples/gpt/userId_example.html
  modules/id5IdSystem.js
  modules/userId.js
  modules/userId.md
  test/spec/modules/userId_spec.js
Labels: LGTM

#3929 EMX Digital: Device info and Video parameter updates
  modules/emx_digitalBidAdapter.js
  test/spec/modules/emx_digitalBidAdapter_spec.js
Labels: needs update

#3920 [33Across adapter] Map ad unit path to element id
  modules/33acrossBidAdapter.js
  modules/33acrossBidAdapter.md
  test/spec/modules/33acrossBidAdapter_spec.js
Labels: needs review

#3861 New Adapter: bidglass
  modules/bidglassBidAdapter.js
  modules/bidglassBidAdapter.md
  test/spec/modules/bidglassAdapter_spec.js
Labels: LGTM

#3916 ozone adapter 2.1 - bug fix for multi bids + GDPR parameter handling
  modules/ozoneBidAdapter.js
  modules/ozoneBidAdapter.md
  test/spec/modules/ozoneBidAdapter_spec.js
Labels: needs docs
