Repository prebid/Prebid.js, pull requests merged in 2019-02, with the labels that each got.

#3493 Fix issue where the ${AUCTION_PRICE} macro was not being replaced in secure creatives
  src/secureCreatives.js
  test/spec/unit/secureCreatives_spec.js
Labels: needs review, needs unit tests

#3503 Onevideo adapter support for new params
  modules/oneVideoBidAdapter.js
  modules/oneVideoBidAdapter.md
  test/spec/modules/oneVideoBidAdapter_spec.js
Labels: needs review

#3523 add adpod to mediaTypes
  src/mediaTypes.js
Labels: adpod

#3496 Fix requestId field
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: LGTM

#3437 Add support to pass custom key in Prebid cache request
  src/videoCache.js
  test/spec/videoCache_spec.js
Labels: LGTM, adpod, on hold

#3440 generate bid.adId uniquely instead of using bidRequest.bidId
  modules/currency.js
  src/auction.js
  src/bidfactory.js
  src/native.js
  src/utils.js
  src/video.js
  test/spec/auctionmanager_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/serverbidServerBidAdapter_spec.js
  test/spec/native_spec.js
  test/spec/unit/core/bidderFactory_spec.js
  test/spec/video_spec.js
Labels: LGTM, adpod

#3438 create some hooks and modify adServerManager function
  src/adServerManager.js
  src/adapterManager.js
  src/auction.js
  src/prebid.js
  src/utils.js
  src/video.js
  test/spec/unit/adServerManager_spec.js
  test/spec/unit/core/adapterManager_spec.js
  test/spec/unit/pbjs_api_spec.js
Labels: adpod

#3508 YieldNexus: Rename adapter's name
  modules/yieldnexusBidAdapter.js
  modules/yieldnexusBidAdapter.md
  test/spec/modules/yieldnexusBidAdapter_spec.js
Labels: needs docs

#3471 Support new param in tag call to ZEDO
  integrationExamples/gpt/pbjs_example_gpt.html
  modules/zedoBidAdapter.js
  modules/zedoBidAdapter.md
  test/spec/modules/zedoBidAdapter_spec.js
Labels: stale

#3481 Admedia adapter
  modules/admediaBidAdapter.js
  modules/admediaBidAdapter.md
  test/spec/modules/admediaBidAdapter_spec.js
Labels: LGTM

#3530 Prebid Server Adapter - support User ID module
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: needs 2nd review

#3537 fixes #3536 map video.playerSize to bid.sizes
  src/adapterManager.js
Labels: needs 2nd review

#3542 checking usConfig.enableOverride value before returning
  src/userSync.js
Labels: needs 2nd review

#3546 OpenX Analytics is throwing an undefined error
  modules/openxAnalyticsAdapter.js
  test/spec/modules/openxAnalyticsAdapter_spec.js
Labels: needs review

#3559 Sonobi - Outstream Support
  modules/sonobiBidAdapter.js
  test/spec/modules/sonobiBidAdapter_spec.js
Labels: LGTM

#3543 minor safety check added
  modules/trionBidAdapter.js
Labels: needs review

#3524 bugfix for Firefox for some ads that use document.write
  src/prebid.js
  test/spec/unit/pbjs_api_spec.js
Labels: needs 2nd review

#3545 Add video support in Grid Bid Adapter
  modules/gridBidAdapter.js
  modules/gridBidAdapter.md
  test/spec/modules/gridBidAdapter_spec.js
Labels: needs review

#3561 Add Adtelligent gdpr support
  modules/adtelligentBidAdapter.js
  test/spec/modules/adtelligentBidAdapter_spec.js
Labels: needs update

#3525 New Adapter VMG
  modules/vmgBidAdapter.js
  modules/vmgBidAdapter.md
  test/spec/modules/vmgBidAdapter_spec.js
Labels: needs update

#3521 New bid adapter for OPEN8
  modules/open8BidAdapter.js
  modules/open8BidAdapter.md
  test/spec/modules/open8BidAdapter_spec.js
Labels: LGTM

#3550 added setTargeting code for custom key-value pairs
  modules/ozoneBidAdapter.js
  test/spec/modules/ozoneBidAdapter_spec.js
Labels: LGTM, adapter support

#3562 mgidAdapter
  modules/mgidBidAdapter.js
  modules/mgidBidAdapter.md
  test/spec/modules/mgidBidAdapter_spec.js
Labels: LGTM

#3571 Audience Network: upgrade bid requests to use latest SDK
  modules/audienceNetworkBidAdapter.js
  test/spec/modules/audienceNetworkBidAdapter_spec.js
Labels: LGTM

#3563 Update TrustX Bid Adapter
  modules/trustxBidAdapter.js
  test/spec/modules/trustxBidAdapter_spec.js
Labels: needs review

#3582 Cleanmedianet: Add cleanmedianet bidder adapter
  modules/cleanmedianetBidAdapter.js
  modules/cleanmedianetBidAdapter.md
  test/spec/modules/cleanmedianetBidAdapter_spec.js
Labels: needs update

#3574 update fun-hooks to latest and update api
  modules/currency.js
  modules/prebidServerBidAdapter/index.js
  package-lock.json
  package.json
  src/auction.js
  src/hook.js
  src/prebid.js
  src/utils.js
Labels: LGTM, needs 2nd review

#3511 Adpod module
  modules/adpod.js
  src/auction.js
  src/hook.js
  src/prebid.js
  src/video.js
  test/spec/modules/adpod_spec.js
Labels: LGTM, adpod

#3489 Adding freewheel module
  modules/freeWheelAdserverVideo.js
  test/spec/modules/freeWheelAdserverVideo_spec.js
Labels: LGTM, adpod, needs docs

#3513 Category translation module for adpod
  modules/appnexusBidAdapter.js
  modules/categoryTranslation.js
  package-lock.json
  src/adapters/bidderFactory.js
  src/utils.js
  test/spec/modules/categoryTranslation_spec.js
  test/spec/unit/core/bidderFactory_spec.js
Labels: LGTM, adpod, needs review

#3484 Add adpod support to AppNexus adapter
  modules/appnexusBidAdapter.js
  src/utils.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: LGTM, adpod, on hold

#3558 update targeting's getBidsReceived to not include adpod bids
  src/targeting.js
  test/spec/unit/core/targeting_spec.js
Labels: LGTM

#3573 Send placeholders for configured native assets
  src/auction.js
  src/native.js
  src/secureCreatives.js
  src/utils.js
  test/spec/native_spec.js
Labels: LGTM, needs 2nd review

#3565 New bidder adapter for MicroAd
  modules/microadBidAdapter.js
  modules/microadBidAdapter.md
  test/spec/modules/microadBidAdapter_spec.js
Labels: LGTM
