Repository prebid/Prebid.js, pull requests merged in 2020-10, with the labels that each got.

#5808 appnexus bid adapter: move criteo data back to tpuids
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: LGTM

#5797 Intentiq id add validation
  modules/intentIqIdSystem.js
  test/spec/modules/intentIqIdSystem_spec.js
Labels: needs review

#5807 Adot bid adapter: add native preset handling and automatic price macro replacement
  modules/adotBidAdapter.js
  modules/adotBidAdapter.md
  test/spec/modules/adotBidAdapter_spec.js
Labels: LGTM

#5803 expose full user id config (including storage) to user id modules
  modules/britepoolIdSystem.js
  modules/criteoIdSystem.js
  modules/haloIdSystem.js
  modules/id5IdSystem.js
  modules/identityLinkIdSystem.js
  modules/intentIqIdSystem.js
  modules/liveIntentIdSystem.js
  modules/lotamePanoramaIdSystem.js
  modules/merkleIdSystem.js
  modules/netIdSystem.js
  modules/parrableIdSystem.js
  modules/pubCommonIdSystem.js
  modules/pubProvidedSystem.js
  modules/sharedIdSystem.js
  modules/unifiedIdSystem.js
  modules/userId/index.js
  modules/zeotapIdPlusIdSystem.js
  test/spec/modules/britepoolIdSystem_spec.js
  test/spec/modules/id5IdSystem_spec.js
  test/spec/modules/identityLinkIdSystem_spec.js
  test/spec/modules/intentIqIdSystem_spec.js
  test/spec/modules/liveIntentIdSystem_spec.js
  test/spec/modules/parrableIdSystem_spec.js
  test/spec/modules/userId_spec.js
Labels: needs docs

#5821 Appnexus: Add omid support
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: needs review

#5796 Integrate option to pass clickThrough urls to renderAd method
  src/prebid.js
  src/utils.js
  test/spec/unit/pbjs_api_spec.js
Labels: needs 2nd review

#5826 IDx user id submodule
  modules/.submodules.json
  modules/idxIdSystem.js
  modules/idxIdSystem.md
  modules/userId/eids.js
  test/spec/modules/idxIdSystem_spec.js
Labels: needs docs

#5831 Adding Test mode for the IronSource bidder
  modules/ironsourceBidAdapter.js
  modules/ironsourceBidAdapter.md
  test/spec/modules/ironsourceBidAdapter_spec.js
Labels: LGTM

#5773 Add vuukle adapter
  modules/vuukleBidAdapter.js
  modules/vuukleBidAdapter.md
  test/spec/modules/vuukleBidAdapter_spec.js
Labels: needs review

#5830 add stroeerCoreBidAdapter
  modules/stroeerCoreBidAdapter.js
  modules/stroeerCoreBidAdapter.md
  test/spec/modules/stroeerCoreBidAdapter_spec.js
Labels: LGTM

#5819 Force refresh userId
  modules/userId/index.js
  test/spec/modules/userId_spec.js
  test/spec/modules/zeotapIdPlusIdSystem_spec.js
Labels: needs 2nd review

#5754 Hybrid adapter. Added support In-Image format
  modules/hybridBidAdapter.js
  modules/hybridBidAdapter.md
  test/spec/modules/hybridBidAdapter_spec.js
Labels: LGTM

#5839 ATS-analytics - add retry logic to not fire request for envelope every time, and cut down analytics requests to 1/10
  modules/atsAnalyticsAdapter.js
  modules/identityLinkIdSystem.js
  test/spec/modules/atsAnalyticsAdapter_spec.js
  test/spec/modules/identityLinkIdSystem_spec.js
Labels: LGTM

#5841 Fix size validate
  modules/relaidoBidAdapter.js
  test/spec/modules/relaidoBidAdapter_spec.js
Labels: LGTM

#5850 Add sharedid support to pubcommon
  modules/pubCommonIdSystem.js
  test/spec/modules/userId_spec.js
Labels: needs docs

#5862 PR Review process tweaks
  PR_REVIEW.md
Labels: LGTM

#5861 Rename pubProvidedSystem.js to pubProvidedIdSystem.js
  modules/pubProvidedIdSystem.js
  test/spec/modules/userId_spec.js
Labels: bug

#5844 [AD-963] - Update JW Player RTD Provider for compliance with RTD Module Phase 3
  integrationExamples/gpt/jwplayerRtdProvider_example.html
  modules/gridBidAdapter.js
  modules/jwplayerRtdProvider.js
  modules/jwplayerRtdProvider.md
  test/spec/modules/gridBidAdapter_spec.js
  test/spec/modules/jwplayerRtdProvider_spec.js
Labels: LGTM

#5774 Reconciliation Real Time Data Provider
  integrationExamples/gpt/reconciliationRtdProvider_example.html
  modules/.submodules.json
  modules/reconciliationRtdProvider.js
  modules/reconciliationRtdProvider.md
  test/spec/modules/reconciliationRtdProvider_spec.js
Labels: needs 2nd review

#5872 Update instream logic to account for multimp
  modules/tripleliftBidAdapter.js
  test/spec/modules/tripleliftBidAdapter_spec.js
Labels: needs review, needs unit tests

#5786 Verizon Media user id module
  modules/.submodules.json
  modules/userId/eids.js
  modules/userId/eids.md
  modules/verizonMediaIdSystem.js
  modules/verizonMediaSystemId.md
  test/spec/modules/verizonMediaIdSystem_spec.js
Labels: LGTM

#5840 Use new ad request format by default in TheMediaGrid Bid Adapter
  modules/gridBidAdapter.js
  modules/gridBidAdapter.md
  test/spec/modules/gridBidAdapter_spec.js
Labels: LGTM

#5805 Floors Module update to include floorMin
  modules/priceFloors.js
  modules/rubiconAnalyticsAdapter.js
  test/spec/modules/priceFloors_spec.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
Labels: LGTM

#5880 (Sovrn) Configurable TTL from bid response
  modules/sovrnBidAdapter.js
  test/spec/modules/sovrnBidAdapter_spec.js
Labels: LGTM

#5864 Rubicon Bid Adapter - Interpret response adds new meta values
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: LGTM

#5892 [AD-1020] JWPlayer RTD: Obtain targeting params from FPD
  integrationExamples/gpt/jwplayerRtdProvider_example.html
  modules/jwplayerRtdProvider.js
  modules/jwplayerRtdProvider.md
  test/spec/modules/jwplayerRtdProvider_spec.js
Labels: LGTM

#5760 Media type renderers
  src/auction.js
  src/video.js
  test/spec/auctionmanager_spec.js
  test/spec/video_spec.js
Labels: LGTM

#5833 New krushmedia Prebid.js adapter
  modules/krushmediaBidAdapter.js
  modules/krushmediaBidAdapter.md
  test/spec/modules/krushmediaBidAdapter_spec.js
Labels: LGTM

#5881 eTarget: adapter update
  modules/etargetBidAdapter.js
  test/spec/modules/etargetBidAdapter_spec.js
Labels: needs update
