Repository prebid/Prebid.js, pull requests merged in 2020-07, with the labels that each got.

#5379 delay request to server by 5 min if we no ads
  modules/proxistoreBidAdapter.js
  test/spec/modules/proxistoreBidAdapter_spec.js
Labels: LGTM

#5425 Added support for userId modules in adform adapters
  modules/adformBidAdapter.js
  modules/adformOpenRTBBidAdapter.js
  test/spec/modules/adformBidAdapter_spec.js
  test/spec/modules/adformOpenRTBBidAdapter_spec.js
Labels: LGTM

#5448 Eplanning fix: decode parameters
  modules/eplanningBidAdapter.js
  test/spec/modules/eplanningBidAdapter_spec.js
Labels: LGTM

#5438 Remove digitrust from prebid server js adapter
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: needs 2nd review

#5388 Add lotame id system
  integrationExamples/gpt/userId_example.html
  modules/.submodules.json
  modules/lotamePanoramaIdSystem.js
  modules/lotamePanoramaIdSystem.md
  modules/userId/eids.js
  test/spec/modules/eids_spec.js
  test/spec/modules/lotamePanoramaIdSystem_spec.js
Labels: LGTM

#5465 oneVideo Adapter Support for Global & Bidder Specific Supply Chain Object Module (SAPR-13809)
  modules/oneVideoBidAdapter.js
  modules/oneVideoBidAdapter.md
  test/spec/modules/oneVideoBidAdapter_spec.js
Labels: question

#5464 Re-add AMX adapter (fixed)
  modules/amxBidAdapter.js
  modules/amxBidAdapter.md
  test/spec/modules/amxBidAdapter_spec.js
Labels: LGTM

#5429 Interactive advertising bureau digitrust exit
  integrationExamples/gpt/digitrust_Full.html
  integrationExamples/gpt/digitrust_Simple.html
  integrationExamples/gpt/digitrust_cmp_test.html
  modules/.submodules.json
  modules/digiTrustIdSystem.js
  modules/digiTrustIdSystem.md
  modules/userId/eids.js
  modules/userId/eids.md
  test/spec/modules/digitrustIdSystem_spec.js
  test/spec/modules/eids_spec.js
Labels: Prebid 4.0

#5471 Appnexus Bid Adapter - rtb.trackers field optional
  modules/appnexusBidAdapter.js
Labels: needs review

#5500 Set cookie domain in pubcid / userid on main domain, not subdomain
  modules/pubCommonIdSystem.js
  modules/userId/index.js
  test/spec/modules/userId_spec.js
Labels: Prebid 4.0, needs 2nd review

#5423 TrueReach Bidder Adapter
  modules/truereachBidAdapter.js
  modules/truereachBidAdapter.md
  test/spec/modules/truereachBidAdapter_spec.js
Labels: needs update

#5437 Add meta.advertiserDomains to pbs adapter
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: needs 2nd review

#5494 mantis privacy support, removed unsupported media types
  modules/mantisBidAdapter.js
  test/spec/modules/mantisBidAdapter_spec.js
Labels: needs review

#5490 Lunamedia ad size parameter update
  modules/lunamediaBidAdapter.js
  modules/lunamediaBidAdapter.md
  test/spec/modules/lunamediaBidAdapter_spec.js
Labels: LGTM

#5427 drop support for userId configs with the `usersync` config object, pe…
  modules/britepoolIdSystem.md
  modules/sharedIdSystem.md
  modules/userId/index.js
  modules/userId/userId.md
  modules/userIdTargeting.md
  test/spec/modules/userId_spec.js
Labels: Prebid 4.0

#5452 Update consentManagementUsp.js to not store and reuse null consent
  modules/consentManagementUsp.js
  test/spec/modules/consentManagementUsp_spec.js
Labels: needs 2nd review

#5506 [synacormedia] Update adapter to support Consent Management Module
  modules/synacormediaBidAdapter.js
  test/spec/modules/synacormediaBidAdapter_spec.js
Labels: needs unit tests

#5418 New bid adapter for Smaato
  modules/smaatoBidAdapter.js
  modules/smaatoBidAdapter.md
  test/spec/modules/smaatoBidAdapter_spec.js
Labels: LGTM

#5522 Fix double encoded targeting string for Yieldlab adapter
  modules/yieldlabBidAdapter.js
  test/spec/modules/yieldlabBidAdapter_spec.js
Labels: LGTM

#5487 Advanced Size Mapping - Code Refactoring.
  modules/sizeMappingV2.js
  src/prebid.js
  test/spec/modules/pubCommonId_spec.js
  test/spec/modules/sizeMappingV2_spec.js
  test/spec/unit/pbjs_api_spec.js
Labels: needs 2nd review

#5445 AdkernelAdn: Configurable user-sync types support
  modules/adkernelAdnBidAdapter.js
Labels: LGTM

#5492 GumGum: add default sizes
  modules/gumgumBidAdapter.js
  test/spec/modules/gumgumBidAdapter_spec.js
Labels: needs unit tests

#5525 Pbadslot phase2
  modules/prebidServerBidAdapter/index.js
  modules/rubiconBidAdapter.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: needs 2nd review

#5363 Add host field into limelight bidder adapter
  modules/projectLimeLightBidAdapter.js
  modules/projectLimeLightBidAdapter.md
  test/spec/modules/projectLimeLightBidAdapter_spec.js
Labels: LGTM

#5482 Instream and Outstream video support for medianetBidAdapter
  modules/medianetBidAdapter.js
  modules/medianetBidAdapter.md
  test/spec/modules/medianetBidAdapter_spec.js
Labels: LGTM

#5549 pubGENIUS bid adapter: fix schain, use canonical URL and send page referrer
  modules/pubgeniusBidAdapter.js
  test/spec/modules/pubgeniusBidAdapter_spec.js
Labels: needs review

#5539 Pb ad slot module
  modules/gptPreAuction.js
  test/spec/modules/gptPreAuction_spec.js
Labels: needs docs

#5538 Update floors module for #5511
  modules/priceFloors.js
  modules/priceFloors.md
  test/spec/modules/priceFloors_spec.js
Labels: needs docs

#5541 New request format for The Media Grid Bid Adapter
  modules/gridBidAdapter.js
  test/spec/modules/gridBidAdapter_spec.js
Labels: needs update

#5504 fixed bug with sortByDealAndPriceBucketOrCpm
  src/targeting.js
  test/spec/unit/core/targeting_spec.js
Labels: needs 2nd review

#5509 Replace third party deep-equal library with native implementation
  allowedModules.js
  package-lock.json
  package.json
  src/utils.js
  test/spec/utils_spec.js
Labels: needs review
