Repository prebid/Prebid.js, pull requests merged in 2020-11, with the labels that each got.

#5910 DMX Fix video bug
  modules/districtmDMXBidAdapter.js
  test/spec/modules/districtmDmxBidAdapter_spec.js
Labels: LGTM

#5856 IX missing sizes testing and diagnosis
  modules/ixBidAdapter.js
  modules/ixBidAdapter.md
  test/spec/modules/ixBidAdapter_spec.js
Labels: LGTM

#5868 feat: add the elapsed time to events for debugging
  src/events.js
  src/utils.js
Labels: needs 2nd review

#5787 Add Auction Options Config
  src/auction.js
  src/config.js
  test/spec/auctionmanager_spec.js
  test/spec/config_spec.js
Labels: LGTM

#5923 rubicon - support all userIds
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: needs review

#5927 Smaato BidAdapter: Add support for userIds
  modules/smaatoBidAdapter.js
  test/spec/modules/smaatoBidAdapter_spec.js
Labels: LGTM

#5906 LunamediaHB bid adapter
  modules/lunamediahbBidAdapter.js
  modules/lunamediahbBidAdapter.md
  test/spec/modules/lunamediahbBidAdapter_spec.js
Labels: LGTM

#5925 Add User ID Targeting to googletag.cmd as a fallback when GPT API is not ready
  modules/userIdTargeting.js
  test/spec/modules/shareUserIds_spec.js
Labels: needs unit tests

#5794 No bid version 1.2.9
  modules/nobidBidAdapter.js
  test/spec/modules/nobidBidAdapter_spec.js
Labels: LGTM, needs docs

#5891 userId module: fix auctionDelay submodules with callbacks
  modules/userId/index.js
  test/spec/modules/userId_spec.js
Labels: LGTM

#5813 Zeta-Prebid
  modules/zetaBidAdapter.js
  modules/zetaBidAdapter.md
  test/spec/modules/zetaBidAdapter_spec.js
Labels: needs docs, needs review

#5974 Update pubCommonIdSystem.js
  modules/pubCommonIdSystem.js
Labels: maintenance

#5932 added feature/getNoBidsForAdUnitCode function
  src/prebid.js
  test/spec/api_spec.js
Labels: LGTM, needs 2nd review

#5988 Update sharedIdSystem.js
  modules/sharedIdSystem.js
Labels: maintenance

#5969 FreeWheel SSP - Added GDPR to userSync
  modules/freewheel-sspBidAdapter.js
  test/spec/modules/freewheel-sspBidAdapter_spec.js
Labels: LGTM

#5951 Fix request size validate
  modules/relaidoBidAdapter.js
  test/spec/modules/relaidoBidAdapter_spec.js
Labels: LGTM

#5866 Prebid Server Bid Adapter: Expose errors and server response times always
  modules/prebidServerBidAdapter/index.js
  modules/rubiconAnalyticsAdapter.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
Labels: LGTM

#5981 Add consent to sync url
  modules/admanBidAdapter.js
Labels: needs docs

#5983 add provider as an option in id5 config params to identify prebid identity wrappers
  modules/id5IdSystem.js
  modules/id5IdSystem.md
  test/spec/modules/id5IdSystem_spec.js
Labels: maintenance

#5973 Instream video support for Yieldmo adapter
  modules/yieldmoBidAdapter.js
  modules/yieldmoBidAdapter.md
  test/spec/modules/yieldmoBidAdapter_spec.js
Labels: LGTM

#5915 PubxAi analytics adapter
  modules/pubxaiAnalyticsAdapter.js
  modules/pubxaiAnalyticsAdapter.md
  test/spec/modules/pubxaiAnalyticsAdapter_spec.js
Labels: LGTM

#5987 Appnexus: Update maintainer
  modules/appnexusBidAdapter.md
Labels: LGTM

#6001 New haxmedia bidder adapter
  modules/haxmediaBidAdapter.js
  modules/haxmediaBidAdapter.md
  test/spec/modules/haxmediaBidAdapter_spec.js
Labels: needs review

#5993 [Triplelift] Add advertiserDomains support
  modules/tripleliftBidAdapter.js
  test/spec/modules/tripleliftBidAdapter_spec.js
Labels: needs review

#5941 sspBC adapter: update to v4.6 (notifications, user sync)
  modules/sspBCAdapter.js
  test/spec/modules/sspBCAdapter_spec.js
Labels: LGTM

#6025 Appnexus - Send CriteoId in eids array.
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: needs review

#6027 Pass user ids in bid request
  modules/districtmDMXBidAdapter.js
Labels: LGTM

#6024 Admixer adapter update - add user syncs
  modules/admixerBidAdapter.js
  test/spec/modules/admixerBidAdapter_spec.js
Labels: LGTM

#5972 Add support for `backupOnly` option in mediaType video renderer
  src/Renderer.js
  src/auction.js
  test/spec/auctionmanager_spec.js
  test/spec/renderer_spec.js
Labels: LGTM

#5978 New mobfox prebid adapter
  modules/mobfoxpbBidAdapter.js
  modules/mobfoxpbBidAdapter.md
  test/spec/modules/mobfoxpbBidAdapter_spec.js
Labels: LGTM

#5957 Update adkernelBidAdapter.js
  modules/adkernelBidAdapter.js
  test/spec/modules/adkernelBidAdapter_spec.js
Labels: needs unit tests

#5994 remove pubcommon optout from user id module checks
  modules/userId/index.js
  test/spec/modules/userId_spec.js
Labels: maintenance, needs review

#6032 ID5 ID module - pass gdpr and usp parameters in body instead of querystring
  modules/id5IdSystem.js
  test/spec/modules/id5IdSystem_spec.js
Labels: maintenance
