Repository prebid/Prebid.js, pull requests merged in 2020-06, with the labels that each got.

#5296 Adtarget bid adapter
  modules/adtargetBidAdapter.js
  modules/adtargetBidAdapter.md
  test/spec/modules/adtargetBidAdapter_spec.js
Labels: LGTM

#5278 ucfunnel adapter update request parameter
  modules/ucfunnelBidAdapter.js
  test/spec/modules/ucfunnelBidAdapter_spec.js
Labels: LGTM, needs review

#5182 AdxPremium Analytics - bug fixes, handling timeout, etc.
  modules/adxpremiumAnalyticsAdapter.js
  modules/adxpremiumAnalyticsAdapter.md
  test/spec/modules/adxpremiumAnalyticsAdapter_spec.js
Labels: LGTM

#5277 Update Dspx adapter
  modules/dspxBidAdapter.js
  modules/dspxBidAdapter.md
  test/spec/modules/dspxBidAdapter_spec.js
Labels: needs review

#5324 Run full suite of unit tests
  test/spec/modules/adtargetBidAdapter_spec.js
Labels: needs review

#5285 Secure creative update
  integrationExamples/gpt/x-domain/creative.html
  src/secureCreatives.js
  test/spec/unit/pbjs_api_spec.js
  test/spec/unit/secureCreatives_spec.js
Labels: needs 2nd review

#5327 Update Usersync Url For Quantumdex bid adapter
  modules/quantumdexBidAdapter.js
Labels: LGTM

#5318 Fix secure protocol check in Beachfront adapter
  modules/beachfrontBidAdapter.js
Labels: LGTM

#5317 new bidder adapter: mediasquareBidAdapter
  modules/mediasquareBidAdapter.js
  modules/mediasquareBidAdapter.md
  test/spec/modules/mediasquareBidAdapter_spec.js
Labels: LGTM

#5297 GumGum: adds new param
  modules/gumgumBidAdapter.js
  test/spec/modules/gumgumBidAdapter_spec.js
Labels: needs review

#5262 Avocet bid adapter
  modules/avocetBidAdapter.js
  modules/avocetBidAdapter.md
  test/spec/modules/avocetBidAdapter_spec.js
Labels: not receiving bids

#5111 Vidazoo: Feature support usp consent
  modules/vidazooBidAdapter.js
  test/spec/modules/vidazooBidAdapter_spec.js
Labels: LGTM

#5328 Add module H12 Media
  modules/h12mediaBidAdapter.js
  modules/h12mediaBidAdapter.md
  test/spec/modules/h12mediaBidAdapter_spec.js
Labels: needs docs, needs update

#5347 AdagioBidAdapter 2.2.2
  modules/adagioBidAdapter.js
  modules/adagioBidAdapter.md
  test/spec/modules/adagioBidAdapter_spec.js
Labels: LGTM

#5276 Adding back ZEDO adapter with changes to make it compatible to latest prebid
  modules/zedoBidAdapter.js
  modules/zedoBidAdapter.md
  test/spec/modules/zedoBidAdapter_spec.js
Labels: needs review

#5343 Vidazoo Adapter: Feature/direct deal targeting
  modules/vidazooBidAdapter.js
  test/spec/modules/vidazooBidAdapter_spec.js
Labels: LGTM

#5342 Add support for aliases
  modules/aniviewBidAdapter.js
  test/spec/modules/aniviewBidAdapter_spec.js
Labels: LGTM

#5333 Fix to issue #5141 exception thrown in pbjs.requestBids when DigiTrus…
  modules/userId/eids.js
Labels: LGTM

#5354 PubMatic analytics adapter to support bidCpmAdustment values
  modules/pubmaticAnalyticsAdapter.js
  modules/pubmaticAnalyticsAdapter.md
  test/spec/modules/pubmaticAnalyticsAdapter_spec.js
Labels: needs update

#5364 Add placement_type and position parameters to spotxBidAdapter
  modules/spotxBidAdapter.js
  test/spec/modules/spotxBidAdapter_spec.js
Labels: LGTM

#5359 Adkernel: configurable user-sync types support
  modules/adkernelBidAdapter.js
  test/spec/modules/adkernelBidAdapter_spec.js
Labels: LGTM

#5369 remove these adapters from 4.0
  modules/audienceNetworkBidAdapter.js
  modules/audienceNetworkBidAdapter.md
  modules/quantumBidAdapter.js
  modules/quantumBidAdapter.md
  test/spec/modules/audienceNetworkBidAdapter_spec.js
  test/spec/modules/quantumBidAdapter_spec.js
Labels: LGTM, needs 2nd review

#5345 Support for ID5
  modules/adheseBidAdapter.js
  test/spec/modules/adheseBidAdapter_spec.js
Labels: needs review

#5353 Added keywords parameter to TheMediaGrid Bid Adapter
  modules/gridBidAdapter.js
  modules/gridBidAdapter.md
  test/spec/modules/gridBidAdapter_spec.js
Labels: needs review

#5356 Apply some updates to Valueimpression bid adapter
  modules/valueimpressionBidAdapter.js
  modules/valueimpressionBidAdapter.md
  test/spec/modules/valueimpressionBidAdapter_spec.js
Labels: needs review

#5358 add meta key to interpreted bid response
  src/adapters/bidderFactory.js
  test/spec/unit/core/bidderFactory_spec.js
Labels: needs review

#5372 GumGum: removes deprecated banner sizes default
  modules/gumgumBidAdapter.js
Labels: LGTM

#5315 UserId SharedId submodule
  integrationExamples/gpt/userId_example.html
  modules/.submodules.json
  modules/sharedIdSystem.js
  modules/sharedIdSystem.md
  modules/userId/eids.js
  modules/userId/eids.md
  modules/userId/userId.md
  test/spec/modules/eids_spec.js
  test/spec/modules/userId_spec.js
Labels: needs update

#5320 Freewheel - Converted the ComponentId property to be 'prebid' in request
  modules/freewheel-sspBidAdapter.js
  test/spec/modules/freewheel-sspBidAdapter_spec.js
Labels: needs review

#5352 Marsmedia & videofy adapters - Add onTimeout & onSetTargeting
  modules/marsmediaBidAdapter.js
  modules/videofyBidAdapter.js
  test/spec/modules/marsmediaBidAdapter_spec.js
  test/spec/modules/videofyBidAdapter_spec.js
Labels: LGTM

#5329 Triplelift Adaptor: Use Floors Module
  modules/tripleliftBidAdapter.js
  test/spec/modules/tripleliftBidAdapter_spec.js
Labels: needs review

#5394 appnexusBidAdapter - fix video params
  modules/appnexusBidAdapter.js
  modules/appnexusBidAdapter.md
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: needs review

#5351 External ids
  modules/smartadserverBidAdapter.js
  test/spec/modules/smartadserverBidAdapter_spec.js
Labels: needs docs

#5365 33Across: CCPA Compliance + Schain support
  modules/33acrossBidAdapter.js
  test/spec/modules/33acrossBidAdapter_spec.js
Labels: LGTM

#5386 Vidazoo Adapter: Feature/user-id
  modules/vidazooBidAdapter.js
  test/spec/modules/vidazooBidAdapter_spec.js
Labels: LGTM

#5407 LiveIntentId submodule updates
  integrationExamples/gpt/userId_example.html
  modules/liveIntentIdSystem.js
  modules/userId/index.js
  package-lock.json
  package.json
  test/spec/modules/liveIntentIdSystem_spec.js
Labels: LGTM

#5336 TCF Purpose 1 and Purpose 2 enforcement for Prebid v4.0
  modules/appnexusBidAdapter.js
  modules/consentManagement.js
  modules/gdprEnforcement.js
  src/adapterManager.js
  src/adapters/bidderFactory.js
  src/constants.json
  src/prebid.js
  test/spec/modules/consentManagement_spec.js
  test/spec/modules/gdprEnforcement_spec.js
  test/spec/unit/core/bidderFactory_spec.js
Labels: 4.0 API Change, needs review

#5391 Ayl gdp rdefault value
  modules/adyoulikeBidAdapter.js
  test/spec/modules/adyoulikeBidAdapter_spec.js
Labels: LGTM

#5357 Add Render RichAudience Adapter
  modules/richaudienceBidAdapter.js
  modules/richaudienceBidAdapter.md
  test/spec/modules/richaudienceBidAdapter_spec.js
Labels: needs update, question

#5346 Add tradedesk user id to appnexus adapter
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: needs review
