Repository prebid/Prebid.js, pull requests merged in 2020-02, with the labels that each got.

#4671 Reviving and moving to prebid 3.0 of smartyAds bi adapter
  modules/smartyadsBidAdapter.js
  modules/smartyadsBidAdapter.md
  test/spec/modules/smartyadsBidAdapter_spec.js
Labels: needs update

#4804 GDPR support added to the vuble bidder
  modules/vubleBidAdapter.js
  test/spec/modules/vubleBidAdapter_spec.js
Labels: LGTM

#4807 Collect data about native + minor changes
  modules/livewrappedAnalyticsAdapter.js
  modules/livewrappedBidAdapter.js
  test/spec/modules/livewrappedAnalyticsAdapter_spec.js
Labels: needs review

#4822 Added size 1800x200
  modules/rubiconBidAdapter.js
Labels: LGTM

#4799 PXYZ - support for US Privacy consent string
  modules/playgroundxyzBidAdapter.js
  test/spec/modules/playgroundxyzBidAdapter_spec.js
Labels: needs review

#4788 Fixed oneVideo TypeError when consentData is undefined
  modules/oneVideoBidAdapter.js
  test/spec/modules/oneVideoBidAdapter_spec.js
Labels: needs review

#4841 Add two more default native params to seedingalliance adapter
  modules/seedingAllianceBidAdapter.js
  test/spec/modules/seedingAllianceAdapter_spec.js
Labels: needs review

#4835 Remove rtusid system
  modules/.submodules.json
  modules/criteortusIdSystem.js
  test/spec/modules/criteortusIdSystem_spec.js
Labels: needs review

#4844 Implemented schain support for prebid and updated documentation examples for prebid3.0
  modules/synacormediaBidAdapter.js
  modules/synacormediaBidAdapter.md
  test/spec/modules/synacormediaBidAdapter_spec.js
Labels: LGTM

#4848 GumGum: adds support for video
  modules/gumgumBidAdapter.js
  test/spec/modules/gumgumBidAdapter_spec.js
Labels: needs review

#4849 use all request id
  modules/proxistoreBidAdapter.js
Labels: LGTM

#4839 Restore adman bidadapter
  modules/admanBidAdapter.js
  modules/admanBidAdapter.md
  test/spec/modules/admanBidAdapter_spec.js
Labels: needs review

#4472 Standardizing First Party Data
  modules/prebidServerBidAdapter/index.js
  modules/rubiconBidAdapter.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: LGTM

#4850 TripleLift COPPA support
  modules/tripleliftBidAdapter.js
  test/spec/modules/tripleliftBidAdapter_spec.js
Labels: LGTM

#4878 eplanning: Add new optional parameter for changing placement names
  modules/eplanningBidAdapter.js
  test/spec/modules/eplanningBidAdapter_spec.js
Labels: LGTM, needs docs

#4863 Rubicon Adapter: Add liveramp support
  modules/prebidServerBidAdapter/index.js
  modules/rubiconBidAdapter.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: needs review

#4808 New Bidder Adapter: AdGlare Ad Server
  modules/adglareBidAdapter.js
  modules/adglareBidAdapter.md
  test/spec/modules/adglareBidAdapter_spec.js
Labels: LGTM

#4772 Districtm dmx passing dealid to prebid
  modules/districtmDMXBidAdapter.js
  test/spec/modules/districtmDmxBidAdapter_spec.js
Labels: LGTM

#4885 Rubicon analytics passes referrerHostname
  modules/rubiconAnalyticsAdapter.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
Labels: LGTM

#4887 PubMatic adapter to support PM Deals
  modules/pubmaticBidAdapter.js
  modules/pubmaticBidAdapter.md
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: needs review

#4880 yieldoneBidAdapter: fix encode referrer twice
  modules/yieldoneBidAdapter.js
Labels: needs review

#4250 Add netId userId module
  modules/netIdSystem.js
  modules/prebidServerBidAdapter/index.js
  modules/userId/userId.md
  test/spec/modules/userId_spec.js
Labels: needs 2nd review, pinned
