Repository prebid/Prebid.js, pull requests merged in 2020-05, with the labels that each got.

#5170 Add Quantumdex Bid Adapter
  modules/quantumdexBidAdapter.js
  modules/quantumdexBidAdapter.md
  test/spec/modules/quantumdexBidAdapter_spec.js
Labels: LGTM

#5164 New version of Konduit Accelerate module
  modules/konduitAnalyticsAdapter.js
  modules/konduitAnalyticsAdapter.md
  modules/konduitWrapper.js
  modules/konduitWrapper.md
  test/spec/modules/konduitAnalyticsAdapter_spec.js
  test/spec/modules/konduitWrapper_spec.js
Labels: question

#5195 Media.net : BidAdapter & Analytics improvements
  modules/medianetAnalyticsAdapter.js
  modules/medianetBidAdapter.js
  test/spec/modules/medianetBidAdapter_spec.js
Labels: LGTM

#5197 parrableIdSystem: Consume US Privacy consent data
  modules/parrableIdSystem.js
  test/spec/modules/parrableIdSystem_spec.js
Labels: LGTM

#5201 Gdpr vendor exceptions
  modules/gdprEnforcement.js
Labels: in progress, needs unit tests

#5166 User id fetch error
  modules/id5IdSystem.js
  modules/identityLinkIdSystem.js
  modules/liveIntentIdSystem.js
  modules/parrableIdSystem.js
  modules/unifiedIdSystem.js
  test/spec/modules/liveIntentIdSystem_spec.js
  test/spec/modules/parrableIdSystem_spec.js
Labels: needs review

#5233 LoopMe adapter: Added mediaType field into bid response
  modules/loopmeBidAdapter.js
Labels: LGTM

#5267 Automatad Bid Adapter: Update CPM sent with WinNotification
  modules/automatadBidAdapter.js
Labels: LGTM

#5257 Onevideo Adaptor -Hp param support
  modules/oneVideoBidAdapter.js
  modules/oneVideoBidAdapter.md
  test/spec/modules/oneVideoBidAdapter_spec.js
Labels: LGTM

#5206 New bidder adapter: pubgenius
  modules/pubgeniusBidAdapter.js
  modules/pubgeniusBidAdapter.md
  test/spec/modules/pubgeniusBidAdapter_spec.js
Labels: LGTM

#5240 OpenX Adapter: Normalize video sizes to numbers from strings
  modules/openxBidAdapter.js
  test/spec/modules/openxBidAdapter_spec.js
Labels: needs review

#5238 Update onBidWon method to only execute 1 url
  integrationExamples/gpt/revcontent_example.html
  modules/revcontentBidAdapter.js
  test/spec/modules/revcontentBidAdapter_spec.js
Labels: needs review

#5210 Added support for GDPR, COPPA, and USP
  modules/cpmstarBidAdapter.js
  modules/cpmstarBidAdapter.md
  test/spec/modules/cpmstarBidAdapter_spec.js
Labels: LGTM

#5208 Stabilize Circle CI Build Job
  test/spec/modules/userId_spec.js
Labels: needs review, pinned

#5266 Adding Edge Query X Adapter (with right md file)
  modules/edgequeryxBidAdapter.js
  modules/edgequeryxBidAdapter.md
  test/spec/modules/edgequeryxBidAdapter_spec.js
Labels: needs review

#5265 Update Platform One Analytics Adapter
  modules/yieldoneAnalyticsAdapter.js
  test/spec/modules/yieldoneAnalyticsAdapter_spec.js
Labels: needs update

#5260 Add craftBidAdapter
  modules/craftBidAdapter.js
  modules/craftBidAdapter.md
  test/spec/modules/craftBidAdapter_spec.js
Labels: LGTM

#5281 [RTB House] Add schain support
  modules/rtbhouseBidAdapter.js
  test/spec/modules/rtbhouseBidAdapter_spec.js
Labels: LGTM

#5274 Fix referer
  modules/relaidoBidAdapter.js
  test/spec/modules/relaidoBidAdapter_spec.js
Labels: LGTM

#5227 Add keywordsparametr
  modules/adprimeBidAdapter.js
  modules/adprimeBidAdapter.md
  test/spec/modules/adprimeBidAdapter_spec.js
Labels: LGTM

#5279 Identity link id system - handle empty response
  modules/identityLinkIdSystem.js
  test/spec/modules/identityLinkIdSystem_spec.js
Labels: LGTM

#5289 Update ixBidAdapter.js
  modules/ixBidAdapter.js
Labels: LGTM

#5261 add adWMGAnalyticsAdapter
  modules/adWMGAnalyticsAdapter.js
  modules/adWMGAnalyticsAdapter.md
  test/spec/modules/adWMGAnalyticsAdapter_spec.js
Labels: needs update

#5235 fix(Renderer): load script only on render
  src/Renderer.js
  test/spec/renderer_spec.js
Labels: needs update

#5284 Gumgum add in video
  modules/gumgumBidAdapter.js
  modules/gumgumBidAdapter.md
  test/spec/modules/gumgumBidAdapter_spec.js
Labels: needs update

#5203 Adtelligent new features
  modules/adtelligentBidAdapter.js
  test/spec/modules/adtelligentBidAdapter_spec.js
Labels: LGTM

#5259 New adapter - videofy
  modules/videofyBidAdapter.js
  modules/videofyBidAdapter.md
  test/spec/modules/videofyBidAdapter_spec.js
Labels: LGTM

#5291 ConsentManagement: fallback to defaultGdprScope if gdprApplies undefined
  modules/consentManagement.js
  test/spec/modules/consentManagement_spec.js
Labels: needs review

#5087 RTD bug fix
  modules/browsiRtdProvider.js
  modules/rtdModule/index.js
  test/spec/modules/realTimeModule_spec.js
Labels: needs 2nd review

#5178 adding check if gdpr module ran enforcment logic
  modules/gdprEnforcement.js
  modules/userId/index.js
  test/spec/modules/gdprEnforcement_spec.js
Labels: LGTM, needs unit tests

#5295 Floors new signals
  modules/priceFloors.js
  modules/rubiconAnalyticsAdapter.js
  test/spec/modules/priceFloors_spec.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
Labels: needs 2nd review

#5303 change iabSubCatId name to primaryCatId
  modules/adpod.js
  modules/adtelligentBidAdapter.js
  modules/appnexusBidAdapter.js
  modules/categoryTranslation.js
  src/adapters/bidderFactory.js
  test/spec/modules/adpod_spec.js
  test/spec/modules/categoryTranslation_spec.js
  test/spec/modules/dfpAdServerVideo_spec.js
  test/spec/modules/freeWheelAdserverVideo_spec.js
  test/spec/modules/konduitWrapper_spec.js
Labels: needs review

#5273 Blue Billywig adapter - Add site config to request similarly to app config
  modules/bluebillywigBidAdapter.js
  test/spec/modules/bluebillywigBidAdapter_spec.js
Labels: needs review

#5282 Media.net Analytics improvements [Bug Fix]
  modules/medianetAnalyticsAdapter.js
  modules/medianetBidAdapter.js
  test/spec/modules/medianetBidAdapter_spec.js
Labels: needs review

#5283 Improvements for SizeMappingV2 (advanced size mapping) module
  integrationExamples/gpt/advanced_size_mapping.html
  modules/sizeMappingV2.js
  test/spec/modules/sizeMappingV2_spec.js
Labels: needs 2nd review

#5263 ablida: add onBidWon function, add bidder adapter version to bid requests
  modules/ablidaBidAdapter.js
  test/spec/modules/ablidaBidAdapter_spec.js
Labels: LGTM
