Repository prebid/Prebid.js, pull requests merged in 2020-01, with the labels that each got.

#4496 Advertly: New Bidder Adapter Submission
  integrationExamples/gpt/hello_world.html
  modules/advertlyBidAdapter.js
  modules/advertlyBidAdapter.md
  test/spec/modules/advertlyBidAdapter_spec.js
Labels: LGTM

#4656 Media.net Adapter: Add CCPA (USP) support to legacy branch (2.44.x)
  modules/medianetBidAdapter.js
  test/spec/modules/medianetBidAdapter_spec.js
Labels: legacy

#4648 Ccpa legacy support for OneVideo
  modules/oneVideoBidAdapter.js
  test/spec/modules/oneVideoBidAdapter_spec.js
Labels: legacy

#4615 Prebid 3 Admixer
  modules/admixerBidAdapter.js
  test/spec/modules/admixerBidAdapter_spec.js
Labels: needs update

#4669 Teads adapter: Add us privacy to 2.X versions
  modules/teadsBidAdapter.js
  test/spec/modules/teadsBidAdapter_spec.js
Labels: legacy

#4581 GumGum: adds us privacy (CCPA) support
  modules/gumgumBidAdapter.js
  test/spec/modules/gumgumBidAdapter_spec.js
Labels: LGTM

#4683 Added CCPA support and GDPR compliance to Cedato adapter
  modules/cedatoBidAdapter.js
  test/spec/modules/cedatoBidAdapter_spec.js
Labels: needs unit tests

#4686 2.44.x-Legacy: Added CCPA support and GDPR compliance to Cedato adapter
  modules/cedatoBidAdapter.js
  test/spec/modules/cedatoBidAdapter_spec.js
Labels: legacy, needs review

#4551 Bidder schain support
  modules/schain.js
  src/adapterManager.js
  test/spec/modules/schain_spec.js
Labels: needs 2nd review

#4614 add seedingAlliance Adapter
  modules/seedingAllianceBidAdapter.js
  modules/seedingAllianceBidAdapter.md
  test/spec/modules/seedingAllianceAdapter_spec.js
Labels: LGTM

#4645 freewheelSSPBidAdapter
  modules/freewheel-sspBidAdapter.js
  modules/freewheel-sspBidAdapter.md
  test/spec/modules/freewheel-sspBidAdapter_spec.js
Labels: needs unit tests, needs update

#4541 ucfunnel adapter support CCPA and remove utils.js in adapter
  modules/ucfunnelBidAdapter.js
  test/spec/modules/ucfunnelBidAdapter_spec.js
Labels: needs docs, needs unit tests, needs update, reviewed

#4652 Fidelity Media Bid Adapter 2.44.x legacy. CCPA support.
  modules/fidelityBidAdapter.js
  modules/fidelityBidAdapter.md
  test/spec/modules/fidelityBidAdapter_spec.js
Labels: legacy

#4689 Add CCPA us_privacy support to spotxBidAdapter
  modules/spotxBidAdapter.js
  test/spec/modules/spotxBidAdapter_spec.js
Labels: needs review

#4687 replace all xhr stubs with global xhr stub to prevent all requests
  CONTRIBUTING.md
  modules/adponeBidAdapter.js
  modules/browsiRtdProvider.js
  modules/mgidBidAdapter.js
  modules/showheroes-bsBidAdapter.js
  modules/videoNowBidAdapter.js
  src/adloader.js
  test/mocks/adloaderStub.js
  test/mocks/xhr.js
  test/spec/AnalyticsAdapter_spec.js
  test/spec/auctionmanager_spec.js
  test/spec/modules/adagioAnalyticsAdapter_spec.js
  test/spec/modules/adponeBidAdapter_spec.js
  test/spec/modules/adxcgAnalyticsAdapter_spec.js
  test/spec/modules/appierAnalyticsAdapter_spec.js
  test/spec/modules/criteortusIdSystem_spec.js
  test/spec/modules/dfpAdServerVideo_spec.js
  test/spec/modules/emoteevBidAdapter_spec.js
  test/spec/modules/eplanningAnalyticsAdapter_spec.js
  test/spec/modules/feedadBidAdapter_spec.js
  test/spec/modules/fintezaAnalyticsAdapter_spec.js
  test/spec/modules/freeWheelAdserverVideo_spec.js
  test/spec/modules/freewheel-sspBidAdapter_spec.js
  test/spec/modules/invisiblyAnalyticsAdapter_spec.js
  test/spec/modules/liveIntentIdSystem_spec.js
  test/spec/modules/livewrappedAnalyticsAdapter_spec.js
  test/spec/modules/mgidBidAdapter_spec.js
  test/spec/modules/openxAnalyticsAdapter_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/prebidmanagerAnalyticsAdapter_spec.js
  test/spec/modules/pubwiseAnalyticsAdapter_spec.js
  test/spec/modules/realTimeModule_spec.js
  test/spec/modules/roxotAnalyticsAdapter_spec.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
  test/spec/modules/scaleableAnalyticsAdapter_spec.js
  test/spec/modules/serverbidServerBidAdapter_spec.js
  test/spec/modules/showheroes-bsBidAdapter_spec.js
  test/spec/modules/sigmoidAnalyticsAdapter_spec.js
  test/spec/modules/sonobiAnalyticsAdapter_spec.js
  test/spec/modules/sortableAnalyticsAdapter_spec.js
  test/spec/modules/sovrnAnalyticsAdapter_spec.js
  test/spec/modules/telariaBidAdapter_spec.js
  test/spec/modules/ucfunnelAnalyticsAdapter_spec.js
  test/spec/modules/userId_spec.js
  test/spec/modules/videoNowBidAdapter_spec.js
  test/spec/modules/vubleAnalyticsAdapter_spec.js
  test/spec/modules/yuktamediaAnalyticsAdaptor_spec.js
  test/spec/unit/core/bidderFactory_spec.js
  test/spec/unit/pbjs_api_spec.js
  test/spec/videoCache_spec.js
  test/test_index.js
Labels: needs 2nd review

#4685 Add static API option to the consentManagementUsp module.
  modules/consentManagementUsp.js
  test/spec/modules/consentManagementUsp_spec.js
Labels: needs docs

#4644 OpenX Adapter: adding legacy CCPA support
  modules/openxBidAdapter.js
  test/spec/modules/openxBidAdapter_spec.js
Labels: LGTM, legacy

#4700 Bridgewell bid adapter: update endpoint
  modules/bridgewellBidAdapter.js
  modules/bridgewellBidAdapter.md
Labels: legacy

#4636 Aardvark: schain support
  modules/aardvarkBidAdapter.js
  test/spec/modules/aardvarkBidAdapter_spec.js
Labels: LGTM

#4705 Add static API option to the consentManagementUsp module for legacy 2.x. (#4685)
  modules/consentManagementUsp.js
  test/spec/modules/consentManagementUsp_spec.js
Labels: legacy, needs 2nd review

#4676 ozone 2.2.0 adapter updates
  modules/ozoneBidAdapter.js
  test/spec/modules/ozoneBidAdapter_spec.js
Labels: LGTM

#4660 Add Segmento Adapter
  modules/segmentoBidAdapter.js
  modules/segmentoBidAdapter.md
  test/spec/modules/segmentoBidAdapter_spec.js
Labels: LGTM

#4591 New adfinity adapter
  modules/adfinityBidAdapter.js
  modules/adfinityBidAdapter.md
  test/spec/modules/adfinityBidAdapter_spec.js
Labels: LGTM

#4695 FreeWheelAdapter-CCPA support CCPA consent in freeWheelSSPAdapter
  modules/freewheel-sspBidAdapter.js
  test/spec/modules/freewheel-sspBidAdapter_spec.js
Labels: needs update

#4296 Fix data transmission issues on AdYouLike bid adapter
  modules/adyoulikeBidAdapter.js
  test/spec/modules/adyoulikeBidAdapter_spec.js
Labels: LGTM

#4633 Innity Bid Adapter: Support for Prebid.js v3
  modules/innityBidAdapter.js
  modules/innityBidAdapter.md
  test/spec/modules/innityBidAdapter_spec.js
Labels: LGTM

#4672 Gamoshi: Add support for CCPA and SChain
  modules/gamoshiBidAdapter.js
  test/spec/modules/gamoshiBidAdapter_spec.js
Labels: LGTM

#4684 Nobid adapter: Added support for CCPA
  modules/nobidBidAdapter.js
  modules/nobidBidAdapter.md
  test/spec/modules/nobidBidAdapter_spec.js
Labels: LGTM

#4704 Adagio bid adapter 2.1.0
  modules/adagioBidAdapter.js
  test/spec/modules/adagioBidAdapter_spec.js
Labels: LGTM

#4697 Criteo adapter should reactivate limited native support
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: LGTM

#4713 ucfunnel adapter native ad support clicktrackers
  modules/ucfunnelBidAdapter.js
  test/spec/modules/ucfunnelBidAdapter_spec.js
Labels: needs review

#4707 AdkernelAdn analytics 3.0 compatible
  modules/adkernelAdnAnalyticsAdapter.js
  test/spec/modules/adkernelAdnAnalytics_spec.js
Labels: LGTM

#4706 SpotX Bid Adapter: Add videoCacheKey
  modules/spotxBidAdapter.js
  test/spec/modules/spotxBidAdapter_spec.js
Labels: needs review

#4688 GDPR and unique request
  modules/proxistoreBidAdapter.js
  package-lock.json
  test/spec/modules/proxistoreBidAdapter_spec.js
Labels: LGTM

#4539 Pre-auction filters and pbAdslot support
  modules/prebidServerBidAdapter/index.js
  modules/rubiconBidAdapter.js
  src/adapterManager.js
  src/constants.json
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/rubiconBidAdapter_spec.js
  test/spec/unit/pbjs_api_spec.js
Labels: feature, needs 2nd review

#4708 AdYouLike bidder adapter support us privacy
  modules/adyoulikeBidAdapter.js
  test/spec/modules/adyoulikeBidAdapter_spec.js
Labels: LGTM, needs review

#4746 [Kargo] Support for CCPA/IAB US Privacy (2.44.x-legacy)
  modules/kargoBidAdapter.js
  test/spec/modules/kargoBidAdapter_spec.js
Labels: LGTM

#4751 Pre-auction filters and pbAdslot support - legacy branch
  modules/prebidServerBidAdapter/index.js
  modules/rubiconBidAdapter.js
  src/adapterManager.js
  src/constants.json
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/rubiconBidAdapter_spec.js
  test/spec/unit/pbjs_api_spec.js
Labels: feature

#4691 IE fix: calling matchMedia with an empty string
  src/sizeMapping.js
Labels: needs 2nd review, needs review

#4714 Updating smartadserver adapter for prebid v3 compatibility.
  modules/smartadserverBidAdapter.js
  modules/smartadserverBidAdapter.md
  test/spec/modules/smartadserverBidAdapter_spec.js
Labels: needs review

#4712 fix(usersync): corrected usersync url
  modules/deepintentBidAdapter.js
  test/spec/modules/deepintentBidAdapter_spec.js
Labels: needs update

#4740 Trion gdpr and usp consent
  modules/trionBidAdapter.js
  test/spec/modules/trionBidAdapter_spec.js
Labels: LGTM

#4749 YIELDONE adapter - update for prebid v3
  modules/yieldoneBidAdapter.js
  test/spec/modules/yieldoneBidAdapter_spec.js
Labels: LGTM

#4760 IE fix: calling matchMedia with an empty string (prebid-2.0)
  src/sizeMapping.js
Labels: needs 2nd review

#4762 Update to v3
  modules/videoreachBidAdapter.js
  modules/videoreachBidAdapter.md
  test/spec/modules/videoreachBidAdapter_spec.js
Labels: needs review

#4759 Support Native
  modules/livewrappedBidAdapter.js
  test/spec/modules/livewrappedBidAdapter_spec.js
Labels: needs review

#4769 Updating the audience network adapter to be 3.x compliant
  modules/audienceNetworkBidAdapter.js
  test/spec/modules/audienceNetworkBidAdapter_spec.js
Labels: needs review

#4703 Adtelligent bid adapter updated to v3.0
  modules/adtelligentBidAdapter.js
  test/spec/modules/adtelligentBidAdapter_spec.js
Labels: needs review

#4753 Upgrade Inskin adapter to Prebid 3
  modules/inskinBidAdapter.js
  test/spec/modules/inskinBidAdapter_spec.js
Labels: needs review, needs unit tests

#4758 initial tribeOS bidder adapter commit
  modules/tribeosBidAdapter.js
  modules/tribeosBidAdapter.md
  test/spec/modules/tribeosBidAdapter_spec.js
Labels: needs docs, needs review

#4032 PBJS support for stored responses
  modules/prebidServerBidAdapter/index.js
  modules/rubiconBidAdapter.js
  src/adapterManager.js
  src/auction.js
  src/debugging.js
  test/spec/auctionmanager_spec.js
  test/spec/debugging_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: feature, needs 2nd review, needs docs

#4745 issue #4728 Fixed digiTrustIdSystem double callback invoke
  modules/digiTrustIdSystem.js
Labels: LGTM

#4791 Wait for DOMContentLoaded event before observe changes on document body on eplanning adapter
  modules/eplanningBidAdapter.js
  test/spec/modules/eplanningBidAdapter_spec.js
Labels: legacy

#4739 FreewheelSSP - enable mediaTypes banner and video with test cases
  modules/freewheel-sspBidAdapter.js
  test/spec/modules/freewheel-sspBidAdapter_spec.js
Labels: needs unit tests, question

#4767 CCPA support for adkernel and adkernelAdn adapters
  modules/adkernelAdnBidAdapter.js
  modules/adkernelBidAdapter.js
  test/spec/modules/adkernelAdnBidAdapter_spec.js
  test/spec/modules/adkernelBidAdapter_spec.js
Labels: LGTM

#4793 fix to allow string for storedAuctionResponse
  modules/prebidServerBidAdapter/index.js
  modules/rubiconBidAdapter.js
Labels: needs review

#4777 Update underdogmedia adapter to contain getUserSyncs
  modules/underdogmediaBidAdapter.js
  test/spec/modules/underdogmediaBidAdapter_spec.js
Labels: question

#4789 Pass auctionId as a argument to bidsBackHandler
  src/auction.js
Labels: needs 2nd review

#4792 change addEventListener to window.addEventlistener
  src/secureCreatives.js
Labels: needs 2nd review

#4785 Add new bid adapter for ResultsMedia
  modules/resultsmediaBidAdapter.js
  modules/resultsmediaBidAdapter.md
  test/spec/modules/resultsmediaBidAdapter_spec.js
Labels: LGTM

#4748 Bridgewell bid adapter: Prebid.js v3 support
  modules/bridgewellBidAdapter.js
  modules/bridgewellBidAdapter.md
  test/spec/modules/bridgewellBidAdapter_spec.js
Labels: LGTM

#4761 Audiencerun bid adapter
  modules/audiencerunBidAdapter.js
  modules/audiencerunBidAdapter.md
  test/spec/modules/audiencerunBidAdapter_spec.js
Labels: LGTM, needs docs
