Repository prebid/Prebid.js, pull requests merged in 2020-09, with the labels that each got.

#5545 Add native support to ablida Bid Adapter
  modules/ablidaBidAdapter.js
  modules/ablidaBidAdapter.md
  test/spec/modules/ablidaBidAdapter_spec.js
Labels: LGTM

#5642 remove cmpuishown event for tcf2 logic
  modules/consentManagement.js
Labels: needs 2nd review

#5682 Fix typo in warning
  src/prebid.js
Labels: LGTM, needs 2nd review

#5673 Price Floors: Fix bug when caching floor lookup
  modules/priceFloors.js
  test/spec/modules/priceFloors_spec.js
Labels: needs 2nd review

#5569 parrableIdSystem: Add an optional timezone and timezone offset allow/block filter
  modules/parrableIdSystem.js
  test/spec/modules/parrableIdSystem_spec.js
Labels: LGTM

#5688 Updated a4g adapter
  modules/a4gBidAdapter.js
  modules/a4gBidAdapter.md
  test/spec/modules/a4gBidAdapter_spec.js
Labels: LGTM

#5563 Adding errors event listener
  src/AnalyticsAdapter.js
  src/constants.json
  src/utils.js
  test/spec/AnalyticsAdapter_spec.js
  test/spec/modules/prebidmanagerAnalyticsAdapter_spec.js
  test/spec/modules/readpeakBidAdapter_spec.js
  test/spec/modules/sigmoidAnalyticsAdapter_spec.js
  test/spec/modules/yuktamediaAnalyticsAdapter_spec.js
Labels: needs 2nd review, needs docs, needs review

#5701 minor validation update to consentManagement.js
  modules/consentManagement.js
Labels: needs 2nd review

#5650 fix GPT Pre-Auction PBS path
  modules/prebidServerBidAdapter/index.js
  modules/rubiconBidAdapter.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: needs 2nd review, needs review

#5695 New adapter "Cointraffic" added
  modules/cointrafficBidAdapter.js
  modules/cointrafficBidAdapter.md
  test/spec/modules/cointrafficBidAdapter_spec.js
Labels: LGTM

#5653 Send GDPR data in analytics request
  modules/livewrappedAnalyticsAdapter.js
  test/spec/modules/livewrappedAnalyticsAdapter_spec.js
Labels: LGTM

#5686 GDPR Enforcement - Bugfix
  modules/gdprEnforcement.js
  test/spec/modules/gdprEnforcement_spec.js
Labels: needs 2nd review

#5716 PBS Bid Adapter: Pass video.placement when context is instream (#5687)
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: needs docs

#5638 allow publisher to define backup renderer
  src/Renderer.js
  src/auction.js
  test/spec/auctionmanager_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/renderer_spec.js
Labels: needs 2nd review

#5640 Zeotap ID+ submodule
  integrationExamples/gpt/userId_example.html
  modules/.submodules.json
  modules/userId/eids.js
  modules/userId/eids.md
  modules/zeotapIdPlusIdSystem.js
  test/spec/modules/eids_spec.js
  test/spec/modules/userId_spec.js
  test/spec/modules/zeotapIdPlusIdSystem_spec.js
Labels: needs 2nd review, needs review, needs update

#5731 Triplelift: fpd and advertiser name support
  modules/tripleliftBidAdapter.js
  test/spec/modules/tripleliftBidAdapter_spec.js
Labels: LGTM

#5524 Audigent HaloID User Id System Module
  integrationExamples/gpt/userId_example.html
  modules/.submodules.json
  modules/haloIdSystem.js
  modules/haloIdSystem.md
  modules/userId/eids.js
  modules/userId/eids.md
  test/spec/modules/eids_spec.js
  test/spec/modules/userId_spec.js
Labels: needs docs, needs review, needs unit tests, needs update

#5589 Fix typo in TheMediaGrid Bid Adapter
  modules/gridBidAdapter.js
  test/spec/modules/gridBidAdapter_spec.js
Labels: needs unit tests

#5616 Check localstorage availability before accessing it
  src/storageManager.js
  test/spec/unit/core/storageManager_spec.js
Labels: needs 2nd review

#5521 Add Supply Supply Chain Object Module support for Yieldlab Adapter
  modules/yieldlabBidAdapter.js
  test/spec/modules/yieldlabBidAdapter_spec.js
Labels: LGTM

#5724 Livewrapped support for video
  modules/livewrappedAnalyticsAdapter.js
  modules/livewrappedBidAdapter.js
  modules/livewrappedBidAdapter.md
  test/spec/modules/livewrappedBidAdapter_spec.js
Labels: LGTM

#5725 Upgrade Circle CI resource
  .circleci/config.yml
Labels: needs 2nd review

#5481 Add support for instream video ads bidsWon tracking
  modules/dfpAdServerVideo.js
  modules/instreamTracking.js
  test/spec/modules/instreamTracking_spec.js
Labels: needs review, needs update

#5703 feat: add getEvents method to the public API
  src/prebid.js
Labels: needs 2nd review

#5770 Quantumdex Bid Adapter: Change the data type of gdpr and schain object in Payload
  modules/quantumdexBidAdapter.js
  test/spec/modules/quantumdexBidAdapter_spec.js
Labels: needs review

#5764 Add a new param cid to bridgewellBidAdapter
  modules/bridgewellBidAdapter.js
  modules/bridgewellBidAdapter.md
  test/spec/modules/bridgewellBidAdapter_spec.js
Labels: LGTM

#4846 Refactor refererDetection to allow for URL discovery on AMP pages.
  src/refererDetection.js
  test/spec/refererDetection_spec.js
Labels: LGTM, assigned, needs 2nd review, pinned

#5771 Intentiq id add url params
  modules/intentIqIdSystem.js
  test/spec/modules/intentIqIdSystem_spec.js
Labels: needs review

#5726 feat(sublimeBidAdapter): updating sublimeBidAdapter module
  modules/sublimeBidAdapter.js
  modules/sublimeBidAdapter.md
  test/spec/modules/sublimeBidAdapter_spec.js
Labels: LGTM

#5781 Add GVL ID and bidder code to CriteoId module
  modules/criteoIdSystem.js
Labels: needs update

#5756 Convert id5id to an object to support passing additional data points to platforms
  modules/adheseBidAdapter.js
  modules/adxcgBidAdapter.js
  modules/avocetBidAdapter.js
  modules/colossussspBidAdapter.js
  modules/districtmDMXBidAdapter.js
  modules/gamoshiBidAdapter.js
  modules/gridBidAdapter.js
  modules/id5IdSystem.js
  modules/livewrappedBidAdapter.js
  modules/openxBidAdapter.js
  modules/ozoneBidAdapter.js
  modules/pulsepointBidAdapter.js
  modules/richaudienceBidAdapter.js
  modules/spotxBidAdapter.js
  modules/userId/eids.js
  modules/vidazooBidAdapter.js
  modules/visxBidAdapter.js
  test/spec/modules/adheseBidAdapter_spec.js
  test/spec/modules/adxcgBidAdapter_spec.js
  test/spec/modules/amxBidAdapter_spec.js
  test/spec/modules/avocetBidAdapter_spec.js
  test/spec/modules/colossussspBidAdapter_spec.js
  test/spec/modules/districtmDmxBidAdapter_spec.js
  test/spec/modules/eids_spec.js
  test/spec/modules/gamoshiBidAdapter_spec.js
  test/spec/modules/gridBidAdapter_spec.js
  test/spec/modules/id5IdSystem_spec.js
  test/spec/modules/justpremiumBidAdapter_spec.js
  test/spec/modules/livewrappedBidAdapter_spec.js
  test/spec/modules/mediasquareBidAdapter_spec.js
  test/spec/modules/openxBidAdapter_spec.js
  test/spec/modules/ozoneBidAdapter_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/pubmaticBidAdapter_spec.js
  test/spec/modules/pulsepointBidAdapter_spec.js
  test/spec/modules/richaudienceBidAdapter_spec.js
  test/spec/modules/smartadserverBidAdapter_spec.js
  test/spec/modules/spotxBidAdapter_spec.js
  test/spec/modules/undertoneBidAdapter_spec.js
  test/spec/modules/userId_spec.js
  test/spec/modules/vidazooBidAdapter_spec.js
  test/spec/modules/visxBidAdapter_spec.js
  test/spec/modules/yuktamediaAnalyticsAdapter_spec.js
Labels: needs 2nd review

#5765 Smaato bid adapter: Optional bidder params to support in-app webview use cases
  modules/smaatoBidAdapter.js
  test/spec/modules/smaatoBidAdapter_spec.js
Labels: needs review

#5782 Add video ad support to ablida bid adapter
  modules/ablidaBidAdapter.js
  modules/ablidaBidAdapter.md
  test/spec/modules/ablidaBidAdapter_spec.js
Labels: LGTM

#5735 Add adrelevantis adapter
  modules/adrelevantisBidAdapter.js
  modules/adrelevantisBidAdapter.md
  test/spec/modules/adrelevantisBidAdapter_spec.js
Labels: needs unit tests, needs update

#5788 Improve warning and documentation for pubmatic publisherId
  modules/pubmaticBidAdapter.js
  modules/pubmaticBidAdapter.md
Labels: needs review

#5784 SpotX bid adapter: add page parameter
  modules/spotxBidAdapter.js
  test/spec/modules/spotxBidAdapter_spec.js
Labels: LGTM

#5755 Media.net Analytics improvements
  modules/medianetAnalyticsAdapter.js
  test/spec/modules/medianetAnalyticsAdapter_spec.js
Labels: LGTM

#5662 Qwarry bid adapter
  modules/qwarryBidAdapter.js
  modules/qwarryBidAdapter.md
  test/spec/modules/qwarryBidAdapter_spec.js
Labels: needs review

#5763 Allow selection of supported default targeting keys at configuration time.
  src/targeting.js
  test/spec/unit/core/targeting_spec.js
Labels: needs review
