Repository prebid/Prebid.js, pull requests merged in 2020-08, with the labels that each got.

#5550 Pubperf analytics adapter added.
  modules/pubperfAnalyticsAdapter.js
  modules/pubperfAnalyticsAdapter.md
  test/spec/modules/pubperfAnalyticsAdapter_spec.js
Labels: needs update

#5543 AdButler Bid Adapter: Add ability to include extra query params
  modules/adbutlerBidAdapter.js
  modules/adbutlerBidAdapter.md
  test/spec/modules/adbutlerBidAdapter_spec.js
Labels: LGTM

#5508 Add apstream adapter
  modules/apstreamBidAdapter.js
  modules/apstreamBidAdapter.md
  test/spec/modules/apstreamBidAdapter_spec.js
Labels: LGTM

#5559 floorProvider can come from data obj now
  modules/priceFloors.js
  test/spec/modules/priceFloors_spec.js
Labels: needs 2nd review

#5350 parrableIdSystem: Populate userIdAsEid with Parrable ID and Optout data
  modules/connectadBidAdapter.js
  modules/openxBidAdapter.js
  modules/ozoneBidAdapter.js
  modules/parrableIdSystem.js
  modules/pulsepointBidAdapter.js
  modules/userId/eids.js
  modules/vidazooBidAdapter.js
  test/spec/modules/eids_spec.js
  test/spec/modules/openxBidAdapter_spec.js
  test/spec/modules/ozoneBidAdapter_spec.js
  test/spec/modules/parrableIdSystem_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/pubmaticBidAdapter_spec.js
  test/spec/modules/pulsepointBidAdapter_spec.js
  test/spec/modules/vidazooBidAdapter_spec.js
Labels: needs review

#5566 Fix a bug for bids originating from DALE
  modules/adheseBidAdapter.js
Labels: needs review

#5567 Automatad Bid Adapter: Add adunit code to bid request
  modules/automatadBidAdapter.js
  test/spec/modules/automatadBidAdapter_spec.js
Labels: needs review, needs unit tests

#5575 Teads adapter: support time to first byte
  modules/teadsBidAdapter.js
  test/spec/modules/teadsBidAdapter_spec.js
Labels: LGTM

#5463 Orbidder: fix getting the end point url for developoment and integration tests from local storage
  modules/orbidderBidAdapter.js
  test/spec/modules/orbidderBidAdapter_spec.js
Labels: LGTM

#5544 Yieldmo adapter: fix #4107, optimize #5098
  modules/yieldmoBidAdapter.js
  test/spec/modules/yieldmoBidAdapter_spec.js
Labels: LGTM

#5591 Fix for 5588;
  modules/dfpAdServerVideo.js
  test/fixtures/video/adUnit.json
Labels: needs 2nd review

#5547 Updated YuktaMedia Analytics Adapter: updated request body with more details
  modules/yuktamediaAnalyticsAdapter.js
  modules/yuktamediaAnalyticsAdapter.md
  test/spec/modules/yuktamediaAnalyticsAdapter_spec.js
  test/spec/modules/yuktamediaAnalyticsAdaptor_spec.js
Labels: needs review

#5498 Adagio bid adapter 2.3.0
  modules/adagioBidAdapter.js
  test/spec/modules/adagioBidAdapter_spec.js
Labels: LGTM

#5472 Triplelift: Add Instream support
  modules/tripleliftBidAdapter.js
  modules/tripleliftBidAdapter.md
  test/spec/modules/tripleliftBidAdapter_spec.js
Labels: LGTM

#5594 Brightcom Bid Adapter: Add GDPR support
  modules/brightcomBidAdapter.js
  test/spec/modules/brightcomBidAdapter_spec.js
Labels: LGTM

#5451 user id module refresh ids when consent changes
  modules/userId/index.js
  test/spec/modules/userId_spec.js
Labels: LGTM, needs 2nd review

#5564 Fix v2CmpResponseCallback handle
  modules/consentManagement.js
Labels: needs 2nd review, needs review

#5444 TCFv2.0 Purpose 7
  modules/appnexusAnalyticsAdapter.js
  modules/gdprEnforcement.js
  src/adapterManager.js
  src/constants.json
  src/prebid.js
  test/spec/modules/gdprEnforcement_spec.js
Labels: LGTM, pinned

#5553 PubMatic: Support for Outstream Renderer (BlueBilyWig Renderer)
  modules/pubmaticBidAdapter.js
  modules/pubmaticBidAdapter.md
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: not receiving bids

#5610 Rubicon Analytics: Pass along floor provider to analytics
  modules/rubiconAnalyticsAdapter.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
Labels: LGTM

#5604 [Synacormedia] Backport changes from 4.x to 3.27.x-legacy branch
  modules/synacormediaBidAdapter.js
  test/spec/modules/synacormediaBidAdapter_spec.js
Labels: legacy

#5568 Added IronSource bidder tests and adapter according to specs
  modules/ironsourceBidAdapter.js
  modules/ironsourceBidAdapter.md
  test/spec/modules/ironsourceBidAdapter_spec.js
Labels: needs docs, needs review

#5620 Update rubicon adapter for liveramp userid requirements change
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: adapter support, needs review

#5583 oneVideo Adapter: User sync pixel updates (VIDEOPUB-17981)
  modules/oneVideoBidAdapter.js
  test/spec/modules/oneVideoBidAdapter_spec.js
Labels: needs review

#5519 Extending the Real Time Data Module
  modules/browsiRtdProvider.js
  modules/rtdModule/index.js
  src/targeting.js
  test/spec/modules/realTimeModule_spec.js
Labels: needs docs

#5633 Legacy branch bug fixes - consent management and dfp video module
  modules/consentManagement.js
  modules/dfpAdServerVideo.js
  test/fixtures/video/adUnit.json
Labels: legacy

#5533 purposes in call for invibes
  modules/invibesBidAdapter.js
  test/spec/modules/invibesBidAdapter_spec.js
Labels: needs review

#5641 updated userid module to stop caching the entire consent object
  modules/userId/index.js
  src/utils.js
  test/spec/modules/userId_spec.js
  test/spec/utils_spec.js
Labels: needs 2nd review

#5537 JW Player Real Time Data Provider
  integrationExamples/gpt/jwplayerRtdProvider_example.html
  modules/.submodules.json
  modules/jwplayerRtdProvider.js
  modules/jwplayerRtdProvider.md
  test/spec/modules/jwplayerRtdProvider_spec.js
Labels: needs review

#5275 Add smartxBidAdapter
  modules/smartxBidAdapter.js
  modules/smartxBidAdapter.md
  test/spec/modules/smartxBidAdapter_spec.js
Labels: needs docs

#5649 Change ironsource to be lower case all over code
  modules/ironsourceBidAdapter.js
  modules/ironsourceBidAdapter.md
  test/spec/modules/ironsourceBidAdapter_spec.js
Labels: needs review

#5655 added pageViewId, language & refererInfo
  modules/yuktamediaAnalyticsAdapter.js
Labels: LGTM

#5666 RP Bid Adapter read user.id
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: needs docs, needs review

#5657 RP Bid Adapter: Use EID data set from userId/eids.js
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: needs review

#5664 qcadapter - tcf2 remove germany specific logic
  modules/quantcastBidAdapter.js
  test/spec/modules/quantcastBidAdapter_spec.js
Labels: LGTM

#5577 merkleId Identity submodule submission
  integrationExamples/gpt/userId_example.html
  modules/.submodules.json
  modules/merkleIdSystem.js
  modules/userId/eids.js
  modules/userId/eids.md
  test/spec/modules/eids_spec.js
  test/spec/modules/userId_spec.js
Labels: needs 2nd review, needs docs, needs review

#5660 Added schain support and usersync output to cpmstarBidAdapter
  modules/cpmstarBidAdapter.js
  test/spec/modules/cpmstarBidAdapter_spec.js
Labels: LGTM

#5486 SpotX: Set ad_mute correctly.
  modules/spotxBidAdapter.js
  test/spec/modules/spotxBidAdapter_spec.js
Labels: needs unit tests

#5665 [Synacormedia] Update bid url scheme
  modules/synacormediaBidAdapter.js
  test/spec/modules/synacormediaBidAdapter_spec.js
Labels: needs review

#5671 Rubicon Bid Adapter: fix incorrect sharedid param
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: needs review
