Repository prebid/Prebid.js, pull requests merged in 2020-04, with the labels that each got.

#4992 Added TheMediaGridNM Bid Adapter
  modules/gridNMBidAdapter.js
  modules/gridNMBidAdapter.md
  test/spec/modules/gridNMBidAdapter_spec.js
Labels: needs review

#5021 Add type information to DSPX bidResponse
  modules/dspxBidAdapter.js
  test/spec/modules/dspxBidAdapter_spec.js
Labels: needs unit tests

#4975 Added support of supply chain object for smartadserverBidAdapter
  modules/smartadserverBidAdapter.js
  test/spec/modules/smartadserverBidAdapter_spec.js
Labels: needs docs, needs review, needs update

#5007 feat(module): multi size request
  modules/vidazooBidAdapter.js
  test/spec/modules/vidazooBidAdapter_spec.js
Labels: LGTM

#5053 Added new Converge Bid Adapter
  modules/convergeBidAdapter.js
  modules/convergeBidAdapter.md
  test/spec/modules/convergeBidAdapter_spec.js
Labels: LGTM

#4566 Added Hybrid.ai adapter
  modules/hybridBidAdapter.js
  modules/hybridBidAdapter.md
  test/spec/modules/hybridBidAdapter_spec.js
Labels: docs, reviewed

#5065 Freewheel: Better size detection and allow multiple bid requests
  modules/freewheel-sspBidAdapter.js
  test/spec/modules/freewheel-sspBidAdapter_spec.js
Labels: needs update

#4982 User ID auctionDelay timeout bugfix
  modules/userId/index.js
  test/spec/modules/userId_spec.js
Labels: needs review, pinned

#5078 Fix bug in rubicon bid adapter for fpd keywords
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: LGTM

#5073 Use TCFv2 consent data in Criteo Id module
  modules/criteoIdSystem.js
  test/spec/modules/criteoIdSystem_spec.js
Labels: LGTM

#5062 Size Mapping V2 supports 'Identical Ad Units'
  allowedModules.js
  modules/sizeMappingV2.js
  src/utils.js
  test/spec/modules/sizeMappingV2_spec.js
Labels: needs 2nd review

#4949 add adot bidder adapter
  modules/adotBidAdapter.js
  modules/adotBidAdapter.md
  test/spec/modules/adotBidAdapter_spec.js
Labels: needs update

#5017 Add Automatad Bid Adapter
  modules/automatadBidAdapter.js
  modules/automatadBidAdapter.md
  test/spec/modules/automatadBidAdapter_spec.js
Labels: LGTM, needs docs

#5040 Prebid adapter for windtalker
  modules/windtalkerBidAdapter.js
  modules/windtalkerBidAdapter.md
  test/spec/modules/windtalkerBidAdapter_spec.js
Labels: needs update

#5064 #5011 Fix to set Secure attribute on cookie when SameSite=none
  src/storageManager.js
Labels: LGTM, needs 2nd review

#5079 Support min &max duration for onevideo
  modules/oneVideoBidAdapter.js
  modules/oneVideoBidAdapter.md
  test/spec/modules/oneVideoBidAdapter_spec.js
Labels: LGTM

#5077 isSafariBrowser update
  src/utils.js
  test/spec/utils_spec.js
Labels: LGTM

#5075 CRITEO RTUS Integration with Yieldmo Prebid
  modules/yieldmoBidAdapter.js
  modules/yieldmoBidAdapter.md
  test/spec/modules/yieldmoBidAdapter_spec.js
Labels: needs update

#4998 Prebid manager analytics utm tags
  modules/prebidmanagerAnalyticsAdapter.js
  test/spec/modules/prebidmanagerAnalyticsAdapter_spec.js
Labels: needs review

#5086 Read OpenRTB app objects if set in config + bug fix for when ad units are reloaded
  modules/livewrappedAnalyticsAdapter.js
  modules/livewrappedBidAdapter.js
  test/spec/modules/livewrappedBidAdapter_spec.js
Labels: needs review

#5105 change payload
  modules/proxistoreBidAdapter.js
  test/spec/modules/proxistoreBidAdapter_spec.js
Labels: LGTM

#4806 Add new bid adapter for ConnectAd
  modules/connectadBidAdapter.js
  modules/connectadBidAdapter.md
  test/spec/modules/connectadBidAdapter_spec.js
Labels: LGTM, reviewed

#5101 Add Relaido Adapter
  modules/relaidoBidAdapter.js
  modules/relaidoBidAdapter.md
  test/spec/modules/relaidoBidAdapter_spec.js
Labels: needs update

#5050 minor consentManagement fix
  modules/consentManagement.js
Labels: needs 2nd review

#5104 PubMatic adapter to support image sync
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: needs review

#5067 Marsmedia - Add vastXml and fix id response
  modules/marsmediaBidAdapter.js
  test/spec/modules/marsmediaBidAdapter_spec.js
Labels: LGTM

#4923 Qc/qc usersyncs
  modules/quantcastBidAdapter.js
  modules/quantcastBidAdapter.md
  test/spec/modules/quantcastBidAdapter_spec.js
Labels: needs review

#5085 ShowHeroes adapter v2
  modules/showheroes-bsBidAdapter.js
  test/spec/modules/showheroes-bsBidAdapter_spec.js
Labels: needs review

#5039 Fixing FirstParty Data deep-merge issue #4950
  src/config.js
  src/utils.js
  test/spec/unit/core/adapterManager_spec.js
  test/spec/utils_spec.js
Labels: LGTM

#5123 parrableIdSystem: Send current page location to back-end
  modules/parrableIdSystem.js
Labels: needs review

#5099 Submitting Tercept Analytics Adapter
  modules/terceptAnalyticsAdapter.js
  modules/terceptAnalyticsAdapter.md
  test/spec/modules/terceptAnalyticsAdapter_spec.js
Labels: LGTM

#5114 User ID's (liveramp, britepool) and gdpr
  modules/colossussspBidAdapter.js
  test/spec/modules/colossussspBidAdapter_spec.js
Labels: needs docs, needs review

#5124 GumGum: uses encodeURIComponent inline
  modules/gumgumBidAdapter.js
  test/spec/modules/gumgumBidAdapter_spec.js
Labels: needs review

#5133 add parameter to the conversant adapter to override the url
  modules/conversantBidAdapter.js
  modules/conversantBidAdapter.md
  test/spec/modules/conversantBidAdapter_spec.js
Labels: LGTM

#5121 Feature/send publisher domain
  modules/atsAnalyticsAdapter.js
  test/spec/modules/atsAnalyticsAdapter_spec.js
Labels: needs review

#5120 New LuponMedia Bid Adapter
  modules/luponmediaBidAdapter.js
  modules/luponmediaBidAdapter.md
Labels: LGTM

#5081 [BUGFIX] AdagioBidAdapter getDataFromLocalStorage
  modules/adagioBidAdapter.js
  test/spec/modules/adagioBidAdapter_spec.js
Labels: needs review

#4977 SublimeBidAdapter: Update to version 0.5.1
  modules/sublimeBidAdapter.js
  test/spec/modules/sublimeBidAdapter_spec.js
Labels: needs review

#5109 Disallowing remote requests from Safari and Firefox due to browsers n…
  integrationExamples/gpt/digitrust_Simple.html
  modules/digiTrustIdSystem.js
Labels: needs 2nd review

#5129 Improve Digital adapter: add support for outstream video
  modules/improvedigitalBidAdapter.js
  test/spec/modules/improvedigitalBidAdapter_spec.js
Labels: needs review

#5137 No bid version 1.2.5
  modules/nobidBidAdapter.js
  test/spec/modules/nobidBidAdapter_spec.js
Labels: LGTM

#5122 [BUGFIX] Teads: fix production GDPR problem
  modules/teadsBidAdapter.js
  test/spec/modules/teadsBidAdapter_spec.js
Labels: needs review

#5132 Reset GPT targeting for custom div ids
  src/prebid.js
  src/targeting.js
Labels: needs 2nd review

#5096 Add warning messages for publishers while native ads send assets containing url without sendId
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: needs review

#5108 UserId module to export user ids as eids with pbjs.getUserIdsAsEids()
  modules/userId/index.js
  test/spec/modules/userId_spec.js
Labels: needs 2nd review

#5160 Remove leftover return value from requestBids
  src/prebid.js
Labels: LGTM

#5158 New adapter: Colombia
  modules/colombiaBidAdapter.js
  modules/colombiaBidAdapter.md
  package-lock.json
  package.json
  test/spec/modules/colombiaBidAdapter_spec.js
Labels: LGTM

#5154 Provide more data in Adhese bid response
  modules/adheseBidAdapter.js
  test/spec/modules/adheseBidAdapter_spec.js
Labels: LGTM

#5168 Between: fix sizes format & update betweenBidAdapter.md
  modules/betweenBidAdapter.js
  modules/betweenBidAdapter.md
  test/spec/modules/betweenBidAdapter_spec.js
Labels: needs review

#5153 Invisibly analytics
  modules/invisiblyAnalyticsAdapter.js
  modules/invisiblyAnalyticsAdapter.md
  test/spec/modules/invisiblyAnalyticsAdapter_spec.js
Labels: LGTM

#5119 circleci enable pipelines
  .circleci/config.yml
Labels: needs 2nd review, needs review
