Repository prebid/Prebid.js, pull requests merged in 2021-02, with the labels that each got.

#6213 PBS Bid Adapter: cooperative sync flag
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: feature, minor

#6170 ID5 User ID Module: pass a flag back to id5 servers if abTesting was enabled
  modules/id5IdSystem.js
  test/spec/modules/id5IdSystem_spec.js
Labels: feature, needs review, patch

#6245 appneuxs Bid Adapter - add support for identitylink userId
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: feature, minor, needs review

#6254 Update britepoolIdSystem.md
  modules/britepoolIdSystem.md
Labels: maintenance, patch

#6255 UNICORN Adapter - accept multiple formats
  modules/unicornBidAdapter.js
  test/spec/modules/unicornBidAdapter_spec.js
Labels: bugfix, feature, patch

#6257 ATS-analytics - add comment clarifying ownership of atsAnalytics
  modules/atsAnalyticsAdapter.js
Labels: maintenance, patch

#6258 [ParrableIdSystem] Ensure base64 payload is url-safe
  modules/parrableIdSystem.js
  test/spec/modules/parrableIdSystem_spec.js
Labels: bugfix, patch

#6259 Keywords + Screen resolution + CPU Core
  modules/richaudienceBidAdapter.js
  modules/richaudienceBidAdapter.md
  test/spec/modules/richaudienceBidAdapter_spec.js
Labels: maintenance, patch

#6241 Rubicon Analytics: Fire event once gptSlots render
  modules/rubiconAnalyticsAdapter.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
Labels: minor, patch

#6252 Rubicon Analytics: New dimension for tracking name of the matching adUnit pattern
  modules/rubiconAnalyticsAdapter.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
Labels: minor, patch

#6256 Adhese Bid Adapter: Per adunit targets
  modules/adheseBidAdapter.js
  test/spec/modules/adheseBidAdapter_spec.js
Labels: feature, minor

#6231 Gjirafa Bid Adapter: added data object as a param
  modules/gjirafaBidAdapter.js
  modules/gjirafaBidAdapter.md
  test/spec/modules/gjirafaBidAdapter_spec.js
Labels: feature, minor

#6224 Inskin Bid Adapter: checking event.source exists before accessing frameElement
  modules/inskinBidAdapter.js
Labels: bugfix, minor

#6268 parrableIDSystem: fix broken tests due to "encoded" base64 logic
  test/spec/modules/parrableIdSystem_spec.js
Labels: bugfix, needs review, patch

#6269 Revert "Extended ID permissions supported by bidder"
  integrationExamples/gpt/userId_example.html
  modules/prebidServerBidAdapter/index.js
  modules/userId/eids.js
  modules/userId/index.js
  plugins/eslint/validateImports.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/userId_spec.js
Labels: bugfix, minor

#6239 smartxBidAdapter: new Feature - Made Out-Stream Player configurable
  modules/smartxBidAdapter.js
  modules/smartxBidAdapter.md
  test/spec/modules/smartxBidAdapter_spec.js
Labels: feature, minor

#6242 Idl1
  modules/idImportLibrary.js
  modules/idImportLibrary.md
  test/spec/modules/idImportLibrary_spec.js
Labels: feature, minor

#6263 Add the trade desk gvlid
  modules/unifiedIdSystem.js
Labels: bugfix, minor

#6272 Rubicon Analytics: Pick up wrapper family field
  modules/rubiconAnalyticsAdapter.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
Labels: maintenance, minor

#6244 Add user sync
  modules/adprimeBidAdapter.js
  test/spec/modules/adprimeBidAdapter_spec.js
Labels: feature, minor, needs review, needs update

#6260 Zeotap id plus gvlid
  modules/zeotapIdPlusIdSystem.js
  test/spec/modules/zeotapIdPlusIdSystem_spec.js
Labels: bugfix, needs review, needs unit tests, patch

#6265 adWMG adapter: add new parameter, fix minor bugs
  modules/adWMGBidAdapter.js
  modules/adWMGBidAdapter.md
  test/spec/modules/adWMGBidAdapter_spec.js
Labels: bugfix, minor, needs review, needs unit tests

#6278 [ParrableIdSystem] Supply iframe state to backend
  modules/parrableIdSystem.js
  test/spec/modules/parrableIdSystem_spec.js
Labels: maintenance, minor

#6206 Bid Viewability Module
  modules/bidViewability.js
  modules/bidViewability.md
  src/adapterManager.js
  src/constants.json
  test/spec/modules/bidViewability_spec.js
  test/spec/unit/core/adapterManager_spec.js
Labels: feature, minor

#6280 disable webdriver tests in trionBidAdapter spec
  test/spec/modules/trionBidAdapter_spec.js
Labels: maintenance, minor, needs review

#6279 [ParrableIdSystem] Supply Prebid library version to backend
  modules/parrableIdSystem.js
  test/spec/modules/parrableIdSystem_spec.js
Labels: maintenance, minor, needs review, needs update

#6277 [ParrableIdSystem] Accept list of partners as an array or string
  modules/parrableIdSystem.js
  test/spec/modules/parrableIdSystem_spec.js
Labels: feature, minor, needs review, needs update

#6122 Rubicon Bid Adapter FPD Update
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: maintenance, minor, needs review

#6281 ID5 User Id Module: update a/b testing to be user based not request based
  modules/id5IdSystem.js
  modules/id5IdSystem.md
  test/spec/modules/id5IdSystem_spec.js
Labels: LGTM, maintenance, minor

#6275 Shared ID gdpr support
  modules/id5IdSystem.js
  modules/pubCommonIdSystem.js
  modules/sharedIdSystem.js
  modules/userId/index.js
  test/spec/modules/sharedIdSystem_spec.js
  test/spec/modules/userId_spec.js
Labels: feature, minor, needs review

#6006 Lemma:set mediaType key value
  modules/lemmaBidAdapter.js
  test/spec/modules/lemmaBidAdapter_spec.js
Labels: maintenance, minor, needs review

#6005 ix Bid Adapter: added support for addtlConsent
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: feature, minor, needs review

#6247 Add bid adapter for Missena
  modules/missenaBidAdapter.js
  modules/missenaBidAdapter.md
  test/spec/modules/missenaBidAdapter_spec.js
Labels: feature, minor, needs review

#6261 Sharethrough: Add support for ID5, Shared ID, and Live Intent ID
  modules/sharethroughBidAdapter.js
  test/spec/modules/sharethroughBidAdapter_spec.js
Labels: feature, minor

#6236 SmartAdServer Bid Adapter: image sync and noAd
  modules/smartadserverBidAdapter.js
  test/spec/modules/smartadserverBidAdapter_spec.js
Labels: feature, minor

#6283 [ParrableIdSystem] Add GVLID and handle TC Consent data
  modules/parrableIdSystem.js
  test/spec/modules/parrableIdSystem_spec.js
Labels: LGTM, feature, minor

#6285 Updated data mapping of auction and winning bid objects in pubxai analytics adapter.
  modules/pubxaiAnalyticsAdapter.js
  test/spec/modules/pubxaiAnalyticsAdapter_spec.js
Labels: bugfix, minor

#6299 Grid Bid Adapter: Added video protocols to the ad request
  modules/gridBidAdapter.js
  test/spec/modules/gridBidAdapter_spec.js
Labels: feature, minor

#6298 Rubicon Bid Adapter: updated transactionId to auctionId for OpenRTB
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: maintenance, minor

#6297 Fix for Issue 6117: Added Module Name in Build to Comments
  gulpfile.js
Labels: LGTM, maintenance, minor

#6303 map tripleliftBidAdapter.js tl_source to bid.meta.mediaType
  modules/tripleliftBidAdapter.js
Labels: maintenance, minor

#6233 Tappx Bid Adapter: new bidder adapter added
  modules/tappxBidAdapter.js
  modules/tappxBidAdapter.md
  test/spec/modules/tappxBidAdapter_spec.js
Labels: LGTM, feature, minor

#6198 Add Native ad capability to AdYouLike adapter
  modules/adyoulikeBidAdapter.js
  modules/adyoulikeBidAdapter.md
  test/spec/modules/adyoulikeBidAdapter_spec.js
Labels: LGTM, feature, minor

#6300 Fix ttl buffer arithmetic
  src/targeting.js
Labels: needs 2nd review

#6306 Adtelligent Bid Adapter: Add Navelix as alias
  modules/adtelligentBidAdapter.js
  test/spec/modules/adtelligentBidAdapter_spec.js
Labels: LGTM, feature, minor

#6304 add warning for non-string adSlots
  modules/pubmaticBidAdapter.js
  modules/pubmaticBidAdapter.md
Labels: LGTM, maintenance, minor

#6253 Update ttl outstream
  modules/districtmDMXBidAdapter.js
Labels: bugfix, needs review, needs update, patch

#6282 [ParrableIdSystem] Accept lowercase timezone names in timezone filter
  modules/parrableIdSystem.js
  test/spec/modules/parrableIdSystem_spec.js
Labels: maintenance, minor, needs review, question

#6311 Rubicon Bid Adapter: Added new size - Id 550 (980x480)
  modules/rubiconBidAdapter.js
Labels: feature, minor

#6314 Revert "Rubicon Bid Adapter: updated transactionId to auctionId for OpenRTB"
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: maintenance, minor

#6315 Rubicon Bid Adapter: adding size 300x200
  modules/rubiconBidAdapter.js
Labels: feature, minor

#6292 IX Bid Adapter: added Prebid version support
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: feature, minor

#6276 Extended ID permissions supported by bidder
  integrationExamples/gpt/userId_example.html
  modules/prebidServerBidAdapter/index.js
  modules/userId/eids.js
  modules/userId/index.js
  src/utils.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/userId_spec.js
Labels: feature, minor, needs 2nd review, needs review

#6312 logan bid adapter
  modules/loganBidAdapter.js
  modules/loganBidAdapter.md
  test/spec/modules/loganBidAdapter_spec.js
Labels: LGTM, feature, minor

#6318 Tapad ID System: Change Graph URL in ID Submodule
  modules/tapadIdSystem.js
Labels: maintenance, minor

#6286 IndexExchange Bid Adapter: Added support for netID, ID+ and FabrickId userId
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: LGTM, feature, minor

#6321 mediasquare fix userId
  modules/mediasquareBidAdapter.js
Labels: bugfix, minor

#6320 Verizon Media ID System: Changed EU consent string parameter name to gdpr_consent
  modules/verizonMediaIdSystem.js
  test/spec/modules/verizonMediaIdSystem_spec.js
Labels: maintenance, minor

#6273 Prebid Server Bid Adapter: adding support for getFloor
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: feature, minor

#6274 AdHash Bidder Adapter: initial prebid.js integration
  modules/adhashBidAdapter.js
  modules/adhashBidAdapter.md
  test/spec/modules/adhashBidAdapter_spec.js
Labels: LGTM, feature, minor

#6295 PBJS Core: added condition to check config for ignoreBidderCacheKey
  src/auction.js
Labels: maintenance, minor

#6313 Inskin adapter: Support bidder aliasing
  modules/inskinBidAdapter.js
Labels: maintenance, minor, needs review

#6322 Fabrick ID System : updates to _setReferrer and appending urls
  modules/fabrickIdSystem.js
  test/spec/modules/fabrickIdSystem_spec.js
Labels: LGTM, bugfix, minor

#6344 Rubicon Analytics: Add option to delay sending of event message
  modules/rubiconAnalyticsAdapter.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
Labels: bugfix, minor

#6339 Adhese Bid Adapter: replace id5 with eid
  modules/adheseBidAdapter.js
  test/spec/modules/adheseBidAdapter_spec.js
Labels: maintenance, minor

#6343 Reconciliation RTD: update adDeliveryId format
  modules/reconciliationRtdProvider.js
Labels: maintenance, minor

#6316 Inskin Bid Adapter: send screen size in the ad call
  modules/inskinBidAdapter.js
  test/spec/modules/inskinBidAdapter_spec.js
Labels: maintenance, minor

#6324 Ozone Bid Adapter: added or updated support for multiple modules
  modules/ozoneBidAdapter.js
  modules/ozoneBidAdapter.md
  test/spec/modules/ozoneBidAdapter_spec.js
Labels: LGTM, maintenance, minor

#6352 Triplelift Bid Adapter: add PubCommon ID support
  modules/tripleliftBidAdapter.js
  test/spec/modules/tripleliftBidAdapter_spec.js
Labels: maintenance, minor

#6319 GMOSSP Bid Adapter : add refererInfo from bidderRequest
  modules/gmosspBidAdapter.js
  test/spec/modules/gmosspBidAdapter_spec.js
Labels: maintenance, minor

#6341 Axonix Bid Adapter: add new bid adapter
  modules/axonixBidAdapter.js
  modules/axonixBidAdapter.md
  test/spec/modules/axonixBidAdapter_spec.js
Labels: LGTM, feature, minor

#6348 Documentation: Prebid Server and Postbid integration example ( ad server-less )
  integrationExamples/postbid/postbid_prebidServer_example.html
Labels: maintenance, minor

#6220 Native: add custom data assets capability
  src/native.js
  test/spec/native_spec.js
Labels: needs 2nd review

#6334 Iprom Bid Adapter: add new bid adapter
  modules/ipromBidAdapter.js
  modules/ipromBidAdapter.md
  test/spec/modules/ipromBidAdapter_spec.js
Labels: feature, minor

#6357 Ucfunnel Bid Adapter: update currency parameter in ad response
  modules/ucfunnelBidAdapter.js
Labels: maintenance, minor
