Repository prebid/Prebid.js, pull requests merged in 2021-11, with the labels that each got.

#7647 Codefuel Bid Adapter: bugfixes and remove config import
  modules/codefuelBidAdapter.js
  modules/codefuelBidAdapter.md
  test/spec/modules/codefuelBidAdapter_spec.js
Labels: bugfix

#7584 Sspbc Bid Adapter: update version and bugfixes
  modules/sspBCBidAdapter.js
  test/spec/modules/sspBCBidAdapter_spec.js
Labels: bugfix

#7585 Prebid Server Bid Adapter: auctionId to $.id UUID to $.source.tid + mergeDeep extPrebid
  modules/prebidServerBidAdapter/index.js
  src/adapterManager.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/unit/core/adapterManager_spec.js
Labels: maintenance

#7601 VidoomyBidAdapter: refactor cookie sync
  modules/vidoomyBidAdapter.js
  test/spec/modules/vidoomyBidAdapter_spec.js
Labels: needs update, bugfix

#7649 TheMediaGrid Bid Adapter: added adlivetech as alias
  modules/adlivetechBidAdapter.md
  modules/gridBidAdapter.js
Labels: maintenance

#7641 Build: move browser targets to package.json
  .babelrc.js
  package.json
Labels: bugfix

#7642 OpenX Bid Adapter: Handle new user Ids
  modules/openxBidAdapter.js
  test/spec/modules/openxBidAdapter_spec.js
Labels: needs docs, maintenance

#7448 Saamba Bid Adapter: support video params, and the floors module
  modules/saambaaBidAdapter.js
  modules/saambaaBidAdapter.md
Labels: maintenance

#7630 IX Bid Adapter: capture errors in LS and send errors in request
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: LGTM, maintenance

#7655 DeepIntent Bid Adapter: secure flag set using proper protocol value
  modules/deepintentBidAdapter.js
Labels: bugfix

#7657 VIS.X Bid Adapter: fix url for ontimeout pixel
  modules/visxBidAdapter.js
  test/spec/modules/visxBidAdapter_spec.js
Labels: bugfix

#7658 Appnexus bid adapter: add support for brandId
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: feature

#7656 Engageya bid adapter improvements
  modules/engageyaBidAdapter.js
  test/spec/modules/engageyaBidAdapter_spec.js
Labels: LGTM, maintenance, minor

#7679 Eplanning & Adapter Manager: fix testing of innerwidth to fix current build
  test/spec/modules/eplanningBidAdapter_spec.js
  test/spec/unit/core/adapterManager_spec.js
Labels: bugfix

#7675 Smaato Bid Adapter: pass through bidRequest.schain
  modules/smaatoBidAdapter.js
  test/spec/modules/smaatoBidAdapter_spec.js
Labels: maintenance

#7674 Seedtag Bid Adapter: expose seedtag gvl id for TFC2 support
  modules/seedtagBidAdapter.js
  test/spec/modules/seedtagBidAdapter_spec.js
Labels: maintenance

#7672 ID5 ID Module: docs only - remove reference to release notes page and some documentation links
  modules/id5IdSystem.md
Labels: maintenance, documentation

#7636 Glimpse Bid Adapter: Capture target demand provider & account id + use storage manager
  modules/glimpseBidAdapter.js
  test/spec/modules/glimpseBidAdapter_spec.js
Labels: maintenance

#7680 Datablocks Bid Adapter: update url
  modules/datablocksBidAdapter.js
Labels: maintenance

#7687 Datablocks Tests: fix failing tests
  test/spec/modules/datablocksBidAdapter_spec.js
Labels: bugfix

#7664 RichAudience Bid Adapter: Update GetFloors
  modules/richaudienceBidAdapter.js
  package-lock.json
  package.json
Labels: bugfix

#7628 imRtdProvider: update bidderDefaultFunction
  modules/imRtdProvider.js
  test/spec/modules/imRtdProvider_spec.js
Labels: maintenance

#7661 IX Bid Adapter: add support for handling vastXML responses in PBJS
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: feature

#7692 PubMatic Bid Adapter: add Groupm as alias bidder
  modules/pubmaticBidAdapter.js
Labels: maintenance

#7671 GPT Pre Auction: setting GPID
  modules/gptPreAuction.js
  test/spec/modules/gptPreAuction_spec.js
Labels: feature

#7689 Gulp: remove linting from node_modules for newer npm versions
  gulpfile.js
Labels: maintenance

#7685 Ogury bid adapter: sending all custom params to the bidder
  modules/oguryBidAdapter.js
  test/spec/modules/oguryBidAdapter_spec.js
Labels: feature, needs review

#7695 Revert "RichAudience Bid Adapter: Update GetFloors" because of package.json upload
  modules/richaudienceBidAdapter.js
  package-lock.json
  package.json
Labels: bugfix

#7555 YieldOne Bid Adapter: add Flux Wrapper support.
  modules/yieldoneBidAdapter.js
  test/spec/modules/yieldoneBidAdapter_spec.js
Labels: maintenance

#7683 PubMatic : Check for 'bid.ext.bidtype' key instead of 'bid.ext.Bidtype' key in translator response object.
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: feature, LGTM

#7701 Smartx Bid Adapter: enable pbjs log for bid request & outstream player config adjustment
  modules/smartxBidAdapter.js
  test/spec/modules/smartxBidAdapter_spec.js
Labels: maintenance

#7693 Undertone Bid Adapter - update canonical and referral URLs 31599
  modules/undertoneBidAdapter.js
Labels: needs review, maintenance

#7639 Adnuntius Bidder: Added option to pass a user id through ortb2.
  modules/adnuntiusBidAdapter.js
  test/spec/modules/adnuntiusBidAdapter_spec.js
Labels: maintenance

#7662 Prebid Core: Restore use of server-side adapter without client-side adapter
  src/prebid.js
Labels: bugfix

#7708 Revert #7662 "Prebid Core: Restore use of server-side adapter without client-side adapter"
  src/prebid.js
Labels: bugfix

#7699 Craft Bid Adapter: use ajax
  modules/craftBidAdapter.js
Labels: bugfix

#7709 Tappx Bid Adapter: add vendor id
  modules/tappxBidAdapter.js
  test/spec/modules/tappxBidAdapter_spec.js
Labels: maintenance

#7704 Gumgum Bid Adapter: add adUnitCode to requests
  modules/gumgumBidAdapter.js
  test/spec/modules/gumgumBidAdapter_spec.js
Labels: maintenance

#7668 AdPlus Bid Adapter: add new bid adapter
  modules/adplusBidAdapter.js
  modules/adplusBidAdapter.md
  test/spec/modules/adplusBidAdapter_spec.js
Labels: feature, needs review, LGTM

#7633 Prebid Core: add new setting to allow zero cpm bids
  modules/appnexusBidAdapter.js
  src/auction.js
  src/targeting.js
  src/utils.js
  test/spec/modules/appnexusBidAdapter_spec.js
  test/spec/unit/core/targeting_spec.js
Labels: feature, needs 2nd review, minor

#7697 Rich Audience Bid Adapter: update mediatype check
  modules/richaudienceBidAdapter.js
Labels: maintenance

#7721 yahoossp Bid Adapter: docs typo fix
  modules/yahoosspBidAdapter.md
Labels: maintenance

#7598 Relaido Bid Adapter: Modified to response ads in a single API request.
  modules/relaidoBidAdapter.js
  test/spec/modules/relaidoBidAdapter_spec.js
Labels: maintenance

#7727 README: update contributors link to point to modules
  README.md
Labels: maintenance, documentation

#7648 Missena Bid Adapter: add back adapter to latest prebid version
  modules/missenaBidAdapter.js
  test/spec/modules/missenaBidAdapter_spec.js
Labels: maintenance

#7710 Intersection RTD Module: add new RTD module
  modules/intersectionRtdProvider.js
  test/spec/modules/intersectionRtdProvider_spec.js
Labels: feature

#7725 Smaato Bid Adapter: pass through instl
  modules/smaatoBidAdapter.js
  test/spec/modules/smaatoBidAdapter_spec.js
Labels: maintenance

#7650 goldbachXandr Bid Adapter: add new bid adapter
  modules/goldbachBidAdapter.js
  modules/goldbachBidAdapter.md
  test/spec/modules/goldbachBidAdapter_spec.js
Labels: feature, LGTM

#7717 AdmixerBidAdapter: add native media type support
  modules/admixerBidAdapter.js
Labels: maintenance

#7700 iprom Bid Adapter: restore adapter in prebid master
  modules/ipromBidAdapter.js
  test/spec/modules/ipromBidAdapter_spec.js
Labels: maintenance

#7602 LuponMedia Bid Adapter: add adapter back to prebid master
  modules/luponmediaBidAdapter.js
  test/spec/modules/luponmediaBidAdapter_spec.js
Labels: maintenance

#7730 VIS.X Bid Adapter: check ad slot existence
  modules/visxBidAdapter.js
  modules/visxBidAdapter.md
  test/spec/modules/visxBidAdapter_spec.js
Labels: maintenance

#7604 showheroes-bs Bid Adapter: fix for outstream render
  modules/showheroes-bsBidAdapter.js
Labels: bugfix

#7734 Revert "showheroes-bs Bid Adapter: fix for outstream render"
  modules/showheroes-bsBidAdapter.js
Labels: bugfix

#7696 Testing Browserlist: remove browsers for testing that are not being built as a target
  browsers.json
  karma.conf.maker.js
Labels: build process, needs 2nd review, maintenance

#7504 freewheel-ssp Bid Adapter: add schain in request params
  modules/freewheel-sspBidAdapter.js
  test/spec/modules/freewheel-sspBidAdapter_spec.js
Labels: maintenance

#7681 UserID Module: allow userid to ppid sync
  modules/userId/index.js
  test/spec/integration/faker/googletag.js
  test/spec/modules/userId_spec.js
Labels: feature, needs review

#7720 EMX Digital Bid Adapter: add GPID support
  modules/emx_digitalBidAdapter.js
  test/spec/modules/emx_digitalBidAdapter_spec.js
Labels: maintenance

#7706 Limelight Digital Bid Adapter: Add optional Publisher ID field
  modules/limelightDigitalBidAdapter.js
  test/spec/modules/limelightDigitalBidAdapter_spec.js
Labels: maintenance

#7660 adyoulike Bid Adapter: Add userIds to bidrequest
  modules/adyoulikeBidAdapter.js
  test/spec/modules/adyoulikeBidAdapter_spec.js
Labels: maintenance

#7473 Dchain module: initial release & Appnexus bid adapter: partial dchain support
  modules/appnexusBidAdapter.js
  modules/dchain.js
  modules/dchain.md
  test/spec/modules/appnexusBidAdapter_spec.js
  test/spec/modules/dchain_spec.js
Labels: feature, minor

#7733 Beachfront Bid Adapter: add first-party data support
  modules/beachfrontBidAdapter.js
  test/spec/modules/beachfrontBidAdapter_spec.js
Labels: maintenance

#7738 SharedID module: update tests to assert on behavior rather than logs
  test/spec/modules/sharedIdSystem_spec.js
Labels: bugfix

#7737 gumgum & adagio Bid Adapters: remove extra defensive code to solve lgtm alert
  modules/adagioBidAdapter.js
  modules/gumgumBidAdapter.js
Labels: maintenance

#7703 33acrossBidAdapter: Add Support for SRA
  modules/33acrossBidAdapter.js
  test/spec/modules/33acrossBidAdapter_spec.js
Labels: maintenance

#7742 Dspx Bid Adapter: remove redundant alias
  modules/dspxBidAdapter.js
Labels: maintenance

#7644 Lotame panorama id submodule: handle consent
  modules/lotamePanoramaIdSystem.js
  test/spec/modules/lotamePanoramaIdSystem_spec.js
Labels: maintenance

#7746 Yahoo SSP Bid Adapter: interstitial fix
  modules/yahoosspBidAdapter.js
  test/spec/modules/yahoosspBidAdapter_spec.js
Labels: bugfix

#7743 Kinesso ID System: fixing the endpoint construction
  modules/kinessoIdSystem.js
Labels: bugfix

#7716 VidoomyBidAdapter: fix video mediatype sizes format
  modules/vidoomyBidAdapter.js
Labels: LGTM, bugfix

#7739 Prebid core: move generation of 'installedModules' to babel
  gulpfile.js
  plugins/pbjsGlobals.js
  src/prebid.js
Labels: maintenance

#7690 Prebid Core: add 'targetingControls.addTargetingKeys' configuration option
  src/targeting.js
  test/spec/unit/core/targeting_spec.js
Labels: feature

#7753 Admixer Bid Adapter: add alias futureads
  modules/admixerBidAdapter.js
  modules/futureads.md
Labels: maintenance

#7728 Weborama Rtd Provider: access user profiles in local storage and add support to wam2gam and smartadserver
  integrationExamples/gpt/weboramaRtdProvider_example.html
  modules/weboramaRtdProvider.js
  modules/weboramaRtdProvider.md
  test/spec/modules/weboramaRtdProvider_spec.js
Labels: LGTM, maintenance

#7740 Zeta Ssp Bid Adapter: vast xml for bid
  modules/zetaSspBidAdapter.md
  modules/zeta_global_sspBidAdapter.js
  test/spec/modules/zeta_global_sspBidAdapter_spec.js
Labels: maintenance

#7749 NextMillennium Bid Adapter: add getUserSyncs function
  modules/nextMillenniumBidAdapter.js
  test/spec/modules/nextMillenniumBidAdapter_spec.js
Labels: maintenance

#7759 BeOp Bid Adapter: fix tracking params
  modules/beopBidAdapter.js
Labels: bugfix

#7744 PBS Bid adapter: timeout user syncs if they never load
  modules/prebidServerBidAdapter/index.js
  src/utils.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/utils_spec.js
Labels: bugfix

#7745 Cwire Bid Adapter: forward additional GET param
  modules/cwireBidAdapter.js
  test/spec/modules/cwireBidAdapter_spec.js
Labels: maintenance

#7767 Criteo Bid Adapter: update fast bid version
  modules/criteoBidAdapter.js
Labels: maintenance

#7718 TargetVideo Bid Adapter: add new bid adapter
  modules/appnexusBidAdapter.js
  modules/targetVideoBidAdapter.js
  modules/targetVideoBidAdapter.md
  test/spec/modules/targetVideoBidAdapter_spec.js
Labels: feature

#7763 Adman Bidder Adapter: add lotamePanoramaId
  modules/admanBidAdapter.js
Labels: maintenance

#7762 ZetaSspBidAdapter: provide media type
  modules/zeta_global_sspBidAdapter.js
  test/spec/modules/zeta_global_sspBidAdapter_spec.js
Labels: maintenance

#7779 Glimpse Bid Adapter: fix GDPR consent choice capture
  modules/glimpseBidAdapter.js
Labels: bugfix

#7780 Mediasquare bidder: remove old user sync method
  modules/mediasquareBidAdapter.js
  test/spec/modules/mediasquareBidAdapter_spec.js
Labels: maintenance
