Repository prebid/Prebid.js, pull requests merged in 2021-01, with the labels that each got.

#6144 FreeWheel Bid Adapter: add support for campaignId, bannerId, and dealId
  modules/freewheel-sspBidAdapter.js
  test/spec/modules/freewheel-sspBidAdapter_spec.js
Labels: LGTM, feature, minor

#6147 IronSourceBidAdapter: Change logic of detect pageURL
  modules/ironsourceBidAdapter.js
Labels: LGTM, bugfix, minor

#6161 Improve Digital adapter: added video skippability params
  modules/improvedigitalBidAdapter.js
  test/spec/modules/improvedigitalBidAdapter_spec.js
Labels: LGTM, feature, minor

#6164 add getUserSyncs to pubxBidAdapter
  modules/pubxBidAdapter.js
  test/spec/modules/pubxBidAdapter_spec.js
Labels: LGTM, feature, minor

#6139 Eplanning: new prioritization metric for adunit sizes
  modules/eplanningBidAdapter.js
  test/spec/modules/eplanningBidAdapter_spec.js
Labels: feature, needs review, patch

#6135 changed vdo.ai bidder code to vdoai
  modules/vdoaiBidAdapter.js
  modules/vdoaiBidAdapter.md
  test/spec/modules/vdoaiBidAdapter_spec.js
Labels: LGTM, bugfix, patch

#6114 appnexusBidAdapter - add support for netId userID
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: LGTM, feature, minor

#6157 Update ucfunnelBidAdapter
  modules/ucfunnelBidAdapter.js
  test/spec/modules/ucfunnelBidAdapter_spec.js
Labels: LGTM, feature, minor

#6143 DfpAdServerVideo: Pass GDPR Consent Data
  modules/dfpAdServerVideo.js
  test/spec/modules/dfpAdServerVideo_spec.js
Labels: maintenance, minor, needs review

#6168 TE Medya Prebid Adapter
  modules/temedyaBidAdapter.js
  modules/temedyaBidAdapter.md
  test/spec/modules/temedyaBidAdapter_spec.js
Labels: LGTM, feature, minor

#6169 ID5 User ID Module: store privacy object from id5 response in local storage
  modules/id5IdSystem.js
  test/spec/modules/id5IdSystem_spec.js
Labels: feature, needs review, patch

#6165 Rise adapter
  modules/riseBidAdapter.js
  modules/riseBidAdapter.md
  test/spec/modules/riseBidAdapter_spec.js
Labels: LGTM, feature, minor

#6148 Gjirafa & Malltv Bid Adapters: new optional params
  modules/gjirafaBidAdapter.js
  modules/malltvBidAdapter.js
Labels: needs review

#6124 Add the root domain check method as a util method added for use mod…
  integrationExamples/gpt/userId_example.html
  modules/userId/index.js
  test/spec/modules/userId_spec.js
Labels: LGTM, feature, minor

#6183 fix includes and find references in various files
  modules/adxpremiumAnalyticsAdapter.js
  modules/cleanmedianetBidAdapter.js
  modules/gamoshiBidAdapter.js
  modules/medianetAnalyticsAdapter.js
  modules/sspBCBidAdapter.js
  modules/verizonMediaIdSystem.js
  modules/yieldmoBidAdapter.js
  modules/yuktamediaAnalyticsAdapter.js
  src/targeting.js
  test/spec/modules/stroeerCoreBidAdapter_spec.js
  test/spec/modules/userId_spec.js
Labels: bugfix, patch

#6181 Fix typo in mediaforce bid adapter
  modules/mediaforceBidAdapter.js
  test/spec/modules/mediaforceBidAdapter_spec.js
Labels: LGTM, bugfix, patch

#5411 Prebid JS Native Phase 2 update:
  src/constants.json
  src/native.js
  src/secureCreatives.js
  test/spec/native_spec.js
Labels: LGTM

#6072 Improve __uspapi behavior in iframe
  modules/consentManagementUsp.js
Labels: maintenance, minor, needs 2nd review

#6155 Sovrn: Add Support for Floor Module
  modules/sovrnBidAdapter.js
  test/spec/modules/sovrnBidAdapter_spec.js
Labels: LGTM, feature, minor

#6185 Lotame panorama id glv
  modules/lotamePanoramaIdSystem.js
Labels: LGTM, feature, patch

#6190 Admixer bid adapter: add fpd
  modules/admixerBidAdapter.js
Labels: LGTM, feature, patch

#6116 Add Adomain Targeting Key and Default Targeting Keys
  src/auction.js
  src/constants.json
  src/targeting.js
  test/spec/auctionmanager_spec.js
Labels: feature, minor, needs 2nd review, needs docs

#6191 Adkernel: torchad alias
  modules/adkernelBidAdapter.js
  test/spec/modules/adkernelBidAdapter_spec.js
Labels: LGTM, feature, patch

#6150 New feature: PBS anti alias
  modules/adtelligentBidAdapter.js
  modules/prebidServerBidAdapter/index.js
  src/adapterManager.js
  src/adapters/bidderFactory.js
  test/spec/modules/adtelligentBidAdapter_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/unit/core/bidderFactory_spec.js
Labels: LGTM, feature, minor, needs 2nd review

#6149 Waardex Bid Adapter: Add video support, refactor code
  modules/waardexBidAdapter.js
  modules/waardexBidAdapter.md
  test/spec/modules/waardexBidAdapter_spec.js
Labels: feature, needs update, patch, question

#6193 ID5 User Id Module: move id5's user id extension to the uids array
  modules/rubiconBidAdapter.js
  modules/spotxBidAdapter.js
  modules/userId/eids.js
  modules/userId/eids.md
  test/spec/modules/eids_spec.js
  test/spec/modules/id5IdSystem_spec.js
  test/spec/modules/nobidBidAdapter_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/spotxBidAdapter_spec.js
Labels: LGTM, maintenance, patch

#6167 Add tapad id submodule
  modules/.submodules.json
  modules/tapadIdSystem.js
  modules/userId/eids.js
  modules/userId/eids.md
  test/spec/modules/eids_spec.js
  test/spec/modules/tapadIdSystem_spec.js
  test/spec/modules/userId_spec.js
Labels: feature, minor

#6166 add AdTrue bid adapter
  modules/adtrueBidAdapter.js
  modules/adtrueBidAdapter.md
  test/spec/modules/adtrueBidAdapter_spec.js
Labels: LGTM, feature, minor

#6200 Waardex bid adapter: use find function from core-js
  modules/waardexBidAdapter.js
Labels: bugfix, minor, needs review

#6194 Price Floors: use standard cpmAdjustment
  modules/priceFloors.js
  test/spec/modules/priceFloors_spec.js
Labels: bugfix, needs 2nd review, needs review, patch

#6184 Rubicon Analytics Adapter: Move wrapper details into wrapper object
  modules/rubiconAnalyticsAdapter.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
Labels: maintenance, patch

#6178 Fallback to utilize ad unit code if dmx id is not provide and increased TTL value
  modules/districtmDMXBidAdapter.js
  test/spec/modules/districtmDmxBidAdapter_spec.js
Labels: LGTM, maintenance, patch

#6188 Rubicon analytics Adapter: Add logic to send batched message when slots render
  modules/rubiconAnalyticsAdapter.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
Labels: bugfix, patch

#6192 Lotame TCF fall back to cookies when consent data is otherwise unavailable
  modules/lotamePanoramaIdSystem.js
  test/spec/modules/lotamePanoramaIdSystem_spec.js
Labels: LGTM, feature, patch

#6187 Lotame panorama id system updates
  modules/lotamePanoramaIdSystem.js
  test/spec/modules/lotamePanoramaIdSystem_spec.js
Labels: maintenance, needs review, patch

#6203 Support Outbrain alias in Zemanta adapter
  modules/zemantaBidAdapter.js
  test/spec/modules/zemantaBidAdapter_spec.js
Labels: maintenance, minor

#6211 Yieldlab Adapter: Change URI of outstream renderer
  modules/yieldlabBidAdapter.js
  test/spec/modules/yieldlabBidAdapter_spec.js
Labels: maintenance, minor

#6208 Livewrapped: GVL id
  modules/livewrappedBidAdapter.js
Labels: maintenance, minor

#6177 IX Bid Adapter: Multiformat support, video adunit param, IXdiags
  modules/ixBidAdapter.js
  modules/ixBidAdapter.md
  test/spec/modules/ixBidAdapter_spec.js
Labels: LGTM, maintenance, patch

#6199 Colossus adapter bidfloor support
  modules/colossussspBidAdapter.js
  test/spec/modules/colossussspBidAdapter_spec.js
Labels: feature, minor

#6080 EMX revised issue with schain forwarding
  modules/emx_digitalBidAdapter.js
  test/spec/modules/emx_digitalBidAdapter_spec.js
Labels: needs review, needs update

#5900 Criteo: Re-enable ad building when mediation is off and remove enableSendAllBids condition
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: LGTM, maintenance, minor

#6217 Change Variable Typo and Make Variable Name More Descriptive
  src/adapterManager.js
Labels: maintenance

#6215 Appnexus - Fix Outstream render issue with Smart Ad Server
  modules/appnexusBidAdapter.js
Labels: bugfix, minor, needs review

#6223 add md file for tapadIdSystem
  modules/tapadIdSystem.md
Labels: maintenance

#6209 Implement glomex bid adapter
  modules/glomexBidAdapter.js
  modules/glomexBidAdapter.md
  test/spec/modules/glomexBidAdapter_spec.js
Labels: LGTM, feature, minor

#6218 Criteo: Increment adapter version
  modules/criteoBidAdapter.js
Labels: LGTM, maintenance, minor

#6229 Triplelift Bid Adapter: Support for video floors
  modules/tripleliftBidAdapter.js
  test/spec/modules/tripleliftBidAdapter_spec.js
Labels: bugfix, patch

#6145 Ats analytics additional analytics data
  modules/atsAnalyticsAdapter.js
  modules/atsAnalyticsAdapter.md
  modules/identityLinkIdSystem.js
  test/spec/modules/atsAnalyticsAdapter_spec.js
Labels: LGTM, feature, patch

#5992 Feature: Multiple Prebid Servers
  modules/prebidServerBidAdapter/index.js
  modules/s2sTesting.js
  src/adapterManager.js
  src/prebid.js
  test/fixtures/fixtures.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/s2sTesting_spec.js
  test/spec/unit/core/adapterManager_spec.js
Labels: LGTM, feature, minor, needs 2nd review

#6214 Between multirequests
  modules/betweenBidAdapter.js
  test/spec/modules/betweenBidAdapter_spec.js
Labels: LGTM, feature, improvement, minor

#6230 Fix astraoneBidAdapter
  modules/astraoneBidAdapter.js
  modules/astraoneBidAdapter.md
  test/spec/modules/astraoneBidAdapter_spec.js
Labels: LGTM, bugfix, minor

#6228 districtmDMX: update banner ttl
  modules/districtmDMXBidAdapter.js
Labels: bugfix, minor

#6048 browsi: updating test parameters
  modules/browsiRtdProvider.md
Labels: needs review, stale

#6159 SpotX Bid Adapter: default to 4/3 aspect ratio when response doesn't contain w or h
  modules/spotxBidAdapter.js
  test/spec/modules/spotxBidAdapter_spec.js
Labels: bugfix, minor

#6112 Extended ID permissions supported by bidder
  integrationExamples/gpt/userId_example.html
  modules/prebidServerBidAdapter/index.js
  modules/userId/eids.js
  modules/userId/index.js
  plugins/eslint/validateImports.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/userId_spec.js
Labels: feature, minor

#6195 Relevant Yield analytics adapter
  modules/relevantAnalyticsAdapter.js
  modules/relevantAnalyticsAdapter.md
  test/spec/modules/relevantAnalyticsAdapter_spec.js
Labels: feature, minor

#6152 Pubmatic Adapter: fix issue where using an adUnit outstream renderer throws an error
  modules/pubmaticBidAdapter.js
  modules/pubmaticBidAdapter.md
Labels: LGTM, bugfix, minor

#6232 Malltv Bid Adapter : added data object as a param
  modules/malltvBidAdapter.js
  modules/malltvBidAdapter.md
  test/spec/modules/malltvBidAdapter_spec.js
Labels: LGTM, feature, minor
