Repository prebid/Prebid.js, pull requests merged in 2021-05, with the labels that each got.

#6686 Bidgewell Bid Adapter: add support for advertiser domains
  modules/bridgewellBidAdapter.js
  test/spec/modules/bridgewellBidAdapter_spec.js
Labels: maintenance, minor

#6666 DMD ID System: add new User ID module
  modules/.submodules.json
  modules/dmdIdSystem.js
  modules/dmdIdSystem.md
  modules/userId/eids.js
  modules/userId/eids.md
  modules/userId/userId.md
  test/spec/modules/dmdIdSystem_spec.js
  test/spec/modules/userId_spec.js
Labels: feature, minor, needs review

#6688 appnexus Bid Adapter - add support for gptPreAuction
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: feature, minor, needs review

#6632 SharedId & PubcommonId: CCPA and COPPA support
  modules/pubCommonIdSystem.js
  modules/sharedIdSystem.js
  src/adapterManager.js
  test/spec/modules/sharedIdSystem_spec.js
  test/spec/unit/core/adapterManager_spec.js
Labels: maintenance, minor, needs 2nd review, needs review, needs update

#6653 appnexus bid adapter - add price floor module support
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: maintenance, minor, needs review

#6616 PBJS Core - Validate adunit page position / PBS and RP adapters updates to pass pos in banner and video requests
  modules/prebidServerBidAdapter/index.js
  modules/rubiconBidAdapter.js
  src/prebid.js
  test/spec/modules/rubiconBidAdapter_spec.js
  test/spec/unit/pbjs_api_spec.js
Labels: 5.0 API Change, feature, major

#6683 Prebid Core: Display bidder in utils.logs and disable bidder config on auction end
  src/adapterManager.js
  src/adapters/bidderFactory.js
  src/auction.js
  src/config.js
  src/utils.js
Labels: bugfix, feature, minor, needs 2nd review

#6676 Prebid Core: add X-Prebid header to ajax requests
  src/ajax.js
Labels: feature, minor, needs docs

#6704 Update README.md - Fix Typo
  README.md
Labels: maintenance, minor

#6701 Criteo Bid Adapter: update contact email
  modules/criteoBidAdapter.md
Labels: maintenance, minor

#6706 Fixing flaky adapter unit tests
  modules/prebidmanagerAnalyticsAdapter.js
  modules/sspBCBidAdapter.js
  modules/userId/index.js
  modules/yieldmoBidAdapter.js
  test/spec/modules/prebidmanagerAnalyticsAdapter_spec.js
  test/spec/modules/sharethroughBidAdapter_spec.js
Labels: bugfix, minor

#6521 Floc Userid System: add new ID module
  integrationExamples/gpt/userId_example.html
  modules/.submodules.json
  modules/flocIdSystem.js
  modules/flocIdSystem.md
  modules/userId/userId.md
  test/spec/modules/userId_spec.js
Labels: feature, minor

#6697 Zeta Bid Adapter: update to endpoint
  modules/zetaBidAdapter.js
  modules/zetaBidAdapter.md
  test/spec/modules/zetaBidAdapter_spec.js
Labels: maintenance, minor

#6714 Adkernel Bid Adapter: add converge digital as alias
  modules/adkernelBidAdapter.js
Labels: maintenance, minor

#6694 Prebid Core: Fix linting in Gulpfile
  gulpfile.js
Labels: maintenance, minor

#6674 Admixer Bid Adapter: add meta key to response
  modules/admixerBidAdapter.js
  test/spec/modules/admixerBidAdapter_spec.js
Labels: maintenance, minor

#6716 Grid Bid Adapter: add support for advertiserDomains
  modules/gridBidAdapter.js
  test/spec/modules/gridBidAdapter_spec.js
Labels: maintenance, minor

#6719 33across bid adapter: Add adomain support
  modules/33acrossBidAdapter.js
  test/spec/modules/33acrossBidAdapter_spec.js
Labels: maintenance, minor

#6724 Uid2 id system: Fix typo in doc
  modules/uid2IdSystem.md
Labels: maintenance, minor

#6626 Tappx Bid Adapter: add floor module support
  modules/tappxBidAdapter.js
  test/spec/modules/tappxBidAdapter_spec.js
Labels: maintenance, minor

#6687 VIS.X: add instream video support
  modules/visxBidAdapter.js
  modules/visxBidAdapter.md
  test/spec/modules/visxBidAdapter_spec.js
Labels: feature, minor

#6551 userID Module: move reading and writing of the consent string hash
  modules/userId/index.js
Labels: bugfix, minor

#6689 ParrableIdSystem : Store third-party cookie support status in first-party cookie
  modules/parrableIdSystem.js
  test/spec/modules/parrableIdSystem_spec.js
Labels: LGTM, maintenance, minor

#6737 ViewDeos Bid Adapter: add gvlid
  modules/viewdeosDXBidAdapter.js
Labels: maintenance, minor

#6679 Rubicon adapter: ortb2 data update to use segtax
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: maintenance, minor, needs review

#6746 Qwarry Bid Adapter: remove gdpr field from request
  modules/qwarryBidAdapter.js
  test/spec/modules/qwarryBidAdapter_spec.js
Labels: bugfix, minor

#6742 Halo RTD Module: add publisher params to RTD request
  modules/haloRtdProvider.js
Labels: maintenance, minor

#6678 Prebid Core: Remove size check on native icons and image assets
  src/native.js
  test/spec/native_spec.js
Labels: bugfix, minor, needs 2nd review

#6740 Prebid Server Bid Adapter: Bugfix for not taking defaultVendor enabled
  modules/prebidServerBidAdapter/index.js
Labels: bugfix, minor

#6751 Beachfront Bid Adapter: add schain support
  modules/beachfrontBidAdapter.js
  modules/beachfrontBidAdapter.md
  test/spec/modules/beachfrontBidAdapter_spec.js
Labels: maintenance, minor

#6755 gdprEnforcement Module: Webpack v5 named export from JSON modules
  modules/gdprEnforcement.js
Labels: maintenance, minor

#6723 Pbs bid adapter: constants import styling for webpack v5 upgrade
  modules/prebidServerBidAdapter/index.js
Labels: maintenance, minor

#6452 First Party Data module: Add new module and two submodules to populate defaults and validate ortb2
  modules/.submodules.json
  modules/enrichmentFpdModule.js
  modules/fpdModule/index.js
  modules/fpdModule/index.md
  modules/validationFpdModule/config.js
  modules/validationFpdModule/index.js
  test/spec/modules/enrichmentFpdModule_spec.js
  test/spec/modules/fpdModule_spec.js
  test/spec/modules/validationFpdModule_spec.js
Labels: feature, minor, taxonomy

#6696 Datablocks bid adapter: update adapter to conform to new bid server's format
  modules/datablocksAnalyticsAdapter.js
  modules/datablocksBidAdapter.js
  modules/datablocksBidAdapter.md
  test/spec/modules/datablocksBidAdapter_spec.js
Labels: LGTM, maintenance, minor

#6757 PBJS videoCache: Update to add auction Id in vasttrack payload
  src/videoCache.js
  test/spec/videoCache_spec.js
Labels: feature, minor

#6759 Permutive RTD module docs: depends on `rtdModule`
  modules/permutiveRtdProvider.md
Labels: maintenance, minor

#6682 PBS Bid Adapter: Video payload update to add w and h values and filter unused context/playerSize
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: maintenance, minor, needs 2nd review

#6764 Sovrn and Sharethrough Bid Adapters: support for advertiserDomains
  modules/sharethroughBidAdapter.js
  modules/sovrnBidAdapter.js
  test/spec/modules/sharethroughBidAdapter_spec.js
  test/spec/modules/sovrnBidAdapter_spec.js
Labels: maintenance, minor

#6744 ucfunnel Bid Adapter: add support for FLoC and Verizon Media ConnectID
  modules/ucfunnelBidAdapter.js
  test/spec/modules/ucfunnelBidAdapter_spec.js
Labels: LGTM, maintenance, minor

#6768 Permutive Rtd Submodule: register submodule in submodules list
  modules/.submodules.json
Labels: bugfix, minor

#6774 Beachfront Bid Adapter: update doc for video params
  modules/beachfrontBidAdapter.md
Labels: maintenance, minor

#6772 Eplanning Bid Adapter: Adjust endpoint parameter formatting
  modules/eplanningBidAdapter.js
  test/spec/modules/eplanningBidAdapter_spec.js
Labels: maintenance, minor

#6770 Beachfront Bid Adapter: add Unified ID 2.0 support
  modules/beachfrontBidAdapter.js
  test/spec/modules/beachfrontBidAdapter_spec.js
Labels: maintenance, minor

#6753 Appnexus bid adapter: create stub for meta.advertiserDomains
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: maintenance, minor

#6775 Conversant adapter - picks up additional params from mediaTypes.video
  modules/conversantBidAdapter.js
  modules/conversantBidAdapter.md
Labels: maintenance, minor

#6776 Relaido Adapter : size of the banner is checked and the banner can be bid on.
  modules/relaidoBidAdapter.js
  test/spec/modules/relaidoBidAdapter_spec.js
Labels: maintenance, minor

#6777 Zeta Bid Adapter: update url forward slash typo
  modules/zetaSspBidAdapter.js
Labels: bugfix, minor

#6781 Adagio Bid Adapter: handle meta.advertiserDomains and update version
  modules/adagioBidAdapter.js
  test/spec/modules/adagioBidAdapter_spec.js
Labels: maintenance, minor

#6749 PubMatic Adapter: add support for FloCID
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: feature, minor, needs review

#6771 TrustX Bid Adapter: added additional sync url
  modules/trustxBidAdapter.js
Labels: maintenance, minor

#6779 Bucksense Bid Adapter: add adomain to adapter
  modules/bucksenseBidAdapter.js
  test/spec/modules/bucksenseBidAdapter_spec.js
Labels: maintenance, minor

#6767 PBS Bid Adapter / Rubicon Project Bid Adapter: update to pass PBJS version in request
  modules/prebidServerBidAdapter/index.js
  modules/rubiconBidAdapter.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: feature, minor

#6743 AOL Bid Adapter: Remove client side support for already deprecated endpoint floor support
  modules/aolBidAdapter.js
  test/spec/modules/aolBidAdapter_spec.js
Labels: maintenance, minor

#6761 tappx Bid Adapter: update isBidRequestValid and fix request url
  modules/tappxBidAdapter.js
  modules/tappxBidAdapter.md
  test/spec/modules/tappxBidAdapter_spec.js
Labels: bugfix, minor

#6787 Qwarry Bid Adapter: add sizes
  modules/qwarryBidAdapter.js
  test/spec/modules/qwarryBidAdapter_spec.js
Labels: maintenance, minor

#6713 Medianet bid adapter: floor module support
  modules/medianetBidAdapter.js
  test/spec/modules/medianetBidAdapter_spec.js
Labels: maintenance, minor

#6791 BetweenBidAdapter: add adomain support
  modules/betweenBidAdapter.js
  test/spec/modules/betweenBidAdapter_spec.js
Labels: maintenance, minor

#6752 Beachfront Bid Adapter: add floors module support
  modules/beachfrontBidAdapter.js
  test/spec/modules/beachfrontBidAdapter_spec.js
Labels: maintenance, minor

#6786 Zeta Ssp Bid Adapter: merge fpd.device and params.device
  modules/zetaSspBidAdapter.js
Labels: maintenance, minor

#6793 pubGENIUS bid adapter: read more video params from mediaTypes.video
  modules/pubgeniusBidAdapter.js
  modules/pubgeniusBidAdapter.md
  test/spec/modules/pubgeniusBidAdapter_spec.js
Labels: maintenance, minor

#6795 Rubicon Analytics Adapter: remove legacy camel case of adserver.adslot
  modules/rubiconAnalyticsAdapter.js
Labels: maintenance, minor

#6747 Criteo Bid Adapter: add comment to explain how to remove dependency on RSA validation lib
  modules/criteoBidAdapter.js
Labels: 5.0 API Change, maintenance, minor

#6778 Criteo Bid Adapter: update adapter to use mediaTypes.video instead of custom parameters
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: 5.0 API Change, maintenance, minor

#6736 CCX Bid Adapter: add support for mediatypes video parameters
  modules/ccxBidAdapter.js
  modules/ccxBidAdapter.md
  test/spec/modules/ccxBidAdapter_spec.js
Labels: maintenance, minor

#6506 Invibes Bid Adapter: multiposition ad serving & support for multiple id modules
  modules/invibesBidAdapter.js
  test/spec/modules/invibesBidAdapter_spec.js
Labels: maintenance, minor

#6801 appnexus bid adapter: add support for flocid
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: maintenance, minor

#6803 Restore xhb - revert accidental commit
  modules/xhbBidAdapter.js
Labels: maintenance, minor

#6805 EMX Digital Bid Adapter: floor module and advertiserDomain support
  modules/emx_digitalBidAdapter.js
  test/spec/modules/emx_digitalBidAdapter_spec.js
Labels: maintenance, minor

#6782 Index Exchange Bid Adapter: coppa support, dealid & ttl field updates
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance, minor

#6810 Permutive Rtd Provider: additional documentation
  modules/permutiveRtdProvider.md
Labels: documentation, minor

#6798 Conversant adapter: add support for the floor module
  modules/conversantBidAdapter.js
  test/spec/modules/conversantBidAdapter_spec.js
Labels: maintenance, minor

#6690 appnexus bid adapter 5.0 - video params updates
  modules/appnexusBidAdapter.js
  modules/appnexusBidAdapter.md
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: Prebid 5.0, feature, major

#6811 JW Player RTD Module - dev doc improvements
  modules/jwplayerRtdProvider.md
Labels: documentation, minor

#6812 Prebid Core: Fix linting error on src/refererDetection.js
  src/refererDetection.js
Labels: Prebid 5.0, bugfix, major

#6813 OpenX Bid Adapter: add support for mediaTypes.video and gpid
  modules/openxBidAdapter.js
  modules/openxBidAdapter.md
  test/spec/modules/openxBidAdapter_spec.js
Labels: maintenance, minor

#6790 SynacorMedia Bid Adapter: Add userID support
  modules/synacormediaBidAdapter.js
  test/spec/modules/synacormediaBidAdapter_spec.js
Labels: maintenance, minor

#6815 VIS.X bid adapter: change tracking win & pending url's
  modules/visxBidAdapter.js
  test/spec/modules/visxBidAdapter_spec.js
Labels: maintenance, minor

#6729 Ogury Bid Adapter: add new adapter
  modules/oguryBidAdapter.js
  modules/oguryBidAdapter.md
  test/spec/modules/oguryBidAdapter_spec.js
Labels: feature, minor

#6741 ParrableIdSystem: Store third-party cookie support status in first-party cookie
  modules/parrableIdSystem.js
  test/spec/modules/parrableIdSystem_spec.js
Labels: maintenance, minor

#6824 ID5 User Id Module: update docs links
  modules/id5IdSystem.md
  modules/userId/userId.md
Labels: maintenance, minor

#6699 Adagio Bid Adapter: decrease adapter weight
  allowedModules.js
  modules/adagioBidAdapter.js
  package-lock.json
  package.json
  test/spec/modules/adagioBidAdapter_spec.js
Labels: maintenance, minor

#6773 PubMatic Adapter : Support For Video Params from AdUnit MediaTypes
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: maintenance, minor

#6825 Kobler bid adapter: Fill currency parameters
  modules/koblerBidAdapter.js
  test/spec/modules/koblerBidAdapter_spec.js
Labels: maintenance, minor

#6726 Adf Bid Adapter: banner and video media type support added
  modules/adfBidAdapter.js
  modules/adfBidAdapter.md
  test/spec/modules/adfBidAdapter_spec.js
Labels: feature, minor, needs review

#6829 Trion bid adapter: support for meta advertiserDomains
  modules/trionBidAdapter.js
  test/spec/modules/trionBidAdapter_spec.js
Labels: maintenance, minor

#6826 Sonobi bid adapter: add support for gpid and set advertiserDomains
  modules/sonobiBidAdapter.js
  test/spec/modules/sonobiBidAdapter_spec.js
Labels: maintenance, minor

#6832 Eplanning Bid Adapter: verify getUserIds exists and is a function; add adomain support
  modules/eplanningBidAdapter.js
  test/spec/modules/eplanningBidAdapter_spec.js
Labels: bugfix

#6410 Dgkeyword Rtd Provider: add new real-time data submodule
  modules/.submodules.json
  modules/dgkeywordRtdProvider.js
  modules/dgkeywordRtdProvider.md
  test/spec/modules/dgkeywordRtdProvider_spec.js
Labels: feature, minor, needs update, taxonomy

#6838 NativoBidAdapter - Added new QS param to the bid request endpoint
  modules/nativoBidAdapter.js
  test/spec/modules/nativoBidAdapter_spec.js
Labels: maintenance

#6842 Beachfront Bid Adapter: add support for advertiser domains
  modules/beachfrontBidAdapter.js
  test/spec/modules/beachfrontBidAdapter_spec.js
Labels: maintenance

#6707 Prebid Core: Check for stale rendering
  src/auctionManager.js
  src/config.js
  src/constants.json
  src/prebid.js
  src/secureCreatives.js
  test/spec/config_spec.js
  test/spec/unit/pbjs_api_spec.js
  test/spec/unit/secureCreatives_spec.js
Labels: feature, minor, needs 2nd review

#6834 tappx Bid Adapter: fix wrong regex and gdpr bug
  modules/tappxBidAdapter.js
Labels: bugfix

#6831 Adyoulike bid adapter - improvements on Native case
  modules/adyoulikeBidAdapter.js
  test/spec/modules/adyoulikeBidAdapter_spec.js
Labels: maintenance

#6835 Zeta Ssp Bid Adapter: Improve user sync logic
  modules/zetaSspBidAdapter.js
  test/spec/modules/zetaSspBidAdapter_spec.js
Labels: maintenance

#6843 Mediasquare Bid Adapter: support advertiserDomains
  modules/mediasquareBidAdapter.js
  test/spec/modules/mediasquareBidAdapter_spec.js
Labels: maintenance

#6711 Apacdex Bid Adapter: add support for meta.advertiserDomains, add and update sample adunit, validate dealId field from server response, add support Price Floors Module
  modules/apacdexBidAdapter.js
  modules/apacdexBidAdapter.md
  test/spec/modules/apacdexBidAdapter_spec.js
Labels: maintenance, minor

#6849 Invibes Bid Adapter - support for meta taxonomy
  modules/invibesBidAdapter.js
  test/spec/modules/invibesBidAdapter_spec.js
Labels: maintenance

#6852 adWMG Adapter: add 'adomain' support
  modules/adWMGBidAdapter.js
  test/spec/modules/adWMGBidAdapter_spec.js
Labels: maintenance

#6853 gjirafa Bid Adapter : added meta.advertiserDomains to bidResponse
  modules/gjirafaBidAdapter.js
  test/spec/modules/gjirafaBidAdapter_spec.js
Labels: maintenance

#6820 sspBC Bid Adapter: add bidfloor to imp and other updates to bid adapter
  modules/sspBCBidAdapter.js
  modules/sspBCBidAdapter.md
Labels: maintenance, minor

#6760 User id module: force calls to getId if there was previously no consent data stored
  modules/userId/index.js
  test/spec/modules/userId_spec.js
Labels: bugfix, minor, needs 2nd review

#6800 Optimized AdUp Technology bid adapter: add support for native, adomain, and multibid
  modules/aduptechBidAdapter.js
  modules/aduptechBidAdapter.md
  test/spec/modules/aduptechBidAdapter_spec.js
Labels: maintenance, minor

#6864 QwarryBidAdapter: added schain
  modules/qwarryBidAdapter.js
  test/spec/modules/qwarryBidAdapter_spec.js
Labels: feature

#6857 PulsePoint Adapter: Fixing issues related to Prebid 5.0
  modules/pulsepointBidAdapter.js
  modules/pulsepointBidAdapter.md
  test/spec/modules/pulsepointBidAdapter_spec.js
Labels: maintenance

#6869 Bugfix: Extend Parrable Cookie Length in Testing
  test/spec/modules/parrableIdSystem_spec.js
Labels: bugfix

#6861 IX Bid Adapter: Adding support for GPT Pre-Auction Module
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance

#6819 Zeta Ssp Bid Adapter: support for eids
  modules/zetaSspBidAdapter.js
  test/spec/modules/zetaSspBidAdapter_spec.js
Labels: maintenance, minor

#6872 Adocean Bid Adapter: add meta.advertiserDomains to bid response
  modules/adoceanBidAdapter.js
  test/spec/modules/adoceanBidAdapter_spec.js
Labels: maintenance

#6862 No Bid Adapter: added bidResponse.meta and advertiserDomains
  modules/nobidBidAdapter.js
  test/spec/modules/nobidBidAdapter_spec.js
Labels: maintenance

#6875 CointrafficBidAdapter: add meta.advertiserDomains and meta.mediaType to bid response
  modules/cointrafficBidAdapter.js
  test/spec/modules/cointrafficBidAdapter_spec.js
Labels: maintenance

#6840 Single Adform adapter
  modules/adfBidAdapter.js
  modules/adformBidAdapter.js
  modules/adformBidAdapter.md
  test/spec/modules/adfBidAdapter_spec.js
  test/spec/modules/adformBidAdapter_spec.js
Labels: 5.0 API Change, maintenance

#6877 GMOSSP BidAdapter: add adomain support
  modules/gmosspBidAdapter.js
  test/spec/modules/gmosspBidAdapter_spec.js
Labels: maintenance

#6878 A4G Bid Adapter: add meta adomain
  modules/a4gBidAdapter.js
  test/spec/modules/a4gBidAdapter_spec.js
Labels: maintenance

#6879 Outbrain adapter: add pbjs version to bid request
  modules/outbrainBidAdapter.js
  test/spec/modules/outbrainBidAdapter_spec.js
Labels: maintenance

#6891 TrustX Bid Adapter: meta.advertiserDomains support
  modules/trustxBidAdapter.js
  test/spec/modules/trustxBidAdapter_spec.js
Labels: maintenance

#6886 Adkernel Bid Adapter: support for denakop alias
  modules/adkernelBidAdapter.js
Labels: maintenance

#6847 Digital Garage RTD module: new rtd submodule #6410
  modules/.submodules.json
  modules/dgkeywordRtdProvider.js
  modules/dgkeywordRtdProvider.md
  test/spec/modules/dgkeywordRtdProvider_spec.js
Labels: feature

#6883 Qwarry Bid Adapter: meta.advertiserDomains added
  modules/qwarryBidAdapter.js
  test/spec/modules/qwarryBidAdapter_spec.js
Labels: maintenance
