Repository prebid/Prebid.js, pull requests merged in 2021-07, with the labels that each got.

#7127 Admixer Bid Adapter: update bidder handler and read orb2
  modules/admixerBidAdapter.js
  test/spec/modules/admixerBidAdapter_spec.js
Labels: maintenance

#7073 Unruly Bid Adapter: consolidated adapter with RhythmOne
  modules/unrulyBidAdapter.js
  modules/unrulyBidAdapter.md
  test/spec/modules/unrulyBidAdapter_spec.js
Labels: LGTM, feature, minor

#7059 Prebid Core: add AD_RENDER_SUCCEEDED event
  src/AnalyticsAdapter.js
  src/constants.json
  src/prebid.js
  test/spec/AnalyticsAdapter_spec.js
Labels: feature

#7114 Logicad Bid Adapter: Add meta.advertiserDomains support
  modules/logicadBidAdapter.js
  test/spec/modules/logicadBidAdapter_spec.js
Labels: maintenance

#7129 smartx Bid Adapter: update renderer url and internal renderer behaviour
  modules/smartxBidAdapter.js
  test/spec/modules/smartxBidAdapter_spec.js
Labels: bugfix

#7135 Ogury Bid Adapter: fix hostname
  modules/oguryBidAdapter.js
  test/spec/modules/oguryBidAdapter_spec.js
Labels: bugfix

#7133 Emx Digital Bid Adapter: support for liveramp id and uid2.0
  modules/emx_digitalBidAdapter.js
  test/spec/modules/emx_digitalBidAdapter_spec.js
Labels: maintenance

#7081 RtbSape Bid Adapter: restore for Prebid 5.x
  modules/rtbsapeBidAdapter.js
  test/spec/modules/rtbsapeBidAdapter_spec.js
Labels: maintenance

#7138 Ogury Bid Adapter: Add new field 'ext' in bid response
  modules/oguryBidAdapter.js
  modules/oguryBidAdapter.md
  test/spec/modules/oguryBidAdapter_spec.js
Labels: maintenance

#7139 Ogury Bid Adapter: Update bid request content-type to 'application/json'
  modules/oguryBidAdapter.js
Labels: bugfix

#7047 Orbidder Bid Adapter: add native support
  modules/orbidderBidAdapter.js
  modules/orbidderBidAdapter.md
  test/spec/modules/orbidderBidAdapter_spec.js
Labels: LGTM, feature, minor

#7140 Adagio Bid Adapter: Fix unavailable localStorage error for legacy 4.43.x (#7128)
  modules/adagioBidAdapter.js
Labels: bugfix

#7130 TheMediaGrid Bid Adapter: fix keywords workflow
  modules/gridBidAdapter.js
  test/spec/modules/gridBidAdapter_spec.js
Labels: maintenance

#7142 Video Reach Bid Adapter: update to v5
  modules/videoreachBidAdapter.js
  test/spec/modules/videoreachBidAdapter_spec.js
Labels: maintenance

#7143 Upgrade Rise Bid Adapter: update to version 5.0
  modules/riseBidAdapter.js
  test/spec/modules/riseBidAdapter_spec.js
Labels: maintenance

#7093 Revcontent Bid Adapter: adjusted for Price Floors Module
  integrationExamples/gpt/revcontent_example_banner.html
  integrationExamples/gpt/revcontent_example_native.html
  modules/revcontentBidAdapter.js
  test/spec/modules/revcontentBidAdapter_spec.js
Labels: maintenance

#6860 Inject creativeComment after render so it actually persists
  src/prebid.js
Labels: bugfix, minor, needs 2nd review

#7058 Kubient Bid Adapter: add video support, issues fixes, and compliance with v5
  modules/kubientBidAdapter.js
  modules/kubientBidAdapter.md
  test/spec/modules/kubientBidAdapter_spec.js
Labels: LGTM, maintenance, minor

#7150 AdGeneration Bid Adapter: adding adomain and updates for ver5.x.
  modules/adgenerationBidAdapter.js
  test/spec/modules/adgenerationBidAdapter_spec.js
Labels: maintenance

#7154 Adnuntius Bid Adater: URL changes
  modules/adnuntiusBidAdapter.js
  test/spec/modules/adnuntiusBidAdapter_spec.js
Labels: maintenance

#7034 Zeta Ssp Bid Adapter: multiple bid reponses
  modules/zetaSspBidAdapter.js
  test/spec/modules/zetaSspBidAdapter_spec.js
Labels: maintenance, minor

#7148 BrightMountainMedia: add UserId support
  modules/brightMountainMediaBidAdapter.js
  test/spec/modules/brightMountainMediaBidAdapter_spec.js
Labels: maintenance

#7136 Proxistore Bid Adapter: support advertiserDomains
  modules/proxistoreBidAdapter.js
  test/spec/modules/proxistoreBidAdapter_spec.js
Labels: maintenance

#7100 Merkle userid module: storing session data and domain
  modules/merkleIdSystem.js
  modules/userId/userId.md
Labels: maintenance, minor, needs review

#7157 Sortable Bid Adapter: update to comply with Prebid 5.x
  modules/sortableBidAdapter.js
  test/spec/modules/sortableBidAdapter_spec.js
Labels: maintenance

#7126 GrowAdvertising: add native support
  modules/growadvertisingBidAdapter.js
  modules/growadvertisingBidAdapter.md
  test/spec/modules/growadvertisingBidAdapter_spec.js
Labels: feature

#7164 TheMediaGrid: added keywords formatting in the ad request
  modules/gridBidAdapter.js
  test/spec/modules/gridBidAdapter_spec.js
Labels: maintenance

#7115 Smartico Bid Adapter: add adomain for Prebid 5.0
  modules/smarticoBidAdapter.js
  test/spec/modules/smarticoBidAdapter_spec.js
Labels: maintenance

#7166 TheMediaGrid: added keywords formatting in the ad request (4.43.x-legacy)
  modules/gridBidAdapter.js
  test/spec/modules/gridBidAdapter_spec.js
Labels: maintenance

#7162 Aniview Bid Adapter: add support for BANNER
  modules/aniviewBidAdapter.js
  test/spec/modules/aniviewBidAdapter_spec.js
Labels: maintenance

#7163 Aniview Bid Adapter: add support for banner
  modules/aniviewBidAdapter.js
  test/spec/modules/aniviewBidAdapter_spec.js
Labels: maintenance

#7076 PBS adapter - fix logic for undefined endpoint URLs
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: bugfix, minor

#7170 Adagio Bid Adapter: fix native clicktrackers support
  modules/adagioBidAdapter.js
  test/spec/modules/adagioBidAdapter_spec.js
Labels: bugfix

#7044 ParrableIdSystem: cache request filter status in first-party cookie
  modules/parrableIdSystem.js
  test/spec/modules/parrableIdSystem_spec.js
Labels: maintenance, minor, needs review

#7168 Innity Bid Adapter: support adomains for Prebid 5.0
  modules/innityBidAdapter.js
  test/spec/modules/innityBidAdapter_spec.js
Labels: maintenance

#7134 GMOSSP Bid Adapter: add IM uid support
  modules/gmosspBidAdapter.js
  test/spec/modules/gmosspBidAdapter_spec.js
Labels: maintenance

#7153 PubMatic Analytics Adapter: added support for Bidder alias
  modules/pubmaticAnalyticsAdapter.js
  test/spec/modules/pubmaticAnalyticsAdapter_spec.js
Labels: LGTM, maintenance, minor

#7141 ID5 Analytics: redaction process skips 'ext' on ID5 ID
  modules/id5AnalyticsAdapter.js
  test/spec/modules/id5AnalyticsAdapter_spec.js
Labels: maintenance

#7099 sharedIdSystem: return pubcid instead of sharedId
  modules/sharedIdSystem.js
  test/spec/modules/sharedIdSystem_spec.js
Labels: bugfix

#7172 Optimera RTD : check for new data on auction init
  modules/optimeraRtdProvider.js
  test/spec/modules/optimeraRtdProvider_spec.js
Labels: bugfix

#7158 Openx Analytics Adapter: optimize config, endpoint override, & send late impression
  modules/openxAnalyticsAdapter.js
  test/spec/modules/openxAnalyticsAdapter_spec.js
Labels: maintenance

#6948 AdtelligentIdSystem : add new ID submodule
  modules/adtelligentBidAdapter.js
  modules/adtelligentIdSystem.js
  modules/adtelligentIdSystem.md
  modules/userId/eids.js
  test/spec/modules/adtelligentIdSystem_spec.js
Labels: feature

#7111 Iqm Bid Adapter: add new bid adapter
  modules/iqmBidAdapter.js
  modules/iqmBidAdapter.md
  test/spec/modules/iqmBidAdapter_spec.js
Labels: feature

#7165 MicroAd Bid Adapter: Support Liveramp
  modules/microadBidAdapter.js
  test/spec/microadBidAdapter_spec.js
Labels: maintenance

#7176 akamaiDAP Id System : moving {domain} parameter from the JSON body to the URL path
  modules/akamaiDAPIdSystem.js
Labels: bugfix

#7105 UserID: bugfix for refreshUserIds with updated info
  modules/userId/index.js
  test/spec/modules/userId_spec.js
Labels: bugfix

#7169 showheroes-bs Bid Adapter: Add support for advertiserDomains
  modules/showheroes-bsBidAdapter.js
  test/spec/modules/showheroes-bsBidAdapter_spec.js
Labels: maintenance

#7107 QuantcastId : Add support for firing pixel in quantcastIdSystem submodule
  modules/quantcastIdSystem.js
  modules/quantcastIdSystem.md
  modules/userId/userId.md
  test/spec/modules/quantcastIdSystem_spec.js
Labels: LGTM, feature

#7171 oneTag Bid Adapter: interpretResponse video enhancements
  modules/onetagBidAdapter.js
  test/spec/modules/onetagBidAdapter_spec.js
Labels: maintenance

#7174 amxIdSystem: update endpoint and internal timeout
  modules/amxIdSystem.js
Labels: maintenance

#7179 TheMediaGrid: added ext.bidder.grid.demandSource processing
  modules/gridBidAdapter.js
  test/spec/modules/gridBidAdapter_spec.js
Labels: maintenance

#7180 Rubicon Analytics: pass along userId providers
  modules/rubiconAnalyticsAdapter.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
Labels: maintenance, needs 2nd review

#7175 Openweb Bid Adapter: add new bid adapter
  modules/openwebBidAdapter.js
  modules/openwebBidAdapter.md
  test/spec/modules/openwebBidAdapter_spec.js
Labels: feature

#7187 Deep Intent Bid Adapter: backward compatible eids added
  modules/deepintentBidAdapter.js
Labels: bugfix

#7184 MediaGrid Adapter: Put demandSource in bid.meta
  modules/gridBidAdapter.js
  test/spec/modules/gridBidAdapter_spec.js
Labels: maintenance, minor

#7152 Opera Ads Bid Adapter: add new bid adapter
  modules/operaadsBidAdapter.js
  modules/operaadsBidAdapter.md
  test/spec/modules/operaadsBidAdapter_spec.js
Labels: feature

#7173 Mantis Bid Adapter: compliant with Prebid v5.0
  modules/mantisBidAdapter.js
  test/spec/modules/mantisBidAdapter_spec.js
Labels: maintenance

#7196 PBJS Core: Leverage defined methods from utils in secureCreatives
  src/secureCreatives.js
  src/utils.js
Labels: bugfix

#7167 Sublime Bid Adapter : send notid in pixel & use timeout from timeoutData
  modules/sublimeBidAdapter.js
  test/spec/modules/sublimeBidAdapter_spec.js
Labels: maintenance

#7190 Aja Bid Adapter: add adomain and adapter in v5
  modules/ajaBidAdapter.js
  test/spec/modules/ajaBidAdapter_spec.js
Labels: maintenance

#7191 Adhese Bid Adapter: add adomain and adapter to 5.0
  modules/adheseBidAdapter.js
  test/spec/modules/adheseBidAdapter_spec.js
Labels: maintenance

#7192 EngageBDR Bid Adapter: add adomain and adapter to prebid 5
  modules/ebdrBidAdapter.js
  test/spec/modules/ebdrBidAdapter_spec.js
Labels: maintenance

#7193 Clickforce Bid Adapter: add adomain and adapter to prebid 5
  modules/clickforceBidAdapter.js
  test/spec/modules/clickforceBidAdapter_spec.js
Labels: maintenance

#7197 GetIntent bid adapter: update to v5 requirements
  modules/getintentBidAdapter.js
  test/spec/modules/getintentBidAdapter_spec.js
Labels: maintenance

#7149 SharedIdSystem: return pubcid instead of sharedId
  modules/sharedIdSystem.js
  test/spec/modules/sharedIdSystem_spec.js
Labels: bugfix

#7177 Nobid Bid Adapter: add support for alias duration
  modules/nobidBidAdapter.js
  test/spec/modules/nobidBidAdapter_spec.js
Labels: maintenance

#7201 Nativo Bid Adapter: Identify refreshed inventory to bidder endpoint
  modules/nativoBidAdapter.js
  test/spec/modules/nativoBidAdapter_spec.js
Labels: maintenance, minor

#7199 DSPX Adapter: Fix userSync problem with passback responses
  modules/dspxBidAdapter.js
  test/spec/modules/dspxBidAdapter_spec.js
Labels: bugfix

#7200 Rads Adapter: Fix userSync problem with passback responses
  modules/radsBidAdapter.js
  test/spec/modules/radsBidAdapter_spec.js
Labels: bugfix

#7182 Realvu Analytics Adapter: improve flagging of 'display:none' containers
  modules/realvuAnalyticsAdapter.js
Labels: maintenance

#7181 tappx Bid Adapter: add internal Tappx params and refactor pageUrl
  modules/tappxBidAdapter.js
  modules/tappxBidAdapter.md
Labels: maintenance

#7205 Criteo Bid Adapter: fix creativeId with correct value
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: bugfix

#7206 Sonobi bid adapter: add support for floor module
  modules/sonobiBidAdapter.js
  test/spec/modules/sonobiBidAdapter_spec.js
Labels: maintenance

#7038 PBS Bid Adapter: outstream video renderer bugfix
  modules/prebidServerBidAdapter/index.js
Labels: bugfix, video

#7207 oguryBidAdapter: handle cookie syncing on prebid.js
  modules/oguryBidAdapter.js
  test/spec/modules/oguryBidAdapter_spec.js
Labels: maintenance

#7208 PBS bid adapter: revised outstream unit test for 7038
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: maintenance

#7198 AdYouLike bidder adapter: handle size given in bid params
  modules/adyoulikeBidAdapter.js
  test/spec/modules/adyoulikeBidAdapter_spec.js
Labels: maintenance

#7188 Smaato: Support Floor Price Module
  modules/smaatoBidAdapter.js
  test/spec/modules/smaatoBidAdapter_spec.js
Labels: LGTM, maintenance

#7161 PBjs Core Ajax: if xfr.open() explodes it lets the caller know
  src/ajax.js
Labels: bugfix

#7194 DeepIntent Bid Adapter: eid fix
  modules/deepintentBidAdapter.js
Labels: bugfix

#7204 Halo ID url params, RTD dupe protection, doc update
  modules/haloIdSystem.js
  modules/haloIdSystem.md
  modules/haloRtdProvider.js
  modules/haloRtdProvider.md
  test/spec/modules/haloIdSystem_spec.js
  test/spec/modules/haloRtdProvider_spec.js
Labels: bugfix, taxonomy

#7227 Adyoulike bidder - Video playerSize format
  modules/adyoulikeBidAdapter.js
Labels: maintenance

#7001 Permutive RTD submodule: TrustX update
  integrationExamples/gpt/permutiveRtdProvider_example.html
  modules/permutiveRtdProvider.js
  modules/permutiveRtdProvider.md
  test/spec/modules/permutiveRtdProvider_spec.js
Labels: maintenance, taxonomy

#7225 Beachfront Bid Adapter: add Halo ID support
  modules/beachfrontBidAdapter.js
  test/spec/modules/beachfrontBidAdapter_spec.js
Labels: feature

#7212 Bizzclick Bid Adapter: update bid adapter for prebid 5
  modules/bizzclickBidAdapter.js
  test/spec/modules/bizzclickBidAdapter_spec.js
Labels: maintenance, minor, not receiving bids

#7229 AdYouLike Bidder - enable Vast response format
  modules/adyoulikeBidAdapter.js
  test/spec/modules/adyoulikeBidAdapter_spec.js
Labels: maintenance

#7233 VIS.X Bid Adapter: fix handling of bid response
  modules/visxBidAdapter.js
  test/spec/modules/visxBidAdapter_spec.js
Labels: bugfix

#7215 AJA Bid Adapter: Supports advertiserDomains response
  modules/ajaBidAdapter.js
  test/spec/modules/ajaBidAdapter_spec.js
Labels: maintenance

#7220 PrebidServer Bid Adapter: add appnexuspsp to S2S Vendors
  modules/prebidServerBidAdapter/config.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: feature

#7234 SmileWanted Adapter: Adding the "positionType" parameter
  modules/smilewantedBidAdapter.js
  test/spec/modules/smilewantedBidAdapter_spec.js
Labels: maintenance

#7235 Pubmatic Analytics Adapter: extend timeout on flaky tests
  test/spec/modules/pubmaticAnalyticsAdapter_spec.js
Labels: maintenance

#7236 Apacdex Bid Adapter: add placementId param and optimize payload data
  modules/apacdexBidAdapter.js
  test/spec/modules/apacdexBidAdapter_spec.js
Labels: maintenance

#7241 Unicorn BidAdapter: add support for meta.advertiserDomain for Prebid 5
  modules/unicornBidAdapter.js
  modules/unicornBidAdapter.md
  test/spec/modules/unicornBidAdapter_spec.js
Labels: maintenance
