Repository prebid/Prebid.js, pull requests merged in 2021-12, with the labels that each got.

#7773 PubCommonID module: use topmost domain for cookie storage
  modules/sharedIdSystem.js
  test/spec/modules/sharedIdSystem_spec.js
Labels: feature

#7750 adxcgBidAdapter: updated backend protocol
  modules/adxcgBidAdapter.js
  modules/adxcgBidAdapter.md
  test/spec/modules/adxcgBidAdapter_spec.js
Labels: maintenance

#7768 Adnuntius Bid Adapter: no cookie feature.
  modules/adnuntiusBidAdapter.js
  test/spec/modules/adnuntiusBidAdapter_spec.js
Labels: maintenance

#7782 AdDefend Bidder: added gdprApplies to bid request parameters
  modules/addefendBidAdapter.js
Labels: bugfix

#7785 Rubicon Bid Adapter: pass along gdprApplies
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: bugfix

#7788 Rich Audience: update for 'adapters that may not handle GDPR'
  modules/richaudienceBidAdapter.js
  test/spec/modules/richaudienceBidAdapter_spec.js
Labels: maintenance

#7722 PBS Bid Adapter: do not pass aspectratios in ORTB2 ext data if native image definition doesn't have ratio_height/ratio_width
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: bugfix

#7754 NextMillennium Bid Adapter: refresh_count for adUnitCode is added
  modules/nextMillenniumBidAdapter.js
  test/spec/modules/nextMillenniumBidAdapter_spec.js
Labels: maintenance

#7783 Glimpse Bid Adapter: handle consent case where GDPR doesn't apply
  modules/glimpseBidAdapter.js
Labels: maintenance

#7758 Colossus SSP Bidder Adapter: add onBidWon()
  modules/colossussspBidAdapter.js
  test/spec/modules/colossussspBidAdapter_spec.js
Labels: maintenance

#7729 RTD Module: add 'onBidRequest' event handler for RTD submodules
  modules/rtdModule/index.js
  test/spec/modules/realTimeDataModule_spec.js
Labels: feature

#7789 5.20.x legacy appnexus bid adapter - add support for brandId
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: feature, needs review, legacy

#7732 CircleCi config: change to npm ci in unit testing workflow
  .circleci/config.yml
Labels: build process, maintenance

#7748 Kinesso ID: fix endpoint query param
  modules/kinessoIdSystem.js
Labels: legacy, bugfix

#7778 Build system: improve build for development workflow
  gulpfile.js
  karma.conf.maker.js
  test/helpers/prebidGlobal.js
  test/test_deps.js
  test/test_index.js
Labels: feature

#7794 Rubicon Bid Adapter: Pass along GPID + Minor refactoring
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: maintenance

#7723 Pubx.ai Analytics Adapter: added additional fields to the Auction object
  modules/pubxaiAnalyticsAdapter.js
  test/spec/modules/pubxaiAnalyticsAdapter_spec.js
Labels: maintenance

#7807 Aniview Bid Adapter: add a new alias
  modules/aniviewBidAdapter.js
Labels: maintenance

#7812 TheMediaGrid, TrustX: fix sync url workflow
  modules/gridBidAdapter.js
  modules/trustxBidAdapter.js
Labels: bugfix

#7617 Adomik Analytics Adapter: add key value pair
  modules/adomikAnalyticsAdapter.js
  test/spec/modules/adomikAnalyticsAdapter_spec.js
Labels: maintenance

#7817 NextMillennium Bid Adapter: fix an error when gdpr is undefined
  modules/nextMillenniumBidAdapter.js
  test/spec/modules/nextMillenniumBidAdapter_spec.js
Labels: bugfix

#7800 Multiple Modules: fix constants JSON imports for webpack
  modules/adlooxAdServerVideo.js
  modules/adlooxAnalyticsAdapter.js
  modules/bidViewability.js
  modules/bidViewabilityIO.js
  modules/currency.js
  modules/instreamTracking.js
  modules/ixBidAdapter.js
  modules/telariaBidAdapter.js
  test/spec/modules/adlooxAnalyticsAdapter_spec.js
  test/spec/modules/bidViewabilityIO_spec.js
  test/spec/modules/bidViewability_spec.js
Labels: build process, maintenance

#7802 LiveWrapped Bid Adapter: support for FPD (and ortb2 config)
  modules/livewrappedBidAdapter.js
  test/spec/modules/livewrappedBidAdapter_spec.js
Labels: maintenance

#7797 Invibes Bid Adapter: support for custom domainId
  modules/invibesBidAdapter.js
  modules/invibesBidAdapter.md
  test/spec/modules/invibesBidAdapter_spec.js
Labels: maintenance

#7819 Eplanning & Adapter Manager: backport test changes to 5.20.x-legacy
  test/spec/modules/eplanningBidAdapter_spec.js
  test/spec/unit/core/adapterManager_spec.js
Labels: bugfix

#7786 adxcgBidAdapter: updated backend protocol for 5.2x-legacy
  modules/adxcgBidAdapter.js
  test/spec/modules/adxcgBidAdapter_spec.js
Labels: legacy, maintenance

#7829 Revert "adxcgBidAdapter: updated backend protocol for 5.2x-legacy"
  modules/adxcgBidAdapter.js
  test/spec/modules/adxcgBidAdapter_spec.js
Labels: maintenance

#7828 Engageya Bid Adapter: support for new size
  modules/engageyaBidAdapter.js
Labels: maintenance

#7814 FeedAd Bid Adapter: add pass through of additional bid parameters
  modules/feedadBidAdapter.js
  modules/feedadBidAdapter.md
  test/spec/modules/feedadBidAdapter_spec.js
Labels: maintenance

#7805 IX Bid Adapter: fix for infinite loop
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: bugfix

#7755 Daily Hunt Bid Adapter: update prebid compliance and add adapter back
  modules/dailyhuntBidAdapter.js
  modules/dailyhuntBidAdapter.md
  test/spec/modules/dailyhuntBidAdapter_spec.js
Labels: maintenance

#7752 iprom Bid Adapter: restore adapter in prebid 5.20.x legacy
  modules/ipromBidAdapter.js
  test/spec/modules/ipromBidAdapter_spec.js
Labels: legacy, maintenance

#7736 Prebid Core: after auction is held, if more bids are matched by adUnitCode next apply filter for bidId
  src/auction.js
Labels: bugfix

#7684 Adkernel Bid Adapter: FPD module support
  modules/adkernelBidAdapter.js
Labels: feature, needs review

#7835 pubGENIUS bid adapter: update url
  modules/pubgeniusBidAdapter.js
  test/spec/modules/pubgeniusBidAdapter_spec.js
Labels: maintenance

#7825 Prebid Core: typo fix
  src/auction.js
Labels: maintenance

#7798 Compass Adapter: add new adapter
  modules/compassBidAdapter.js
  modules/compassBidAdapter.md
  test/spec/modules/compassBidAdapter_spec.js
Labels: feature

#7784 GPT Pre Auction: New logic options - customPreAuction & useDefaultPreAuction
  modules/gptPreAuction.js
  test/spec/modules/gptPreAuction_spec.js
Labels: feature, needs 2nd review

#7836 Bliink Bid Adapter: update bidderFactory import path
  modules/bliinkBidAdapter.js
Labels: bugfix

#7815 Doceree bid adaptor: New GDPR related parameters
  modules/docereeBidAdapter.js
  modules/docereeBidAdapter.md
  test/spec/modules/docereeBidAdapter_spec.js
Labels: maintenance

#7769 Prebid Core: Consent management allow auction to continue when CMP doesn't respond
  modules/consentManagement.js
  test/spec/modules/consentManagement_spec.js
Labels: bugfix

#7761 Loglylift Bid Adapter: add new bid adapter
  modules/loglyliftBidAdapter.js
  modules/loglyliftBidAdapter.md
  test/spec/modules/loglyliftBidAdapter_spec.js
Labels: feature

#7838 IX Bid Adapter: update GPID Support
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance

#7858 Limelight Bid Adapter: add field user id as eids to payload
  modules/limelightDigitalBidAdapter.js
  test/spec/modules/limelightDigitalBidAdapter_spec.js
Labels: maintenance

#7854 Livewrapped Analytics adapter: Pass runner-up bid from livewrapped wrapper
  modules/livewrappedAnalyticsAdapter.js
  test/spec/modules/livewrappedAnalyticsAdapter_spec.js
Labels: maintenance

#7822 Optimera RTD: fix targeting and auction init issues (4.43.x-legacy)
  modules/optimeraRtdProvider.js
  test/spec/modules/optimeraRtdProvider_spec.js
Labels: bugfix

#7790 ZetaGlobal SSP Analytics Adapter: add new analytics adapter
  modules/zeta_global_sspAnalyticsAdapter.js
  modules/zeta_global_sspAnalyticsAdapter.md
  test/spec/modules/zeta_global_sspAnalyticsAdapter_spec.js
Labels: feature, needs docs

#7850 OptimeraRTD Module: Expose non-ad related data to the page. (#7849)
  modules/optimeraRtdProvider.js
  test/spec/modules/optimeraRtdProvider_spec.js
Labels: maintenance

#7818 IX Bid Adapter: make sure siteId is string type
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance

#7809 IX Bid Adapter: Add support for ID5, Lotame Panorama ID, Epsilon Publisher Link, Audigent Halo ID, SharedID
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance

#7844 adxcgBidAdapter: updated backend protocol for 5.2 legacy
  modules/adxcgBidAdapter.js
  test/spec/modules/adxcgBidAdapter_spec.js
Labels: maintenance

#7396 Prebid Core: mergeConfig and mergeBidderConfig functions
  src/config.js
  src/prebid.js
  src/utils.js
  test/spec/config_spec.js
Labels: feature, taxonomy

#7863 Adyoulike bidder: improve robustness to multiple mediatypes
  modules/adyoulikeBidAdapter.js
  test/spec/modules/adyoulikeBidAdapter_spec.js
Labels: bugfix

#7856 Ozone Bid Adapter: Support schain module
  modules/ozoneBidAdapter.js
  test/spec/modules/ozoneBidAdapter_spec.js
Labels: maintenance

#7869 Logly Lift Bid Adapter_spec: Fix test
  test/spec/modules/loglyliftBidAdapter_spec.js
Labels: bugfix

#7860 Bliink Bid Adapter: Add support gdprApplies when consent string does not exist
  modules/bliinkBidAdapter.js
  test/spec/modules/bliinkBidAdapter_spec.js
Labels: bugfix

#7876 Onetag Bid Adapter: update gdprApplies to always be passed
  modules/onetagBidAdapter.js
Labels: bugfix

#7772 id Import Library: update with more params to capture email
  modules/idImportLibrary.js
  modules/idImportLibrary.md
  test/spec/modules/idImportLibrary_spec.js
Labels: feature

#7846 Adomik Analytics Adapter: update sampling
  modules/adomikAnalyticsAdapter.js
  test/spec/modules/adomikAnalyticsAdapter_spec.js
Labels: maintenance

#7882 showheroes-bs Bid Adapter: refactoring + fix test
  modules/showheroes-bsBidAdapter.js
  test/spec/modules/showheroes-bsBidAdapter_spec.js
Labels: bugfix

#7852 Adquery ID System: add new ID module
  modules/.submodules.json
  modules/adqueryIdSystem.js
  modules/adqueryIdSystem.md
  modules/userId/eids.js
  modules/userId/userId.md
  test/spec/modules/adqueryIdSystem_spec.js
  test/spec/modules/eids_spec.js
  test/spec/modules/userId_spec.js
Labels: feature

#7891 Ogury Bid Adapter: adding prebid.js and ogury adapter versions
  modules/oguryBidAdapter.js
  test/spec/modules/oguryBidAdapter_spec.js
Labels: maintenance

#7879 RTB House Bid Adapter: add channel as an optional param
  modules/rtbhouseBidAdapter.js
  test/spec/modules/rtbhouseBidAdapter_spec.js
Labels: maintenance

#7892 Proxistore Bid Adapter: delete console log
  modules/proxistoreBidAdapter.js
Labels: maintenance

#7893 Richaudience Bid Adapter: add schain to endpoint payload
  modules/richaudienceBidAdapter.js
  test/spec/modules/richaudienceBidAdapter_spec.js
Labels: maintenance

#7888 PubMatic Analytics Adapter: add logging for "advertiser domain"
  modules/pubmaticAnalyticsAdapter.js
  test/spec/modules/pubmaticAnalyticsAdapter_spec.js
Labels: maintenance

#7896 Criteo Id Module: ensure that cookies are written only on TLD+1 domain
  modules/criteoIdSystem.js
  test/spec/modules/criteoIdSystem_spec.js
Labels: bugfix

#7894 adkernel Bid Adapter : add alias
  modules/adkernelBidAdapter.js
Labels: maintenance

#7898 Rise Bid Adapter: pass hp in supply schain
  modules/riseBidAdapter.js
  test/spec/modules/riseBidAdapter_spec.js
Labels: bugfix
