Repository prebid/Prebid.js, pull requests merged in 2021-03, with the labels that each got.

#6363 TheMediaGrid Bid Adapter: fix trouble with alias using
  modules/gridBidAdapter.js
  test/spec/modules/gridBidAdapter_spec.js
Labels: bugfix, minor

#6356 Rubicon Analytics Adapter: pass along advertiserDomains
  modules/rubiconAnalyticsAdapter.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
Labels: maintenance, minor

#6330 PBS Bid Adapter: cooperative sync flag
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: LGTM, feature, minor

#6373 TrustX Bid Adapter: Fix alias error
  modules/trustxBidAdapter.js
  test/spec/modules/trustxBidAdapter_spec.js
Labels: bugfix, minor

#6376 Adform Bid Adapter: add global targeting to the request query as parameter
  modules/adformBidAdapter.js
  test/spec/modules/adformBidAdapter_spec.js
Labels: maintenance, minor

#6355 Gamoshi Bid Adapter: update adaptor aliases
  modules/gamoshiBidAdapter.js
Labels: maintenance, minor

#6337 Marsmedia Bid Adapter: add support for viewability, floor price module, COPPA & CCPA
  modules/marsmediaBidAdapter.js
  test/spec/modules/marsmediaBidAdapter_spec.js
Labels: maintenance, minor

#6359 PBJS Core: fix bidderRequest matching for finding a renderer
  src/auction.js
Labels: maintenance, minor

#6369 Seedtag Bid Adapter: add support for a new type of placement
  modules/seedtagBidAdapter.js
  test/spec/modules/seedtagBidAdapter_spec.js
Labels: LGTM, maintenance, minor

#6384 Adyoulike Bid Adapter: added conditional statement to native events
  modules/adyoulikeBidAdapter.js
Labels: maintenance, minor

#6382 oneVideo Bid Adapter: remove adapter adId because of conflict with pbjs core
  modules/oneVideoBidAdapter.js
  test/spec/modules/oneVideoBidAdapter_spec.js
Labels: LGTM, bugfix, minor

#6383 PBS Bid Adapter: add dchain (demand chain object) to prebid server adapter
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: feature, minor

#6331 Gulp Build: fix to populate modules list when gulp bundle is executed
  gulpfile.js
Labels: bugfix, minor, needs 2nd review

#6370 Smartx Bid Adapter: updated out-stream render to support smartPlay 5.2
  modules/smartxBidAdapter.js
  modules/smartxBidAdapter.md
  test/spec/modules/smartxBidAdapter_spec.js
Labels: maintenance, minor, needs review

#6293 Fpd 2.0 Update
  modules/admixerBidAdapter.js
  modules/adrelevantisBidAdapter.js
  modules/amxBidAdapter.js
  modules/avocetBidAdapter.js
  modules/criteoBidAdapter.js
  modules/gptPreAuction.js
  modules/gridBidAdapter.js
  modules/inmarBidAdapter.js
  modules/jwplayerRtdProvider.js
  modules/luponmediaBidAdapter.js
  modules/prebidServerBidAdapter/index.js
  modules/rubiconBidAdapter.js
  modules/smaatoBidAdapter.js
  modules/tripleliftBidAdapter.js
  src/adapterManager.js
  src/config.js
  src/prebid.js
  test/spec/adUnits_spec.js
  test/spec/config_spec.js
  test/spec/modules/adrelevantisBidAdapter_spec.js
  test/spec/modules/amxBidAdapter_spec.js
  test/spec/modules/criteoBidAdapter_spec.js
  test/spec/modules/gptPreAuction_spec.js
  test/spec/modules/gridBidAdapter_spec.js
  test/spec/modules/jwplayerRtdProvider_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/rubiconBidAdapter_spec.js
  test/spec/modules/smaatoBidAdapter_spec.js
  test/spec/modules/tripleliftBidAdapter_spec.js
Labels: feature, minor

#6379 PBS Bid Adapter: fix s2s alias collision with built-in adapter aliasing
  modules/prebidServerBidAdapter/index.js
Labels: bugfix, minor, needs review

#6323 PBJS Core: clean side-effect when checking that local storage is enabled
  src/storageManager.js
  test/spec/unit/core/storageManager_spec.js
Labels: LGTM, bugfix, minor, needs 2nd review

#6302 Jwplayer doc changes for FPD update
  integrationExamples/gpt/jwplayerRtdProvider_example.html
  modules/jwplayerRtdProvider.md
Labels: LGTM, maintenance, minor

#6368 Adagio Bid Adapter: add Native support
  modules/adagioBidAdapter.js
  modules/adagioBidAdapter.md
  test/spec/modules/adagioBidAdapter_spec.js
Labels: maintenance, minor, needs review

#6394 Connectad Bid Adapter: EIDS support update
  modules/connectadBidAdapter.js
Labels: maintenance, minor

#6371 TheMediaGridNM Bid Adapter: fix trouble with alias
  modules/gridNMBidAdapter.js
  test/spec/modules/gridNMBidAdapter_spec.js
Labels: bugfix, minor

#6400 Rubicon Analytics: Pass along source agnostic gam ids
  modules/rubiconAnalyticsAdapter.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
Labels: maintenance, minor

#6393 Permutive RTD Module: add support for TrustX
  integrationExamples/gpt/permutiveRtdProvider_example.html
  modules/permutiveRtdProvider.js
  modules/permutiveRtdProvider.md
  test/spec/modules/permutiveRtdProvider_spec.js
Labels: LGTM, maintenance, minor

#6365 SmartRTB Bid Adapter: add alias and update valid opts
  modules/smartrtbBidAdapter.js
  test/spec/modules/smartrtbBidAdapter_spec.js
Labels: maintenance, minor

#6364 Sonobi Bid Adapter: send eids in bid request.
  modules/sonobiBidAdapter.js
  test/spec/modules/sonobiBidAdapter_spec.js
Labels: LGTM, maintenance, minor

#6378 Apacdex Bid Adapter: userId module support, show demo ads in debug mode & other maintenance
  modules/apacdexBidAdapter.js
  test/spec/modules/apacdexBidAdapter_spec.js
Labels: maintenance, minor, needs review

#6350 Novatiq ID System: add snowflake userId submodule
  modules/.submodules.json
  modules/novatiqIdSystem.js
  modules/novatiqIdSystem.md
  modules/userId/eids.js
  modules/userId/eids.md
  modules/userId/userId.md
  test/spec/modules/novatiqIdSystem_spec.js
Labels: feature, minor

#6408 IronSource Bid Adapter: add session_id & is_wrapper params to adapter
  modules/ironsourceBidAdapter.js
  test/spec/modules/ironsourceBidAdapter_spec.js
Labels: maintenance, minor

#6403 AMX Bid Adapter: add or update general adapter support and code refactoring
  modules/amxBidAdapter.js
  test/spec/modules/amxBidAdapter_spec.js
Labels: LGTM, maintenance, minor

#6158 Criteo: versioned Fastbid wrapper
  modules/criteoBidAdapter.js
  modules/criteoBidAdapter.md
  test/spec/modules/criteoBidAdapter_spec.js
Labels: LGTM, Prebid 5.0

#6416 VOX & Hybrid Bid Adapters: fix global var name to avoid conflicts
  modules/hybridBidAdapter.js
  modules/voxBidAdapter.js
Labels: maintenance, minor

#6418 LiveIntent Id System: fix for parsing response twice
  modules/liveIntentIdSystem.js
  test/spec/modules/liveIntentIdSystem_spec.js
Labels: bugfix, minor

#6419 PBJS Core: use mediaType renderer when backupOnly and no bid.renderer
  src/auction.js
Labels: bugfix, minor

#6391 GumGum Bid Adapter: pass bidfloor currency in bidrequest
  modules/gumgumBidAdapter.js
  test/spec/modules/gumgumBidAdapter_spec.js
Labels: maintenance, minor

#6421 Documentation: fixed a typo and sentence structure for Geoedge markdown
  modules/geoedgeRtdProvider.md
Labels: maintenance, minor

#6413 Spotx Bid Adapter: add publisher support for cache.ignoreBidderCacheKey
  modules/spotxBidAdapter.js
  test/spec/modules/spotxBidAdapter_spec.js
Labels: maintenance, minor, needs update

#6405 BizzClick Bid Adapter: add at, ccpa, gdpr and coppa support
  modules/bizzclickBidAdapter.js
  test/spec/modules/bizzclickBidAdapter_spec.js
Labels: maintenance, minor

#6412 Qwarry Bid Adapter: add referer detection
  modules/qwarryBidAdapter.js
  test/spec/modules/qwarryBidAdapter_spec.js
Labels: maintenance, minor

#6402 Smartyads Bid Adapter: add coppa field from config
  modules/smartyadsBidAdapter.js
  test/spec/modules/smartyadsBidAdapter_spec.js
Labels: maintenance, minor

#6428 PBS Bid Adapter: Fpd2.0 bug fix for first party data issue
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: bugfix, minor

#6409 a4g Bid Adapter: delete adid and use crid if it exists
  modules/a4gBidAdapter.js
  test/spec/modules/a4gBidAdapter_spec.js
Labels: maintenance, minor

#5921 Mediawallah ID System: add openlink userId submodule
  modules/.submodules.json
  modules/mwOpenLinkIdSystem.js
  modules/mwOpenLinkIdSystem.md
  modules/userId/eids.js
  modules/userId/eids.md
  modules/userId/userId.md
  test/spec/modules/mwOpenLinkIdSystem_spec.js
  test/spec/modules/userId_spec.js
Labels: feature, minor, needs update

#6438 Documentation: Adjust desired bitrate examples smartx adapter
  modules/smartxBidAdapter.md
Labels: maintenance, minor

#6441 ImprovedDigital Bid Adapter: remove adId and minor version update
  modules/improvedigitalBidAdapter.js
  test/spec/modules/improvedigitalBidAdapter_spec.js
Labels: maintenance, minor

#6434 Integration Example: ID import library example
  integrationExamples/gpt/idImportLibrary_example.html
Labels: maintenance, minor

#6332 Mass Module: add module to support MASS protocol
  integrationExamples/mass/index.html
  modules/mass.js
  modules/mass.md
  test/spec/modules/mass_spec.js
Labels: feature, minor

#6439 Axonix bid adapter: set both connectiontype & effectivetype in the request
  modules/axonixBidAdapter.js
  test/spec/modules/axonixBidAdapter_spec.js
Labels: bugfix, minor

#6442 Sublime Bid Adapter: v0.7.1 & add extra information in tracking pixels
  modules/sublimeBidAdapter.js
  test/spec/modules/sublimeBidAdapter_spec.js
Labels: maintenance, minor

#6399 Interactive Offers Bid Adapter: add new bid adapter
  modules/interactiveOffersBidAdapter.js
  modules/interactiveOffersBidAdapter.md
  test/spec/modules/interactiveOffersBidAdapter_spec.js
Labels: feature, minor, needs review

#6401 AdYouLike Bid Adapter: replace shorthand "image" native config
  modules/adyoulikeBidAdapter.js
  test/spec/modules/adyoulikeBidAdapter_spec.js
Labels: maintenance, minor

#6435 AMX Bid Adapter: video bugfix to set mediaType on bid instead of meta object
  modules/amxBidAdapter.js
  test/spec/modules/amxBidAdapter_spec.js
Labels: bugfix, minor, needs review

#6445 LiveWrapper Bid Adapter: use userIdAsEids to handle all user ids
  modules/livewrappedBidAdapter.js
  test/spec/modules/livewrappedBidAdapter_spec.js
Labels: maintenance, minor

#6420 Invibes Bid Adapter: read legitimate interests & add userIds support for pubcommonId / pubProvidedId
  modules/invibesBidAdapter.js
  test/spec/modules/invibesBidAdapter_spec.js
Labels: maintenance, minor

#6338 AdTrue Bid Adapter: getUserSyncs logic update
  modules/adtrueBidAdapter.js
  test/spec/modules/adtrueBidAdapter_spec.js
Labels: maintenance, minor

#6390 IX Bid Adapter: add priceFloors support and an integration example
  integrationExamples/gpt/adUnitFloors.html
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance, minor

#6429 PBS adapter: remove condition on gdpr consentstring which isnt required by the tcf2 spec when gdprapplies is false
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: maintenance, minor, needs 2nd review

#6467 UserId Module: trim stored value prior to checking if the first character indicates it's json
  modules/userId/index.js
Labels: maintenance, minor

#6447 Kargo Bid Adapter: add gdpr support
  modules/kargoBidAdapter.js
  test/spec/modules/kargoBidAdapter_spec.js
Labels: maintenance, minor, needs review

#6426 Bid Glass Adapter: Merge externally set targeting params
  modules/bidglassBidAdapter.js
Labels: maintenance, minor, needs review

#6333 Optimon Analytics Adapter: add new analytics adapter
  modules/optimonAnalyticsAdapter.js
  modules/optimonAnalyticsAdapter.md
  test/spec/modules/optimonAnalyticsAdapter_spec.js
Labels: feature, minor

#6443 UID 2.0 Userid submodule
  integrationExamples/gpt/userId_example.html
  modules/uid2IdSystem.js
  modules/uid2IdSystem.md
  modules/userId/eids.js
  modules/userId/eids.md
  modules/userId/userId.md
  test/spec/modules/eids_spec.js
  test/spec/modules/userId_spec.js
Labels: feature, minor, needs 2nd review, needs docs

#6436 H12media Bid Adapter: added new optional params, fixes, and various integration support
  modules/h12mediaBidAdapter.js
  test/spec/modules/h12mediaBidAdapter_spec.js
Labels: LGTM, maintenance, minor

#6398 AdYouLike Bid Adapter: add video capabilities
  modules/adyoulikeBidAdapter.js
  modules/adyoulikeBidAdapter.md
Labels: maintenance, minor

#6460 Openx Bid Adapter: add floor support for Video
  modules/openxBidAdapter.js
  test/spec/modules/openxBidAdapter_spec.js
Labels: maintenance, minor

#6461 Rubicon Analytics Adapter: use pbsBidId if present in response
  modules/rubiconAnalyticsAdapter.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
Labels: LGTM, maintenance, minor

#6471 ID5: differentiate the IDs provided when the user is opted out vs in the control group of A/B testing
  modules/id5IdSystem.js
  test/spec/modules/id5IdSystem_spec.js
Labels: maintenance, minor

#6415 Adagio Bid Adapter: add capability to pass ext-data from localStorage in bidRequest
  modules/adagioBidAdapter.js
  test/spec/modules/adagioBidAdapter_spec.js
Labels: maintenance, minor, needs review

#6457 Seedtag Bid Adapter: add connection type to bid request
  modules/seedtagBidAdapter.js
  test/spec/modules/seedtagBidAdapter_spec.js
Labels: maintenance, minor

#6450 AdDefend Bid Adapter: new bid adapter
  modules/addefendBidAdapter.js
  modules/addefendBidAdapter.md
  test/spec/modules/addefendBidAdapter_spec.js
Labels: feature, minor

#6478 GumGum Bid Adapter: adds meta field to bidresponse
  modules/gumgumBidAdapter.js
  test/spec/modules/gumgumBidAdapter_spec.js
Labels: maintenance, minor

#6475 Documentation: example integration file path and name changed to hello_world
  README.md
Labels: LGTM, maintenance, minor

#6477 Incorrect atypes on various eids
  modules/userId/eids.js
  test/spec/adapters/adbutler_spec.js
  test/spec/modules/conversantBidAdapter_spec.js
  test/spec/modules/eids_spec.js
  test/spec/modules/pubmaticBidAdapter_spec.js
  test/spec/modules/rubiconBidAdapter_spec.js
  test/spec/modules/userId_spec.js
Labels: bugfix, minor

#6473 ix Bid Adapter: add support for roundel alias
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance, minor, needs docs

#6437 Doceree Bid Adapter: new bid adapter
  modules/docereeBidAdapter.js
  modules/docereeBidAdapter.md
  test/spec/modules/docereeBidAdapter_spec.js
Labels: feature, minor, needs review

#6490 Openx Bid Adapter: Add user ID sub-modules to Prebid Openx Adapter
  modules/openxBidAdapter.js
  test/spec/modules/openxBidAdapter_spec.js
Labels: feature, needs docs

#6459 Smaato Bid Adapter: FPD Revision for 2.0 changes
  modules/smaatoBidAdapter.js
Labels: maintenance, minor

#6495 Conversant adapter: add adomain, remove digitrust
  modules/conversantBidAdapter.js
  test/spec/modules/conversantBidAdapter_spec.js
Labels: maintenance, minor

#6455 Rads Bid Adapter : add GDPR support & user sync support
  modules/radsBidAdapter.js
  test/spec/modules/radsBidAdapter_spec.js
Labels: maintenance, minor

#6427 Proxistore Bid Adapter: add cookieless url endpoint & use floor module
  modules/proxistoreBidAdapter.js
  test/spec/modules/proxistoreBidAdapter_spec.js
Labels: LGTM, maintenance, minor

#6481 AdYoulike Bid Adapter: Add an "Insertion" tracking for Native mediatype
  modules/adyoulikeBidAdapter.js
  test/spec/modules/adyoulikeBidAdapter_spec.js
Labels: maintenance, minor

#6456 Dspx Bid Adapter : add user sync support
  modules/dspxBidAdapter.js
  test/spec/modules/dspxBidAdapter_spec.js
Labels: maintenance, minor
