Repository prebid/Prebid.js, pull requests merged in 2021-09, with the labels that each got.

#7309 IQZone Bid Adapter: new adapter
  modules/iqzoneBidAdapter.js
  modules/iqzoneBidAdapter.md
  test/spec/modules/iqzoneBidAdapter_spec.js
Labels: feature, needs review

#7372 smartx Bid Adapter: bugfix outstream options for default outstream renderer configuration
  modules/smartxBidAdapter.js
  modules/smartxBidAdapter.md
  test/spec/modules/smartxBidAdapter_spec.js
Labels: bugfix

#6310 Adloox RTD Module: add new RTD module
  integrationExamples/gpt/adloox.html
  modules/adlooxAnalyticsAdapter.js
  modules/adlooxAnalyticsAdapter.md
  modules/adlooxRtdProvider.js
  modules/adlooxRtdProvider.md
  test/spec/modules/adlooxAnalyticsAdapter_spec.js
  test/spec/modules/adlooxRtdProvider_spec.js
Labels: feature

#7356 Finteza Analytics Adapter: bugfix for flaky test (Issue #7348)
  test/spec/modules/fintezaAnalyticsAdapter_spec.js
Labels: bugfix

#7364 IX Adapter: buildRequests refactor
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance

#7363 Onetag Bid Adapter: extend mediaType support
  modules/onetagBidAdapter.js
  test/spec/modules/onetagBidAdapter_spec.js
Labels: maintenance

#7377 Impactify Bid Adapter: add userid schain support
  modules/impactifyBidAdapter.js
  test/spec/modules/impactifyBidAdapter_spec.js
Labels: maintenance

#7328 VIS.X Bid Adapter: migrate from GET to POSTs & send additional userIDs as an EIDS object
  modules/visxBidAdapter.js
  test/spec/modules/visxBidAdapter_spec.js
Labels: maintenance

#7362 Rise Bid Adapter: improve isBidRequestValid and size detection along with other updates
  modules/riseBidAdapter.js
Labels: LGTM, maintenance

#7380 smartyAds Bid Adapter: change ad unit parameters
  modules/smartyadsBidAdapter.js
  modules/smartyadsBidAdapter.md
  test/spec/modules/smartyadsBidAdapter_spec.js
Labels: maintenance

#7386 TrustX Bid Adapter: convert all id-like request fields to a string
  modules/trustxBidAdapter.js
  test/spec/modules/trustxBidAdapter_spec.js
Labels: maintenance

#7290 Sharethrough adapter: connect to OpenRTB endpoint
  modules/sharethroughBidAdapter.js
  modules/sharethroughBidAdapter.md
  test/spec/modules/sharethroughBidAdapter_spec.js
Labels: LGTM, maintenance

#7366 Rubicon Analytics Adapter: suppress empty targeting values
  modules/rubiconAnalyticsAdapter.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
Labels: maintenance

#7391 VIS.X Bid Adapter: pass targeting to bidResponse.adserverTargeting
  modules/visxBidAdapter.js
  test/spec/modules/visxBidAdapter_spec.js
Labels: maintenance

#7383 ADman Media Adapter: compatible with version 5 and support uid2
  modules/admanBidAdapter.js
  test/spec/modules/admanBidAdapter_spec.js
Labels: maintenance

#7279 TheMediaGrid Bid Adapter: fill user.id from fpd cookie
  modules/gridBidAdapter.js
  modules/gridBidAdapter.md
  test/spec/modules/gridBidAdapter_spec.js
Labels: maintenance

#7369 ReadMe.md Update: change npm install to ci & remove average issue tag
  README.md
Labels: maintenance, documentation

#7376 Ad Partner Bid Adapter: add user syncs and partner ID
  modules/adpartnerBidAdapter.js
  modules/adpartnerBidAdapter.md
  test/spec/modules/adpartnerBidAdapter_spec.js
Labels: maintenance

#7385 TheMediaGrid Bid Adapter: Request key fixes
  modules/gridBidAdapter.js
  test/spec/modules/gridBidAdapter_spec.js
Labels: bugfix

#7237 Prebid Core: Add readConfig functionality to clone the config instead of referencing it
  src/config.js
  src/prebid.js
  test/spec/config_spec.js
Labels: feature

#7315 PBS Bid Adapter: Add additional ortb2 fields in request object
  modules/enrichmentFpdModule.js
  modules/prebidServerBidAdapter/index.js
  modules/validationFpdModule/config.js
  modules/validationFpdModule/index.js
  test/spec/modules/enrichmentFpdModule_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/validationFpdModule_spec.js
Labels: feature, needs docs, taxonomy

#7322 Publink Id System (Conversant): add new user id module
  modules/.submodules.json
  modules/publinkIdSystem.js
  modules/publinkIdSystem.md
  modules/userId/eids.js
  test/spec/modules/publinkIdSystem_spec.js
Labels: feature

#7374 Price Floors: Use gam adSlot if on bidRequest
  modules/priceFloors.js
  test/spec/integration/faker/googletag.js
  test/spec/modules/priceFloors_spec.js
Labels: maintenance

#7390 IX Bid Adapter: Adding support for IX Outstream Renderer
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: feature

#7394 Sonobi Bid Adapter: remove outstream bid.ad
  modules/sonobiBidAdapter.js
  test/spec/modules/sonobiBidAdapter_spec.js
Labels: maintenance

#7299 BLIINK Bid Adapter : Add new adapter
  modules/bliinkBidAdapter.js
  modules/bliinkBidAdapter.md
  test/spec/modules/bliinkBidAdapter_spec.js
Labels: feature

#7337 PBjs Core (Targeting): bugfix for issue #7323 adding extra spaces
  src/targeting.js
  test/spec/unit/core/targeting_spec.js
Labels: bugfix

#7316 Between Bid Adapter: add ids
  modules/betweenBidAdapter.js
  test/spec/modules/betweenBidAdapter_spec.js
Labels: maintenance

#7336 TargetVideo Bid Adapter: add new adapter
  modules/appnexusBidAdapter.js
Labels: feature

#7400 Merkle Id System: configurable endpoint
  integrationExamples/gpt/userId_example.html
  modules/merkleIdSystem.js
Labels: maintenance

#7395 Timeout RTD module: initial release
  modules/timeoutRtdProvider.js
  modules/timeoutRtdProvider.md
  test/spec/modules/timeoutRtdProvider_spec.js
Labels: feature

#7371 CriteoIdSystem: returns a callback to initiate user sync
  modules/criteoIdSystem.js
  test/spec/modules/criteoIdSystem_spec.js
Labels: maintenance

#7408 Rubicon Bid adapter: Add sizeId 562 (300x431)
  modules/rubiconBidAdapter.js
Labels: maintenance

#7406 Timeout RTD submodule: register parent module
  modules/.submodules.json
Labels: maintenance

#7412 Beachfront Bid Adapter: add validation console messages
  modules/beachfrontBidAdapter.js
Labels: maintenance

#7414 Rubicon Bid Adapter: Add new sizes
  modules/rubiconBidAdapter.js
Labels: maintenance

#7389 PulsePoint Bid Adapter: support for additional user id providers
  modules/pulsepointBidAdapter.js
  test/spec/modules/pulsepointBidAdapter_spec.js
Labels: maintenance

#7417 smartx Bid Adapter: fix empty title not configurable
  modules/smartxBidAdapter.js
Labels: bugfix

#7409 gjirafa Bid Adapter: add biskoID and segmeents
  modules/gjirafaBidAdapter.js
Labels: maintenance

#7411 Integr8 Bid Adapter: add biskoID and segments
  modules/integr8BidAdapter.js
Labels: maintenance

#7410 malltv Bid Adapter : add biskoId, auctionId, and segments
  modules/malltvBidAdapter.js
Labels: maintenance

#7353 Fluct Bid Adapter: add adomain for Prebid 5 compliance
  modules/fluctBidAdapter.js
  test/spec/modules/fluctBidAdapter_spec.js
Labels: maintenance

#7404 Merkle Id System: make endpoint optionally configurable
  integrationExamples/gpt/userId_example.html
  modules/merkleIdSystem.js
  test/spec/modules/merkleIdSystem_spec.js
Labels: maintenance

#7424 Timeout RTD Provider & Insticator & Sharethrough Bid Adapter: bug fixes for imports
  modules/insticatorBidAdapter.js
  modules/sharethroughBidAdapter.js
  modules/timeoutRtdProvider.js
Labels: bugfix

#7425 Publink UserId Submodule: publinkIdSystem_spec.js test fix on ie11
  test/spec/modules/publinkIdSystem_spec.js
Labels: bugfix

#7429 Onetag Bid Adapter: minor bugfix
  modules/onetagBidAdapter.js
Labels: bugfix

#7418 Criteo Bid Adapter: update FastBid version to 113
  modules/criteoBidAdapter.js
Labels: maintenance

#7432 Nativo Bid Adapter: Define GVLID
  modules/nativoBidAdapter.js
Labels: maintenance

#7419 PubMatic bid adapter: while retrieving floor from floor module pass banner-sizes instead of *
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: maintenance

#7427 Adf adapter: price floors module support added
  modules/adfBidAdapter.js
  test/spec/modules/adfBidAdapter_spec.js
Labels: maintenance

#7433 Rubicon Analytics Adapter: Send error.description instead of error.message
  modules/rubiconAnalyticsAdapter.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
  test/spec/modules/rubiconAnalyticsSchema.json
Labels: bugfix

#7426 seeding Alliance Bid Adapter: update to comply with Prebid 5
  modules/seedingAllianceBidAdapter.js
  test/spec/modules/seedingAllianceAdapter_spec.js
Labels: maintenance

#7403 AdHash Bid Adaptor : update to comply with Prebid 5.0
  modules/adhashBidAdapter.js
  modules/adhashBidAdapter.md
  test/spec/modules/adhashBidAdapter_spec.js
Labels: maintenance

#7301 AFP Bid Adapter: add new bid adapter and integration examples
  integrationExamples/gpt/afpExample.html
  integrationExamples/gpt/afpGamExample.html
  modules/afpBidAdapter.js
  modules/afpBidAdapter.md
  test/spec/modules/afpBidAdapter_spec.js
Labels: feature

#7442 Rise Bid Adapteer: docs update
  modules/riseBidAdapter.md
Labels: maintenance

#7437 Weborama Real-time Data Module: add new RTD module
  integrationExamples/gpt/weboramaRtdProvider_example.html
  modules/weboramaRtdProvider.js
  modules/weboramaRtdProvider.md
  test/spec/modules/weboramaRtdProvider_spec.js
Labels: feature, taxonomy

#7441 New bidder adapter - Adquery
  modules/adqueryBidAdapter.js
  modules/adqueryBidAdapter.md
  test/spec/modules/adqueryBidAdapter_spec.js
Labels: feature, minor

#7443 Medianet Bid Adapter: Sending `ortb2Imp` in bid request
  modules/medianetBidAdapter.js
  test/spec/modules/medianetBidAdapter_spec.js
Labels: maintenance

#7423 Medianet Analytics Adapter: Removed PR log and fixed sampling
  modules/medianetAnalyticsAdapter.js
  test/spec/modules/medianetAnalyticsAdapter_spec.js
Labels: bugfix

#7398 Invibes Bid Adapter : multi request support
  modules/invibesBidAdapter.js
  test/spec/modules/invibesBidAdapter_spec.js
Labels: maintenance

#7455 Triplelift Bid Adapter: Increase Instream TTL
  modules/tripleliftBidAdapter.js
  test/spec/modules/tripleliftBidAdapter_spec.js
Labels: maintenance

#7430 TheMediaGridNM: use /hbjson endpoint
  modules/gridNMBidAdapter.js
  test/spec/modules/gridNMBidAdapter_spec.js
Labels: maintenance

#7460 IX Bid Adapter: fix infinite loop
  modules/ixBidAdapter.js
Labels: bugfix

#7461 .submodules : update to include weborama rtd
  modules/.submodules.json
Labels: maintenance

#7444 Inskin Bid Adapter: override schain with publisher id
  modules/inskinBidAdapter.js
  modules/inskinBidAdapter.md
  test/spec/modules/inskinBidAdapter_spec.js
Labels: maintenance, minor

#7439 PublinkId - validate hash and fix decode
  modules/conversantBidAdapter.js
  modules/publinkIdSystem.js
  test/spec/modules/publinkIdSystem_spec.js
Labels: needs review, LGTM, bugfix, minor

#7407 Vidoomy Bid Adapter: bugfix for cookie sync with pixel fires
  modules/vidoomyBidAdapter.js
Labels: bugfix

#7464 Colossus Adapter: add pbAdSlot support
  modules/colossussspBidAdapter.js
  test/spec/modules/colossussspBidAdapter_spec.js
Labels: maintenance

#7475 User ID Module: update ID submodules list
  modules/.submodules.json
Labels: bugfix

#7472 Ogury Bid Adapter: fix getusersync method
  modules/oguryBidAdapter.js
  test/spec/modules/oguryBidAdapter_spec.js
Labels: bugfix

#7471 Multiple Bid/Analytics Adapters: import utils functions as needed and not the whole module
  modules/adkernelBidAdapter.js
  modules/adlooxAdServerVideo.js
  modules/adlooxAnalyticsAdapter.js
  modules/adlooxRtdProvider.js
  modules/admanBidAdapter.js
  modules/admixerBidAdapter.js
  modules/admixerIdSystem.js
  modules/adnowBidAdapter.js
  modules/adnuntiusBidAdapter.js
  modules/adoceanBidAdapter.js
  modules/adpartnerBidAdapter.js
  modules/adpod.js
  modules/adprimeBidAdapter.js
  modules/adqueryBidAdapter.js
  modules/adrelevantisBidAdapter.js
Labels: maintenance, import_utils_as_needed

#7469 Multiple Bid/Analytics Adapters : import utils functions as needed, not whole module
  modules/33acrossBidAdapter.js
  modules/a4gBidAdapter.js
  modules/ablidaBidAdapter.js
  modules/adagioAnalyticsAdapter.js
  modules/adagioBidAdapter.js
  modules/adbookpspBidAdapter.js
  modules/adfBidAdapter.js
  modules/adgenerationBidAdapter.js
  modules/adkernelAdnAnalyticsAdapter.js
  modules/adkernelAdnBidAdapter.js
Labels: maintenance, import_utils_as_needed

#7477 Multiple Bid/Analytics/ID Adapters: import utils functions as needed and not the whole module
  modules/adWMGBidAdapter.js
  modules/adriverBidAdapter.js
  modules/adtargetBidAdapter.js
  modules/adtelligentBidAdapter.js
  modules/adtrueBidAdapter.js
  modules/aduptechBidAdapter.js
  modules/advangelistsBidAdapter.js
  modules/adxcgAnalyticsAdapter.js
  modules/adxcgBidAdapter.js
  modules/adxpremiumAnalyticsAdapter.js
  modules/adyoulikeBidAdapter.js
  modules/ajaBidAdapter.js
  modules/akamaiDAPIdSystem.js
  modules/aniviewBidAdapter.js
  modules/aolBidAdapter.js
Labels: maintenance, import_utils_as_needed

#7490 Multiple Bid/Analytics/ID/ other modules: import utils functions as needed and not the whole module
  modules/krushmediaBidAdapter.js
  modules/kubientBidAdapter.js
  modules/limelightDigitalBidAdapter.js
  modules/liveIntentIdSystem.js
  modules/livewrappedAnalyticsAdapter.js
  modules/livewrappedBidAdapter.js
  modules/liveyieldAnalyticsAdapter.js
  modules/lockerdomeBidAdapter.js
  modules/loganBidAdapter.js
  modules/lotamePanoramaIdSystem.js
  modules/lunamediahbBidAdapter.js
  modules/madvertiseBidAdapter.js
  modules/marsmediaBidAdapter.js
  modules/mathildeadsBidAdapter.js
  modules/mediaforceBidAdapter.js
Labels: maintenance, import_utils_as_needed

#7507 TheMediaGrid: fix bug with wrong vastUrl
  modules/gridBidAdapter.js
  test/spec/modules/gridBidAdapter_spec.js
Labels: bugfix

#7500 Gumgum Bid Adapter: improve GPID support by checking pbadslot beefore adserver.adslot
  modules/gumgumBidAdapter.js
  test/spec/modules/gumgumBidAdapter_spec.js
Labels: bugfix

#7454 PBjs Core : User sync iframe over image
  src/userSync.js
  test/spec/userSync_spec.js
Labels: bugfix

#7493 Multiple Bid/Analytics/ID/ other modules: import utils functions as needed and not the whole module
  modules/proxistoreBidAdapter.js
  modules/pubCommonId.js
  modules/pubProvidedIdSystem.js
  modules/publinkIdSystem.js
  modules/pubmaticAnalyticsAdapter.js
  modules/pubmaticBidAdapter.js
  modules/pubperfAnalyticsAdapter.js
  modules/pubwiseAnalyticsAdapter.js
  modules/pubwiseBidAdapter.js
  modules/pubxBidAdapter.js
  modules/pubxaiAnalyticsAdapter.js
  modules/pulsepointBidAdapter.js
  modules/pxyzBidAdapter.js
  modules/quantcastBidAdapter.js
  modules/radsBidAdapter.js
Labels: maintenance, import_utils_as_needed

#7453 PBjs Core: use GPT's slot.updateTargetingFromMap instead of slot.setTargeting (Issue #7416)
  src/targeting.js
  test/spec/unit/pbjs_api_spec.js
Labels: feature

#7483 Multiple Bid/Analytics/ID Adapters: import utils functions as needed and not the whole module
  modules/datablocksBidAdapter.js
  modules/deepintentBidAdapter.js
  modules/dgkeywordRtdProvider.js
  modules/districtmDMXBidAdapter.js
  modules/dmdIdSystem.js
  modules/docereeBidAdapter.js
  modules/dspxBidAdapter.js
  modules/ebdrBidAdapter.js
  modules/emx_digitalBidAdapter.js
  modules/enrichmentFpdModule.js
  modules/eplanningAnalyticsAdapter.js
  modules/eplanningBidAdapter.js
  modules/etargetBidAdapter.js
  modules/express.js
  modules/fabrickIdSystem.js
Labels: maintenance, import_utils_as_needed

#7466 Pbjs Core: avoid import all from utils in src/ files
  src/AnalyticsAdapter.js
  src/Renderer.js
  src/adapterManager.js
  src/adloader.js
  src/ajax.js
  src/auction.js
  src/bidfactory.js
  src/config.js
  src/cpmBucketManager.js
  src/prebid.js
  src/storageManager.js
  src/targeting.js
  src/userSync.js
  src/videoCache.js
Labels: needs 2nd review, maintenance, import_utils_as_needed

#7468 Key Prebid Modules: import only what is needed from utils
  modules/multibid/index.js
  modules/prebidServerBidAdapter/index.js
  modules/rtdModule/index.js
  modules/userId/eids.js
  modules/userId/index.js
  modules/validationFpdModule/index.js
Labels: needs 2nd review, maintenance, import_utils_as_needed

#7496 Multiple Bid/Analytics/ID/ other modules: import utils functions as needed and not the whole module
  modules/seedtagBidAdapter.js
  modules/sharedIdSystem.js
  modules/sharethroughAnalyticsAdapter.js
  modules/sharethroughBidAdapter.js
  modules/showheroes-bsBidAdapter.js
  modules/sigmoidAnalyticsAdapter.js
  modules/sirdataRtdProvider.js
  modules/sizeMappingV2.js
  modules/smaatoBidAdapter.js
  modules/smartadserverBidAdapter.js
  modules/smartxBidAdapter.js
  modules/smartyadsBidAdapter.js
  modules/smilewantedBidAdapter.js
  modules/sonobiAnalyticsAdapter.js
  modules/sortableAnalyticsAdapter.js
Labels: maintenance, import_utils_as_needed

#7506 JustPremium Bid Adapter: schain support added
  modules/justpremiumBidAdapter.js
  test/spec/modules/justpremiumBidAdapter_spec.js
Labels: maintenance

#7491 Multiple Bid/Analytics/ID/ other modules: import utils functions as needed and not the whole module
  modules/mediakeysBidAdapter.js
  modules/medianetAnalyticsAdapter.js
  modules/medianetBidAdapter.js
  modules/medianetRtdProvider.js
  modules/merkleIdSystem.js
  modules/mgidBidAdapter.js
  modules/microadBidAdapter.js
  modules/mwOpenLinkIdSystem.js
  modules/nativoBidAdapter.js
  modules/naveggIdSystem.js
  modules/nextMillenniumBidAdapter.js
  modules/nobidBidAdapter.js
  modules/novatiqIdSystem.js
  modules/oneVideoBidAdapter.js
  modules/onomagicBidAdapter.js
Labels: maintenance, import_utils_as_needed

#7486 Multiple Bid/Analytics/ID/ other modules: import utils functions as needed and not the whole module
  modules/instreamTracking.js
  modules/integr8BidAdapter.js
  modules/intentIqIdSystem.js
  modules/interactiveOffersBidAdapter.js
  modules/invibesBidAdapter.js
  modules/invisiblyAnalyticsAdapter.js
  modules/iqmBidAdapter.js
  modules/iqzoneBidAdapter.js
  modules/ixBidAdapter.js
  modules/jixieBidAdapter.js
  modules/kargoBidAdapter.js
  modules/kinessoIdSystem.js
  modules/koblerBidAdapter.js
  modules/konduitAnalyticsAdapter.js
  modules/konduitWrapper.js
Labels: maintenance, import_utils_as_needed

#7478 Fluct Bid Adapter: ie polyfill for url search params
  allowedModules.js
  modules/fluctBidAdapter.js
Labels: maintenance

#7485 Multiple Bid/Analytics/ID/ other modules: import utils functions as needed and not the whole module
  modules/growadvertisingBidAdapter.js
  modules/gumgumBidAdapter.js
  modules/h12mediaBidAdapter.js
  modules/haloIdSystem.js
  modules/hybridBidAdapter.js
  modules/iasRtdProvider.js
  modules/id5IdSystem.js
  modules/idImportLibrary.js
  modules/idxIdSystem.js
  modules/impactifyBidAdapter.js
  modules/improvedigitalBidAdapter.js
  modules/imuIdSystem.js
  modules/inmarBidAdapter.js
  modules/innityBidAdapter.js
  modules/inskinBidAdapter.js
Labels: maintenance, import_utils_as_needed

#7480 Multiple Bid/Analytics/ID Adapters: import utils functions as needed and not the whole module
  modules/bluebillywigBidAdapter.js
  modules/boldwinBidAdapter.js
  modules/braveBidAdapter.js
  modules/bridgewellBidAdapter.js
  modules/brightMountainMediaBidAdapter.js
  modules/brightcomBidAdapter.js
  modules/britepoolIdSystem.js
  modules/browsiRtdProvider.js
  modules/bucksenseBidAdapter.js
  modules/buzzoolaBidAdapter.js
  modules/byDataAnalyticsAdapter.js
  modules/ccxBidAdapter.js
  modules/cleanmedianetBidAdapter.js
  modules/clickforceBidAdapter.js
  modules/cointrafficBidAdapter.js
Labels: maintenance, import_utils_as_needed

#7492 Multiple Bid/Analytics/ID/ other modules: import utils functions as needed and not the whole module
  modules/ooloAnalyticsAdapter.js
  modules/openwebBidAdapter.js
  modules/openxAnalyticsAdapter.js
  modules/openxBidAdapter.js
  modules/operaadsBidAdapter.js
  modules/optimeraRtdProvider.js
  modules/optoutBidAdapter.js
  modules/orbidderBidAdapter.js
  modules/outbrainBidAdapter.js
  modules/ozoneBidAdapter.js
  modules/padsquadBidAdapter.js
  modules/parrableIdSystem.js
  modules/pixfutureBidAdapter.js
  modules/prebidmanagerAnalyticsAdapter.js
  modules/priceFloors.js
Labels: maintenance, import_utils_as_needed

#7484 Multiple Bid/Analytics/ID/ other modules: import utils functions as needed and not the whole module
  modules/feedadBidAdapter.js
  modules/fintezaAnalyticsAdapter.js
  modules/flocIdSystem.js
  modules/fluctBidAdapter.js
  modules/freewheel-sspBidAdapter.js
  modules/gamoshiBidAdapter.js
  modules/gdprEnforcement.js
  modules/getintentBidAdapter.js
  modules/gmosspBidAdapter.js
  modules/gnetBidAdapter.js
  modules/googleAnalyticsAdapter.js
  modules/gothamadsBidAdapter.js
  modules/gptPreAuction.js
  modules/gridBidAdapter.js
  modules/gridNMBidAdapter.js
Labels: maintenance, import_utils_as_needed

#7482 Multiple Bid/Analytics/ID/other modules: import utils functions as needed and not the whole module
  modules/coinzillaBidAdapter.js
  modules/colossussspBidAdapter.js
  modules/concertAnalyticsAdapter.js
  modules/concertBidAdapter.js
  modules/connectadBidAdapter.js
  modules/consentManagement.js
  modules/consentManagementUsp.js
  modules/consumableBidAdapter.js
  modules/contentexchangeBidAdapter.js
  modules/conversantBidAdapter.js
  modules/cpmstarBidAdapter.js
  modules/craftBidAdapter.js
  modules/criteoBidAdapter.js
  modules/criteoIdSystem.js
  modules/currency.js
Labels: maintenance, import_utils_as_needed

#7495 Multiple Bid/Analytics/ID/ other modules: import utils functions as needed and not the whole module
  modules/realvuAnalyticsAdapter.js
  modules/reconciliationRtdProvider.js
  modules/relaidoBidAdapter.js
  modules/resetdigitalBidAdapter.js
  modules/revcontentBidAdapter.js
  modules/rhythmoneBidAdapter.js
  modules/richaudienceBidAdapter.js
  modules/riseBidAdapter.js
  modules/roxotAnalyticsAdapter.js
  modules/rtbhouseBidAdapter.js
  modules/rtbsapeBidAdapter.js
  modules/rubiconAnalyticsAdapter.js
  modules/rubiconBidAdapter.js
  modules/scaleableAnalyticsAdapter.js
  modules/seedingAllianceBidAdapter.js
Labels: maintenance, import_utils_as_needed

#7498 Multiple Bid/Analytics/ID/ other modules: import utils functions as needed and not the whole module
  modules/timeoutRtdProvider.js
  modules/tpmnBidAdapter.js
  modules/trionBidAdapter.js
  modules/tripleliftBidAdapter.js
  modules/truereachBidAdapter.js
  modules/trustxBidAdapter.js
  modules/ucfunnelBidAdapter.js
  modules/uid2IdSystem.js
  modules/underdogmediaBidAdapter.js
  modules/unicornBidAdapter.js
  modules/unifiedIdSystem.js
  modules/unrulyBidAdapter.js
  modules/vdoaiBidAdapter.js
  modules/verizonMediaIdSystem.js
  modules/vidazooBidAdapter.js
Labels: maintenance, import_utils_as_needed

#7502 Multiple Bid/Analytics/ID/ other modules: import utils functions as needed and not the whole module
  modules/videobyteBidAdapter.js
  modules/videoreachBidAdapter.js
  modules/vidoomyBidAdapter.js
  modules/viewdeosDXBidAdapter.js
  modules/visxBidAdapter.js
  modules/voxBidAdapter.js
  modules/vuukleBidAdapter.js
  modules/waardexBidAdapter.js
  modules/weboramaRtdProvider.js
  modules/winrBidAdapter.js
  modules/wipesBidAdapter.js
  modules/yieldlabBidAdapter.js
  modules/yieldliftBidAdapter.js
  modules/yieldmoBidAdapter.js
  modules/yieldoneAnalyticsAdapter.js
  modules/yieldoneBidAdapter.js
  modules/yuktamediaAnalyticsAdapter.js
  modules/zeotapIdPlusIdSystem.js
  modules/zetaBidAdapter.js
  modules/zeta_global_sspBidAdapter.js
Labels: maintenance, import_utils_as_needed

#7474 E-planning Bid Adapter: hostname modification
  modules/eplanningBidAdapter.js
  test/spec/modules/eplanningBidAdapter_spec.js
Labels: maintenance

#7459 Livewrapped Bid Adapter: read data-adunitid attribute & pass to analytics endpoint
  modules/livewrappedAnalyticsAdapter.js
  test/spec/modules/livewrappedAnalyticsAdapter_spec.js
Labels: maintenance

#7470 Rubicon Bid Adapter: bugfix for copying params.video.language
  modules/rubiconBidAdapter.js
Labels: bugfix

#7451 tappx Bid Adapter: fix site param and add extra video params
  modules/tappxBidAdapter.js
  test/spec/modules/tappxBidAdapter_spec.js
Labels: bugfix

#7501 Yieldmo Bid Adapter: add shared id support and cleaned up device.ip
  modules/yieldmoBidAdapter.js
  test/spec/modules/yieldmoBidAdapter_spec.js
Labels: maintenance

#7514 Slimcut Bid Adapter: porting from 4.x with adomain
  modules/slimcutBidAdapter.js
  test/spec/modules/slimcutBidAdapter_spec.js
Labels: maintenance

#7517 Nativo Bid Adapter: update to adUnit param usage
  modules/nativoBidAdapter.js
  modules/nativoBidAdapter.md
  test/spec/modules/nativoBidAdapter_spec.js
Labels: maintenance

#7515 PubLink id system: adds params for site id and api key
  modules/publinkIdSystem.js
  modules/publinkIdSystem.md
  test/spec/modules/publinkIdSystem_spec.js
Labels: maintenance

#7505 Gumgum Bid Adapter: use nearest matching h/w dimensions from bid request
  modules/gumgumBidAdapter.js
  test/spec/modules/gumgumBidAdapter_spec.js
Labels: bugfix

#7450 Pubmatic Bid Adapter: add support for JW player
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: maintenance

#7518 Vidoomy Bid Adapter: fix gdpr consent failsafe
  modules/vidoomyBidAdapter.js
Labels: bugfix

#7422 Relaido Bid Adapter: support imuid module
  modules/relaidoBidAdapter.js
  test/spec/modules/relaidoBidAdapter_spec.js
Labels: maintenance

#7521 Relaido Bid Adapter: support imuid (with utils fix after revert)
  modules/relaidoBidAdapter.js
  test/spec/modules/relaidoBidAdapter_spec.js
Labels: maintenance

#7397 Mytarget Bid Adapter : update adapter to comply with Prebid 5
  modules/mytargetBidAdapter.js
  test/spec/modules/mytargetBidAdapter_spec.js
Labels: maintenance

#7431 IAS RTD adapter: improve workflow
  modules/iasRtdProvider.js
  test/spec/modules/iasRtdProvider_spec.js
Labels: maintenance
