Repository prebid/Prebid.js, pull requests merged in 2022-08, with the labels that each got.

#8701 Improve Digital adapter: flag support for native 1.2 JS trackers in bid request
  modules/improvedigitalBidAdapter.js
  test/spec/modules/improvedigitalBidAdapter_spec.js
Labels: maintenance

#8706 c1x Bid Adapter: adding back adapter with updated pbjs compliance
  modules/c1xBidAdapter.js
  modules/c1xBidAdapter.md
  test/spec/modules/c1xBidAdapter_spec.js
Labels: feature, LGTM

#8682 BeyondMedia Bid Adapter: initial bid adapter release
  modules/andBeyondMediaBidAdapter.js
  modules/andBeyondMediaBidAdapter.md
  test/spec/modules/andBeyondMediaBidAdapter_spec.js
Labels: feature

#8767 Intimate Merger Universal Identifier System: add imppid
  modules/imuIdSystem.js
  modules/imuIdSystem.md
  modules/userId/eids.js
  test/spec/modules/eids_spec.js
  test/spec/modules/imuIdSystem_spec.js
  test/spec/modules/userId_spec.js
Labels: feature, needs review

#8778 Various files: clean up unneeded code
  integrationExamples/gpt/1plusXRtdProviderExample.html
  integrationExamples/gpt/airgridRtdProvider_example.html
  integrationExamples/gpt/amp/remote.html
  integrationExamples/gpt/blueconicRtdProvider_example.html
  integrationExamples/gpt/hadronRtdProvider_example.html
  integrationExamples/gpt/inskin_example.html
  integrationExamples/gpt/prebidServer_example.html
  integrationExamples/gpt/serverbidServer_example.html
  integrationExamples/gpt/userId_example.html
  integrationExamples/postbid/oas/postbid-config.js
  libraries/analyticsAdapter/examples/libraries/example.js
  libraries/analyticsAdapter/examples/libraries/example2.js
  modules/browsiRtdProvider.js
  modules/consentManagementUsp.js
  modules/fintezaAnalyticsAdapter.js
  modules/freewheel-sspBidAdapter.js
  modules/nobidBidAdapter.js
  modules/openxBidAdapter.js
  modules/synacormediaBidAdapter.js
  modules/tappxBidAdapter.js
  modules/trustpidSystem.js
  modules/visxBidAdapter.js
  src/config.js
Labels: maintenance

#8760 Prebid Core: Handled edge cases for allowedAlternateBidderCodes functionality
  src/adapters/bidderFactory.js
  test/spec/unit/core/bidderFactory_spec.js
Labels: LGTM, maintenance

#8783 Criteo Adapter: remove bid.adId
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: maintenance

#8789 PubMatic Adapter : send device.language in ISO-639-1-alpha-2 (2 character language) format
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: maintenance

#8723 Snigel Bid Adapter: initial adapter release
  modules/snigelBidAdapter.js
  modules/snigelBidAdapter.md
  test/spec/modules/snigelBidAdapter_spec.js
Labels: feature

#8796 openxOrtb bid adapter: support 204 response, small bug fix
  modules/openxOrtbBidAdapter.js
  test/spec/modules/openxOrtbBidAdapter_spec.js
Labels: bugfix

#8750 CleanIO RTD Module: support billable event
  modules/cleanioRtdProvider.js
  test/spec/modules/cleanioRtdProvider_spec.js
  test/spec/modules/concertAnalyticsAdapter_spec.js
  test/spec/modules/eplanningAnalyticsAdapter_spec.js
  test/spec/modules/fintezaAnalyticsAdapter_spec.js
  test/spec/modules/invisiblyAnalyticsAdapter_spec.js
  test/spec/modules/konduitAnalyticsAdapter_spec.js
  test/spec/modules/optimonAnalyticsAdapter_spec.js
  test/spec/modules/pianoDmpAnalyticsAdapter_spec.js
  test/spec/modules/prebidmanagerAnalyticsAdapter_spec.js
  test/spec/modules/pubperfAnalyticsAdapter_spec.js
  test/spec/modules/pubstackAnalyticsAdapter_spec.js
  test/spec/modules/pubwiseAnalyticsAdapter_spec.js
  test/spec/modules/sigmoidAnalyticsAdapter_spec.js
  test/spec/modules/sovrnAnalyticsAdapter_spec.js
  test/spec/modules/yieldoneAnalyticsAdapter_spec.js
Labels: maintenance

#8790 PubMatic Bid Adapter: Sending allowedAlternateBidderCodes data to AdServer
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: maintenance

#8679 Ttd Bid adapter: support for transaction id, bcat, and consolidate params
  modules/ttdBidAdapter.js
  modules/ttdBidAdapter.md
  test/spec/modules/ttdBidAdapter_spec.js
Labels: maintenance

#8718 NextMillennium Bid Adapter: Add referrer and imp to bid request
  modules/nextMillenniumBidAdapter.js
  test/spec/modules/nextMillenniumBidAdapter_spec.js
Labels: maintenance

#8788 UserID Module: continue the auction if userId init fails
  modules/userId/index.js
  test/spec/modules/userId_spec.js
Labels: bugfix

#8762 sspBC bid adapter - remove storage/cookie check, add screen size to request
  modules/sspBCBidAdapter.js
  test/spec/modules/sspBCBidAdapter_spec.js
Labels: feature, needs review

#8755 Ozone Bid Adapter: Various improvements
  modules/ozoneBidAdapter.js
  modules/ozoneBidAdapter.md
  test/spec/modules/ozoneBidAdapter_spec.js
Labels: LGTM, maintenance

#8803 Adkernel Bid Adapter: DisplayIo alias
  modules/adkernelBidAdapter.js
Labels: maintenance

#8797 Vidazoo Bid Adapter: pass referrer to server + pubProvidedId support
  modules/vidazooBidAdapter.js
  test/spec/modules/vidazooBidAdapter_spec.js
Labels: maintenance

#8802 Aniview Bid adapter: fix lgtm alert
  modules/aniviewBidAdapter.js
Labels: maintenance

#8801 Zeta Global BidAdapter: update the bid endpoint.
  modules/zeta_global_sspBidAdapter.js
  test/spec/modules/zeta_global_sspBidAdapter_spec.js
Labels: maintenance

#8806 Adnuntius Bid Adapter: allow Adnuntius to read dimensions
  modules/adnuntiusBidAdapter.js
  test/spec/modules/adnuntiusBidAdapter_spec.js
Labels: maintenance

#8808 Sharethrough Bid Adapter: Fix `bcat` and `badv` from First Party Data
  modules/sharethroughBidAdapter.js
  test/spec/modules/sharethroughBidAdapter_spec.js
Labels: bugfix

#8791 Prebid Core : fix issue of mergeConfig
  src/config.js
  test/spec/config_spec.js
Labels: bugfix

#8798 Boldwin Bid Adapter: added endpointId param
  modules/boldwinBidAdapter.js
  modules/boldwinBidAdapter.md
  test/spec/modules/boldwinBidAdapter_spec.js
Labels: maintenance

#8816 ShowHeroes Bid Adapter: add new endpoint
  modules/showheroes-bsBidAdapter.js
  modules/showheroes-bsBidAdapter.md
  test/spec/modules/showheroes-bsBidAdapter_spec.js
Labels: maintenance

#8817 Yahoossp bid adapter: Fix schain data handling
  modules/yahoosspBidAdapter.js
  test/spec/modules/yahoosspBidAdapter_spec.js
Labels: bugfix

#8811 Various files: fix LGTM trailing semi-colon
  gulpfile.js
  modules/1plusXRtdProvider.js
  modules/akamaiDapRtdProvider.js
  modules/bliinkBidAdapter.js
  modules/byDataAnalyticsAdapter.js
  modules/c1xBidAdapter.js
  modules/criteoBidAdapter.js
  modules/eplanningBidAdapter.js
  modules/hadronAnalyticsAdapter.js
  modules/improvedigitalBidAdapter.js
  modules/imuIdSystem.js
  modules/kueezBidAdapter.js
  modules/mediafuseBidAdapter.js
  modules/newspassidBidAdapter.js
  modules/openxOrtbBidAdapter.js
  modules/prebidServerBidAdapter/index.js
  modules/shinezBidAdapter.js
  modules/spotxBidAdapter.js
  modules/taboolaBidAdapter.js
  modules/userId/index.js
  modules/videoheroesBidAdapter.js
  modules/weboramaRtdProvider.js
  src/config.js
  src/native.js
Labels: maintenance

#8815 Criteo Adapter: Add Price floor support
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: maintenance

#8821 Various files: fix LGTM trailing semi-colon
  modules/33acrossBidAdapter.js
  modules/adagioBidAdapter.js
  modules/adgenerationBidAdapter.js
  modules/apacdexBidAdapter.js
  modules/appnexusBidAdapter.js
  modules/boldwinBidAdapter.js
  modules/colossussspBidAdapter.js
  modules/consentManagementUsp.js
  modules/consumableBidAdapter.js
  modules/criteoBidAdapter.js
  modules/gridBidAdapter.js
  modules/gridNMBidAdapter.js
  modules/hadronRtdProvider.js
  modules/merkleIdSystem.js
  modules/microadBidAdapter.js
  modules/mobfoxpbBidAdapter.js
  modules/oguryBidAdapter.js
  modules/operaadsBidAdapter.js
  modules/ozoneBidAdapter.js
  modules/pubmaticAnalyticsAdapter.js
  modules/pubmaticBidAdapter.js
  modules/pulsepointBidAdapter.js
  modules/relaidoBidAdapter.js
  modules/riseBidAdapter.js
  modules/rubiconBidAdapter.js
  modules/sirdataRtdProvider.js
  modules/smartxBidAdapter.js
  modules/sspBCBidAdapter.js
  modules/tripleliftBidAdapter.js
  modules/ttdBidAdapter.js
  modules/vrtcalBidAdapter.js
  src/adapterManager.js
  src/auction.js
  src/utils.js
Labels: maintenance

#8822 AdYouLike bidder adapter: update pageUrl and referrer values
  modules/adyoulikeBidAdapter.js
  test/spec/modules/adyoulikeBidAdapter_spec.js
Labels: maintenance

#8761 Relaido Bid Adapter: Add support for banner.
  modules/relaidoBidAdapter.js
  test/spec/modules/relaidoBidAdapter_spec.js
Labels: feature, needs review

#8771 Rise bid adapter - support multi seller end points
  modules/riseBidAdapter.js
  modules/riseBidAdapter.md
  test/spec/modules/riseBidAdapter_spec.js
Labels: feature, needs review

#8622 Adtargetme Bid Adapter: initial release
  modules/adtrgtmeBidAdapter.js
  modules/adtrgtmeBidAdapter.md
  test/spec/modules/adtrgtmeBidAdapter_spec.js
Labels: feature

#8824 AdagioBidAdapter: fix domain/page detection via refererInfo (keep `topmostLocation` information only)
  modules/adagioBidAdapter.js
  test/spec/modules/adagioBidAdapter_spec.js
Labels: bugfix

#8814 Adtelligent Bid Adapter: add OCM alias
  modules/adtelligentBidAdapter.js
  test/spec/modules/adtelligentBidAdapter_spec.js
Labels: maintenance

#8828 Openx Analytics Adapter: remove endpoint calls, add deprecation warning
  modules/openxAnalyticsAdapter.js
  modules/openxAnalyticsAdapter.md
  test/spec/modules/openxAnalyticsAdapter_spec.js
Labels: maintenance

#8832 Aniview Bid Adapter: add a new alias
  modules/aniviewBidAdapter.js
Labels: maintenance

#8820 Pubmatic bid adapter: improved site object handling
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: maintenance

#8819 Build system: fix "test-coverage"
  babelConfig.js
  karma.conf.maker.js
  package-lock.json
  package.json
Labels: build process, bugfix

#8810 CPMStar Bid Adapter : change request method to post & added data to endpoint
  modules/cpmstarBidAdapter.js
  test/spec/modules/cpmstarBidAdapter_spec.js
Labels: maintenance

#8825 Kargo Bid Adapter: Pull Page URL from refererInfo
  modules/kargoBidAdapter.js
  test/spec/modules/kargoBidAdapter_spec.js
Labels: bugfix

#8813 Zeta ssp adapter: added multiimp request support
  modules/zeta_global_sspBidAdapter.js
  test/spec/modules/zeta_global_sspBidAdapter_spec.js
Labels: maintenance

#8754 Datawrkz Bid Adapter: initial adapter release
  modules/datawrkzBidAdapter.js
  modules/datawrkzBidAdapter.md
  test/spec/modules/datawrkzBidAdapter_spec.js
Labels: feature

#8834 Vidazoo Bid Adapter: Cookie sync improvements
  modules/vidazooBidAdapter.js
  test/spec/modules/vidazooBidAdapter_spec.js
Labels: maintenance

#8793 consumable Bid Adapter: add video support
  modules/consumableBidAdapter.js
  test/spec/modules/consumableBidAdapter_spec.js
Labels: feature

#8848 Lasso Bid Adapter: update version and request credential setting
  modules/lassoBidAdapter.js
Labels: maintenance

#8785 Prebid core: fix bug with some native assets being lost from ortb native responses
  src/native.js
  test/spec/native_spec.js
Labels: bugfix

#8829 Browsi RTD Module: add support for page view billable events
  modules/browsiRtdProvider.js
  test/spec/modules/browsiRtdProvider_spec.js
Labels: maintenance

#8849 Readme: remove dead dev dependency and maintenance badges
  README.md
Labels: docs, maintenance

#8768 Adriver Bid and Id Modules: buyerid bug fix
  modules/adriverBidAdapter.js
  modules/adriverIdSystem.js
  test/spec/modules/adriverBidAdapter_spec.js
  test/spec/modules/adriverIdSystem_spec.js
Labels: bugfix

#8838 Prebid Core: Native Privacy Link Solution
  src/native.js
  test/spec/native_spec.js
Labels: bugfix

#8842 Criteo Bid Adapter: add support for banner+native multiformat ad unit
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: feature, LGTM

#8792 Ras Bid Adapter: support for SlotSequence parameter
  modules/rasBidAdapter.js
  modules/rasBidAdapter.md
  test/spec/modules/rasBidAdapter_spec.js
Labels: maintenance

#8827 Improve Digital adapter: refactor code to align with latest RAZR creative tags
  modules/improvedigitalBidAdapter.js
  src/adloader.js
  test/spec/modules/improvedigitalBidAdapter_spec.js
Labels: maintenance

#8860 Sonobi Bid Adapter: update GVLID
  modules/sonobiBidAdapter.js
Labels: maintenance

#8862 dgkeyword RTD provider: fix tests causing ID5 test failures
  modules/dgkeywordRtdProvider.js
  test/spec/modules/dgkeywordRtdProvider_spec.js
Labels: bugfix

#8784 ID5 User ID Module - refactor fetch and add server-side config options
  modules/id5IdSystem.js
  modules/id5IdSystem.md
  test/spec/modules/id5IdSystem_spec.js
Labels: needs review, maintenance

#8855 PBJs Core (adserver.js) : remove unused code
  src/adserver.js
Labels: maintenance

#8847 Displayio Bid Adapter: custom render; fix eids payload
  modules/displayioBidAdapter.js
  test/spec/modules/displayioBidAdapter_spec.js
Labels: bugfix

#8872 Adtelligent Bid Adapter: add VidCrunch LLC alias
  modules/adtelligentBidAdapter.js
  test/spec/modules/adtelligentBidAdapter_spec.js
Labels: maintenance

#8774 bidWatch Analytics Adapter : limit bandwidth usage + refactory
  modules/bidwatchAnalyticsAdapter.js
  test/spec/modules/bidwatchAnalyticsAdapter_spec.js
Labels: maintenance

#8883 Consumable Bid Adapter: remove impressionUrl
  modules/consumableBidAdapter.js
Labels: maintenance

#8861 Prebid Core: Add ttl buffer to videoCache.js
  src/videoCache.js
  test/spec/videoCache_spec.js
Labels: maintenance

#8870 BetweenBidAdapter: default value for the cur parameter
  modules/betweenBidAdapter.js
  test/spec/modules/betweenBidAdapter_spec.js
Labels: maintenance

#8856 Mediago Bid Adapter: initial adapter release
  modules/mediagoBidAdapter.js
  modules/mediagoBidAdapter.md
  test/spec/modules/mediagoBidAdapter_spec.js
Labels: feature

#8896 Tappx Bid Adapter: fix host info http regex
  modules/tappxBidAdapter.js
Labels: maintenance

#8864 Prebid core: optimize getRefererInfo to run only once per page
  src/refererDetection.js
  test/spec/modules/enrichmentFpdModule_spec.js
  test/spec/modules/fpdModule_spec.js
Labels: feature

#8765 Prebid Core: Batch Video Cache Requests feature
  src/auction.js
  test/spec/videoCache_spec.js
Labels: feature

#8854 AcuityAds Bid Adapter: initial adapter release
  modules/acuityAdsBidAdapter.js
  modules/acuityAdsBidAdapter.md
  test/spec/modules/acuityAdsBidAdapter_spec.js
Labels: feature, LGTM

#8902 ImRtdProvider: add segment max
  modules/imRtdProvider.js
  modules/imRtdProvider.md
  test/spec/modules/imRtdProvider_spec.js
Labels: maintenance

#8340 Lifestreet Bid adapter: initial release
  modules/lifestreetBidAdapter.js
  test/spec/modules/lifestreetBidAdapter_spec.js
Labels: feature

#8877 TrustPid module: Refactor - update acronyms handling
  modules/trustpidSystem.js
  modules/trustpidSystem.md
  modules/userId/userId.md
  test/spec/modules/trustpidSystem_spec.js
Labels: maintenance

#8900 Triplelift Bid Adapter: ingest all userIds
  modules/tripleliftBidAdapter.js
  test/spec/modules/tripleliftBidAdapter_spec.js
Labels: maintenance

#8745 BeOp Bid Adapter: Fix tracker on BidWon and BidTimeout notice
  modules/beopBidAdapter.js
  test/spec/modules/beopBidAdapter_spec.js
Labels: bugfix

#8899 consumableBidAdapter: add price floor support
  modules/consumableBidAdapter.js
  test/spec/modules/consumableBidAdapter_spec.js
Labels: maintenance

#8866 Prebid core: optimize sizeMapping to reduce computation when not in use
  src/sizeMapping.js
Labels: feature, needs 2nd review

#8892 IX Bid Adapter: Add banner pos support
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance

#8881 Permutive RTD Module: merge external submodule params
  modules/permutiveRtdProvider.js
  test/spec/modules/permutiveRtdProvider_spec.js
Labels: bugfix

#8921 Seedtag Bid Adapter: update documentation
  modules/seedtagBidAdapter.md
Labels: maintenance

#8915 Prebid core: accept custom Promise constructor
  src/utils/promise.js
Labels: needs 2nd review, maintenance

#8919 Pubmatic Bid Adapter: add tmax value on bidder timeout
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: maintenance

#8918 RTB House Bid Adapter: Add SDA support based on ortb2 object
  modules/rtbhouseBidAdapter.js
Labels: maintenance

#8882 Prebid Core: rewording PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: needs 2nd review, maintenance

#8924 Insticator Bid adapter: fix User ID cookie expiration time
  modules/insticatorBidAdapter.js
Labels: maintenance

#8922 Various files: fix LGTM semi-colon insertion
  modules/adriverBidAdapter.js
  modules/datawrkzBidAdapter.js
  modules/id5IdSystem.js
Labels: maintenance

#8851 Mabidder Bid Adapter: initial adapter release
  modules/mabidderBidAdapter.js
  modules/mabidderBidAdapter.md
  test/spec/modules/mabidderBidAdapter_spec.js
Labels: feature

#8906 IX Bid Adapter: deprecate detecMissingSize config
  modules/ixBidAdapter.js
  modules/ixBidAdapter.md
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance

#8926 Browsi RTD Module: billable events bugfix
  modules/browsiRtdProvider.js
Labels: bugfix

#8930 PBjs Core: clear currency conversionCache after rate file has been downloaded
  modules/currency.js
  test/spec/modules/currency_spec.js
Labels: bugfix

#8932 yahoossp bid adapter: Update outstream renderer CDN location update
  modules/yahoosspBidAdapter.js
Labels: maintenance

#8905 PBjs Core (Native): ortb tracker support
  src/native.js
  test/spec/native_spec.js
Labels: feature

#8890 Appnexus Bid Adapter: update logic of native viewability script
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
  test/spec/modules/big-richmediaBidAdapter_spec.js
Labels: bugfix

#8833 PBjs Core: allow video cacheKey for outstream
  src/auction.js
  src/video.js
Labels: feature, needs docs

#8685 OneKey Id Submodule: initial release
  modules/.submodules.json
  modules/oneKeyIdSystem.js
  modules/oneKeyIdSystem.md
  modules/userId/eids.js
  test/spec/modules/oneKeyIdSystem_spec.js
Labels: feature, needs docs

#8686 OneKey RTD Module: initial release
  modules/.submodules.json
  modules/oneKeyRtdProvider.js
  modules/oneKeyRtdProvider.md
  test/spec/modules/oneKeyRtdProvider_spec.js
Labels: feature, needs docs
