Repository prebid/Prebid.js, pull requests merged in 2022-02, with the labels that each got.

#7964 DSPx Bid Adapter: add pbver, mediatypes, pcode, auto ad format
  modules/dspxBidAdapter.js
  modules/dspxBidAdapter.md
  test/spec/modules/dspxBidAdapter_spec.js
Labels: maintenance

#7993 add a configurable "bidCacheFilterFunction"
  src/targeting.js
  test/fixtures/fixtures.js
  test/spec/unit/core/targeting_spec.js
Labels: feature

#7996 Ogury Bid Adapter: fixing value for 'at' ad request field for first price model
  modules/oguryBidAdapter.js
  test/spec/modules/oguryBidAdapter_spec.js
Labels: bugfix

#7970 Mediasquare Bid Adapter: add gvlid
  modules/mediasquareBidAdapter.js
Labels: maintenance

#7933 Prebid Core: creative comment injection spot reverted
  src/prebid.js
  test/spec/unit/pbjs_api_spec.js
Labels: bugfix

#7885 PBS Adapter: allow "extra" bids that are not tied to any request
  modules/adpod.js
  modules/currency.js
  modules/mass.js
  modules/medianetAnalyticsAdapter.js
  modules/prebidServerBidAdapter/index.js
  modules/priceFloors.js
  modules/sizeMappingV2.js
  modules/telariaBidAdapter.js
  src/adapterManager.js
  src/adapters/bidderFactory.js
  src/auction.js
  src/auctionIndex.js
  src/auctionManager.js
  src/bidfactory.js
  src/native.js
  src/utils.js
  src/video.js
  src/videoCache.js
  test/helpers/indexStub.js
  test/spec/auctionmanager_spec.js
  test/spec/modules/adpod_spec.js
  test/spec/modules/currency_spec.js
  test/spec/modules/mass_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/priceFloors_spec.js
  test/spec/modules/telariaBidAdapter_spec.js
  test/spec/native_spec.js
  test/spec/unit/core/adapterManager_spec.js
  test/spec/unit/core/auctionIndex_spec.js
  test/spec/unit/core/bidderFactory_spec.js
  test/spec/unit/pbjs_api_spec.js
  test/spec/videoCache_spec.js
  test/spec/video_spec.js
Labels: feature

#7999 CircleCI config: separate 5.20.x-legacy dependencies cache
  .circleci/config.yml
Labels: bugfix

#7902 Adnuntius rtd provider: initial release
  modules/adnuntiusRtdProvider.js
  modules/adnuntiusRtdProvider.md
  test/spec/modules/adnuntiusRtdProvider_spec.js
Labels: feature, needs review

#7991 Prebid core: isolate global and bidder-specific configuration
  src/utils.js
  test/spec/config_spec.js
Labels: bugfix

#8000 Malltv bid adapter: added gdpr applies and gdpr consent to bid request parameters
  modules/malltvBidAdapter.js
Labels: maintenance

#7813 TheMediaGrid: RTD module support with mergeDeep of user.data
  modules/gridBidAdapter.js
  test/spec/modules/gridBidAdapter_spec.js
Labels: maintenance

#7997 Prebid Targeting: add a configurable "bidCacheFilterFunction" (#7993)
  src/targeting.js
  test/fixtures/fixtures.js
  test/spec/unit/core/targeting_spec.js
Labels: feature

#8010 Revert "Bump log4js from 6.3.0 to 6.4.1"
  package-lock.json
Labels: maintenance

#8002 RTB House Bid Adapter: Add gvlid
  modules/rtbhouseBidAdapter.js
Labels: maintenance

#8005 AdYouLike Bid Adapter: add gvlid
  modules/adyoulikeBidAdapter.js
  test/spec/modules/adyoulikeBidAdapter_spec.js
Labels: maintenance

#8009 Mediasquare Bid Adapter: add floor module support
  modules/mediasquareBidAdapter.js
  test/spec/modules/mediasquareBidAdapter_spec.js
Labels: maintenance

#7989 Prebid Src: pass requestObject to BEFORE_BIDDER_REQUEST event
  src/adapters/bidderFactory.js
Labels: feature, needs 2nd review

#8012 IX Bid Adapter: added trustpid.com support and removed a few user providers
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance

#8020 IQzone Bid Adapter: add new param
  modules/iqzoneBidAdapter.js
  modules/iqzoneBidAdapter.md
  test/spec/modules/iqzoneBidAdapter_spec.js
Labels: maintenance

#7855 Kubient Bid Adapter: support coppa, update sync URL
  modules/kubientBidAdapter.js
  test/spec/modules/kubientBidAdapter_spec.js
Labels: maintenance

#8017 Rubicon Bid Adapter: fix placement issue & update renderer
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: bugfix

#8025 Price Floor Module: retrieve matching bid request
  modules/priceFloors.js
Labels: bugfix

#8027 Price floors module: expand on bug fix with custom priceFloor schemas tests
  modules/priceFloors.js
  test/spec/modules/priceFloors_spec.js
Labels: bugfix

#7965 VidoomyAdapter: add schain and bidfloor to vidoomy adapter
  modules/vidoomyBidAdapter.js
  modules/vidoomyBidAdapter.md
  test/spec/modules/vidoomyBidAdapter_spec.js
Labels: needs update, maintenance

#8013 MediaKeys Bid Adapter: fix for first party data `geo` usage
  modules/mediakeysBidAdapter.js
  test/spec/modules/mediakeysBidAdapter_spec.js
Labels: bugfix

#8018 RichaudienceBidAdapter: Change currency floor module
  modules/richaudienceBidAdapter.js
Labels: bugfix

#8034 Adkernel Bid Adapter: add motionspots alias
  modules/adkernelBidAdapter.js
Labels: maintenance

#7969 Prebid Core: add filename to pbjsGlobals module append
  plugins/pbjsGlobals.js
Labels: bugfix

#7994 Novatiq ID module: sharedID changes
  modules/novatiqIdSystem.js
  modules/novatiqIdSystem.md
  test/spec/modules/novatiqIdSystem_spec.js
Labels: maintenance

#8008 Kubient Bid Adapter: update if bidfloor is zero
  modules/kubientBidAdapter.js
  test/spec/modules/kubientBidAdapter_spec.js
Labels: maintenance

#8030 Automatad Bid Adapter: register on timeout event and endpoint changes
  modules/automatadBidAdapter.js
  test/spec/modules/automatadBidAdapter_spec.js
Labels: maintenance

#8026 Nexx360 Bid Adapter: add new bid adapter
  modules/nexx360BidAdapter.js
  modules/nexx360BidAdapter.md
  test/spec/modules/nexx360BidAdapter_spec.js
Labels: feature

#8065 Build system: specify corejs version for babel
  .babelrc.js
Labels: bugfix

#8055 Option to send floors/adunitcode in the Google Analytics Adapter
  modules/googleAnalyticsAdapter.js
  modules/googleAnalyticsAdapter.md
Labels: feature, needs review

#8039 TheMediaGrid Bid Adapter: support for Interstitial flag
  modules/gridBidAdapter.js
  test/spec/modules/gridBidAdapter_spec.js
Labels: needs update

#8042 TrustX Bid Adapter: added instl support
  modules/trustxBidAdapter.js
  test/spec/modules/trustxBidAdapter_spec.js
Labels: maintenance

#8070 Readme : update built files & add gulp-serve-and-test
  README.md
Labels: maintenance, documentation

#8051 CircleCI config: use "browsers" image
  .circleci/config.yml
Labels: build process, needs 2nd review, maintenance

#8033 Big-Richmedia Bid Adapter: initial release
  modules/big-richmediaBidAdapter.js
  modules/big-richmediaBidAdapter.md
  test/spec/modules/big-richmediaBidAdapter_spec.js
Labels: feature

#8075 BizzClick Bid Adapter: fix schain settings
  modules/bizzclickBidAdapter.js
  test/spec/modules/bizzclickBidAdapter_spec.js
Labels: bugfix

#8061 RichaudienceBidAdapter: Add demand type Skin
  modules/richaudienceBidAdapter.js
Labels: feature, needs review

#7801 Prebid core & PBS Adapter: debugging tools to intercept bid requests and mock their response
  modules/debugging/bidInterceptor.js
  modules/debugging/index.js
  modules/debugging/pbsInterceptor.js
  modules/prebidServerBidAdapter/index.js
  src/adapters/bidderFactory.js
  src/debugging.js
  src/utils.js
  test/spec/debugging_spec.js
  test/spec/modules/debugging_mod_spec.js
  test/spec/utils_spec.js
Labels: feature

#8059 IX Bid Adapter: GPID, dfp_ad_unit_code, pageUrl & bid renderer updates
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: feature, needs review

#8078 AdYouLike Bid Adapter: fix icon url issue for Native
  modules/adyoulikeBidAdapter.js
  test/spec/modules/adyoulikeBidAdapter_spec.js
Labels: bugfix

#8019 Engageya Bid Adapter: wider image validation
  modules/engageyaBidAdapter.js
  modules/engageyaBidAdapter.md
  test/spec/modules/engageyaBidAdapter_spec.js
Labels: maintenance

#8068 Limelight Digital Bid Adapter: Prevent duplicate iframe and pixel syncs
  modules/limelightDigitalBidAdapter.js
  modules/limelightDigitalBidAdapter.md
  test/spec/modules/limelightDigitalBidAdapter_spec.js
Labels: LGTM, maintenance

#8085 Relaido Bid Adapter: change to get the renderer URL for each response
  modules/relaidoBidAdapter.js
  test/spec/modules/relaidoBidAdapter_spec.js
Labels: maintenance

#8088 ZetaSspBidAdapter: provide device.language
  modules/zeta_global_sspBidAdapter.js
  test/spec/modules/zeta_global_sspBidAdapter_spec.js
Labels: maintenance

#8043 Prebid Core: Adding support for a global return of consent metadata.
  src/adapterManager.js
  src/prebid.js
  test/spec/modules/consentManagementUsp_spec.js
  test/spec/modules/consentManagement_spec.js
Labels: LGTM

#8095 Pubxai Bid Adapter: added extra field to the winning bid object.
  modules/pubxaiAnalyticsAdapter.js
  test/spec/modules/pubxaiAnalyticsAdapter_spec.js
Labels: maintenance

#8072 IQZone Bidder: add user sync
  modules/iqzoneBidAdapter.js
  test/spec/modules/iqzoneBidAdapter_spec.js
Labels: maintenance

#8044 orbidder Bid Adapter: add unit test for price floor module
  test/spec/modules/orbidderBidAdapter_spec.js
Labels: maintenance

#8098 Zeta Global Ssp Adapter: remove devicetype
  modules/zeta_global_sspBidAdapter.js
Labels: maintenance

#8104 33across, Smaato, OneVideo, & Sharethrough Bid Adapters: Add GVLID
  modules/33acrossBidAdapter.js
  modules/oneVideoBidAdapter.js
  modules/sharethroughBidAdapter.js
  modules/smaatoBidAdapter.js
Labels: maintenance

#8069 Medianet Analytics Adapter: Multiple bidResponse with same requestId fix
  modules/medianetAnalyticsAdapter.js
  test/spec/modules/medianetAnalyticsAdapter_spec.js
Labels: bugfix

#8109 RhythmOne and Unruly Bid Adapter: add gvlid
  modules/rhythmoneBidAdapter.js
  modules/unrulyBidAdapter.js
Labels: maintenance

#8108 Marsmedia adapter: Remove bidderCode from Response
  modules/marsmediaBidAdapter.js
Labels: bugfix

#8105 NextRoll Bid Adapter: update privacy link and icon
  modules/nextrollBidAdapter.js
  test/spec/modules/nextrollBidAdapter_spec.js
Labels: maintenance

#8111 Criteo Bid Adapter: read mediaTypes.banner.sizes instead of bidRequest.Sizes
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: bugfix

#8110 VIS.X: fix bug with onTimeout function arguments
  modules/visxBidAdapter.js
  test/spec/modules/visxBidAdapter_spec.js
Labels: bugfix

#8057 Adriver id system
  modules/adriverBidAdapter.js
  modules/adriverIdSystem.js
  modules/adriverIdSystem.md
  test/spec/modules/adriverBidAdapter_spec.js
  test/spec/modules/adriverIdSystem_spec.js
Labels: feature, needs review, needs docs

#8015 appnexus bid adapter - add support for pubProvidedId userId
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: feature
