Repository prebid/Prebid.js, pull requests merged in 2022-06, with the labels that each got.

#8235 Prebid 7: Remove stored auction response
  modules/prebidServerBidAdapter/index.js
  modules/rubiconBidAdapter.js
  src/adapterManager.js
  test/spec/auctionmanager_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/rubiconBidAdapter_spec.js
  test/spec/videoCache_spec.js
Labels: needs 2nd review, maintenance, major, 7.0 API Change

#8506 Media.net RTD module: use internal prebid method for loading external script
  modules/medianetRtdProvider.js
  src/adloader.js
  test/spec/modules/medianetRtdProvider_spec.js
Labels: maintenance

#8491 Criteo - Update Publisher Tag version referenced by prebid adapter
  modules/criteoBidAdapter.js
Labels: maintenance

#8449 Kargo Bid Adapter: onTimeout Support
  modules/kargoBidAdapter.js
  test/spec/modules/kargoBidAdapter_spec.js
Labels: maintenance

#8509 Synacormedia Bid Adapter: Add GPID and Prebid Ad Slot support
  modules/synacormediaBidAdapter.js
  test/spec/modules/synacormediaBidAdapter_spec.js
Labels: maintenance

#8452 Insticator Bid adapter: Adds Support for Video
  modules/insticatorBidAdapter.js
  test/spec/modules/insticatorBidAdapter_spec.js
Labels: feature

#8448 Gdpr Enforcement module and sharedId/pubCommonId modules: vendor consent should not be enforced for first-party-id modules
  modules/gdprEnforcement.js
  modules/ixBidAdapter.js
  modules/pubCommonId.js
  modules/sharedIdSystem.js
  src/storageManager.js
  test/spec/modules/gdprEnforcement_spec.js
Labels: needs 2nd review, bugfix

#8229 Prebid 7: Allow USP module to work without explicit configuration
  modules/consentManagement.js
  modules/consentManagementUsp.js
  test/spec/modules/consentManagementUsp_spec.js
Labels: major, 7.0 API Change

#8517 PubMatic Analytics Adapter : Added support for logging multiple bids
  modules/pubmaticAnalyticsAdapter.js
  test/spec/modules/pubmaticAnalyticsAdapter_spec.js
Labels: maintenance

#8518 AdOcean bid adapter: support for SupplyChain object
  modules/adoceanBidAdapter.js
  test/spec/modules/adoceanBidAdapter_spec.js
Labels: maintenance

#8513 Prebid.js 7: update pbsBidAdapter to use imp.ext.prebid.bidder.BIDDER
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: maintenance, 7.0 API Change

#8529 IX Bid Adapter: Change to a new endpoint
  modules/ixBidAdapter.js
  modules/ixBidAdapter.md
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance

#8356 Prebid 7: remove support for TCFv1
  modules/apacdexBidAdapter.js
  modules/appnexusBidAdapter.js
  modules/consentManagement.js
  modules/craftBidAdapter.js
  modules/gdprEnforcement.js
  modules/goldbachBidAdapter.js
  modules/improvedigitalBidAdapter.js
  modules/inskinBidAdapter.js
  modules/kubientBidAdapter.js
  modules/mediafuseBidAdapter.js
  modules/nobidBidAdapter.js
  modules/optoutBidAdapter.js
  modules/pixfutureBidAdapter.js
  modules/prebidServerBidAdapter/index.js
  modules/proxistoreBidAdapter.js
  modules/quantcastBidAdapter.js
  modules/quantcastIdSystem.js
  modules/sspBCBidAdapter.js
  modules/teadsBidAdapter.js
  modules/ucfunnelBidAdapter.js
  modules/userId/index.js
  modules/winrBidAdapter.js
  modules/yahoosspBidAdapter.js
  src/utils/gpdr.js
  test/spec/modules/consentManagement_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/quantcastBidAdapter_spec.js
  test/spec/modules/teadsBidAdapter_spec.js
  test/spec/modules/userId_spec.js
  test/spec/modules/yahoosspBidAdapter_spec.js
Labels: major, 7.0 API Change

#8514 AdxPremium analytics adapter: do not generate network activity after tests have completed
  karma.conf.maker.js
  modules/adxpremiumAnalyticsAdapter.js
  src/AnalyticsAdapter.js
  test/spec/AnalyticsAdapter_spec.js
Labels: maintenance

#8542 Triplelift Bid Adapter: get opeCloud data from local storage
  modules/tripleliftBidAdapter.js
  test/spec/modules/tripleliftBidAdapter_spec.js
Labels: feature

#8507 AdUp Technology bid adapter: add support for floor prices
  modules/aduptechBidAdapter.js
  test/spec/modules/aduptechBidAdapter_spec.js
Labels: maintenance

#8544 Cwire Bid Adapter: fix cwcreative parameter conversion
  modules/cwireBidAdapter.js
  modules/cwireBidAdapter.md
  test/spec/modules/cwireBidAdapter_spec.js
Labels: bugfix

#8328 TrafficGate Bid Adapter: add new bid adapter
  modules/trafficgateBidAdapter.js
  modules/trafficgateBidAdapter.md
  test/spec/modules/trafficgateBidAdapter_spec.js
Labels: feature

#8413 Piano DMP Analytics Adapter: add new analytics adapter
  modules/pianoDmpAnalyticcsAdapter.md
  modules/pianoDmpAnalyticsAdapter.js
  test/spec/modules/pianoDmpAnalyticsAdapter_spec.js
Labels: feature

#8526 Synacormedia bid adapter: add tmax to requests based upon provided timeouts
  modules/synacormediaBidAdapter.js
  test/spec/modules/synacormediaBidAdapter_spec.js
Labels: maintenance

#8524 PBjs Core Consent management: use last consent provided by CMP on timeout
  modules/consentManagement.js
  test/spec/modules/consentManagement_spec.js
Labels: bugfix

#8527 Prebid Core: Library support
  gulpHelpers.js
  gulpfile.js
  libraries/getOrigin/index.js
  modules/.submodules.json
  modules/ooloAnalyticsAdapter.js
  modules/resetdigitalBidAdapter.js
  modules/rtbhouseBidAdapter.js
  src/utils.js
  webpack.conf.js
Labels: feature

#8560 Parrable ID system: fix spurious test failures
  test/spec/modules/parrableIdSystem_spec.js
Labels: bugfix

#8555 Criteo Id System: add support for user sync pixels
  modules/criteoIdSystem.js
  test/spec/modules/criteoIdSystem_spec.js
Labels: maintenance

#8419 Blueconic RTD submodule: initial release
  integrationExamples/gpt/blueconicRtdProvider_example.html
  modules/.submodules.json
  modules/blueconicRtdProvider.js
  modules/blueconicRtdProvider.md
  test/spec/modules/blueconicRtdProvider_spec.js
Labels: feature, taxonomy

#8531 IDX Bid Adaper: added new bid adapter
  modules/idxBidAdapter.js
  modules/idxBidAdapter.md
  test/spec/modules/idxBidAdapter_spec.js
Labels: feature

#8505 Alkimi bid adapter: added supply chain, GDPR TCF, COPPA, & USP support
  modules/alkimiBidAdapter.js
  test/spec/modules/alkimiBidAdapter_spec.js
Labels: maintenance

#8547 Missena Bid Adapter: added getUserSyncs and testmode
  modules/missenaBidAdapter.js
  test/spec/modules/missenaBidAdapter_spec.js
Labels: maintenance

#8219 Prebid core & PBS adapter: Feature tags and optional compilation of native support
  .eslintrc.js
  features.json
  gulpHelpers.js
  gulpfile.js
  karma.conf.maker.js
  karmaRunner.js
  modules/prebidServerBidAdapter/index.js
  modules/sizeMappingV2.js
  plugins/pbjsGlobals.js
  src/adapterManager.js
  src/adapters/bidderFactory.js
  src/auction.js
  src/prebid.js
  src/secureCreatives.js
  src/targeting.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/sizeMappingV2_spec.js
  test/spec/unit/core/adapterManager_spec.js
  test/spec/unit/core/bidderFactory_spec.js
  test/spec/unit/core/targeting_spec.js
  test/spec/unit/pbjs_api_spec.js
  test/spec/unit/secureCreatives_spec.js
  webpack.conf.js
Labels: feature

#8504 Yieldlab Bid Adapter: support for ad unit sizes
  README.md
  modules/yieldlabBidAdapter.js
  test/spec/modules/yieldlabBidAdapter_spec.js
Labels: maintenance

#8578 adQuery bid adapter: edit to local id generation function
  modules/adqueryBidAdapter.js
Labels: bugfix

#8435 Tnc id module: initial release
  modules/.submodules.json
  modules/tncIdSystem.js
  modules/tncIdSystem.md
  modules/userId/eids.js
  modules/userId/eids.md
  modules/userId/userId.md
  src/adloader.js
  test/spec/modules/eids_spec.js
  test/spec/modules/tncIdSystem_spec.js
  test/spec/modules/userId_spec.js
Labels: feature

#8575 Prebid Core: Set permissions for GitHub actions
  .github/workflows/issue_tracker.yml
  .github/workflows/release-drafter.yml
Labels: maintenance

#8583 Prebid Core: Included githubactions in the dependabot config
  .github/dependabot.yml
Labels: maintenance

#8586 Update README to mention `gulp bundle`
  README.md
Labels: maintenance

#8581 Sovrn: Update adapter to remove tpids and how it gets sizes
  modules/sovrnBidAdapter.js
  test/spec/modules/sovrnBidAdapter_spec.js
Labels: needs review, maintenance

#8570 33accross Bid Adapter: add 33across_mgni alias
  modules/33acrossBidAdapter.js
  test/spec/modules/33acrossBidAdapter_spec.js
Labels: maintenance

#8552 Gumgum Bid Adapter: prebid changes to support jp products
  modules/gumgumBidAdapter.js
  modules/gumgumBidAdapter.md
  test/spec/modules/gumgumBidAdapter_spec.js
Labels: maintenance

#8585 FPD module: fix bug with fpd enrichment / validation not running on requestBids
  modules/fpdModule/index.js
  test/spec/modules/fpdModule_spec.js
Labels: bugfix

#8590 Yieldlab Bid Adapter: pass extId to bid request
  modules/yieldlabBidAdapter.js
  test/spec/modules/yieldlabBidAdapter_spec.js
Labels: maintenance

#8521 Yieldmo Bid Adapter: update adapter to perform user synchronization
  modules/yieldmoBidAdapter.js
  test/spec/modules/yieldmoBidAdapter_spec.js
Labels: LGTM, maintenance

#8591 Prebid Core: Implement transaction id on imp.ext.tid
  src/prebid.js
  test/spec/unit/pbjs_api_spec.js
Labels: feature, needs 2nd review

#8519 Dianomi Bid adapter: add new bid adapter
  modules/dianomiBidAdapter.js
  modules/dianomiBidAdapter.md
  test/spec/modules/dianomiBidAdapter_spec.js
Labels: feature, LGTM

#8559 cpex Id System: Fixes and cleanup, adds eids, changes cookie name
  modules/cpexIdSystem.js
  modules/userId/eids.js
  test/spec/modules/cpexIdSystem_spec.js
  test/spec/modules/eids_spec.js
Labels: maintenance

#8604 Adkernel Bid Adapter: add Sonic Twist alias
  modules/adkernelBidAdapter.js
Labels: maintenance

#8607 Medianet Bidder Adpater: Support for FPD, transactionId and url changes
  modules/medianetBidAdapter.js
  test/spec/modules/medianetBidAdapter_spec.js
Labels: maintenance

#8592 Build system: do not use `require.resolve` for resolving library file paths
  gulpHelpers.js
Labels: maintenance

#8516 Readpeak Bid Adapter: Add onBidWon Callback
  modules/readpeakBidAdapter.js
  test/spec/modules/readpeakBidAdapter_spec.js
Labels: bugfix

#8494 Shinez Bid Adapter: update adapter to comply with latest Prebid version
  modules/shinezBidAdapter.js
  modules/shinezBidAdapter.md
  test/spec/modules/shinezBidAdapter_spec.js
Labels: feature

#8533 IX Bid Adapter: Added Support for Native MediaTypes
  modules/ixBidAdapter.js
  modules/ixBidAdapter.md
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance

#8600 Insticator Bid adapter: Add video placement param
  modules/insticatorBidAdapter.js
  test/spec/modules/insticatorBidAdapter_spec.js
Labels: maintenance

#8620 Ventes Bid Adapter: stage Url to production
  modules/ventesBidAdapter.js
  modules/ventesBidAdapter.md
  test/spec/modules/ventesBidAdapter_spec.js
Labels: bugfix

#8611 Missena bidAdapter: pass gdpr data to sync frame
  modules/missenaBidAdapter.js
  test/spec/modules/missenaBidAdapter_spec.js
Labels: bugfix

#8616 Kargo Bid Adapter: fixing adm for legacy vast support
  modules/kargoBidAdapter.js
  test/spec/modules/kargoBidAdapter_spec.js
Labels: needs update, maintenance

#8612 Vrtcal Bid Adapter: added GDPR, CCPA, COPPA, and timeout passing support
  modules/vrtcalBidAdapter.js
  test/spec/modules/vrtcalBidAdapter_spec.js
Labels: maintenance

#8582 Debugging module: multiple bugfixes
  gulpfile.js
  modules/debugging/bidInterceptor.js
  modules/debugging/index.js
  plugins/pbjsGlobals.js
  test/spec/modules/debugging_mod_spec.js
  webpack.conf.js
Labels: bugfix

#8627 Relaido Bid Adapter: Add support for bids[].params.video.playerSize
  modules/relaidoBidAdapter.js
  test/spec/modules/relaidoBidAdapter_spec.js
Labels: maintenance
