Repository prebid/Prebid.js, pull requests merged in 2022-01, with the labels that each got.

#7901 Criteo Bid Adapter: update version
  modules/criteoBidAdapter.js
Labels: maintenance

#7897 Compass Adapter: update bid params
  modules/compassBidAdapter.js
  test/spec/modules/compassBidAdapter_spec.js
Labels: maintenance

#7877 RTD module: set targeting on onAuctionEnd event
  modules/rtdModule/index.js
  test/spec/modules/realTimeDataModule_spec.js
Labels: bugfix

#7899 Improve Digital bid adapter: added support for cat and genre
  modules/improvedigitalBidAdapter.js
  test/spec/modules/improvedigitalBidAdapter_spec.js
Labels: maintenance

#7776 Welect Bid Adapter: update prebid compliance and add adapter back to master
  modules/welectBidAdapter.js
  test/spec/modules/welectBidAdapter_spec.js
Labels: maintenance

#7861 Prebid Core: async submodule loading
  src/hook.js
Labels: maintenance

#7903 Teads bid adapter: switch GPID logic to the new imp.ext.gpid field
  modules/teadsBidAdapter.js
  test/spec/modules/teadsBidAdapter_spec.js
Labels: maintenance

#7833 Glimpse Bid Adapter: Capture publisher-supplied first party data
  modules/glimpseBidAdapter.js
  test/spec/modules/glimpseBidAdapter_spec.js
Labels: maintenance

#7874 Prebid Core: creative comment injection spot reverted
  src/prebid.js
  test/spec/unit/pbjs_api_spec.js
Labels: needs 2nd review, maintenance

#7884 Adman Bid Adapter: update getUserSyncs()
  modules/admanBidAdapter.js
  test/spec/modules/admanBidAdapter_spec.js
Labels: maintenance

#7904 NextMillennium Bid Adapter: refresh_count variable moved to into ext
  modules/nextMillenniumBidAdapter.js
  test/spec/modules/nextMillenniumBidAdapter_spec.js
Labels: maintenance

#7905 Tappx Bid Adapter: fix adtypes bug
  modules/tappxBidAdapter.js
  test/spec/modules/tappxBidAdapter_spec.js
Labels: bugfix

#7910 Kargo Bid Adapter: Fix issue with double-array for advertiserDomains
  modules/kargoBidAdapter.js
  test/spec/modules/kargoBidAdapter_spec.js
Labels: bugfix

#7907 Colossus Bid Adapter: update bid params
  modules/colossussspBidAdapter.js
  modules/colossussspBidAdapter.md
  test/spec/modules/colossussspBidAdapter_spec.js
Labels: maintenance

#7890 Prebid Core: fix typeerror from reading properties of undefined ('getSlotElementId')
  src/secureCreatives.js
Labels: bugfix

#7913 Gumgum Bid Adapter: fix failing test
  modules/gumgumBidAdapter.js
Labels: bugfix

#7857 Sharethrough Bid Adapter: Add First Party Data and Outstream Support
  modules/sharethroughBidAdapter.js
  test/spec/modules/sharethroughBidAdapter_spec.js
Labels: maintenance

#7919 seeding Alliance Bid Adapter: no bids and netRevenue bugfix
  modules/seedingAllianceBidAdapter.js
Labels: needs review, bugfix

#7920 AdHash Bidder Adapter: update root
  modules/adhashBidAdapter.js
  test/spec/modules/adhashBidAdapter_spec.js
Labels: maintenance

#7682 Synacormedia bid adapter: add support for floors module
  modules/synacormediaBidAdapter.js
  test/spec/modules/synacormediaBidAdapter_spec.js
Labels: feature, needs review, maintenance

#7922 RTD module: log submodules on init
  modules/rtdModule/index.js
Labels: feature

#7911 Integration examples: update the AMP creative
  integrationExamples/gpt/amp/creative.html
Labels: needs review, maintenance

#7643 Generic viewability module: add new module
  modules/viewability.js
  modules/viewability.md
  test/spec/modules/viewability_spec.js
Labels: feature

#7930 Consumable Bid Adapter: change maintainer
  modules/consumableBidAdapter.md
Labels: maintenance

#7862 RTD module: allow submodules to setBidRequestData without `waitForIt`
  modules/rtdModule/index.js
  test/spec/modules/realTimeDataModule_spec.js
Labels: bugfix

#7816 Pilotx Bid Adapter: add new bid adapter
  modules/pilotxBidAdapter.js
  modules/pilotxBidAdapter.md
  test/spec/modules/pilotxBidAdapter_spec.js
Labels: feature

#7908 Rubicon Analytics: Handle bad advertiserDomain scenarios
  modules/rubiconAnalyticsAdapter.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
Labels: maintenance

#7934 Gnet Bid Adapter: Change endpoint and add parameter
  modules/gnetBidAdapter.js
  modules/gnetBidAdapter.md
  test/spec/modules/gnetBidAdapter_spec.js
Labels: maintenance

#7886 JwPlayer RTD module: Write to oRTB content segments
  modules/jwplayerRtdProvider.js
  modules/jwplayerRtdProvider.md
  test/spec/modules/jwplayerRtdProvider_spec.js
Labels: maintenance

#7756 Brandmetrics RTD Module: add new RTD module
  modules/brandmetricsRtdProvider.js
  modules/brandmetricsRtdProvider.md
  test/spec/modules/brandmetricsRtdProvider_spec.js
Labels: feature, needs update

#7940 Criteo Bid Adapteer: add schain support
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: maintenance

#7878 Evolution Bid Adapter: update compliance with Prebid v5
  modules/e_volutionBidAdapter.js
  test/spec/modules/e_volutionBidAdapter_spec.js
Labels: maintenance

#7939 Adagio Bid Adapter: remove referrer. reachedTop validation
  modules/adagioBidAdapter.js
  modules/adagioBidAdapter.md
  test/spec/modules/adagioBidAdapter_spec.js
Labels: maintenance

#7932 Gumgum Bid Adapter: support multiple GG params
  modules/gumgumBidAdapter.js
  test/spec/modules/gumgumBidAdapter_spec.js
Labels: bugfix

#7927 YahooSSP bid adapter: Expose vendor ID for TCFv2 enforcement
  modules/yahoosspBidAdapter.js
  test/spec/modules/yahoosspBidAdapter_spec.js
Labels: maintenance

#7906 Displayio Bid Adapter: add new bid adapter
  modules/displayioBidAdapter.js
  modules/displayioBidAdapter.md
  test/spec/modules/displayioBidAdapter_spec.js
Labels: feature

#7944 Core: fix pbjs.validateAdUnitPos() to handle 0 value
  src/prebid.js
  test/spec/unit/pbjs_api_spec.js
Labels: bugfix

#7929 Sovrn Bid Adaptter: add video to Sovrn adapter
  modules/sovrnBidAdapter.js
  modules/sovrnBidAdapter.md
  test/spec/modules/sovrnBidAdapter_spec.js
Labels: feature, LGTM

#7914 Undertone bid adapter: support for floors module
  modules/undertoneBidAdapter.js
  test/spec/modules/undertoneBidAdapter_spec.js
Labels: feature

#7946 Interactive Offers Bid Adapter: new fields and remap on the internal object
  modules/interactiveOffersBidAdapter.js
Labels: maintenance

#7951 appnexus bid adapter - add support for auction level keywords
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: feature

#7917 Prebid core: accept and propagate AD_RENDER_FAILED / AD_RENDER_SUCCEEDED events from cross-origin ads
  integrationExamples/gpt/x-domain/creative.html
  src/adRendering.js
  src/prebid.js
  src/secureCreatives.js
  src/utils.js
  test/spec/unit/secureCreatives_spec.js
Labels: needs 2nd review, bugfix

#7948 Improve Digital adapter: add COPPA support
  modules/improvedigitalBidAdapter.js
  test/spec/modules/improvedigitalBidAdapter_spec.js
Labels: feature

#7947 Rubicon Analytics: Pass along the order which bidders were called
  modules/rubiconAnalyticsAdapter.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
Labels: maintenance

#7937 Aseal Bid Adapter: add new bid adapter
  modules/asealBidAdapter.js
  modules/asealBidAdapter.md
  test/spec/modules/asealBidAdapter_spec.js
Labels: feature

#7962 Richaudience Bid Adapter: uncaught error on non-gdpr locations #7955
  modules/richaudienceBidAdapter.js
Labels: bugfix

#7961 Ogury Bid Adapter: 'adding location to bid timeout tracks'
  modules/oguryBidAdapter.js
  test/spec/modules/oguryBidAdapter_spec.js
Labels: maintenance

#7912 Weborama RTD submodule: add support to more bid adapters
  integrationExamples/gpt/weboramaRtdProvider_example.html
  modules/weboramaRtdProvider.js
  modules/weboramaRtdProvider.md
  test/spec/modules/weboramaRtdProvider_spec.js
Labels: feature, LGTM

#7712 Prebid Core: refactor bidderSettings to have only one entry point
  .eslintrc.js
  modules/appnexusBidAdapter.js
  modules/priceFloors.js
  modules/sortableAnalyticsAdapter.js
  package-lock.json
  package.json
  src/auction.js
  src/bidderSettings.js
  src/targeting.js
  src/utils.js
  test/spec/auctionmanager_spec.js
  test/spec/modules/sortableAnalyticsAdapter_spec.js
  test/spec/unit/core/bidderSettings_spec.js
Labels: maintenance

#7967 Ogury Bid Adapter: fix some check conditions - US/non-GDPR issue
  modules/oguryBidAdapter.js
  test/spec/modules/oguryBidAdapter_spec.js
Labels: bugfix

#7966 Conversant Bid Adapter: support for first party data through ortb2
  modules/conversantBidAdapter.js
  test/spec/modules/conversantBidAdapter_spec.js
Labels: maintenance

#7953 Prebid core: accept MessageChannel communication from cross-origin creatives
  integrationExamples/gpt/x-domain/creative.html
  src/secureCreatives.js
  test/spec/unit/pbjs_api_spec.js
  test/spec/unit/secureCreatives_spec.js
Labels: bugfix

#7949 PBjs Core - Adloader : add brandmetrics module to approved external js- loaders
  src/adloader.js
Labels: bugfix

#7958 Rise Bid Adapter: support onbid won
  modules/riseBidAdapter.js
  test/spec/modules/riseBidAdapter_spec.js
Labels: maintenance

#7938 Hadron Id Submodule: initial release & deprecate Halo Id submodule
  integrationExamples/gpt/hadronRtdProvider_example.html
  integrationExamples/gpt/idImportLibrary_example.html
  integrationExamples/gpt/userId_example.html
  modules/.submodules.json
  modules/hadronIdSystem.js
  modules/hadronIdSystem.md
  modules/hadronRtdProvider.js
  modules/hadronRtdProvider.md
  modules/haloIdSystem.md
  modules/haloRtdProvider.md
  modules/userId/eids.js
  test/spec/modules/eids_spec.js
  test/spec/modules/hadronIdSystem_spec.js
  test/spec/modules/hadronRtdProvider_spec.js
  test/spec/modules/userId_spec.js
Labels: maintenance

#7945 Trustpid User ID Module: initial release
  modules/.submodules.json
  modules/trustpidSystem.js
  modules/trustpidSystem.md
  modules/userId/eids.js
  modules/userId/eids.md
  modules/userId/userId.md
  test/spec/modules/trustpidSystem_spec.js
Labels: feature

#7973 malltv Bid Adapter: update maintainer and docs
  modules/malltvBidAdapter.md
Labels: maintenance

#7982 YieldOne Bid Adapter: add IMID support.
  modules/yieldoneBidAdapter.js
  test/spec/modules/yieldoneBidAdapter_spec.js
Labels: maintenance

#7980 PubMatic Bid Adapter : Added support for considering video params from mediaTypes object of Bid
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: maintenance

#7981 PubMatic Bid Adapter(for Prebid 5.20.x): added support for considering video params from mediaTypes object of Bid
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: maintenance

#7824 Vibrant Media Bid Adapter: add new bid adapter
  modules/vibrantmediaBidAdapter.js
  modules/vibrantmediaBidAdapter.md
  test/spec/modules/vibrantmediaBidAdapter_spec.js
Labels: feature

#7963 sspBC Bid Adapter: improvee native support , matching site/placement, & other maintenance
  modules/sspBCBidAdapter.js
  test/spec/modules/sspBCBidAdapter_spec.js
Labels: maintenance

#7972 nextMillennium Bid Adapter: fix for missing intermediate objects response
  modules/nextMillenniumBidAdapter.js
Labels: bugfix
