Repository prebid/Prebid.js, pull requests merged in 2022-09, with the labels that each got.

#8927 LimelightDigital: support schain
  modules/limelightDigitalBidAdapter.js
  test/spec/modules/limelightDigitalBidAdapter_spec.js
Labels: maintenance

#8716 Experimental Fledge Module & OpenXOrtb Adapter: initial release and bidder support
  modules/fledgeForGpt.js
  modules/fledgeForGpt.md
  modules/openxOrtbBidAdapter.js
  src/adapterManager.js
  src/adapters/bidderFactory.js
  src/utils.js
  test/spec/modules/fledge_spec.js
  test/spec/modules/openxOrtbBidAdapter_spec.js
  test/spec/unit/core/adapterManager_spec.js
  test/spec/unit/core/bidderFactory_spec.js
Labels: feature

#8948 bidWatch Analytics Adapter : forward advertiserDomains
  modules/bidwatchAnalyticsAdapter.js
  test/spec/modules/bidwatchAnalyticsAdapter_spec.js
Labels: maintenance

#8893 Yieldlab Bid Adapter support floor module
  modules/yieldlabBidAdapter.js
  test/spec/modules/yieldlabBidAdapter_spec.js
Labels: maintenance

#8954 Revert "Prebid core: optimize getRefererInfo to run only once per pag…
  src/refererDetection.js
  test/spec/modules/enrichmentFpdModule_spec.js
  test/spec/modules/fpdModule_spec.js
Labels: bugfix

#8949 Taboola Bid Adapter: Support Dynamic Endpoint Url Param
  modules/taboolaBidAdapter.js
  modules/taboolaBidAdapter.md
  test/spec/modules/taboolaBidAdapter_spec.js
Labels: maintenance

#8935 PBjs Core (Debugging): fix DOMException: Failed to read the 'sessionStorage'
  src/debugging.js
Labels: bugfix

#8933 SpotX Bid Adapter: Support UID2
  modules/spotxBidAdapter.js
  test/spec/modules/spotxBidAdapter_spec.js
Labels: maintenance

#8901 Yieldmo Adapter: Pass Auction Id and Transaction Id in Bid Request
  modules/yieldmoBidAdapter.js
  test/spec/modules/yieldmoBidAdapter_spec.js
Labels: maintenance

#8961 Adtelligent Bid Adapter: Add gvlid for OCM alias
  modules/adtelligentBidAdapter.js
Labels: maintenance

#8962 Outbrain adapter: wlang support
  modules/outbrainBidAdapter.js
  test/spec/modules/outbrainBidAdapter_spec.js
Labels: maintenance

#8898 Kargo: Add support for Kargo Social Canvas product
  modules/kargoBidAdapter.js
Labels: maintenance

#8963 Dependency Updates: npm audit fix and a few depend-a-bot security warnings
  package-lock.json
Labels: dependencies, maintenance

#8909 Xe Bid Adapter: initial adapter release
  modules/xeBidAdapter.js
  modules/xeBidAdapter.md
  test/spec/modules/xeBidAdapter_spec.js
Labels: feature

#8966 Adrino Bid Adapter: pass userId object to bidder
  modules/adrinoBidAdapter.js
  test/spec/modules/adrinoBidAdapter_spec.js
Labels: maintenance

#8968 Onetag Bid Adapter: update createEidsArray to userIdsAsEids
  modules/onetagBidAdapter.js
Labels: maintenance

#8876 DiscoveryDSP Bid Adapter: initial adapter release
  modules/discoveryBidAdapter.js
  modules/discoveryBidAdapter.md
  test/spec/modules/discoveryBidAdapter_spec.js
Labels: feature

#8939 Appnexus Bid Adapter: add support to read ortb2 keywords
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: maintenance

#8951 Teads bid adapter: additional user id support
  modules/teadsBidAdapter.js
  test/spec/modules/teadsBidAdapter_spec.js
Labels: maintenance

#8976 Dependencies: upgrade gulp-eslint to 6.0.0
  package-lock.json
  package.json
Labels: dependencies

#8978 Adriver ID system: fix spurious test failure
  test/spec/modules/adriverIdSystem_spec.js
Labels: bugfix

#8977 Prebid core: fix bug with native adUnits generating invalid PBS requests
  src/constants.json
  src/native.js
  test/spec/native_spec.js
Labels: bugfix

#8945 Viewability Module: remove viewability module functionality
  modules/viewability.js
  modules/viewability.md
  test/spec/modules/viewability_spec.js
Labels: maintenance

#8982 CPMStar Bid Adapter: Updated buildRequests method to use new referer
  modules/cpmstarBidAdapter.js
Labels: maintenance

#8979 SpotX Adapter: Pass url to renderer
  modules/spotxBidAdapter.js
  test/spec/modules/spotxBidAdapter_spec.js
Labels: bugfix

#8960 LiveIntent Analytics Adapter: initial release
  modules/liveIntentAnalyticsAdapter.js
  modules/liveIntentAnalyticsAdapter.md
  test/spec/modules/liveIntentAnalyticsAdapter_spec.js
Labels: feature

#8958 StroeerCore Bid Adapter: add video support
  modules/stroeerCoreBidAdapter.js
  modules/stroeerCoreBidAdapter.md
  test/spec/modules/stroeerCoreBidAdapter_spec.js
Labels: feature

#8740 NextMillennium Bid Adapter: Added video support
  modules/nextMillenniumBidAdapter.js
  test/spec/modules/nextMillenniumBidAdapter_spec.js
Labels: feature

#8989 AMX bid adapter: update refererInfo for Prebid 7
  modules/amxBidAdapter.js
  test/spec/modules/amxBidAdapter_spec.js
Labels: maintenance

#8988 Sharethrough Bid Adapter: Add support for Transaction ID
  modules/sharethroughBidAdapter.js
  test/spec/modules/sharethroughBidAdapter_spec.js
Labels: maintenance

#8986 ucfunnel Bid Adapter: add GPID support and fix page and domain parameter.
  modules/ucfunnelBidAdapter.js
  test/spec/modules/ucfunnelBidAdapter_spec.js
Labels: maintenance

#8914 Core & multiple modules: collect granular timing metrics for auctions, requests, responses
  modules/categoryTranslation.js
  modules/consentManagement.js
  modules/consentManagementUsp.js
  modules/currency.js
  modules/dataControllerModule/index.js
  modules/dchain.js
  modules/fpdModule/index.js
  modules/mass.js
  modules/multibid/index.js
  modules/prebidServerBidAdapter/index.js
  modules/priceFloors.js
  modules/pubCommonId.js
  modules/rtdModule/index.js
  modules/userId/index.js
  src/adapterManager.js
  src/adapters/bidderFactory.js
  src/auction.js
  src/auctionManager.js
  src/prebid.js
  src/secureCreatives.js
  src/utils/perfMetrics.js
  test/spec/unit/utils/perfMetrics_spec.js
Labels: feature

#8904 Dianomi Bid Adapter: add usersyncs
  modules/dianomiBidAdapter.js
  modules/dianomiBidAdapter.md
  test/spec/modules/dianomiBidAdapter_spec.js
Labels: maintenance

#8995 USP consent management module: fix bug with zero-conf not being enabled on first auction
  modules/consentManagementUsp.js
  test/spec/modules/consentManagementUsp_spec.js
Labels: bugfix

#8946 Navegg ID System: Added call to NaveggID API
  modules/naveggIdSystem.js
Labels: maintenance

#8975 NextMillennium Bid Adapter: sends not one size, but multiple for a request
  modules/nextMillenniumBidAdapter.js
  test/spec/modules/nextMillenniumBidAdapter_spec.js
Labels: maintenance

#8999 openxOrtb: minor bugfix - handle response with missing seatbid and no nbr
  modules/openxOrtbBidAdapter.js
  test/spec/modules/openxOrtbBidAdapter_spec.js
Labels: bugfix

#8996 CircleCI integration: re-enable e2e tests
  .circleci/config.yml
  test/helpers/testing-utils.js
  wdio.conf.js
Labels: build process, maintenance

#8845 Caroda Bid Adapter: initial adapter release
  modules/carodaBidAdapter.js
  modules/carodaBidAdapter.md
  test/spec/modules/carodaBidAdapter_spec.js
Labels: feature

#9003 CI: let Karma manage browserstack tunnel
  .circleci/config.yml
  karma.conf.maker.js
Labels: build process, maintenance

#8965 IX Bid Adapter: update sid location and remove its fallback logic
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: bugfix

#9009 Improve Digital adapter: Basic ads endpoint
  modules/improvedigitalBidAdapter.js
  test/spec/modules/improvedigitalBidAdapter_spec.js
Labels: maintenance

#9012 Appnexus Bid Adapter: fix undefined state with adunit ortb keywords
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: bugfix

#9017 Rubicon Analytics: Do not overwrite billing `type`
  modules/rubiconAnalyticsAdapter.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
Labels: maintenance

#8997 Rubicon Bid Adapter: Choose video when banner mediaType is not present
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: maintenance

#9016 AdagioBidAdapter: Native multiple js trackers + fix FPD handling
  modules/adagioBidAdapter.js
  modules/adagioBidAdapter.md
  test/spec/modules/adagioBidAdapter_spec.js
Labels: bugfix

#8943 Mediasquare Bid Adapter: add metrics to onBidWon Event
  modules/mediasquareBidAdapter.js
  test/spec/modules/mediasquareBidAdapter_spec.js
Labels: maintenance

#8992 1plusX RTD Module: Send GDPR info to PAPI
  modules/1plusXRtdProvider.js
  test/spec/modules/1plusXRtdProvider_spec.js
Labels: bugfix

#9025 Vidazoo Bid Adapter: update unique deal id expiry
  modules/vidazooBidAdapter.js
Labels: maintenance

#9027 bidWatch Analytics Adapter : forward adId
  modules/bidwatchAnalyticsAdapter.js
  test/spec/modules/bidwatchAnalyticsAdapter_spec.js
Labels: maintenance

#9031 Adquery Bid Adapter: added sizes to bid request
  modules/adqueryBidAdapter.js
  test/spec/modules/adqueryBidAdapter_spec.js
Labels: maintenance

#9022 PBS Adapter: test for override of default s2s currency
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: maintenance

#9036 Adagio Adapter: set back to the original style after getSlotPosition
  modules/adagioBidAdapter.js
  test/spec/modules/adagioBidAdapter_spec.js
Labels: bugfix

#9038 Seedtag Bid Adapter: add schain to payload
  modules/seedtagBidAdapter.js
  test/spec/modules/seedtagBidAdapter_spec.js
Labels: maintenance

#9033 Taboola Adapter: Adding Some Optional Chaining Checks
  modules/taboolaBidAdapter.js
Labels: maintenance

#9042 nextMillennium Bid Adapter: Enhance work with video format
  modules/nextMillenniumBidAdapter.js
Labels: maintenance

#9041 Nativo Bid Adapter: fix floors bug
  modules/nativoBidAdapter.js
Labels: bugfix

#9011 GrowthCode ID Module: initial module release
  modules/growthCodeIdSystem.js
  modules/growthCodeIdSystem.md
  modules/userId/eids.js
  test/spec/modules/growthCodeIdSystem_spec.js
Labels: feature

#9043 TheMediaGrid: fix trustx aliasing in s2s
  modules/gridBidAdapter.js
Labels: maintenance

#9050 Rubicon. bugfix for singleRequest config regression
  modules/rubiconBidAdapter.js
Labels: bugfix

#9054 Criteo bid adapter: Update FastBid default version
  modules/criteoBidAdapter.js
Labels: maintenance

#9019 Mediakeys Bid Adapter: native support multiple javascript trackers
  modules/mediakeysBidAdapter.js
  modules/mediakeysBidAdapter.md
  test/spec/modules/mediakeysBidAdapter_spec.js
Labels: LGTM, maintenance

#9052 clean.io RTD Module: Added additional properties on Billable Event.
  modules/cleanioRtdProvider.js
Labels: maintenance

#9056 Colossus Bid Adapter: update buildRequests - add tid to request data
  modules/colossussspBidAdapter.js
  test/spec/modules/colossussspBidAdapter_spec.js
Labels: maintenance

#9057 Yandex Bid Adapter: add win notifications, change endpoint, floor support, add ref to payload
  modules/yandexBidAdapter.js
  test/spec/modules/yandexBidAdapter_spec.js
Labels: maintenance

#8984 dgkeywordRtdProvider submodule: support 1plusX SDK
  modules/dgkeywordRtdProvider.js
  test/spec/modules/dgkeywordRtdProvider_spec.js
Labels: maintenance
