Repository prebid/Prebid.js, pull requests merged in 2022-05, with the labels that each got.

#8335 33Across user id sub-module: initial release
  integrationExamples/gpt/userId_example.html
  modules/.submodules.json
  modules/33acrossIdSystem.js
  modules/33acrossIdSystem.md
  modules/userId/eids.js
  modules/userId/eids.md
  modules/userId/userId.md
  test/spec/modules/33acrossIdSystem_spec.js
  test/spec/modules/eids_spec.js
Labels: feature

#8317 Prebid Server Adapter: add native asset id parameter
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: maintenance

#8352 AdYouLike Bidder: clean on video ad treatment
  modules/adyoulikeBidAdapter.js
Labels: maintenance

#8269 Automatad Bid Adapter: make placementId param optional
  modules/automatadBidAdapter.js
  modules/automatadBidAdapter.md
  test/spec/modules/automatadBidAdapter_spec.js
Labels: maintenance

#8225 Prebid 7: Remove FLOC id submodule
  integrationExamples/gpt/userId_example.html
  modules/.submodules.json
  modules/appnexusBidAdapter.js
  modules/flocIdSystem.js
  modules/flocIdSystem.md
  modules/goldbachBidAdapter.js
  modules/ixBidAdapter.js
  modules/mediafuseBidAdapter.js
  modules/openxBidAdapter.js
  modules/pixfutureBidAdapter.js
  modules/pubmaticBidAdapter.js
  modules/sharethroughBidAdapter.js
  modules/teadsBidAdapter.js
  modules/ucfunnelBidAdapter.js
  modules/userId/userId.md
  modules/winrBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
  test/spec/modules/bridgewellBidAdapter_spec.js
  test/spec/modules/goldbachBidAdapter_spec.js
  test/spec/modules/ixBidAdapter_spec.js
  test/spec/modules/mediafuseBidAdapter_spec.js
  test/spec/modules/openxBidAdapter_spec.js
  test/spec/modules/pubmaticBidAdapter_spec.js
  test/spec/modules/sharethroughBidAdapter_spec.js
  test/spec/modules/teadsBidAdapter_spec.js
  test/spec/modules/ucfunnelBidAdapter_spec.js
  test/spec/modules/userId_spec.js
  test/spec/modules/winrBidAdapter_spec.js
Labels: needs docs, needs 2nd review, maintenance, major, 7.0 API Change

#8281 Prebid 7: Delete onevideo bid adapter
  modules/oneVideoBidAdapter.js
  modules/oneVideoBidAdapter.md
  test/spec/modules/oneVideoBidAdapter_spec.js
Labels: maintenance, major, 7.0 API Change

#8231 Aseal Bid Adapter: add session id & update request payload
  modules/asealBidAdapter.js
  test/spec/modules/asealBidAdapter_spec.js
Labels: feature, needs review

#8353 PubNX bid adapter: remove documentation
  modules/pubnxBidAdapter.md
Labels: maintenance, documentation

#8349 JwPlayer RTD Module: Support cids
  modules/jwplayerRtdProvider.js
  modules/jwplayerRtdProvider.md
  test/spec/modules/jwplayerRtdProvider_spec.js
Labels: maintenance

#8342 Insticator Bid adapter: added support for additional attributes
  modules/insticatorBidAdapter.js
  test/spec/modules/insticatorBidAdapter_spec.js
Labels: maintenance

#8361 Prebid 7 : update instl for current prebid standards
  modules/cleanmedianetBidAdapter.js
  modules/gamoshiBidAdapter.js
  modules/waardexBidAdapter.js
Labels: needs 2nd review, 7.0 API Change

#8276 Sovrn Bid Adapter: Enforce required video parameters
  modules/sovrnBidAdapter.js
  test/spec/modules/sovrnBidAdapter_spec.js
Labels: maintenance

#8292 MimuteMedia - Add support for Banner
  modules/minutemediaBidAdapter.js
  modules/minutemediaBidAdapter.md
  test/spec/modules/minutemediaBidAdapter_spec.js
Labels: needs update, maintenance

#8375 Adf adapter: add coppa signal support
  modules/adfBidAdapter.js
  test/spec/modules/adfBidAdapter_spec.js
Labels: maintenance

#8377 bizzclick Bid Adapter: remove privacy settings duplication
  modules/bizzclickBidAdapter.js
Labels: maintenance

#8357 Prebid core: do not enforce adapters' mediaType support for PBS bids
  modules/prebidServerBidAdapter/index.js
  src/prebid.js
Labels: bugfix

#8378 Sovrn Bid Adapter: handle multiple seatbids in response
  modules/sovrnBidAdapter.js
  test/spec/modules/sovrnBidAdapter_spec.js
Labels: maintenance

#8326 Alkimi Bid Adapter: add new bid adapter
  modules/alkimiBidAdapter.js
  modules/alkimiBidAdapter.md
  test/spec/modules/alkimiBidAdapter_spec.js
Labels: feature

#8390 talkads Bid Adapter: update params access in case of different ad servers
  modules/talkadsBidAdapter.js
  test/spec/modules/talkadsBidAdapter_spec.js
Labels: maintenance

#8302 BidWatch Analytics Adapter: add new analytics adapter
  modules/bidwatchAnalyticsAdapter.js
  modules/bidwatchAnalyticsAdapter.md
  test/spec/modules/bidwatchAnalyticsAdapter_spec.js
Labels: feature

#8371 Improve Digital adapter: change asset source for native ads
  modules/improvedigitalBidAdapter.js
  test/spec/modules/improvedigitalBidAdapter_spec.js
Labels: maintenance

#8400 LKQD Bid Adapter: remove device ip bug
  modules/lkqdBidAdapter.js
  test/spec/modules/lkqdBidAdapter_spec.js
Labels: maintenance

#8364 cpex Id System: initial release
  modules/.submodules.json
  modules/cpexIdSystem.js
  modules/cpexIdSystem.md
  modules/userId/userId.md
  test/spec/modules/cpexIdSystem_spec.js
Labels: feature

#8401 UserID module: graceful handling of exceptions from ID submodules
  modules/id5IdSystem.js
  modules/userId/index.js
  src/utils.js
  test/spec/modules/id5IdSystem_spec.js
  test/spec/modules/userId_spec.js
Labels: bugfix

#8398 Ogury Bid Adapter: removing floor field from bid request when not defined
  modules/oguryBidAdapter.js
  test/spec/modules/oguryBidAdapter_spec.js
Labels: maintenance

#8392 Prebid Server Bid Adapter: Pass floors signal to PBS if Price Floors enabled for auction
  modules/prebidServerBidAdapter/index.js
  modules/rubiconBidAdapter.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: needs 2nd review, maintenance

#8396 Price Floors Module: Support adUnit level floors
  modules/priceFloors.js
  test/spec/modules/priceFloors_spec.js
Labels: needs 2nd review, maintenance

#8388 AirGrid RTD module: Support for xandr / appnexus auction level keywords.
  modules/.submodules.json
  modules/airgridRtdProvider.js
  modules/airgridRtdProvider.md
  test/spec/modules/airgridRtdProvider_spec.js
Labels: feature

#8405 Alkimi Bid Adapter: change maintainer email
  modules/alkimiBidAdapter.md
Labels: maintenance

#8404 TheMediaGrid: support ortb2.site.content.data from config
  modules/gridBidAdapter.js
  test/spec/modules/gridBidAdapter_spec.js
Labels: maintenance

#8386 PubMatic Bid Adapter : Remove GroupM as alias
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: maintenance

#8384 Intentiq module: adding dynamic ttl and rtt and storing data in localstorate
  modules/intentIqIdSystem.js
  test/spec/modules/intentIqIdSystem_spec.js
Labels: feature

#8402 Floc ID Module: remove call for floc
  modules/flocIdSystem.js
Labels: bugfix

#8379 Core & Multiple modules: replace all usage of `require` with `import`
  .eslintrc.js
  modules/engageyaBidAdapter.js
  modules/eplanningAnalyticsAdapter.js
  modules/fintezaAnalyticsAdapter.js
  modules/googleAnalyticsAdapter.js
  modules/invisiblyAnalyticsAdapter.js
  modules/my6senseBidAdapter.js
  modules/prebidmanagerAnalyticsAdapter.js
  modules/weboramaRtdProvider.js
  src/AnalyticsAdapter.js
  src/adapterManager.js
  src/auction.js
  src/auctionManager.js
  src/bidderSettings.js
  src/config.js
  src/events.js
  src/native.js
  src/prebid.js
  src/targeting.js
  src/utils.js
Labels: maintenance

#8406 Sirdata RTD Module: bug fixes & add new bidders
  modules/sirdataRtdProvider.js
Labels: feature

#8407 AdagioBidAdapter: site information detection (use refererInfo)
  modules/adagioBidAdapter.js
  test/spec/modules/adagioBidAdapter_spec.js
Labels: maintenance

#8354 JwPlayer RTD Module: Set Ortb content to config
  modules/jwplayerRtdProvider.js
  test/spec/modules/jwplayerRtdProvider_spec.js
Labels: maintenance

#8347 Audigent Hadron: Add New Analytics Adapter
  modules/hadronAnalyticsAdapter.js
  modules/hadronAnalyticsAdapter.md
  test/spec/modules/hadronAnalyticsAdapter_spec.js
Labels: feature

#8395 Sspbc Bid Adapter: Gather language in payload; various formatting changes
  modules/sspBCBidAdapter.js
  modules/sspBCBidAdapter.md
  test/spec/modules/sspBCBidAdapter_spec.js
Labels: maintenance

#8411 Prebid Core: declare required deps for webpack build
  package-lock.json
  package.json
Labels: bugfix

#8365 Multiple modules: automatically fill in PPID for DFP video URLs
  modules/dfpAdServerVideo.js
  modules/userId/index.js
  src/adserver.js
  test/spec/modules/dfpAdServerVideo_spec.js
  test/spec/modules/userId_spec.js
Labels: feature

#8202 Invibes Bid Adapter: write id to first party from bid adapter
  modules/invibesBidAdapter.js
  test/spec/modules/invibesBidAdapter_spec.js
Labels: maintenance

#8350 Weborama RTD submodule: specify list of bidders to share data
  integrationExamples/gpt/weboramaRtdProvider_example.html
  modules/weboramaRtdProvider.js
  modules/weboramaRtdProvider.md
  test/spec/modules/weboramaRtdProvider_spec.js
Labels: maintenance

#8228 TrustP ID Module: Refactor acronyms handler
  modules/trustpidSystem.js
  modules/trustpidSystem.md
  modules/userId/userId.md
  test/spec/modules/trustpidSystem_spec.js
Labels: maintenance

#8382 appnexus bid adapter - fix in psp keywords conversion logic
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: bugfix

#8417 DistrictmDmx Bid Adapter: removal
  modules/districtmDMXBidAdapter.js
  modules/districtmDmxBidAdapter.md
  test/spec/modules/districtmDmxBidAdapter_spec.js
Labels: maintenance, 7.0 API Change

#8408 UserID module: do not start initialization until `pbjs.processQueue()` has been called
  modules/currency.js
  modules/userId/index.js
  src/hook.js
  src/utils/promise.js
  test/spec/unit/utils/promise_spec.js
Labels: bugfix

#8418 Adtelligent Bid Adapter: add PGAM alias
  modules/adtelligentBidAdapter.js
  test/spec/modules/adtelligentBidAdapter_spec.js
Labels: maintenance

#8391 BeOp Bid Adapter: prefer canonical URL when present & prepend protocol
  modules/beopBidAdapter.js
  test/spec/modules/beopBidAdapter_spec.js
Labels: maintenance

#8425 IX Bid Adapter: add detected page url to ixdiag
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance

#8423 LiveIntent Id Submodule: Update live-connect to 2.3.3; better consent processing
  package-lock.json
  package.json
  test/spec/modules/liveIntentIdSystem_spec.js
Labels: bugfix

#8403 Loglylift Bid Adapter: support cta and privacyLink in tests
  test/spec/modules/loglyliftBidAdapter_spec.js
Labels: maintenance

#8373 Prebid 7: change default of `allowAlternateBidderCodes` from `true` to `false`
  src/adapters/bidderFactory.js
  test/spec/unit/core/bidderFactory_spec.js
Labels: major, 7.0 API Change

#8426 Kargo Bid Adapter: adding media type to bid response, supporting vastXml response
  modules/kargoBidAdapter.js
  test/spec/modules/kargoBidAdapter_spec.js
Labels: maintenance

#8321 Prebid 7: TheMediaGrid: make trustxBidAdapter as alias of gridBidAdapter
  modules/gridBidAdapter.js
  modules/trustxBidAdapter.js
  modules/trustxBidAdapter.md
  test/spec/modules/trustxBidAdapter_spec.js
Labels: major, 7.0 API Change

#8431 Vidoomy adapter: update sync URLs
  modules/vidoomyBidAdapter.js
Labels: maintenance

#8434 Adagio Bid Adapter: remove useless data in bid request
  modules/adagioBidAdapter.js
Labels: maintenance

#8416 Ogury Bid Adapter: Add device infos with size in bidrequest
  modules/oguryBidAdapter.js
  test/spec/modules/oguryBidAdapter_spec.js
Labels: maintenance

#8279 Prebid 7: Change default bidder access to storage manager
  modules/vidazooBidAdapter.js
  src/storageManager.js
  test/spec/modules/adagioBidAdapter_spec.js
  test/spec/modules/adnuntiusBidAdapter_spec.js
  test/spec/modules/apstreamBidAdapter_spec.js
  test/spec/modules/concertBidAdapter_spec.js
  test/spec/modules/conversantBidAdapter_spec.js
  test/spec/modules/craftBidAdapter_spec.js
  test/spec/modules/criteoBidAdapter_spec.js
  test/spec/modules/eplanningBidAdapter_spec.js
  test/spec/modules/invibesBidAdapter_spec.js
  test/spec/modules/kargoBidAdapter_spec.js
  test/spec/modules/quantcastBidAdapter_spec.js
  test/spec/modules/trionBidAdapter_spec.js
  test/spec/modules/unicornBidAdapter_spec.js
  test/spec/modules/vidazooBidAdapter_spec.js
  test/spec/unit/core/storageManager_spec.js
Labels: LGTM, maintenance, major, 7.0 API Change

#8310 Video Heroes Bid Adapter: add new bid adapter
  modules/videoheroesBidAdapter.js
  modules/videoheroesBidAdapter.md
  test/spec/modules/videoheroesBidAdapter_spec.js
Labels: feature

#8440 cpex Id module: Remove window reference
  modules/cpexIdSystem.js
Labels: bugfix

#8439 Jixie Bid Adapter: add schain
  modules/jixieBidAdapter.js
  test/spec/modules/jixieBidAdapter_spec.js
Labels: maintenance

#8437 Prebid 7: Remove AppNexus Alias for Brealtime and DistrictM
  modules/appnexusBidAdapter.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: maintenance

#8453 Dac ID System: change docs from DAC ID to AudienceOne
  modules/dacIdSystem.md
Labels: maintenance

#8284 Akamai RTD: fixed bugs on rtd module and added the entropy values
  integrationExamples/gpt/akamaidap_segments_example.html
  modules/.submodules.json
  modules/akamaiDapRtdProvider.js
  modules/akamaiDapRtdProvider.md
  src/adloader.js
  test/spec/modules/akamaiDapRtdProvider_spec.js
Labels: bugfix

#8454 Zeta global ssp bid adapter: add shortname param
  modules/zeta_global_sspBidAdapter.js
  test/spec/modules/zeta_global_sspBidAdapter_spec.js
Labels: maintenance

#8464 Revert "Akamai RTD: fixed bugs on rtd module and added the entropy values"
  integrationExamples/gpt/akamaidap_segments_example.html
  modules/.submodules.json
  modules/akamaiDapRtdProvider.js
  modules/akamaiDapRtdProvider.md
  src/adloader.js
  test/spec/modules/akamaiDapRtdProvider_spec.js
Labels: maintenance

#8467 Finteza Analytics Adapter: add more information to unit test messages
  test/spec/modules/fintezaAnalyticsAdapter_spec.js
Labels: maintenance

#8473 Ftrack Id Module: remove configured url validation
  modules/ftrackIdSystem.js
  test/spec/modules/ftrackIdSystem_spec.js
Labels: maintenance

#8477 Conversant adapter: accept position from the AdUnit
  modules/conversantBidAdapter.js
  test/spec/modules/conversantBidAdapter_spec.js
Labels: maintenance

#8479 NovatiqId User Module: include IAB Vendor ID
  modules/novatiqIdSystem.js
Labels: maintenance

#8468 Prebid 7: Clean up misc halo references
  modules/beachfrontBidAdapter.js
  modules/ixBidAdapter.js
  modules/openxBidAdapter.js
  modules/ucfunnelBidAdapter.js
  modules/userId/eids.js
  test/spec/modules/beachfrontBidAdapter_spec.js
Labels: maintenance

#8476 Colossus Bid Adapter: move floors logic after placement.sizes are defined
  modules/colossussspBidAdapter.js
Labels: bugfix

#8455 Adloox Analytics/RTD: prefer gpid over pbadslot
  modules/adlooxAnalyticsAdapter.js
  modules/adlooxAnalyticsAdapter.md
  modules/adlooxRtdProvider.js
  modules/adlooxRtdProvider.md
Labels: maintenance

#8430 SOVRN Bid Adapter: refactor old test code
  test/spec/modules/sovrnBidAdapter_spec.js
Labels: maintenance

#8481 Relaido & Proxistore Tests: remove console.logs
  modules/relaidoBidAdapter.js
  test/spec/modules/proxistoreBidAdapter_spec.js
Labels: maintenance

#8445 Kobler adapter: remove outdated parameters, simplify testing
  modules/koblerBidAdapter.js
  modules/koblerBidAdapter.md
  test/spec/modules/koblerBidAdapter_spec.js
Labels: feature

#8451 Prebid 7: Adapter fixes for reading impression position
  modules/adrelevantisBidAdapter.js
  modules/gamoshiBidAdapter.js
  modules/pixfutureBidAdapter.js
  modules/smilewantedBidAdapter.js
  modules/spotxBidAdapter.js
Labels: maintenance

#8480 Prebid 7: Remove Akamai DAP ID in favor of RTD
  integrationExamples/gpt/akamaidap_email_example.html
  integrationExamples/gpt/akamaidap_signature_example.html
  integrationExamples/gpt/akamaidap_x1_example.html
  modules/.submodules.json
  modules/akamaiDAPIdSystem.js
  modules/akamaiDAPIdSystem.md
  modules/userId/eids.js
  modules/userId/eids.md
  modules/userId/userId.md
  test/spec/modules/akamaiDAPIdSystem_spec.js
  test/spec/modules/userId_spec.js
Labels: maintenance, 7.0 API Change

#8483 Taboola bid adapter: initial release
  modules/taboolaBidAdapter.js
  modules/taboolaBidAdapter.md
  test/spec/modules/taboolaBidAdapter_spec.js
Labels: feature

#8432 Ftrack Id Module: replace native appendChild with Prebid's loadExternalScript
  modules/ftrackIdSystem.js
  src/adloader.js
  test/spec/modules/ftrackIdSystem_spec.js
Labels: maintenance

#8316 IncrementX Bid Adapter: Initial Release
  modules/incrxBidAdapter.js
  modules/incrxBidAdapter.md
  test/spec/modules/incrxBidAdapter_spec.js
Labels: feature

#8486 Adyoulike Bidder Adapter - schain support
  modules/adyoulikeBidAdapter.js
  test/spec/modules/adyoulikeBidAdapter_spec.js
Labels: maintenance

#8471 ZetaGlobalSsp BidAdapter: shortname to url
  modules/zeta_global_sspBidAdapter.js
  test/spec/modules/zeta_global_sspBidAdapter_spec.js
Labels: maintenance

#8487 Akamai RTD Module: Fixed randomly failing test cases and updated the variable names
  integrationExamples/gpt/akamaidap_segments_example.html
  modules/akamaiDapRtdProvider.js
  modules/akamaiDapRtdProvider.md
  test/spec/modules/akamaiDapRtdProvider_spec.js
Labels: bugfix

#8489 Adriver ID system: fix spurious test failure
  test/spec/modules/adriverIdSystem_spec.js
Labels: bugfix

#8492 TheMediaGrid: support bid.ortb2.site.content.id
  modules/gridBidAdapter.js
  test/spec/modules/gridBidAdapter_spec.js
Labels: maintenance

#8493 Mantis Bid Adapter: use core ajax method
  modules/mantisBidAdapter.js
Labels: maintenance

#8444 Automatad Bid Adapter: changes to ajax request options for bid requests
  modules/automatadBidAdapter.js
  test/spec/modules/automatadBidAdapter_spec.js
Labels: maintenance

#8501 Various Magnite Adapters: GVL ID update
  modules/slimcutBidAdapter.js
  modules/spotxBidAdapter.js
  modules/telariaBidAdapter.js
Labels: maintenance

#8498 Adf adapter: avoid preflight request
  modules/adfBidAdapter.js
  test/spec/modules/adfBidAdapter_spec.js
Labels: maintenance
