Repository prebid/Prebid.js, pull requests merged in 2022-04, with the labels that each got.

#8245 Gamoshi Bid Adapter: Handle gdpr applies correctly
  modules/gamoshiBidAdapter.js
Labels: bugfix

#8185 Prebid core: make GDPR/USP consent data available without requiring an auction
  modules/consentManagement.js
  modules/consentManagementUsp.js
  src/consentHandler.js
  test/spec/modules/consentManagementUsp_spec.js
  test/spec/modules/consentManagement_spec.js
  test/spec/modules/userId_spec.js
  test/spec/unit/core/consentHandler_spec.js
Labels: feature, CORE HIGH IMPACT

#8244 Between bid Adapter: add image userSync and change default currency
  modules/betweenBidAdapter.js
  test/spec/modules/betweenBidAdapter_spec.js
Labels: maintenance

#8236 Colossus Bid Adapter: fix buildRequests
  modules/colossussspBidAdapter.js
  test/spec/modules/colossussspBidAdapter_spec.js
Labels: bugfix

#8227 Prebid 7: Delete userid targeting module
  modules/userIdTargeting.js
  modules/userIdTargeting.md
  test/spec/modules/shareUserIds_spec.js
Labels: needs docs, needs 2nd review, maintenance, major, 7.0 API Change

#8183 Yandex Bid Adapter: initial release
  modules/yandexBidAdapter.js
  modules/yandexBidAdapter.md
  test/spec/modules/yandexBidAdapter_spec.js
Labels: feature

#8198 LiveIntent Id Submodule: Update live-connect build dependency to 2.3.1
  package-lock.json
  package.json
  test/spec/modules/liveIntentIdSystem_spec.js
Labels: maintenance

#8250 Adman Bid Adapter: update sync url
  modules/admanBidAdapter.js
  test/spec/modules/admanBidAdapter_spec.js
Labels: maintenance

#8237 Glimpse: update api and request shape, optimize and refactor
  modules/glimpseBidAdapter.js
  modules/glimpseBidAdapter.md
  test/spec/modules/glimpseBidAdapter_spec.js
Labels: feature, needs review

#8256 Seeding alliance Adapter: multiple replacement of auction price bugfix
  modules/seedingAllianceBidAdapter.js
Labels: bugfix

#8206 Biddo Bid Adapter: add new bid adapter
  modules/biddoBidAdapter.js
  modules/biddoBidAdapter.md
  test/spec/modules/biddoBidAdapter_spec.js
Labels: feature, needs review

#8252 consumable Bid Adapter : add bidResponse fields
  modules/consumableBidAdapter.js
  test/spec/modules/consumableBidAdapter_spec.js
Labels: maintenance

#8221 Add DistroScale Bid Adapter
  modules/distroscaleBidAdapter.js
  modules/distroscaleBidAdapter.md
  test/spec/modules/distroscaleBidAdapter_spec.js
Labels: feature, LGTM

#8215 PulsePoint Bid Adapter: Support for first party eid data
  modules/pulsepointBidAdapter.js
  test/spec/modules/pulsepointBidAdapter_spec.js
Labels: needs update, maintenance

#8259 nexx360 Bid Adapter : add support for video
  modules/nexx360BidAdapter.js
  modules/nexx360BidAdapter.md
  test/spec/modules/nexx360BidAdapter_spec.js
Labels: feature

#8249 justPremium Bid Adapter : support for user sync pixels
  modules/justpremiumBidAdapter.js
  test/spec/modules/justpremiumBidAdapter_spec.js
Labels: maintenance

#8268 Rubicon Analytics: Bump ajv to stable version
  package-lock.json
  package.json
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
  test/spec/modules/rubiconAnalyticsSchema.json
Labels: bugfix

#8270 Loglylift Bid Adapter: add support for banners
  modules/loglyliftBidAdapter.js
  modules/loglyliftBidAdapter.md
  test/spec/modules/loglyliftBidAdapter_spec.js
Labels: feature

#8267 Documentation: PR-reviewer update
  PR_REVIEW.md
Labels: maintenance, documentation

#8242 Permutive RTD module: support IAB Audience taxonomy
  integrationExamples/gpt/permutiveRtdProvider_example.html
  modules/permutiveRtdProvider.js
  modules/permutiveRtdProvider.md
  test/spec/modules/permutiveRtdProvider_spec.js
Labels: needs review, maintenance

#8266 Appnexus Bid Adapter : add support for setConfig pageUrl
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: maintenance

#8199 Mediasniper Bid Adapter: add new bid adapter
  modules/mediasniperBidAdapter.js
  modules/mediasniperBidAdapter.md
  test/spec/modules/mediasniperBidAdapter_spec.js
Labels: feature

#8277 justPremium Bid Adapter : documentation update
  modules/justpremiumBidAdapter.md
Labels: maintenance

#8262 Prebid Core: add documentResolver callback and allow the user to supply a different document object to render
  modules/appnexusBidAdapter.js
  src/Renderer.js
  src/adloader.js
  src/auction.js
  src/prebid.js
  src/utils.js
  test/spec/adloader_spec.js
  test/spec/renderer_spec.js
Labels: feature

#8207 Build system: fix basic e2e tests
  .circleci/config.yml
  gulpfile.js
  modules/currency.js
  modules/debugging/pbsInterceptor.js
  package-lock.json
  package.json
  test/fake-server/bundle.js
  test/fake-server/fake-responder.js
  test/fake-server/fixtures/basic-banner/request.json
  test/fake-server/fixtures/basic-outstream/request.json
  test/fake-server/index.js
  test/helpers/testing-utils.js
  test/pages/banner.html
  test/pages/bidderSettings.html
  test/pages/consent_mgt_gdpr.html
  test/pages/currency.html
  test/pages/instream.html
  test/pages/multiple_bidders.html
  test/pages/native.html
  test/pages/outstream.html
  test/pages/priceGranularity.html
  test/pages/sizeConfig.html
  test/pages/userSync.html
  test/spec/e2e/banner/basic_banner_ad.spec.js
  test/spec/e2e/instream/basic_instream_video_ad.spec.js
  test/spec/e2e/modules/e2e_bidderSettings.spec.js
  test/spec/e2e/modules/e2e_consent_mgt_gdpr.spec.js
  test/spec/e2e/modules/e2e_currency.spec.js
  test/spec/e2e/modules/e2e_priceGranularity.spec.js
  test/spec/e2e/modules/e2e_sizeConfig.spec.js
  test/spec/e2e/modules/e2e_userSync.spec.js
  test/spec/e2e/multi-bidder/e2e_multiple_bidders.spec.js
  test/spec/e2e/native/basic_native_ad.spec.js
  test/spec/e2e/outstream/basic_outstream_video_ad.spec.js
  wdio.conf.js
Labels: build process, needs 2nd review, maintenance

#8191 Vibrant Media Bid Adapter: onBidWon pixel trigger
  modules/vibrantmediaBidAdapter.js
Labels: maintenance

#8201 UserID module: better initialization logic
  modules/userId/index.js
  test/helpers/consentData.js
  test/spec/modules/eplanningBidAdapter_spec.js
  test/spec/modules/id5IdSystem_spec.js
  test/spec/modules/idImportLibrary_spec.js
  test/spec/modules/idxIdSystem_spec.js
  test/spec/modules/parrableIdSystem_spec.js
  test/spec/modules/userId_spec.js
  test/spec/modules/zeotapIdPlusIdSystem_spec.js
  test/spec/unit/pbjs_api_spec.js
Labels: needs review, needs 2nd review, bugfix, CORE HIGH IMPACT

#8282 AdYouLike Bidder - Add size in video bid
  modules/adyoulikeBidAdapter.js
  test/spec/modules/adyoulikeBidAdapter_spec.js
Labels: maintenance

#8286 NextMillennium bid adapter: Test endpoint was added
  modules/nextMillenniumBidAdapter.js
Labels: maintenance

#8280 MallTv Analytics Adapter: fix adapter manager registration code
  modules/malltvAnalyticsAdapter.js
Labels: bugfix

#8290 Adot Bid Adapter: set minduration and maxduration to optional
  modules/adotBidAdapter.js
  test/spec/modules/adotBidAdapter_spec.js
Labels: maintenance

#8261 AudienceRun Bid Adapter: Add Support for User Matching, Referer, …
  modules/audiencerunBidAdapter.js
  test/spec/modules/audiencerunBidAdapter_spec.js
Labels: maintenance

#8296 BetweenBidAdapter: jst fix
  modules/betweenBidAdapter.js
Labels: maintenance

#8298 Seeding Alliance Bid Adapter: change bidder URL and add versioning
  modules/seedingAllianceBidAdapter.js
Labels: maintenance

#8246 PubMatic: add "acat" parameter
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: taxonomy, maintenance

#8306 Build CircleCI: disable e2e tests
  .circleci/config.yml
Labels: maintenance

#8305 Consent management: fix bug with adUnits without a size causing exception in GPDR processing
  modules/consentManagement.js
  test/spec/modules/consentManagement_spec.js
Labels: bugfix

#8304 Consent management: fix bug where 'static' consent configuration does not work correctly
  modules/consentManagement.js
  modules/consentManagementUsp.js
  test/spec/modules/consentManagementUsp_spec.js
  test/spec/modules/consentManagement_spec.js
Labels: bugfix

#8122 adomik Analytics Adapter: sampling revamp, add AB test info, enhance bidWon info
  modules/adomikAnalyticsAdapter.js
  test/spec/modules/adomikAnalyticsAdapter_spec.js
Labels: maintenance

#8247 Apacdex Adapter: change endpoint url and TCF purpose 1 enforcement
  modules/apacdexBidAdapter.js
  test/spec/modules/apacdexBidAdapter_spec.js
Labels: needs docs, maintenance

#8288 Prebid Core: send all bid info within the timeout event
  src/auction.js
  test/spec/auctionmanager_spec.js
Labels: needs 2nd review, maintenance

#8004 OTM bid adapter: use top origin as default domain
  modules/otmBidAdapter.js
  test/spec/modules/otmBidAdapter_spec.js
Labels: maintenance

#8309 PBS adapter: fix bug with priceFloors sometimes not being set in request
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: bugfix

#8216 Prebid Core: Support for multiple bidder codes from a single adapter
  src/adapters/bidderFactory.js
  test/spec/unit/core/bidderFactory_spec.js
Labels: feature, needs docs, needs 2nd review, CORE HIGH IMPACT

#8318 Cointraffic Bidder: domain change
  modules/cointrafficBidAdapter.js
  test/spec/modules/cointrafficBidAdapter_spec.js
Labels: maintenance

#8285 nexx360 Bid Adapter : gvlid added and params updated with bidfloor and keywords support
  modules/nexx360BidAdapter.js
  test/spec/modules/nexx360BidAdapter_spec.js
Labels: maintenance

#8330 Prebid 7: remove appnexusAnalyticsAdapter
  modules/appnexusAnalyticsAdapter.js
Labels: 7.0 API Change

#8297 MobfoxPB Adapter: update adapter to comply with Prebid 5 changes
  modules/mobfoxpbBidAdapter.js
  modules/mobfoxpbBidAdapter.md
  test/spec/modules/mobfoxpbBidAdapter_spec.js
Labels: feature

#8314 Jixie Bid adapter: support more userids
  modules/jixieBidAdapter.js
  modules/jixieBidAdapter.md
  test/spec/modules/jixieBidAdapter_spec.js
Labels: maintenance

#8348 Triplelift Bid Adapter: Updating Prebid floors logic and unit test coverage
  modules/tripleliftBidAdapter.js
  test/spec/modules/tripleliftBidAdapter_spec.js
Labels: maintenance
