Repository prebid/Prebid.js, pull requests merged in 2022-10, with the labels that each got.

#9010 Prebid Core: Improve Native ad robustness to null values
  src/native.js
  test/spec/native_spec.js
Labels: bugfix

#9059 Debugging module: do not force `ad` in mocked bid responses
  modules/debugging/bidInterceptor.js
Labels: bugfix

#9071 AMX: Ignore empty "adUnitId" parameter
  modules/amxBidAdapter.js
  test/spec/modules/amxBidAdapter_spec.js
Labels: maintenance

#9051 ix Bid Adapter: set request source tid to auctionId
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance

#9070 Debugging module: graceful handling of missing sessionStorage
  modules/debugging/debugging.js
  test/spec/modules/debugging_mod_spec.js
Labels: bugfix

#9078 YahooSSP bid adapter: Pass device screen dimensions in payload
  modules/yahoosspBidAdapter.js
  test/spec/modules/yahoosspBidAdapter_spec.js
Labels: maintenance

#9074 Multiple bid adapters: use auctionId for `source.tid`
  modules/adfBidAdapter.js
  modules/adkernelAdnBidAdapter.js
  modules/adxcgBidAdapter.js
  modules/dianomiBidAdapter.js
  modules/finativeBidAdapter.js
  modules/improvedigitalBidAdapter.js
  modules/readpeakBidAdapter.js
  modules/seedingAllianceBidAdapter.js
  modules/sharethroughBidAdapter.js
  modules/talkadsBidAdapter.js
  modules/truereachBidAdapter.js
  modules/ttdBidAdapter.js
  package-lock.json
  test/spec/modules/adfBidAdapter_spec.js
  test/spec/modules/adxcgBidAdapter_spec.js
  test/spec/modules/dianomiBidAdapter_spec.js
  test/spec/modules/sharethroughBidAdapter_spec.js
  test/spec/modules/ttdBidAdapter_spec.js
Labels: bugfix

#9072 Prebid core: accept pub-defined transactionId from `ortb2Imp.ext.tid`
  src/prebid.js
  test/spec/unit/pbjs_api_spec.js
Labels: feature

#8981 Conversant Analytics Adapter: initial release
  modules/conversantAnalyticsAdapter.js
  modules/conversantAnalyticsAdapter.md
  test/spec/modules/conversantAnalyticsAdapter_spec.js
Labels: feature, needs review

#9061 TheMediaGrid: Support multiRequest param
  modules/gridBidAdapter.js
  test/spec/modules/gridBidAdapter_spec.js
Labels: feature

#8865 Prebid Core: Refine coordination of PBS+PBJS Floors
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: feature

#9005 AndBeyond.Media adapter: update bidder code
  modules/beyondmediaBidAdapter.js
  modules/beyondmediaBidAdapter.md
  test/spec/modules/beyondmediaBidAdapter_spec.js
Labels: needs update, maintenance

#9018 Prebid Core: Allow Cpm Custom Rounding
  src/cpmBucketManager.js
  test/spec/cpmBucketManager_spec.js
Labels: feature

#9083 Nativo Bid Adapter: change QS param referrer value
  modules/nativoBidAdapter.js
  test/spec/modules/nativoBidAdapter_spec.js
Labels: maintenance

#9087 Adkernel Bid Adapter: rtbdemand.com alias
  modules/adkernelBidAdapter.js
Labels: maintenance

#9092 Lotame Panorama Id System: bug fixes
  modules/lotamePanoramaIdSystem.js
  test/spec/modules/lotamePanoramaIdSystem_spec.js
Labels: bugfix

#9044 Eplanning Bid Adapter: add support for video
  modules/eplanningBidAdapter.js
  test/spec/modules/eplanningBidAdapter_spec.js
Labels: feature

#9069 ConnectID: Support new easy-opt out method
  modules/connectIdSystem.js
  test/spec/modules/connectIdSystem_spec.js
Labels: maintenance

#9013 Core & multiple modules: introduce new `bidRejected` event, and refactor bid rejection logic
  modules/categoryTranslation.js
  modules/currency.js
  modules/dchain.js
  modules/debugging/legacy.js
  modules/mass.js
  modules/multibid/index.js
  modules/prebidServerBidAdapter/index.js
  modules/priceFloors.js
  src/adapters/bidderFactory.js
  src/auction.js
  src/constants.json
  src/prebid.js
  src/targeting.js
  test/fixtures/fixtures.js
  test/spec/auctionmanager_spec.js
  test/spec/modules/currency_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/priceFloors_spec.js
  test/spec/unit/core/bidderFactory_spec.js
  test/spec/unit/core/targeting_spec.js
  test/spec/unit/pbjs_api_spec.js
Labels: feature

#9097 Yahoo and AOL Bid Adapters: add epsilon user id source
  modules/aolBidAdapter.js
  modules/yahoosspBidAdapter.js
Labels: maintenance

#9091 Appnexus Bid Adapter: add support for debug params via query string
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: maintenance

#9104 Taboola Bid Adapter: fix multiple impressions bug
  modules/taboolaBidAdapter.js
  test/spec/modules/taboolaBidAdapter_spec.js
Labels: bugfix

#9068 Magnite Analytics Adapter: New Adapter
  modules/magniteAnalyticsAdapter.js
  modules/magniteAnalyticsAdapter.md
  modules/rubiconAnalyticsAdapter.js
  test/spec/modules/magniteAnalyticsAdapter_spec.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
Labels: feature

#9099 UserID: call gpt `setPublisherProvidedId` when PPID is available
  modules/userId/index.js
  test/spec/modules/userId_spec.js
Labels: LGTM, bugfix

#9096 Yahoossp and Aol Bid Adapters: Added epsilon.com user id source
  modules/aolBidAdapter.js
  modules/yahoosspBidAdapter.js
  test/spec/modules/aolBidAdapter_spec.js
  test/spec/modules/yahoosspBidAdapter_spec.js
Labels: maintenance

#9067 PixFuture Bid Adapter: redisigned user sync
  modules/pixfutureBidAdapter.js
Labels: bugfix

#9103 Pubmatic Bid Adapter: use new dealpriority in deal tier module execution
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: maintenance

#9112 33Across Bid Adapter: Add structured user agent information to RTB payload
  modules/33acrossBidAdapter.js
  test/spec/modules/33acrossBidAdapter_spec.js
Labels: maintenance

#9109 AdYouLike Bid Adapter : fix page and ref Url values
  modules/adyoulikeBidAdapter.js
  test/spec/modules/adyoulikeBidAdapter_spec.js
Labels: bugfix

#9079 Mediasquare Bid Adapter: add video renderer + change with floors
  modules/mediasquareBidAdapter.js
  test/spec/modules/mediasquareBidAdapter_spec.js
Labels: maintenance

#9107 TTD Bid Adapter: add support for site.ref & user.data
  modules/ttdBidAdapter.js
Labels: maintenance

#9115 1plusX Rtd Module: Add FPID support for PAPI and Fix Test Bug
  modules/1plusXRtdProvider.js
  test/spec/modules/1plusXRtdProvider_spec.js
Labels: bugfix

#9100 PBS Bid Adapter: alias Fix
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: bugfix

#9124 Grid & MGID bid adapters: set `spec.gvlid`
  modules/gridBidAdapter.js
  modules/mgidBidAdapter.js
Labels: bugfix

#9058 IAS RTD Module: custom adUnitPath mapping
  modules/iasRtdProvider.js
  modules/iasRtdProvider.md
  test/spec/modules/iasRtdProvider_spec.js
Labels: maintenance

#9063 Brightcom Bid adapter: add support for uspConsent, coppa, schain, userIdAsEids, userId
  modules/brightcomBidAdapter.js
  test/spec/modules/brightcomBidAdapter_spec.js
Labels: maintenance

#9066 PubWise Bid Adapter: clean up and updates to adUnit parsing
  modules/pubwiseBidAdapter.js
  test/spec/modules/pubwiseBidAdapter_spec.js
Labels: maintenance

#9114 PulsePoint Bid Adapter: First party data
  modules/pulsepointBidAdapter.js
  test/spec/modules/pulsepointBidAdapter_spec.js
Labels: maintenance

#9117 Mgid Bid Adapter: fix usage of ortb2 data
  modules/mgidBidAdapter.js
  test/spec/modules/mgidBidAdapter_spec.js
Labels: maintenance

#9123 FTRACK USER ID MODULE: tweaking the createEidsArray() method to accept two schema patterns
  modules/ftrackIdSystem.js
  modules/userId/eids.js
  test/spec/modules/eids_spec.js
  test/spec/modules/ftrackIdSystem_spec.js
Labels: bugfix

#9086 Weborama RTD Module: add support to asset ids on contextual api
  integrationExamples/gpt/weboramaRtdProvider_example.html
  modules/weboramaRtdProvider.js
  modules/weboramaRtdProvider.md
  test/spec/modules/weboramaRtdProvider_spec.js
Labels: maintenance

#9084 IX Bid Adapter: send bid floor per size in format ext
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance

#9093 Freewheel-SSP Bid Adapter: add alias, update local param, and other additions
  modules/freewheel-sspBidAdapter.js
  modules/freewheel-sspBidAdapter.md
  test/spec/modules/freewheel-sspBidAdapter_spec.js
Labels: maintenance

#9108 Aso Bid Adapter: support schain
  modules/asoBidAdapter.js
  modules/asoBidAdapter.md
  test/spec/modules/asoBidAdapter_spec.js
Labels: maintenance

#9128 Prebid core: restore bid-level `renderer`
  src/auction.js
  test/spec/auctionmanager_spec.js
Labels: bugfix

#9089 Smaato Bid Adapter: Native support
  modules/smaatoBidAdapter.js
  modules/smaatoBidAdapter.md
  test/spec/modules/smaatoBidAdapter_spec.js
Labels: feature

#9127 fledgeForGpt module: docs update
  modules/fledgeForGpt.md
Labels: maintenance

#9090 Medianet Analytics Adapter: Handle edge case in bid won and url changes
  modules/medianetAnalyticsAdapter.js
  test/spec/modules/medianetAnalyticsAdapter_spec.js
Labels: maintenance

#9130 Teads adapter: use user id module and send user-agent client hints
  modules/teadsBidAdapter.js
  test/spec/modules/teadsBidAdapter_spec.js
Labels: maintenance

#9138 Prebid core: do not enforce valid size in bid responses
  src/adapters/bidderFactory.js
  test/spec/unit/core/bidderFactory_spec.js
Labels: bugfix

#9140 Criteo Bid Adapter: add support of static floors
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: maintenance

#8987 CHTNW Adapter: initial release
  modules/chtnwBidAdapter.js
  modules/chtnwBidAdapter.md
  test/spec/modules/chtnwBidAdapter_spec.js
Labels: feature

#8858 Video Module: Initial Release
  integrationExamples/videoModule/jwplayer/bidMarkedAsUsed.html
  integrationExamples/videoModule/jwplayer/bidRequestScheduling.html
  integrationExamples/videoModule/jwplayer/eventListeners.html
  integrationExamples/videoModule/jwplayer/gamAdServerMediation.html
  integrationExamples/videoModule/jwplayer/mediaMetadata.html
  integrationExamples/videoModule/jwplayer/playlist.html
  integrationExamples/videoModule/videojs/bidMarkedAsUsed.html
  integrationExamples/videoModule/videojs/bidRequestScheduling.html
  integrationExamples/videoModule/videojs/eventListeners.html
  integrationExamples/videoModule/videojs/gamAdServerMediation.html
  integrationExamples/videoModule/videojs/mediaMetadata.html
  integrationExamples/videoModule/videojs/playlist.html
  libraries/video/constants/enums.js
  libraries/video/constants/events.js
  libraries/video/constants/ortb.js
  libraries/video/constants/vendorCodes.js
  libraries/video/shared/eventHandler.js
  libraries/video/shared/parentModule.js
  libraries/video/shared/state.js
  libraries/video/shared/vastXmlBuilder.js
  libraries/video/shared/vastXmlEditor.js
  modules/.submodules.json
  modules/appnexusBidAdapter.js
  modules/gridNMBidAdapter.js
  modules/jwplayerVideoProvider.js
  modules/jwplayerVideoProvider.md
  modules/spotxBidAdapter.js
  modules/synacormediaBidAdapter.js
  modules/videoModule/addingSubmodule.md
  modules/videoModule/coreVideo.js
  modules/videoModule/gamAdServerSubmodule.js
  modules/videoModule/index.js
  modules/videoModule/videoImpressionVerifier.js
  modules/videojsVideoProvider.js
  modules/videojsVideoProvider.md
  package-lock.json
  package.json
  src/events.js
  src/prebid.js
  test/spec/modules/videoModule/coreVideo_spec.js
  test/spec/modules/videoModule/pbVideo_spec.js
  test/spec/modules/videoModule/shared/parentModule_spec.js
  test/spec/modules/videoModule/shared/state_spec.js
  test/spec/modules/videoModule/shared/vastXmlBuilder_spec.js
  test/spec/modules/videoModule/shared/vastXmlEditor_spec.js
  test/spec/modules/videoModule/submodules/jwplayerVideoProvider_spec.js
  test/spec/modules/videoModule/submodules/videojsVideoProvider_spec.js
  test/spec/modules/videoModule/videoImpressionVerifier_spec.js
  test/spec/unit/pbjs_api_spec.js
Labels: feature, needs docs

#8738 PBJS-ORTB conversion library
  libraries/ortbConverter/README.md
  libraries/ortbConverter/converter.js
  libraries/ortbConverter/lib/composer.js
  libraries/ortbConverter/lib/mergeProcessors.js
  libraries/ortbConverter/lib/sizes.js
  libraries/ortbConverter/processors/banner.js
  libraries/ortbConverter/processors/default.js
  libraries/ortbConverter/processors/mediaType.js
  libraries/ortbConverter/processors/native.js
  libraries/ortbConverter/processors/video.js
  libraries/pbsExtensions/pbsExtensions.js
  libraries/pbsExtensions/processors/aliases.js
  libraries/pbsExtensions/processors/mediaType.js
  libraries/pbsExtensions/processors/params.js
  libraries/pbsExtensions/processors/pbs.js
  libraries/pbsExtensions/processors/requestExtPrebid.js
  libraries/pbsExtensions/processors/video.js
  modules/consentManagement.js
  modules/consentManagementUsp.js
  modules/currency.js
  modules/improvedigitalBidAdapter.js
  modules/multibid/index.js
  modules/openxOrtbBidAdapter.js
  modules/prebidServerBidAdapter/index.js
  modules/prebidServerBidAdapter/ortbConverter.js
  modules/priceFloors.js
  modules/schain.js
  modules/userId/index.js
  package-lock.json
  src/pbjsORTB.js
  src/utils.js
  src/utils/currency.js
  test/spec/modules/improvedigitalBidAdapter_spec.js
  test/spec/modules/openxOrtbBidAdapter_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/ortbConverter/banner_spec.js
  test/spec/ortbConverter/composer_spec.js
  test/spec/ortbConverter/converter_spec.js
  test/spec/ortbConverter/currency_spec.js
  test/spec/ortbConverter/default_processors_spec.js
  test/spec/ortbConverter/gdpr_spec.js
  test/spec/ortbConverter/mediaTypes_spec.js
  test/spec/ortbConverter/mergeProcessors_spec.js
  test/spec/ortbConverter/multibid_spec.js
  test/spec/ortbConverter/native_spec.js
  test/spec/ortbConverter/pbjsORTB_spec.js
  test/spec/ortbConverter/pbsExtensions/aliases_spec.js
  test/spec/ortbConverter/pbsExtensions/params_spec.js
  test/spec/ortbConverter/pbsExtensions/video_spec.js
  test/spec/ortbConverter/priceFloors_spec.js
  test/spec/ortbConverter/schain_spec.js
  test/spec/ortbConverter/userId_spec.js
  test/spec/ortbConverter/usp_spec.js
  test/spec/ortbConverter/video_spec.js
  test/spec/utils_spec.js
Labels: feature, needs review, needs docs

#9102 Oxxion Rtd Module: initial module release
  modules/oxxionRtdProvider.js
  modules/oxxionRtdProvider.md
  test/spec/modules/oxxionRtdProvider_spec.js
Labels: feature

#9106 Prebid core: return a promise from `requestBids`
  src/prebid.js
  test/spec/unit/pbjs_api_spec.js
Labels: feature

#9150 Price Floors: fix a typo bug with noDecodeURL
  modules/priceFloors.js
Labels: bugfix

#9152 Kargo Bid Adapter: page URL from topmostLocation
  modules/kargoBidAdapter.js
Labels: LGTM, maintenance

#9122 Concert Bid Adapter: Add prebid unified ID 2.0 and slot coordinates
  modules/concertBidAdapter.js
  test/spec/modules/concertBidAdapter_spec.js
Labels: maintenance

#9155 Teads Bid Adapter: add the gvlid declaration
  modules/teadsIdSystem.js
Labels: maintenance

#9135 AAX Blockmeter RTD Module : Initial Release
  modules/.submodules.json
  modules/aaxBlockmeterRtdProvider.js
  modules/aaxBlockmeterRtdProvider.md
  src/adloader.js
  test/spec/modules/aaxBlockmeter_spec.js
Labels: feature

#9116 Multiple modules: USP data deletion event handling
  modules/consentManagementUsp.js
  modules/rtdModule/index.js
  modules/userId/index.js
  src/adapterManager.js
  test/spec/modules/consentManagementUsp_spec.js
  test/spec/modules/realTimeDataModule_spec.js
  test/spec/modules/userId_spec.js
  test/spec/unit/core/adapterManager_spec.js
Labels: feature

#9156 IX Bid Adapter: completely change request to POST method
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance

#9146 dgkeywordRtdProvider submodule: fix to set default setting of reading FPID
  modules/dgkeywordRtdProvider.js
  test/spec/modules/dgkeywordRtdProvider_spec.js
Labels: bugfix

#9125 Improve Digital adapter: publisher endpoint, addtl consent, syncs
  modules/improvedigitalBidAdapter.js
  test/spec/modules/improvedigitalBidAdapter_spec.js
Labels: maintenance

#9151 Criteo Bid Adapter : Bump Publisher Tag version
  modules/criteoBidAdapter.js
Labels: maintenance

#9136 Prebid core: allow configurable TTL buffer
  src/auction.js
  src/prebid.js
  src/targeting.js
  test/spec/auctionmanager_spec.js
  test/spec/unit/core/targeting_spec.js
  test/spec/unit/pbjs_api_spec.js
Labels: feature

#9168 IX Bid Adapter: increase request size limit
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance

#9120 Mgid RTD Module : add new RTD module
  integrationExamples/gpt/mgidRtdProvider_example.html
  modules/.submodules.json
  modules/mgidRtdProvider.js
  modules/mgidRtdProvider.md
  test/spec/modules/mgidRtdProvider_spec.js
Labels: feature

#9173 IX Bid Adapter: Media Type Specific SiteId Support
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance

#9133 Admatic Bid Adapter: initial adapter release
  modules/admaticBidAdapter.js
  modules/admaticBidAdapter.md
  src/adloader.js
  test/spec/modules/admaticBidAdapter_spec.js
Labels: feature

#9174 FtrackId: correcting the eid object schema
  modules/userId/eids.js
  test/spec/modules/eids_spec.js
  test/spec/modules/ftrackIdSystem_spec.js
Labels: bugfix
