Repository prebid/Prebid.js, pull requests merged in 2023-10, with the labels that each got.

#10556 Sharethrough Bid Adapter: revise getUserSyncs method
  modules/sharethroughBidAdapter.js
  test/spec/modules/sharethroughBidAdapter_spec.js
Labels: maintenance

#10489 Edge226 Bid Adapter : initial release
  modules/edge226BidAdapter.js
  modules/edge226BidAdapter.md
  test/spec/modules/edge226BidAdapter_spec.js
Labels: feature

#10519 NoBid Bid Adapter : add support for first party user id
  modules/nobidBidAdapter.js
  test/spec/modules/nobidBidAdapter_spec.js
Labels: maintenance

#10559 Liveintent & UID2 ID systems: share EID configuration
  libraries/uid2Eids/uid2Eids.js
  modules/liveIntentIdSystem.js
  modules/uid2IdSystem.js
Labels: bugfix

#10561 GumGum Bid Adapter: Send pubProvidedId in the query string
  modules/gumgumBidAdapter.js
  test/spec/modules/gumgumBidAdapter_spec.js
Labels: maintenance

#10477 RAS Bid Adapter: fledge support
  modules/rasBidAdapter.js
  test/spec/modules/rasBidAdapter_spec.js
Labels: needs unit tests, maintenance

#10415 Lm_Kiviads Bid Adapter : initial adapter release
  modules/lm_kiviadsBidAdapter.js
  modules/lm_kiviadsBidAdapter.md
  test/spec/modules/lm_kiviadsBidAdapter_spec.js
Labels: feature

#10382 Outbrain adapter: Read OB user token from local storage
  modules/outbrainBidAdapter.js
  test/spec/modules/outbrainBidAdapter_spec.js
Labels: needs unit tests

#10563 Lm_Kiviads Bid Adapter : fix getAdUnitSizes location
  modules/lm_kiviadsBidAdapter.js
Labels: bugfix

#10562 imds Bid Adapter : fix incorrectly named user sync property
  modules/imdsBidAdapter.js
  modules/imdsBidAdapter.md
  test/spec/modules/imdsBidAdapter_spec.js
Labels: bugfix

#10569 Preciso BidAdapter : modified BidderRequest params
  integrationExamples/gpt/hello_world.html
  modules/precisoBidAdapter.js
  test/spec/modules/precisoBidAdapter_spec.js
Labels: maintenance

#10558 Core & currency module: fix bug where bid responses are collected after auction ends
  modules/currency.js
  src/auction.js
  test/spec/auctionmanager_spec.js
  test/spec/modules/currency_spec.js
Labels: bugfix

#10571 Mediasquare Bid Adapter: add attribute to track
  modules/mediasquareBidAdapter.js
  test/spec/modules/mediasquareBidAdapter_spec.js
Labels: maintenance

#10570 LiveIntent UserId module: Add support for openx and pubmatic id
  modules/liveIntentIdSystem.js
  test/spec/modules/eids_spec.js
  test/spec/modules/liveIntentIdMinimalSystem_spec.js
  test/spec/modules/liveIntentIdSystem_spec.js
Labels: maintenance

#10574 consentManagementUsp: fix bug where data deletion events are triggered when CMP does not support `registerDeletion`
  modules/consentManagementUsp.js
  test/spec/modules/consentManagementUsp_spec.js
Labels: bugfix

#10564 Oxxion Analytics Adapter : changes in bidwon
  modules/oxxionAnalyticsAdapter.js
  test/spec/modules/oxxionAnalyticsAdapter_spec.js
Labels: maintenance

#10576 YahooAds Bid Adapter: Documentation update
  modules/yahoosspBidAdapter.md
Labels: maintenance

#10543 Doceree Bid Adaptor: bidwon and timeout hooks added
  modules/docereeBidAdapter.js
  test/spec/modules/docereeBidAdapter_spec.js
Labels: maintenance

#10581 Sovrn Bid Adapter: make minduration optional
  modules/sovrnBidAdapter.js
  test/spec/modules/sovrnBidAdapter_spec.js
Labels: maintenance

#10499 Bliink Bid Adapter: enhance request data with eids, bidFloor, device info & domLoadingDuration
  modules/bliinkBidAdapter.js
  test/spec/modules/bliinkBidAdapter_spec.js
Labels: maintenance

#10586 OperaAds Bid Adapter : add gvlid
  modules/operaadsBidAdapter.js
Labels: maintenance

#10589 Kargo Bid Adapter: adding site to Kargo adapter
  modules/kargoBidAdapter.js
  test/spec/modules/kargoBidAdapter_spec.js
Labels: maintenance

#10541 Prebid core: cached bids should contain the ID of the auction they actually won
  src/targeting.js
  test/spec/unit/core/targeting_spec.js
  test/spec/unit/pbjs_api_spec.js
Labels: feature

#10466 Underdogmedia Bid Adapter: Update pbTimeout Assignment
  modules/underdogmediaBidAdapter.js
  test/spec/modules/underdogmediaBidAdapter_spec.js
Labels: needs unit tests, bugfix

#10494 Adspirit Bid Adapter : initial release
  modules/adspiritBidAdapter.js
  modules/adspiritBidAdapter.md
Labels: feature

#10600 Bucksense bid adapter: add missing gvlid
  modules/bucksenseBidAdapter.js
Labels: maintenance

#10579 VRTCAL Bid Adapter : updated user sync support
  modules/vrtcalBidAdapter.js
  test/spec/modules/vrtcalBidAdapter_spec.js
Labels: maintenance

#10603 Qortex RTD Provider: add module to submodules.json
  modules/.submodules.json
Labels: maintenance

#10606 Revert "Utiq ID submodule: Update submodule name and parameters"
  modules/.submodules.json
  modules/utiqSystem.js
  modules/utiqSystem.md
  test/spec/modules/utiqSystem_spec.js
Labels: maintenance

#10577 PubmaticBidAdapter: Read and pass gpid from ortb2imp.ext in API call
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: maintenance

#10609 IX Bid Adapter: add EUID abd Criteo to EID allowlist
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance

#10618 Kargo Bid Adapter: Updates to GPID retrieval
  modules/kargoBidAdapter.js
  test/spec/modules/kargoBidAdapter_spec.js
Labels: maintenance

#10616 Various modules: Received spelling
  modules/priceFloors.js
  modules/pubmaticAnalyticsAdapter.js
  modules/qortexRtdProvider.js
  modules/topicsFpdModule.js
  test/spec/modules/concertBidAdapter_spec.js
  test/spec/modules/qortexRtdProvider_spec.js
Labels: maintenance

#10588 FreeWheel Bid Adapter: support passing content object in config
  modules/freewheel-sspBidAdapter.js
  test/spec/modules/freewheel-sspBidAdapter_spec.js
Labels: maintenance

#10597 Zeta Global SSP Bid Adapter: change shortname to no longer be a required parameter
  modules/zeta_global_sspBidAdapter.js
  test/spec/modules/zeta_global_sspBidAdapter_spec.js
Labels: maintenance

#10584 DXKulture Bid Adapter: implementing ORTB conversion library
  modules/dxkultureBidAdapter.js
  modules/dxkultureBidAdapter.md
  test/spec/modules/dxkultureBidAdapter_spec.js
Labels: feature, LGTM

#10631 LiveIntent UserId module: update LiveConnect dependency; fix caching bug
  package-lock.json
  package.json
Labels: maintenance

#10510 UID2: support Client-side token generation and build tag
  features.json
  modules/uid2IdSystem.js
  modules/uid2IdSystem_shared.js
  test/spec/modules/euidIdSystem_spec.js
  test/spec/modules/uid2IdSystem_helpers.js
  test/spec/modules/uid2IdSystem_spec.js
Labels: feature

#10551 Jixie Bid Adapter : support ids extraction based on config object and misc. changes
  modules/jixieBidAdapter.js
  test/spec/modules/jixieBidAdapter_spec.js
Labels: maintenance

#10630 Criteo Id module: Update to comply with storage.type value
  modules/criteoIdSystem.js
  test/spec/modules/criteoIdSystem_spec.js
Labels: maintenance

#10629 UID2 module: Add documentation for cstg
  modules/uid2IdSystem.md
Labels: maintenance

#10608 PBjs Core : Update RTDs not in .submodules
  modules/.submodules.json
Labels: needs 2nd review, maintenance

#10590 Yahoo ConnectId Module : backend sync updates.
  modules/connectIdSystem.js
  test/spec/modules/connectIdSystem_spec.js
Labels: maintenance

#10628 Flipp Bid Adapter: add additional check for userKey value, update docs
  modules/flippBidAdapter.js
  modules/flippBidAdapter.md
Labels: maintenance

#10643 Snigel bid adapter: include query string in page field (7.54.x-legacy)
  modules/snigelBidAdapter.js
  test/spec/modules/snigelBidAdapter_spec.js
Labels: maintenance

#10644 Snigel bid adapter: include query string in page field
  modules/snigelBidAdapter.js
  test/spec/modules/snigelBidAdapter_spec.js
Labels: maintenance

#10640 ShowHeroes bid adapter: use gvlid
  modules/showheroes-bsBidAdapter.js
Labels: maintenance

#10651 Docs : remove documentation that coppa needs to come from getConfig
  PR_REVIEW.md
Labels: maintenance

#10633 Adagio Bid Adapter : adapt video outstream implementation docs
  modules/adagioBidAdapter.js
  modules/adagioBidAdapter.md
Labels: maintenance

#10582 Sparteo Bid Adapter: initial release
  modules/sparteoBidAdapter.js
  modules/sparteoBidAdapter.md
  test/spec/modules/sparteoBidAdapter_spec.js
Labels: feature

#10624 A1media Bid Adpater: resolve AUCTION_PRICE macro
  modules/a1MediaBidAdapter.js
  test/spec/modules/a1MediaBidAdapter_spec.js
Labels: bugfix

#10604 Connatix Bid Adapter : update PlayerId, CustomerId and Referrer
  modules/connatixBidAdapter.js
  modules/connatixBidAdapter.md
  test/spec/modules/connatixBidAdapter_spec.js
Labels: maintenance

#10615 Discovery Bid Adapter: add adUnitCode, gpid, and adslot
  modules/discoveryBidAdapter.js
  test/spec/modules/discoveryBidAdapter_spec.js
Labels: maintenance

#10598 Programmatica Bid Adapter : initial release
  modules/programmaticaBidAdapter.js
  modules/programmaticaBidAdapter.md
  test/spec/modules/programmaticaBidAdapter_spec.js
Labels: feature

#10601 Impactify Bid Adapter : add different mediatypes and manage local storage
  modules/impactifyBidAdapter.js
  modules/impactifyBidAdapter.md
  test/spec/modules/impactifyBidAdapter_spec.js
Labels: maintenance

#10377 dynamicAdBoostModule: New module
  modules/dynamicAdBoostRtdProvider.js
  modules/dynamicAdBoostRtdProvider.md
  test/spec/modules/dynamicAdBoostRtdProvider_spec.js
Labels: feature

#10659 Kargo Bid Adapter: Support for sending ortb2.user.data
  modules/kargoBidAdapter.js
  test/spec/modules/kargoBidAdapter_spec.js
Labels: maintenance

#10660 sspBC Bid Adapter: update video detection for VAST4
  modules/sspBCBidAdapter.js
Labels: bugfix

#10649 fledgeForGpt: use `imp.ext.ae` instead of `defaultForSlots`; add `prebid.ortb2` and `prebid.ortb2Imp` auction signals
  modules/fledgeForGpt.js
  modules/prebidServerBidAdapter/index.js
  modules/prebidServerBidAdapter/ortbConverter.js
  src/adapters/bidderFactory.js
  test/spec/modules/fledgeForGpt_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/unit/core/bidderFactory_spec.js
Labels: feature

#10662 Orbidder changes: send all Prebid.JS bidRequests fields to orbidder
  modules/orbidderBidAdapter.js
  test/spec/modules/orbidderBidAdapter_spec.js
Labels: maintenance

#10667 Insticator Bid Adapter : get config fix for device
  modules/insticatorBidAdapter.js
Labels: maintenance
