Repository prebid/Prebid.js, pull requests merged in 2023-08, with the labels that each got.

#10186 Connatix Bid Adapter : Initial Release
  modules/connatixBidAdapter.js
  modules/connatixBidAdapter.md
  test/spec/modules/connatixBidAdapter_spec.js
Labels: feature

#10293 Undertone Bid Adapter : documentation update
  modules/undertoneBidAdapter.md
Labels: maintenance

#10307 Mediasquare Bid Adapter : convert bid attributes to string
  modules/mediasquareBidAdapter.js
  test/spec/modules/mediasquareBidAdapter_spec.js
Labels: bugfix

#10301 AdsInteractive Bid Adapter : added gvlid
  modules/adsinteractiveBidAdapter.js
Labels: maintenance

#10314 Criteo Bid Adapter: do not call API when dataDeletionRequest has no id
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: bugfix

#10295 Doumentation : update eids.md
  modules/userId/eids.md
Labels: maintenance

#10310 AdGeneration Bid Adapter : fix userSync
  modules/adgenerationBidAdapter.js
  test/spec/modules/adgenerationBidAdapter_spec.js
Labels: bugfix

#10315 Grid Bid Adapter: fix GPID priorities
  modules/gridBidAdapter.js
  test/spec/modules/gridBidAdapter_spec.js
Labels: bugfix

#10303 Freepass Bid Adaptor : add publisher param, also set site,source
  modules/freepassBidAdapter.js
  modules/freepassBidAdapter.md
  test/spec/modules/freepassBidAdapter_spec.js
Labels: feature

#10279 Optidigital Bid Adapter : update usersync
  modules/optidigitalBidAdapter.js
  test/spec/modules/optidigitalBidAdapter_spec.js
Labels: maintenance

#10243 Snigel Bid Adapter: GPP support
  modules/snigelBidAdapter.js
  modules/snigelBidAdapter.md
  test/spec/modules/snigelBidAdapter_spec.js
Labels: maintenance

#10316 Smartyads Bid Adapter: bid won functionality
  modules/smartyadsBidAdapter.js
  test/spec/modules/smartyadsBidAdapter_spec.js
Labels: maintenance

#10322 A1Media RTD Module: fix cookie name
  modules/a1MediaRtdProvider.js
Labels: bugfix

#10323 Nativo Bid Adapter : changed request method to POST and added OpenRTB payload
  modules/nativoBidAdapter.js
  test/spec/modules/nativoBidAdapter_spec.js
Labels: maintenance

#10288 Criteo Bid Adapter : interpreting bid response without zone id provided in request
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: bugfix

#10294 AdRelevantis Bid Adapter: parseMediaType to support NATIVE
  modules/adrelevantisBidAdapter.js
Labels: bugfix

#10327 Brandmetrics RTD Module : set default value of consent to undefined
  modules/brandmetricsRtdProvider.js
  test/spec/modules/brandmetricsRtdProvider_spec.js
Labels: bugfix

#10333 CriteoBidAdapter : bump fast bid current version to 139
  modules/criteoBidAdapter.js
Labels: maintenance

#10332 Rubicon Bid Adapter: fix saving state of single request option
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: bugfix

#10334 LiveIntent UserId module: Add support for index id
  modules/liveIntentIdSystem.js
  test/spec/modules/eids_spec.js
  test/spec/modules/liveIntentIdMinimalSystem_spec.js
  test/spec/modules/liveIntentIdSystem_spec.js
Labels: maintenance

#10124 Topics Module: Support for Fetch Header Functionality
  integrationExamples/topics/topics-server.js
  modules/topicsFpdModule.js
  test/spec/modules/topicsFpdModule_spec.js
Labels: feature

#10284 Prebid core: fix ortb native to legacy to use imptrackers
  src/native.js
  test/spec/native_spec.js
Labels: bugfix

#10291 Geoedge RTD module: support monitoring all GPT ad slots
  modules/geoedgeRtdProvider.js
  modules/geoedgeRtdProvider.md
  src/adloader.js
  test/spec/modules/geoedgeRtdProvider_spec.js
Labels: maintenance

#10292 AdMatic Bid Adapter: added ortb2Imp params
  modules/admaticBidAdapter.js
  test/spec/modules/admaticBidAdapter_spec.js
Labels: maintenance

#10304 Oxxion Analytics Adapter : support new attributes
  modules/oxxionAnalyticsAdapter.js
  test/spec/modules/oxxionAnalyticsAdapter_spec.js
Labels: maintenance

#10336 Criteo Bid Adapter : Pass bid id through criteo bid adapter
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: maintenance

#10326 Bid Viewability Module: Support Core's Billing Deferral Logic
  modules/bidViewability.js
  modules/bidViewability.md
  test/spec/modules/bidViewability_spec.js
Labels: feature

#10335 LiveIntent Id module: Update dependency of Live Connect
  package-lock.json
  package.json
Labels: maintenance

#10341 liveIntent Id System: fix ix eid mismatch with ix adapter
  modules/liveIntentIdSystem.js
  test/spec/modules/eids_spec.js
Labels: bugfix

#10344 Nexx360 Bid Adapter : Ad and adUrl banner split
  modules/nexx360BidAdapter.js
  test/spec/modules/nexx360BidAdapter_spec.js
Labels: maintenance

#10346 Adagio Bid Adapter : enrich bid params
  modules/adagioBidAdapter.js
  test/spec/modules/adagioBidAdapter_spec.js
Labels: maintenance

#10328 PubMatic Analytics Adapter : log floor values only when floor file is fetched successfully
  modules/pubmaticAnalyticsAdapter.js
  src/constants.json
  test/spec/modules/pubmaticAnalyticsAdapter_spec.js
Labels: maintenance

#10271 Native: privacyLink is now converted to ortb.privacy
  src/constants.json
  src/native.js
  test/spec/native_spec.js
Labels: bugfix

#10136 fledgeForGpt: consolidate publisher configuration
  modules/fledgeForGpt.js
  modules/fledgeForGpt.md
  test/spec/modules/fledge_spec.js
Labels: maintenance

#10340 Core: enable `Sec-Browsing-Topics` header on outgoing bidder requests
  modules/geoedgeRtdProvider.js
  modules/prebidServerBidAdapter/index.js
  src/adapters/bidderFactory.js
  src/ajax.js
  test/mocks/xhr.js
  test/spec/modules/adlooxAdServerVideo_spec.js
  test/spec/modules/adlooxRtdProvider_spec.js
  test/spec/modules/categoryTranslation_spec.js
  test/spec/modules/conversantAnalyticsAdapter_spec.js
  test/spec/modules/currency_spec.js
  test/spec/modules/dmdIdSystem_spec.js
  test/spec/modules/euidIdSystem_spec.js
  test/spec/modules/feedadBidAdapter_spec.js
  test/spec/modules/geoedgeRtdProvider_spec.js
  test/spec/modules/greenbidsRtdProvider_spec.js
  test/spec/modules/hadronIdSystem_spec.js
  test/spec/modules/id5AnalyticsAdapter_spec.js
  test/spec/modules/id5IdSystem_spec.js
  test/spec/modules/identityLinkIdSystem_spec.js
  test/spec/modules/intentIqIdSystem_spec.js
  test/spec/modules/invisiblyAnalyticsAdapter_spec.js
  test/spec/modules/jwplayerRtdProvider_spec.js
  test/spec/modules/magniteAnalyticsAdapter_spec.js
  test/spec/modules/mgidRtdProvider_spec.js
  test/spec/modules/oguryBidAdapter_spec.js
  test/spec/modules/ooloAnalyticsAdapter_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/priceFloors_spec.js
  test/spec/modules/publinkIdSystem_spec.js
  test/spec/modules/pubmaticAnalyticsAdapter_spec.js
  test/spec/modules/pubwiseAnalyticsAdapter_spec.js
  test/spec/modules/teadsIdSystem_spec.js
  test/spec/modules/uid2IdSystem_helpers.js
  test/spec/modules/uid2IdSystem_spec.js
  test/spec/modules/userId_spec.js
  test/spec/modules/zeta_global_sspAnalyticsAdapter_spec.js
  test/spec/unit/core/ajax_spec.js
  test/spec/unit/core/bidderFactory_spec.js
  test/spec/videoCache_spec.js
Labels: feature

#10354 Activity Controls GPP: invalidate covered = 0 in mspa
  libraries/mspa/activityControls.js
  test/spec/libraries/mspa/activityControls_spec.js
Labels: feature

#10339 GrowthCode Analytics: Updates/BugFixes
  integrationExamples/gpt/growthcode.html
  modules/growthCodeAnalyticsAdapter.js
  modules/growthCodeAnalyticsAdapter.md
  test/spec/modules/growthCodeAnalyticsAdapter_spec.js
Labels: maintenance

#10360 fledgeForGpt: consolidate publisher configuration
  modules/fledgeForGpt.js
  modules/fledgeForGpt.md
  test/spec/modules/fledge_spec.js
Labels: feature

#10361 fluct Bid Adapter: add gpid to bid requests
  modules/fluctBidAdapter.js
  test/spec/modules/fluctBidAdapter_spec.js
Labels: maintenance

#10355 identityLinkSubmodule: add additional check on retrieving the envelope
  modules/identityLinkIdSystem.js
  test/spec/modules/identityLinkIdSystem_spec.js
Labels: bugfix

#10342 Cadent Aperture MX Bid Adapter: support GPP and GPP Section Ids
  modules/cadentApertureMXBidAdapter.js
  test/spec/modules/cadentApertureMXBidAdapter_spec.js
Labels: maintenance

#10363 Yieldmo Bid Adapter : adding 4.x VAST protocol support
  modules/yieldmoBidAdapter.js
  test/spec/modules/yieldmoBidAdapter_spec.js
Labels: bugfix

#10197 Relay Bid Adapter : Initial Release
  modules/relayBidAdapter.js
  modules/relayBidAdapter.md
  test/spec/modules/relayBidAdapter_spec.js
Labels: feature

#10362 Prebid Server adapter: improve cookie_sync tests, check GPP fields are populated
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: maintenance

#10318 fluct Bid Adapter: add user.data to bid requests
  modules/fluctBidAdapter.js
  test/spec/modules/fluctBidAdapter_spec.js
Labels: maintenance

#10259 Core: add privacyIcon to not native asset list
  src/constants.json
Labels: on hold, bugfix

#10371 PubMatic Bid Adapter : Support geo (lat & lon) using ortb2.(device|user)
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: maintenance

#10369 Jixie adapter changes: adding sendingi of gpid, and send several ids that sits in first party cookie
  modules/jixieBidAdapter.js
  test/spec/modules/jixieBidAdapter_spec.js
Labels: maintenance

#10306 KueezRtb Bid Adapter: pass gpp consent to userSync server.
  modules/kueezRtbBidAdapter.js
  test/spec/modules/kueezRtbBidAdapter_spec.js
Labels: maintenance

#10287 NoBid Bid Adapter: Support for GPP 1.1
  modules/nobidBidAdapter.js
  modules/nobidBidAdapter.md
  test/spec/modules/nobidBidAdapter_spec.js
Labels: maintenance

#10372 Yandex Bid Adapter: add userIdAsEids
  modules/yandexBidAdapter.js
  test/spec/modules/yandexBidAdapter_spec.js
Labels: maintenance

#10380 Adkernel Bid Adapter: add Headbidder alias
  modules/adkernelBidAdapter.js
Labels: feature

#10138 Preciso Bid adapter : Initial release
  modules/precisoBidAdapter.js
  modules/precisoBidAdapter.md
  test/spec/modules/precisoBidAdapter_spec.js
Labels: feature

#10312 Adquery Bid Adapter : fix getId and decode method
  modules/adqueryBidAdapter.js
  modules/adqueryIdSystem.js
  test/spec/modules/adqueryIdSystem_spec.js
Labels: bugfix

#10385 Triplelift Bid Adapter: PAAPI bid response support
  modules/tripleliftBidAdapter.js
  test/spec/modules/tripleliftBidAdapter_spec.js
Labels: feature

#10383 geolocationRtdProvider: fix `geo.lastfix`
  modules/geolocationRtdProvider.js
  test/spec/modules/geolocationRtdProvider_spec.js
Labels: bugfix

#10384 teadsBidAdapter: Send pageTitle + pageDescription
  modules/teadsBidAdapter.js
  test/spec/modules/teadsBidAdapter_spec.js
Labels: maintenance

#10374 PubMatic Analytics Adapter: Handled bid rejection in case of "Floor not met"
  modules/pubmaticAnalyticsAdapter.js
  test/spec/modules/pubmaticAnalyticsAdapter_spec.js
Labels: maintenance

#10389 AlkimiBidAdapter: add GVL_ID
  modules/alkimiBidAdapter.js
Labels: maintenance

#10388 Sharethrough Bid Adapter: add GDPR and GPP support
  modules/sharethroughBidAdapter.js
  test/spec/modules/sharethroughBidAdapter_spec.js
Labels: maintenance

#10394 Pubmatic Analytics Adapter : changing the dealId default value
  modules/pubmaticAnalyticsAdapter.js
  test/spec/modules/pubmaticAnalyticsAdapter_spec.js
Labels: maintenance

#10343 NoBid Analytics Adapter: initial release
  modules/nobidAnalyticsAdapter.js
  modules/nobidAnalyticsAdapter.md
  test/spec/modules/nobidAnalyticsAdapter_spec.js
Labels: feature

#10401 Rubicon Bid Adapter: params.position NATIVE Fix
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: bugfix

#10358 kulturemedia bid adapter: rebrand to dxkulture
  modules/dxkultureBidAdapter.js
  modules/dxkultureBidAdapter.md
  test/spec/modules/dxkultureBidAdapter_spec.js
Labels: maintenance

#10399 Magnite Analytics Adapter:support for eventDispatcher
  modules/magniteAnalyticsAdapter.js
  test/spec/modules/magniteAnalyticsAdapter_spec.js
Labels: feature

#10395 Eplanning Bid Adapter : add floors support
  modules/eplanningBidAdapter.js
  test/spec/modules/eplanningBidAdapter_spec.js
Labels: maintenance

#10330 gptPreAuction: fix bug where adServer object are not set in case of twin ad unit
  modules/gptPreAuction.js
  test/spec/modules/gptPreAuction_spec.js
Labels: bugfix

#10408 Triplelift Bid Adapter: stop override on placement
  modules/tripleliftBidAdapter.js
Labels: bugfix

#10409 Rubicon Bid Adapter: Format rubicon EID
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: maintenance

#10420 Hadron ID System : remove unused parameters from documentation
  modules/hadronIdSystem.md
Labels: maintenance

#10423 SmileWanted Bid Adapter : add gvlid
  modules/smilewantedBidAdapter.js
Labels: maintenance
