Repository prebid/Prebid.js, pull requests merged in 2023-04, with the labels that each got.

#9748 TheMediaGrid Bid Adapter : update gpid logic
  modules/gridBidAdapter.js
  test/spec/modules/gridBidAdapter_spec.js
Labels: bugfix

#9740 StroeerCore Bid Adapter: handle gdpr applies correctly
  modules/stroeerCoreBidAdapter.js
  test/spec/modules/stroeerCoreBidAdapter_spec.js
Labels: bugfix

#9750 Dspx Bid Adapter : fix Linting Error
  modules/dspxBidAdapter.js
Labels: bugfix

#9603 BEdigitech Bid Adapter: New Bid Adapter
  modules/bedigitechBidAdapter.js
  modules/bedigitechBidAdapter.md
  test/spec/modules/bedigitechBidAdapter_spec.js
Labels: feature

#9737 AMX Bid Adapter: assumed filterSettings is not null
  modules/amxBidAdapter.js
  test/spec/modules/amxBidAdapter_spec.js
Labels: bugfix

#9739 Prebid Core: update secureCreatives.js error msg format
  src/secureCreatives.js
Labels: maintenance

#9756 SharedID: wait for ID from pixel on first page load
  modules/sharedIdSystem.js
  modules/userId/index.js
  test/spec/modules/userId_spec.js
Labels: bugfix

#9759 Vidoomy Bid Adapter: schain serialize fixes
  modules/vidoomyBidAdapter.js
  test/spec/modules/vidoomyBidAdapter_spec.js
Labels: bugfix

#9745 Rubicon Bid Adapter: add ext.tid to slot params data
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: maintenance

#9617 Multiple Adapters : removing cross-module imports
  modules/adagioBidAdapter.js
  modules/adyoulikeBidAdapter.js
  modules/bluebillywigBidAdapter.js
  modules/connectadBidAdapter.js
  modules/impactifyBidAdapter.js
  modules/mediakeysBidAdapter.js
  modules/sharethroughBidAdapter.js
  modules/smartadserverBidAdapter.js
  modules/sovrnBidAdapter.js
  modules/ttdBidAdapter.js
  modules/yieldmoBidAdapter.js
  test/spec/modules/adagioBidAdapter_spec.js
  test/spec/modules/adyoulikeBidAdapter_spec.js
  test/spec/modules/bluebillywigBidAdapter_spec.js
  test/spec/modules/connectadBidAdapter_spec.js
  test/spec/modules/improvedigitalBidAdapter_spec.js
  test/spec/modules/mediakeysBidAdapter_spec.js
  test/spec/modules/sharethroughBidAdapter_spec.js
  test/spec/modules/smartadserverBidAdapter_spec.js
  test/spec/modules/sovrnBidAdapter_spec.js
  test/spec/modules/ttdBidAdapter_spec.js
  test/spec/modules/yieldmoBidAdapter_spec.js
Labels: maintenance

#8293 Build system: do not allow cross-module imports
  modules/audiencerunBidAdapter.js
  modules/jixieBidAdapter.js
  plugins/eslint/validateImports.js
  test/spec/modules/audiencerunBidAdapter_spec.js
  test/spec/modules/jixieBidAdapter_spec.js
Labels: improvement, maintenance

#9670 Core: cache `refererInfo` as long as location does not change
  src/refererDetection.js
  test/spec/refererDetection_spec.js
Labels: feature

#9690 Greenbids Analytics Adapter: create new analytics adapter for Greenbids
  modules/greenbidsAnalyticsAdapter.js
  modules/greenbidsAnalyticsAdapter.md
  test/spec/modules/greenbidsAnalyticsAdapter_spec.js
Labels: feature

#9755 Id5Id: Add localStorage availability to id5id fetch request
  modules/id5IdSystem.js
  test/spec/modules/id5IdSystem_spec.js
Labels: maintenance

#9757 Craft Bid Adapter : update for imuIdSystem
  modules/craftBidAdapter.js
Labels: maintenance

#9764 ZetaGlobalSsp Bid Adapter: provide tagid from params
  modules/zeta_global_sspBidAdapter.js
  test/spec/modules/zeta_global_sspBidAdapter_spec.js
Labels: maintenance

#9765 AIDEM Bid Adapter: extended app/site parameters on win notice
  modules/aidemBidAdapter.js
  test/spec/modules/aidemBidAdapter_spec.js
Labels: maintenance

#9753 BrightcomSSP, Brightcom bid adapters: remove options overwrite from buildRequests
  modules/brightcomBidAdapter.js
  modules/brightcomSSPBidAdapter.js
Labels: bugfix

#9762 TTD Bid Adapter: add support for video.plcmt and imp.rwdd
  modules/ttdBidAdapter.js
  test/spec/modules/ttdBidAdapter_spec.js
Labels: maintenance

#9754 Criteo ID Module: Add error callback for pixel sync call
  modules/criteoIdSystem.js
  test/spec/modules/criteoIdSystem_spec.js
Labels: maintenance

#9701 PubMatic Bid Adapter: native 1.2 support
  modules/pubmaticAnalyticsAdapter.js
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: feature

#9778 Undertone Bid Adapter: add gvlid
  modules/undertoneBidAdapter.js
Labels: maintenance

#9777 Appnexus Bid dapter : add GVLIDs to aliases
  modules/appnexusBidAdapter.js
Labels: maintenance

#9779 Gumgum Bid Adapter: add gvlid, remove digitrust
  modules/gumgumBidAdapter.js
Labels: maintenance

#9742 Adrino Bid Adapter: multiple bids in one request to Adrino Adserver
  modules/adrinoBidAdapter.js
  test/spec/modules/adrinoBidAdapter_spec.js
Labels: feature

#9772 AJA Bid Adapter: adding banner size map support
  modules/ajaBidAdapter.js
Labels: maintenance

#9782 OpenxOrtbAdapter: add back missing params support for coppa and video
  modules/openxOrtbBidAdapter.js
  modules/openxOrtbBidAdapter.md
  test/spec/modules/openxOrtbBidAdapter_spec.js
Labels: maintenance

#9749 vidazoo Bid Adapter: update support of metaData
  modules/vidazooBidAdapter.js
  test/spec/modules/vidazooBidAdapter_spec.js
Labels: maintenance

#9780 Concert Bid Adapter: Enable support for additional userId's
  modules/concertBidAdapter.js
  test/spec/modules/concertBidAdapter_spec.js
Labels: maintenance

#9752 Prebid core: fix image assets in converted legacy response
  src/native.js
  test/spec/auctionmanager_spec.js
Labels: needs 2nd review, bugfix

#9751 Mgid Adapter: update & refactor
  modules/mgidBidAdapter.js
  test/spec/modules/mgidBidAdapter_spec.js
Labels: maintenance

#9790 OpenXOrtb Bid Adapter: fix multiformat requests
  modules/openxOrtbBidAdapter.js
  test/spec/modules/openxOrtbBidAdapter_spec.js
Labels: bugfix

#9793 IX Bid Adapter: refactor build request method and ft improvements
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance

#9716 Yahoo ConnectId UserID Module: explicit storage management
  modules/connectIdSystem.js
  modules/connectIdSystem.md
  test/spec/modules/connectIdSystem_spec.js
Labels: maintenance

#9796 Ogury Bid Adapter: add device pixel density in bid request
  modules/oguryBidAdapter.js
  test/spec/modules/oguryBidAdapter_spec.js
Labels: maintenance

#9785 Growthcode UserId: Bug fixes & Better Error Catching
  modules/growthCodeIdSystem.js
Labels: bugfix

#9703 LiveIntent UserId module: Add support for bidswitch and medianet ids
  modules/liveIntentIdSystem.js
  modules/userId/eids.js
  modules/userId/eids.md
  test/spec/modules/eids_spec.js
  test/spec/modules/liveIntentIdSystem_spec.js
Labels: maintenance

#9769 CORE: disable the requirement for having a url, when enabling renderNow in Renderer
  src/Renderer.js
  test/spec/renderer_spec.js
Labels: bugfix

#9791 JW Player Video Adapter: Support multiple setup listeners
  modules/jwplayerVideoProvider.js
  test/spec/modules/videoModule/submodules/jwplayerVideoProvider_spec.js
Labels: LGTM, bugfix

#9746 Pub-X Bid Adapter: adding page url support
  modules/pubxBidAdapter.js
  test/spec/modules/pubxBidAdapter_spec.js
Labels: maintenance

#9696 Magnite Analytics Adapter : add seat non bid handling
  modules/magniteAnalyticsAdapter.js
  test/spec/modules/magniteAnalyticsAdapter_spec.js
Labels: maintenance

#9794 openxBidAdapter: update to OpenRTB adapter
  modules/openxBidAdapter.js
  modules/openxBidAdapter.md
  modules/openxOrtbBidAdapter.md
  test/spec/modules/openxBidAdapter_spec.js
  test/spec/modules/openxOrtbBidAdapter_spec.js
Labels: maintenance

#9706 IVS Bid Adapter: initial adapter release
  modules/ivsBidAdapter.js
  modules/ivsBidAdapter.md
  test/spec/modules/ivsBidAdapter_spec.js
Labels: feature

#9807 IVS bid adapter: fix tests
  test/spec/modules/ivsBidAdapter_spec.js
Labels: maintenance

#9731 Kargo Bid Adapter: Refactor of bid request
  modules/kargoBidAdapter.js
  test/spec/modules/kargoBidAdapter_spec.js
Labels: maintenance

#9809 Criteo Bid Adapter: Map device sua field to user ext sua
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: maintenance

#9810 NeuwoRtdModule: The global.site.cattax field is not set anymore as it is not defined in openrtb 2.5
  modules/neuwoRtdProvider.js
  test/spec/modules/neuwoRtdProvider_spec.js
Labels: maintenance

#9815 kueezRtb Bid Adapter: add support for passing metaData object
  modules/kueezRtbBidAdapter.js
  test/spec/modules/kueezRtbBidAdapter_spec.js
Labels: maintenance

#9820 AdMatic Bid Adapter: badv added
  modules/admaticBidAdapter.js
  test/spec/modules/admaticBidAdapter_spec.js
Labels: maintenance

#9767 Nativo Bid Adapter: Adding UserId support
  modules/nativoBidAdapter.js
  test/spec/modules/nativoBidAdapter_spec.js
Labels: feature

#9795 Vidoomy Adapter: Added userId module
  modules/vidoomyBidAdapter.js
  test/spec/modules/vidoomyBidAdapter_spec.js
Labels: feature

#9744 PubMatic bid adapter: support optional video compilation
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: feature, LGTM

#9768 Eskimi Bid Adapter: initial adapter release
  modules/eskimiBidAdapter.js
  modules/eskimiBidAdapter.md
  test/spec/modules/eskimiBidAdapter_spec.js
Labels: feature

#9830 MinuteMediaPlus Bid Adapter: pass gpid to server
  modules/minutemediaplusBidAdapter.js
  test/spec/modules/minutemediaplusBidAdapter_spec.js
Labels: maintenance

#9831 KueezRtb Bid Adapter: pass gpid to server
  modules/kueezRtbBidAdapter.js
  test/spec/modules/kueezRtbBidAdapter_spec.js
Labels: maintenance

#9829 Adnuntius Bid Adapter: Europe endpoint
  modules/adnuntiusBidAdapter.js
  test/spec/modules/adnuntiusBidAdapter_spec.js
Labels: maintenance

#9832 TheMediaGrid: make gridNMBidAdater as alias for gridBidAdapter
  modules/gridBidAdapter.js
  modules/gridNMBidAdapter.js
  modules/gridNMBidAdapter.md
  test/spec/modules/gridBidAdapter_spec.js
  test/spec/modules/gridNMBidAdapter_spec.js
Labels: maintenance

#9662 pairId userId submodule: initial commit for pairId submodule
  modules/pairIdSystem.js
  modules/userId/eids.js
  test/spec/modules/pairIdSystem_spec.js
Labels: feature

#9460 Yieldmo Adapter: Send GPP data in bid request.
  modules/yieldmoBidAdapter.js
  test/spec/modules/yieldmoBidAdapter_spec.js
Labels: maintenance

#9818 Bidwatch Analytics Adapter: add of the referer for bid won
  modules/bidwatchAnalyticsAdapter.js
Labels: maintenance

#9817 Mediasquare Bid Adapter: add of the referer for onBidWon
  modules/mediasquareBidAdapter.js
Labels: maintenance

#9834 Vidoomy Bid Adapter: sync url changed
  modules/vidoomyBidAdapter.js
Labels: maintenance

#9653 AppNexus bid adapter: support optional video compilation
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
  test/spec/modules/big-richmediaBidAdapter_spec.js
  test/spec/unit/pbjs_api_spec.js
Labels: maintenance

#9840 ortbConverter: support video.plcmt
  libraries/ortbConverter/processors/video.js
Labels: feature

#9839 Documentation: Add FLEDGE aka Protected Audience API examples
  integrationExamples/gpt/fledge_example.html
  integrationExamples/gpt/prebidServer_fledge_example.html
Labels: maintenance

#9704 Core: fix spurious warnings on `mergeConfig`
  src/config.js
  test/spec/modules/ooloAnalyticsAdapter_spec.js
Labels: bugfix

#9825 Vidoomy Bid Adapter: added block module
  modules/vidoomyBidAdapter.js
  modules/vidoomyBidAdapter.md
  test/spec/modules/vidoomyBidAdapter_spec.js
Labels: maintenance

#9846 Yieldmo Bid Adapter : empty array instead of string
  modules/yieldmoBidAdapter.js
  test/spec/modules/yieldmoBidAdapter_spec.js
Labels: bugfix

#9850 RTB house Bid Adapter: fix encoding bug for bid response of native ads
  modules/rtbhouseBidAdapter.js
  test/spec/modules/rtbhouseBidAdapter_spec.js
Labels: bugfix

#9849 Missena Bid Adapter: fix alias
  modules/missenaBidAdapter.js
Labels: maintenance

#9783 New adapter: EMTV
  modules/emtvBidAdapter.js
  modules/emtvBidAdapter.md
  test/spec/modules/emtvBidAdapter_spec.js
Labels: feature

#9845 Criteo Id Module: ensure all kind of privacy strings are sent to backend
  modules/criteoIdSystem.js
  test/spec/modules/criteoIdSystem_spec.js
Labels: maintenance

#9858 NextMillennium Bd Adapter : add gvlid
  modules/nextMillenniumBidAdapter.js
Labels: bugfix

#9860 Adrino Bid Adapter: banner support added
  modules/adrinoBidAdapter.js
  test/spec/modules/adrinoBidAdapter_spec.js
Labels: maintenance

#9851 Criteo Bid Adapter: map native assets to slot.ext.assets
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: maintenance

#9857 Realvu analytics adapter: fix test failures on Edge
  test/spec/modules/realvuAnalyticsAdapter_spec.js
Labels: maintenance

#9868 Prebid 8: Delete Inskin
  modules/inskinBidAdapter.js
  modules/inskinBidAdapter.md
  test/spec/modules/inskinBidAdapter_spec.js
Labels: maintenance, 8.0 API Change

#9872 Prebid 8: Renaming TrustPid User ID module to Utiq
  modules/.submodules.json
  modules/ixBidAdapter.js
  modules/userId/eids.js
  modules/userId/eids.md
  modules/userId/userId.md
  modules/utiqSystem.js
  modules/utiqSystem.md
  test/spec/modules/utiqSystem_spec.js
Labels: major, 8.0 API Change

#9871 RTBHouse Adapter: `bcat` & `badv` support
  modules/rtbhouseBidAdapter.js
  test/spec/modules/rtbhouseBidAdapter_spec.js
Labels: maintenance

#8913 Prebid 8: Inmar Bid Adapter, remove adapter
  modules/inmarBidAdapter.js
  modules/inmarBidAdapter.md
  test/spec/modules/inmarBidAdapter_spec.js
Labels: 8.0 API Change
