Repository prebid/Prebid.js, pull requests merged in 2023-01, with the labels that each got.

#9387 Aso Bid Adapter: add bcmint alias
  modules/asoBidAdapter.js
Labels: maintenance

#9377 AIDEM Bid Adapter: added wpar and placementId param
  modules/aidemBidAdapter.js
  modules/aidemBidAdapter.md
  test/spec/modules/aidemBidAdapter_spec.js
Labels: maintenance

#9376 Taboola Bid Adapter: onBidWon, userSyncs, gpp support and FPD
  modules/taboolaBidAdapter.js
  test/spec/modules/taboolaBidAdapter_spec.js
Labels: feature

#9370 Yieldlab Bid Adapter: read and pass UserIdsAsEids atype information
  modules/yieldlabBidAdapter.js
  test/spec/modules/yieldlabBidAdapter_spec.js
Labels: maintenance

#9392 Medianet RTD module: fix `getTargetingData` to retrieve correct adUnits
  modules/medianetRtdProvider.js
  test/spec/modules/medianetRtdProvider_spec.js
Labels: bugfix

#9371 Holid Bid Adapter: initial release
  modules/holidBidAdapter.js
  modules/holidBidAdapter.md
  test/spec/modules/holidBidAdapter_spec.js
Labels: feature

#9396 Appnexus Bid Adapter : add video data from the request to the bid response
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: bugfix

#9397 Feedad Bid Adapter: added new bid request parameters
  modules/feedadBidAdapter.js
  test/spec/modules/feedadBidAdapter_spec.js
Labels: maintenance

#9345 yahoospp bidder& aol bidder: GPP Support in bid requests
  modules/aolBidAdapter.js
  modules/yahoosspBidAdapter.js
  test/spec/modules/aolBidAdapter_spec.js
  test/spec/modules/yahoosspBidAdapter_spec.js
Labels: maintenance

#9288 Orbitsoft Bid Adapter : add adapter back to current version
  modules/orbitsoftBidAdapter.js
  test/spec/modules/orbitsoftBidAdapter_spec.js
Labels: feature

#9401 Taboola Bid Adapter: add GPID support
  modules/taboolaBidAdapter.js
  test/spec/modules/taboolaBidAdapter_spec.js
Labels: bugfix

#9380 Yieldmo Adapter: Add support for structured user agent
  modules/yieldmoBidAdapter.js
  test/spec/modules/yieldmoBidAdapter_spec.js
Labels: maintenance

#9403 Appnnexus Bid Adapter : support for adomain
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: maintenance

#9408 smartx Bid Adapter: add support for sitekey
  modules/smartxBidAdapter.js
  test/spec/modules/smartxBidAdapter_spec.js
Labels: maintenance

#9383 Adloox RTD: fix breakage since 7.x release
  integrationExamples/gpt/adloox.html
  modules/adlooxAnalyticsAdapter.md
  modules/adlooxRtdProvider.js
  modules/adlooxRtdProvider.md
  test/spec/modules/adlooxRtdProvider_spec.js
Labels: bugfix

#9415 Seedtag Bid Adapter - Add GPP consent
  modules/seedtagBidAdapter.js
  test/spec/modules/seedtagBidAdapter_spec.js
Labels: maintenance

#9409 nexx360 Bid Adapter: ssp added to meta.demandSource
  modules/nexx360BidAdapter.js
Labels: maintenance

#9368 Alkimi Bid Adapter: using the floors convention
  modules/alkimiBidAdapter.js
  test/spec/modules/alkimiBidAdapter_spec.js
Labels: maintenance

#9346 Appush Bid Adapter: initial release
  modules/appushBidAdapter.js
  modules/appushBidAdapter.md
  test/spec/modules/appushBidAdapter_spec.js
Labels: feature

#9428 TargetVideo Bid Adapter: Updating margin rule
  modules/targetVideoBidAdapter.js
  test/spec/modules/targetVideoBidAdapter_spec.js
Labels: bugfix

#9395 PBjs Core (Price Floors) : Support inverseBidAdjustment function
  modules/priceFloors.js
  test/spec/modules/priceFloors_spec.js
Labels: bugfix

#9429 Criteo Bid Adapter : Bump Publisher Tag version (fix getFloor usage)
  modules/criteoBidAdapter.js
Labels: feature

#9394 IX Bid Adapter: retrieve user/agent hints and fix tmax issue
  modules/ixBidAdapter.js
  package-lock.json
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance

#9426 PBjs Core (Promises): fix static method GreedyPromise.resolve not working with Angular + Zone.js
  src/utils/promise.js
Labels: bugfix

#9434 USP consent management: handle errors from CMPs that cannot deal with `registerDeletion`
  modules/consentManagementUsp.js
  test/spec/modules/consentManagementUsp_spec.js
Labels: bugfix

#9439 nexx360 Bid Adapter: aliases list update
  modules/nexx360BidAdapter.js
Labels: feature

#9438 Update live-connect-js version
  package-lock.json
  package.json
Labels: maintenance

#9417 Seedtag Bid Adapter : enable video/banner mediatypes for inImage/inBanner/inArticle/inScreen
  modules/seedtagBidAdapter.js
  test/spec/modules/seedtagBidAdapter_spec.js
Labels: feature

#9416 ID5 ID Module: The payload extended with document.referer and canonicalUrl
  modules/id5IdSystem.js
Labels: maintenance

#9427 Admixer Bid Adapter : adding floor module support and new alias
  modules/admixerBidAdapter.js
  test/spec/modules/admixerBidAdapter_spec.js
Labels: feature

#9451 Admatic Bid Adapter : bugfix with AdserverCurrency param
  modules/admaticBidAdapter.js
Labels: bugfix

#9445 OpenX Bid Adapter : add support for BidRequest.Device.sua using user agent client hints
  modules/openxBidAdapter.js
  test/spec/modules/openxBidAdapter_spec.js
  test/spec/modules/openxOrtbBidAdapter_spec.js
Labels: maintenance

#9442 nextMillenniumBidAdapter: fix replaceGetUserMacro function
  modules/nextMillenniumBidAdapter.js
  test/spec/modules/nextMillenniumBidAdapter_spec.js
Labels: bugfix

#9447 Kargo Bid Adapter: Adding Vast URL Support
  modules/kargoBidAdapter.js
  test/spec/modules/kargoBidAdapter_spec.js
Labels: maintenance

#9452 openxOrtbBidAdapter: fix device.sua test
  test/spec/modules/openxOrtbBidAdapter_spec.js
Labels: maintenance

#9450 Criteo Bid Adapter : bump Publisher Tag version (fix documentContext not used)
  modules/criteoBidAdapter.js
Labels: maintenance

#9443 BLIINK Bid Adapter: fix ttl
  modules/bliinkBidAdapter.js
  test/spec/modules/bliinkBidAdapter_spec.js
Labels: bugfix

#9455 Triplelift Bid Adapter: Support for GPP in bid requests
  modules/tripleliftBidAdapter.js
  test/spec/modules/tripleliftBidAdapter_spec.js
Labels: maintenance

#9418 Lotame Panorama ID Module : add safari handling
  modules/lotamePanoramaIdSystem.js
  test/spec/modules/lotamePanoramaIdSystem_spec.js
Labels: maintenance

#9458 Adnuntius Bid Adapter : bug fix for multiple mediatypes
  modules/adnuntiusBidAdapter.js
  test/spec/modules/adnuntiusBidAdapter_spec.js
Labels: bugfix

#9461 Emx Digital Bid Adapter : adding US Privacy string support
  modules/emx_digitalBidAdapter.js
  test/spec/modules/emx_digitalBidAdapter_spec.js
Labels: maintenance

#9463 consumable Bid Adapter: support gdpr and usp user sync params
  modules/consumableBidAdapter.js
  test/spec/modules/consumableBidAdapter_spec.js
Labels: maintenance

#9258 PBS Bid Adapter : site should not exist when app is present
  libraries/ortbConverter/processors/default.js
  modules/prebidServerBidAdapter/ortbConverter.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/ortbConverter/default_processors_spec.js
Labels: bugfix

#9423 Prebid Server Bid Adapter: Updated PBS filterSettings in /cookie_sync call to match userSync filterSettings in PBJS config
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: maintenance

#9459 ArcSpan RTD Module: Initial Release
  modules/.submodules.json
  modules/arcspanRtdProvider.js
  modules/arcspanRtdProvider.md
  src/adloader.js
  test/spec/modules/arcspanRtdProvider_spec.js
Labels: feature

#9465 PulsePoint Bid Adapter: support timeout/tmax
  modules/pulsepointBidAdapter.js
  test/spec/modules/pulsepointBidAdapter_spec.js
Labels: maintenance

#9432 hadronId user id submodule: force localStorage
  modules/hadronIdSystem.js
  test/spec/modules/hadronIdSystem_spec.js
  test/spec/modules/userId_spec.js
Labels: maintenance

#9405 Outbrain Bid Adapter: added video support
  modules/outbrainBidAdapter.js
  test/spec/modules/outbrainBidAdapter_spec.js
Labels: feature

#9437 Smartadserver Bid Adapter: support floors per media type
  modules/smartadserverBidAdapter.js
  test/spec/modules/smartadserverBidAdapter_spec.js
Labels: maintenance

#9388 Smartytech Bid Adapter: Add video format
  modules/smartytechBidAdapter.js
  modules/smartytechBidAdapter.md
  test/spec/modules/smartytechBidAdapter_spec.js
Labels: feature

#9441 Core & priceFloors: pass bid request to `bidCpmAdjustment`; warn about invalid `adUnit.floors` definitions
  modules/priceFloors.js
  src/auction.js
  src/utils/cpm.js
  test/spec/unit/utils/cpm_spec.js
Labels: bugfix

#9474 Permutive RTD Module: fixes potential error when reading _pssps localStorage key
  modules/permutiveRtdProvider.js
Labels: bugfix

#9472 SmartyadsBidAdapter: update request params
  modules/smartyadsBidAdapter.md
Labels: maintenance, documentation

#9446 C-Wire Bid Adapter: Code refactorings
  modules/cwireBidAdapter.js
  modules/cwireBidAdapter.md
  test/spec/modules/cwireBidAdapter_spec.js
Labels: maintenance

#9485 Nexx360 Bid Adapter: bidderCode fix
  modules/nexx360BidAdapter.js
  test/spec/modules/nexx360BidAdapter_spec.js
Labels: bugfix

#9482 Taboola Bid Adapter: pass nurl to bidResponse
  modules/taboolaBidAdapter.js
  test/spec/modules/taboolaBidAdapter_spec.js
Labels: bugfix
