Repository prebid/Prebid.js, pull requests merged in 2023-11, with the labels that each got.

#10654 FreeWheel SSP Adapter: add gvlid in spec
  modules/freewheel-sspBidAdapter.js
  test/spec/modules/freewheel-sspBidAdapter_spec.js
Labels: needs update, maintenance

#10678 openx Bid Adapter: add prebid version
  modules/openxBidAdapter.js
  test/spec/modules/openxBidAdapter_spec.js
Labels: maintenance

#10676 Rubicon Bid Adapter : add size 720x1280
  modules/rubiconBidAdapter.js
Labels: maintenance

#10647 AdMatic Bid Adapter: added native type
  modules/admaticBidAdapter.js
  test/spec/modules/admaticBidAdapter_spec.js
Labels: feature

#10673 Reset Digital Bid Adapter: refactoring usersync method
  modules/resetdigitalBidAdapter.js
Labels: maintenance

#10665 Criteo Bid Adapter: Fledge Support
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: feature

#10693 LiveIntent UserId module:: Update live-connect-js dependency (V7)
  package-lock.json
  package.json
Labels: maintenance

#10610 Relevant Bid Adapter : support s2s
  modules/relevantdigitalBidAdapter.js
  test/spec/modules/relevantdigitalBidAdapter_spec.js
Labels: needs unit tests, maintenance

#10638 Publink Id System : pass cached id through for better tracking
  modules/publinkIdSystem.js
  test/spec/modules/publinkIdSystem_spec.js
Labels: maintenance

#10695 PubMatic Bid Adapter: Support for cookie deprecation label
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: maintenance

#10697 BLIINK Bid Adapter: hotfix gvlid parameter in release 8.19.0
  modules/bliinkBidAdapter.js
  test/spec/modules/bliinkBidAdapter_spec.js
Labels: bugfix

#10698 Tappx Bid Adapter : fixed referrer for iframes using external sites error
  modules/tappxBidAdapter.js
Labels: bugfix

#10691 Mediago Bid Adapter: add imp params for analysis
  modules/mediagoBidAdapter.js
  test/spec/modules/mediagoBidAdapter_spec.js
Labels: maintenance

#10623 GoldfishAds Rtd Provider : Initial Module Release
  modules/goldfishAdsRtdProvider.js
  modules/goldfishAdsRtdProvider.md
  test/spec/modules/goldfishAdsRtdProvider_spec.js
Labels: feature

#10555 ZetaGlobalSsp Analytics Adapter : make event object with only needed fields
  modules/zeta_global_sspAnalyticsAdapter.js
  test/spec/modules/zeta_global_sspAnalyticsAdapter_spec.js
Labels: bugfix

#10674 GumGum Bid Adapter: add support for video.plcmt
  modules/gumgumBidAdapter.js
  test/spec/modules/gumgumBidAdapter_spec.js
Labels: maintenance

#10671 Rubicon Bid Adapter: PAAPI/Fledge support
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: maintenance

#10682 Pangle Bid Adapter : add support for video
  modules/pangleBidAdapter.js
  test/spec/modules/pangleBidAdapter_spec.js
Labels: feature

#10703 Rubicon Bid Adapter : send Fastlane cdep flag
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: maintenance

#10700 Outbrain bid adapter: pass GPP consent
  modules/outbrainBidAdapter.js
  test/spec/modules/outbrainBidAdapter_spec.js
Labels: maintenance

#10639 Appnexus Bid Adapter : adding 'adzymic' as a new alias
  modules/appnexusBidAdapter.js
Labels: maintenance

#10707 Consumable Bid Adapter: fix us privacy format and make gpp applicable sections optional
  modules/consumableBidAdapter.js
  test/spec/modules/consumableBidAdapter_spec.js
Labels: bugfix

#10704 IX Bid Adapter: Support for exchangeId and externalId
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: feature

#10706 Pubmatic: Contribute vendor details for Prebid server adapter
  modules/prebidServerBidAdapter/config.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: maintenance

#10701 priceFloors: Prevent warning when floor price value is 0
  modules/priceFloors.js
  test/spec/modules/priceFloors_spec.js
Labels: needs unit tests, bugfix

#10692 LiveIntent UserId module:: Update live-connect-js dependency (V8)
  package-lock.json
  package.json
Labels: maintenance

#10689 Yieldmo Bid Adapter: Adding tmax to banner bid requests
  modules/yieldmoBidAdapter.js
  test/spec/modules/yieldmoBidAdapter_spec.js
Labels: bugfix

#10694 Discovery Bid Adapter: add bidId, keywords, and pbadslot
  modules/discoveryBidAdapter.js
  test/spec/modules/discoveryBidAdapter_spec.js
Labels: feature

#10711 Adagio Bid Adapter: fix floor prices module support
  modules/adagioBidAdapter.js
Labels: maintenance

#10679 Currency module: better error handling
  modules/currency.js
  modules/sonobiAnalyticsAdapter.js
  src/auction.js
  src/constants.json
  test/spec/auctionmanager_spec.js
  test/spec/modules/currency_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/sonobiAnalyticsAdapter_spec.js
Labels: bugfix

#10712 Discovery Bid Adapter : add referer stack
  modules/discoveryBidAdapter.js
  test/spec/modules/discoveryBidAdapter_spec.js
Labels: maintenance

#10680 adstir Bid Adapter: initial release
  modules/adstirBidAdapter.js
  modules/adstirBidAdapter.md
  test/spec/modules/adstirBidAdapter_spec.js
Labels: feature, needs docs

#10720 Criteo Bid Adapter : add missing video fields
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: maintenance

#10611 TPMN Bid Adapter: Change End-Point & Support Video
  integrationExamples/gpt/tpmn_example.html
  integrationExamples/gpt/tpmn_serverless_example.html
  modules/tpmnBidAdapter.js
  modules/tpmnBidAdapter.md
  test/spec/modules/tpmnBidAdapter_spec.js
Labels: feature

#10718 Improve Digital Bid Adapter: adding PG flag
  modules/improvedigitalBidAdapter.js
  test/spec/modules/improvedigitalBidAdapter_spec.js
Labels: maintenance

#10635 33Across Analytics Adapter: initial release
  modules/33acrossAnalyticsAdapter.js
  modules/33acrossAnalyticsAdapter.md
  test/spec/modules/33acrossAnalyticsAdapter_spec.js
Labels: needs update

#10721 Rubicon Bid Adapter: Pass SUA data if available
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: maintenance

#10719 Adttelligent Bid Adapter : add Indicue alias
  modules/adtelligentBidAdapter.js
  test/spec/modules/adtelligentBidAdapter_spec.js
Labels: feature

#10418 Media Filter RTD Provider : initial modul release
  modules/.submodules.json
  modules/mediafilterRtdProvider.js
  modules/mediafilterRtdProvider.md
  src/adloader.js
  test/spec/modules/mediafilterRtdProvider_spec.js
Labels: feature

#10713 Use gppApplicableSections and gppString In LiveIntent's Prebid User Id Module
  modules/liveIntentIdSystem.js
  package-lock.json
  test/spec/modules/liveIntentIdSystem_spec.js
Labels: maintenance

#10728 Revert "NoBid Bid Adapter : add support for first party user id"
  modules/nobidBidAdapter.js
  test/spec/modules/nobidBidAdapter_spec.js
Labels: bugfix

#10699 Adagio Analytics Adapter: handle bid cache usecases
  modules/adagioAnalyticsAdapter.js
  test/spec/modules/adagioAnalyticsAdapter_spec.js
Labels: maintenance

#10534 Missena Bid Adapter: floor implementation
  modules/missenaBidAdapter.js
  test/spec/modules/missenaBidAdapter_spec.js
Labels: maintenance

#10723 Build system: Log unhandled errors during tests
  test/test_deps.js
Labels: maintenance

#10684 Doceree AdManager Bid Adapter: initial release
  modules/docereeAdManagerBidAdapter.js
  modules/docereeAdManagerBidAdapter.md
  test/spec/modules/docereeAdManagerBidAdapter_spec.js
Labels: feature, needs docs

#10675 Operaads Bid Adapter: provide a way to build bid requests for applications
  modules/operaadsBidAdapter.js
  modules/operaadsBidAdapter.md
  test/spec/modules/operaadsBidAdapter_spec.js
Labels: feature

#10652 AsterioBid Analytics Adapter : initial release
  modules/asteriobidAnalyticsAdapter.js
  modules/asteriobidAnalyticsAdapter.md
  test/spec/modules/asteriobidAnalyticsAdapter_spec.js
Labels: feature

#10743 Discovery Bid Adapter : remove duplicate eids
  modules/discoveryBidAdapter.js
Labels: maintenance

#10525 Adxcg Bid Adapter: use ortbConverter
  modules/adxcgBidAdapter.js
  test/spec/modules/adxcgBidAdapter_spec.js
Labels: feature

#9647 Core: unify rendering paths; codify (and test) cross-domain render example
  gulpfile.js
  integrationExamples/gpt/x-domain/creative.html
  libraries/creativeRender/constants.js
  libraries/creativeRender/crossDomain.js
  libraries/creativeRender/direct.js
  libraries/creativeRender/writer.js
  package-lock.json
  package.json
  src/adRendering.js
  src/auction.js
  src/prebid.js
  src/secureCreatives.js
  src/utils.js
  test/spec/creative/crossDomainCreative_spec.js
  test/spec/unit/pbjs_api_spec.js
  test/spec/unit/secureCreatives_spec.js
  webpack.creative.js
Labels: feature

#10750 Iprom Bid Adapter : add gvlid
  modules/ipromBidAdapter.js
Labels: maintenance

#10405 ShinezRTB Bid Adapter : initial release
  modules/shinezRtbBidAdapter.js
  modules/shinezRtbBidAdapter.md
  test/spec/modules/shinezRtbBidAdapter_spec.js
Labels: feature

#10696 Criteo bid adapter: Bump fastbid version
  modules/criteoBidAdapter.js
Labels: maintenance

#10763 adxcg Bid Adapter : fix convertTypes util import
  modules/adxcgBidAdapter.js
Labels: bugfix

#10757 Boldwin Bid Adapter : update sync url
  modules/boldwinBidAdapter.js
  test/spec/modules/boldwinBidAdapter_spec.js
Labels: maintenance

#10755 Onetag Bid Adapter : add FLEDGE/PAAPI support
  modules/onetagBidAdapter.js
  test/spec/modules/onetagBidAdapter_spec.js
Labels: maintenance

#10683 FPD Enrichment: support for Cookie Deprecation Label
  modules/gdprEnforcement.js
  src/activities/redactor.js
  src/consentHandler.js
  src/fpd/enrichment.js
  test/spec/fpd/enrichment_spec.js
  test/spec/modules/gdprEnforcement_spec.js
Labels: feature

#10749 ConceptX Bid Adapter : bugfix to avoid appending to the request url on build
  modules/conceptxBidAdapter.js
Labels: bugfix

#10751 Greenbids Analytics Adapter : add bugfixes to legacy 7.54.x updates
  modules/greenbidsAnalyticsAdapter.js
  modules/greenbidsRtdProvider.js
  test/spec/modules/greenbidsAnalyticsAdapter_spec.js
  test/spec/modules/greenbidsRtdProvider_spec.js
Labels: maintenance

#10760 Sparteo Bid Adapter: send bidder params in OpenRTB request
  modules/sparteoBidAdapter.js
  test/spec/modules/sparteoBidAdapter_spec.js
Labels: maintenance

#10769 Impactify Bid Adapter : Removing checks on bid request
  modules/impactifyBidAdapter.js
  test/spec/modules/impactifyBidAdapter_spec.js
Labels: maintenance

#10709 Unruly: Protected Audience Support
  modules/unrulyBidAdapter.js
  test/spec/modules/unrulyBidAdapter_spec.js
Labels: feature

#10762 Relaido Bid Adapter : add userIdAsEids and canonical_url to request
  modules/relaidoBidAdapter.js
  test/spec/modules/relaidoBidAdapter_spec.js
Labels: maintenance

#10775 Adagio Bid Adapter: add GPID support
  modules/adagioBidAdapter.js
  test/spec/modules/adagioBidAdapter_spec.js
Labels: maintenance

#10776 Core: add option to turn off `Sec-Browsing-Topics` header
  src/adapters/bidderFactory.js
  test/spec/unit/core/bidderFactory_spec.js
Labels: feature

#10777 TPMN Bid Adapter: remove OptionsObject
  modules/tpmnBidAdapter.js
Labels: bugfix

#10774 GrowthCode RTD: bounce requests when the PID is missing
  modules/growthCodeRtdProvider.js
Labels: bugfix

#10752 DynamicAdBoost Module : add to adloader list
  src/adloader.js
Labels: maintenance

#10739 Generic analytics: fix spurious warning messages
  modules/genericAnalyticsAdapter.js
  src/events.js
  test/spec/modules/genericAnalyticsAdapter_spec.js
Labels: bugfix
