Repository prebid/Prebid.js, pull requests merged in 2023-12, with the labels that each got.

#10781 Flipp Bid Adapter: update constant NETWORK_ID
  modules/flippBidAdapter.js
Labels: bugfix

#10778 identityLink Id System : fix 3p call to always use tcf consent type 4
  modules/identityLinkIdSystem.js
  test/spec/modules/identityLinkIdSystem_spec.js
Labels: bugfix

#10784 VOX Bid Adapter: Add GVLID
  modules/voxBidAdapter.js
Labels: maintenance

#10783 LiveIntent UserId module: Add support for sovrn id
  modules/liveIntentIdSystem.js
  test/spec/modules/eids_spec.js
  test/spec/modules/liveIntentIdMinimalSystem_spec.js
  test/spec/modules/liveIntentIdSystem_spec.js
Labels: maintenance

#10773 Unruly Bid Adapter : include Prebid.js version in request
  modules/unrulyBidAdapter.js
  test/spec/modules/unrulyBidAdapter_spec.js
Labels: maintenance

#10782 MgidX Bid Adapter: refactor request.gdpr object generating
  modules/mgidXBidAdapter.js
  test/spec/modules/mgidXBidAdapter_spec.js
Labels: maintenance

#10761 NextMillennium Bid Adapter: support for GPP consent string, `site.pagecat`, `site.content.cat` and `site.content.language`
  modules/nextMillenniumBidAdapter.js
  test/spec/modules/nextMillenniumBidAdapter_spec.js
Labels: maintenance

#10786 LiveIntent UserId module: Use openx.net as source for the openx id
  modules/liveIntentIdSystem.js
  test/spec/modules/eids_spec.js
Labels: bugfix

#10790 Rise Bid Adapter : support currency
  modules/riseBidAdapter.js
  modules/riseBidAdapter.md
  test/spec/modules/riseBidAdapter_spec.js
Labels: maintenance

#10791 MinuteMedia Bid Adapter : support currency
  modules/minutemediaBidAdapter.js
  modules/minutemediaBidAdapter.md
  test/spec/modules/minutemediaBidAdapter_spec.js
Labels: maintenance

#10797 Core: Add eventString to error executing handler message
  src/events.js
  test/spec/unit/core/events_spec.js
Labels: maintenance

#10794 Adagio Bid Adapter: remove useless adrequest fields
  modules/adagioBidAdapter.js
  test/spec/modules/adagioBidAdapter_spec.js
Labels: maintenance

#10772 VIS.X Bid Adapter : add response time tracking on bidWon event
  modules/visxBidAdapter.js
  test/spec/modules/visxBidAdapter_spec.js
Labels: feature, LGTM

#10801 ViantOrtb Bid Adapter : update endpoint url
  modules/viantOrtbBidAdapter.js
  test/spec/modules/viantOrtbBidAdapter_spec.js
Labels: maintenance

#10796 Teads Bid Adapter: add new window features to request
  modules/teadsBidAdapter.js
  test/spec/modules/teadsBidAdapter_spec.js
Labels: maintenance

#10805 Sparteo Bid Adapter : handle vastUrl for video context
  modules/sparteoBidAdapter.js
  test/spec/modules/sparteoBidAdapter_spec.js
Labels: maintenance

#10724 Mediago Bid Adapter : add cookieSync and gdpr
  modules/mediagoBidAdapter.js
  test/spec/modules/mediagoBidAdapter_spec.js
Labels: maintenance

#10729 Sovrn Bid Adapter : send coppa signal
  modules/sovrnBidAdapter.js
  test/spec/modules/sovrnBidAdapter_spec.js
Labels: maintenance

#10765 GeoEdge RTD module: collect CPM and curency from the winning bid
  modules/geoedgeRtdProvider.js
  test/spec/modules/geoedgeRtdProvider_spec.js
Labels: maintenance

#10771 Support UID 2.0 pgamssp module
  modules/pgamsspBidAdapter.js
  test/spec/modules/pgamsspBidAdapter_spec.js
Labels: maintenance

#10809 GumGum Bid Adapter : added gpid to video requests
  modules/gumgumBidAdapter.js
  test/spec/modules/gumgumBidAdapter_spec.js
Labels: maintenance

#10814 Browsi RTD : fix for targeting
  modules/browsiRtdProvider.js
  test/spec/modules/browsiRtdProvider_spec.js
Labels: bugfix

#10812 nextMillennium Bid Adapter : add pbjs version and support for user.eids
  modules/nextMillenniumBidAdapter.js
  test/spec/modules/nextMillenniumBidAdapter_spec.js
Labels: maintenance

#10818 deepintent Bid Adapter: add gvlid
  modules/deepintentBidAdapter.js
Labels: maintenance

#10798 Adagio Analytics Adapter: listen to AUCTION_END
  modules/adagioAnalyticsAdapter.js
  test/spec/modules/adagioAnalyticsAdapter_spec.js
Labels: maintenance

#10787 Pubmatic Analytics Adapter : skip duplicate data for pubmatic bids in logger and tracker
  modules/pubmaticAnalyticsAdapter.js
  test/spec/modules/pubmaticAnalyticsAdapter_spec.js
Labels: maintenance

#10825 Tead Bid Adapter: support ad slot name in code parameter of ad unit
  modules/teadsBidAdapter.js
Labels: maintenance

#10685 PBjs Core : new event fired before add bid response
  modules/rtdModule/index.js
  src/auction.js
  src/constants.json
  test/spec/unit/pbjs_api_spec.js
Labels: feature

#10764 Invibes Bid Adapter : infinite scroll tcf
  modules/invibesBidAdapter.js
  test/spec/modules/invibesBidAdapter_spec.js
Labels: maintenance

#10833 Mediago Bid Adapter : switch domain name
  modules/mediagoBidAdapter.js
Labels: maintenance

#10828 Bizzclick Bid Adapter : update adapter, used ortbConverter lib
  modules/bizzclickBidAdapter.js
  modules/bizzclickBidAdapter.md
  test/spec/modules/bizzclickBidAdapter_spec.js
Labels: feature

#10821 PubMatic Bid Adapter : passing a unique wiid to pubmatic ssp and logger call
  modules/pubmaticAnalyticsAdapter.js
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: maintenance

#10837 Criteo Bid Adapter: Add support for app.publisher.id in bid request
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: maintenance

#10807 Taboola Bid Adapter : providing visibility in case of adapter timeout
  modules/taboolaBidAdapter.js
  test/spec/modules/taboolaBidAdapter_spec.js
Labels: maintenance

#10841 Yieldmo Bid Adapter : adding support for video.plcmt
  modules/yieldmoBidAdapter.js
  test/spec/modules/yieldmoBidAdapter_spec.js
Labels: maintenance

#10845 HadronId Module: implementing user consent in backend calls
  modules/hadronIdSystem.js
  test/spec/modules/hadronIdSystem_spec.js
Labels: maintenance

#10859 Admixer Bid Adaper: add admixerwl alias
  modules/admixerBidAdapter.js
  modules/admixerBidAdapter.md
  test/spec/modules/admixerBidAdapter_spec.js
Labels: feature

#10860 AdagioAnalyticsAdapter: fix function param check
  modules/adagioAnalyticsAdapter.js
Labels: bugfix

#10842 NoBid Analytics Adapter: support for counting blocked requests for the Optimizer
  modules/nobidAnalyticsAdapter.js
  test/spec/modules/nobidAnalyticsAdapter_spec.js
Labels: maintenance

#10811 consentManagementGpp: fix handling of CMP errors
  modules/consentManagementGpp.js
  test/spec/modules/consentManagementGpp_spec.js
Labels: needs 2nd review, bugfix

#10789 Taboola Bid Adapter: implement Iframe user sync
  modules/taboolaBidAdapter.js
  test/spec/modules/taboolaBidAdapter_spec.js
Labels: needs unit tests

#10744 AMX bid adapter: fix timeout handler, bump version
  modules/amxBidAdapter.js
  test/spec/modules/amxBidAdapter_spec.js
Labels: feature

#10862 Ucfunnel Bid Adapter: add format support
  modules/ucfunnelBidAdapter.js
  test/spec/modules/ucfunnelBidAdapter_spec.js
Labels: maintenance

#10874 Core: fix headers in ortbConverter readme
  libraries/ortbConverter/README.md
Labels: maintenance

#10822 Sparteo Bid Adapter: Add UserSync
  modules/sparteoBidAdapter.js
  test/spec/modules/sparteoBidAdapter_spec.js
Labels: maintenance

#10846 Yandex Bid Adapter: Add rtt (roud trip time) tracking via nurl
  modules/yandexBidAdapter.js
  test/spec/modules/yandexBidAdapter_spec.js
Labels: maintenance

#10813 AdMatic Bid Adapter : consent management features added
  modules/admaticBidAdapter.js
  test/spec/modules/admaticBidAdapter_spec.js
Labels: maintenance

#10873 Taboola Bid Adapter: Cookie Look Up Logic Fix
  modules/taboolaBidAdapter.js
  test/spec/modules/taboolaBidAdapter_spec.js
Labels: maintenance

#10803 ZetaGlobalSsp Bid Adapter : support topics module
  modules/zeta_global_sspBidAdapter.js
  test/spec/modules/zeta_global_sspBidAdapter_spec.js
Labels: feature

#10869 Adnuntius Bid Adapter: bugfix for storageFunction
  modules/adnuntiusBidAdapter.js
Labels: bugfix

#10875 Yandex Bid Adapter: add support for topicsFpdModule
  modules/yandexBidAdapter.js
  test/spec/modules/yandexBidAdapter_spec.js
Labels: needs unit tests, maintenance

#10884 Yandex Bid Adapter: add jsdoc
  modules/yandexBidAdapter.js
Labels: maintenance
