Repository prebid/Prebid.js, pull requests merged in 2023-05, with the labels that each got.

#9873 Prebid 8: Delete viewability.js
  modules/viewability.js
Labels: maintenance

#9856 AdMatic Bid Adapter: added Video / Banner params
  modules/admaticBidAdapter.js
  test/spec/modules/admaticBidAdapter_spec.js
Labels: maintenance

#9865 Triplelift Bid Adapter: copying ad unit impression data
  modules/tripleliftBidAdapter.js
  test/spec/modules/tripleliftBidAdapter_spec.js
Labels: maintenance

#9864 Prebid 8: Delete openxortb and analytics
  modules/openxAnalyticsAdapter.js
  modules/openxAnalyticsAdapter.md
  modules/openxOrtbBidAdapter.js
  modules/openxOrtbBidAdapter.md
  test/spec/modules/openxAnalyticsAdapter_spec.js
  test/spec/modules/openxBidAdapter_spec.js
  test/spec/modules/openxOrtbBidAdapter_spec.js
Labels: maintenance

#9880 Multiple modules: do not use bidderTimeout as TTL
  modules/ablidaBidAdapter.js
  modules/axonixBidAdapter.js
  modules/dspxBidAdapter.js
  modules/iqmBidAdapter.js
  modules/orbitsoftBidAdapter.js
  modules/radsBidAdapter.js
  modules/stvBidAdapter.js
  modules/underdogmediaBidAdapter.js
  modules/vdoaiBidAdapter.js
  modules/wipesBidAdapter.js
  modules/yieldoneBidAdapter.js
Labels: bugfix

#9882 Revert "Grid Bid Adapter: add support for video.plcmt"
  modules/gridBidAdapter.js
  test/spec/modules/gridBidAdapter_spec.js
Labels: bugfix

#9875 UserId Module: avoid passing an empty eids array
  modules/userId/index.js
  test/spec/ortbConverter/userId_spec.js
Labels: maintenance

#9811 Sovrn Bid Adapter: add gpp support
  modules/sovrnBidAdapter.js
  test/spec/modules/sovrnBidAdapter_spec.js
Labels: maintenance

#9885 Triplelift Bid Adapter: relax check on consentString before appending gdprApplies to usersyncs
  modules/tripleliftBidAdapter.js
Labels: maintenance

#9862 Core & multiple modules: populate ortb2.source.tid
  .github/workflows/codeql-analysis.yml
  libraries/ortbConverter/processors/default.js
  modules/prebidServerBidAdapter/ortbConverter.js
  src/adapterManager.js
  test/spec/modules/ivsBidAdapter_spec.js
  test/spec/modules/nexx360BidAdapter_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/scatteredBidAdapter_spec.js
  test/spec/unit/core/adapterManager_spec.js
Labels: 8.0 API Change

#9854 Yahoo connect id: storage fixes.
  modules/connectIdSystem.js
  test/spec/modules/connectIdSystem_spec.js
Labels: maintenance

#9381 Prebid 8: IMDS bid adapter - Rename synacormedia adapter
  modules/imdsBidAdapter.js
  modules/imdsBidAdapter.md
  test/spec/modules/imdsBidAdapter_spec.js
Labels: maintenance, 8.0 API Change

#9887 Prebid 8: Dead Module removal
  modules/glimpseBidAdapter.js
  modules/glimpseBidAdapter.md
  modules/liveyieldAnalyticsAdapter.js
  modules/liveyieldAnalyticsAdapter.md
  test/spec/modules/glimpseBidAdapter_spec.js
  test/spec/modules/liveyieldAnalyticsAdapter_spec.js
Labels: maintenance

#9890 Impactify Bid Adapter : Remove syncstore from adapter
  modules/impactifyBidAdapter.js
Labels: maintenance

#9866 Prebid 8: Delete GA analytics - universal analytics
  modules/googleAnalyticsAdapter.js
  modules/googleAnalyticsAdapter.md
  test/spec/modules/googleAnalyticsAdapter_spec.js
Labels: maintenance

#9874 Prebid 8: Delete zeus
  modules/zeusPrimeRtdProvider.js
  modules/zeusPrimeRtdProvider.md
Labels: maintenance, 8.0 API Change

#9881 Adloox server video: mock out blob URLs in tests
  test/spec/modules/adlooxAdServerVideo_spec.js
Labels: maintenance

#9685 Relevant Digital Bid Adapter: initial release
  modules/relevantdigitalBidAdapter.js
  modules/relevantdigitalBidAdapter.md
  test/spec/modules/relevantdigitalBidAdapter_spec.js
Labels: feature, needs update

#9898 Prebid 8 - deprecate bidder category translation feature in core
  libraries/categoryTranslationMapping/index.js
  modules/appnexusBidAdapter.js
  modules/goldbachBidAdapter.js
  modules/mediafuseBidAdapter.js
  src/adapters/bidderFactory.js
  test/spec/modules/adrelevantisBidAdapter_spec.js
  test/spec/modules/adriverBidAdapter_spec.js
  test/spec/modules/appnexusBidAdapter_spec.js
  test/spec/modules/big-richmediaBidAdapter_spec.js
  test/spec/modules/goldbachBidAdapter_spec.js
  test/spec/modules/mediafuseBidAdapter_spec.js
  test/spec/modules/winrBidAdapter_spec.js
  test/spec/unit/core/bidderFactory_spec.js
Labels: feature, 8.0 API Change

#9848 Greenbids RTD Provider: create new RTD provider for Greenbids
  modules/greenbidsRtdProvider.js
  modules/greenbidsRtdProvider.md
  test/spec/modules/greenbidsRtdProvider_spec.js
Labels: feature

#9859 FreeWheel SSP Bid Adapter: add GPP support
  modules/freewheel-sspBidAdapter.js
  test/spec/modules/freewheel-sspBidAdapter_spec.js
Labels: maintenance

#9904 Prebid 8: Delete adgeneration
  modules/adgenerationBidAdapter.js
  modules/adgenerationBidAdapter.md
  test/spec/modules/adgenerationBidAdapter_spec.js
Labels: maintenance, 8.0 API Change

#9640 Prebid Core: Functionality to Optionally Defer Billing for an Ad
  src/adapterManager.js
  src/auction.js
  src/prebid.js
  test/spec/unit/pbjs_api_spec.js
Labels: feature

#9905 Prebid 8: do not use hardcoded `bidderCode` in responses from bid adapters
  modules/33acrossBidAdapter.js
  modules/adkernelAdnBidAdapter.js
  modules/advangelistsBidAdapter.js
  modules/beachfrontBidAdapter.js
  modules/browsiBidAdapter.js
  modules/finativeBidAdapter.js
  modules/fluctBidAdapter.js
  modules/kulturemediaBidAdapter.js
  modules/livewrappedBidAdapter.js
  modules/mediasniperBidAdapter.js
  modules/revcontentBidAdapter.js
  modules/rhythmoneBidAdapter.js
  modules/saambaaBidAdapter.js
  modules/seedingAllianceBidAdapter.js
  modules/showheroes-bsBidAdapter.js
  modules/smartytechBidAdapter.js
  modules/sspBCBidAdapter.js
  modules/theAdxBidAdapter.js
  modules/underdogmediaBidAdapter.js
  modules/videobyteBidAdapter.js
  test/spec/modules/33acrossBidAdapter_spec.js
  test/spec/modules/adkernelAdnBidAdapter_spec.js
  test/spec/modules/advangelistsBidAdapter_spec.js
  test/spec/modules/beachfrontBidAdapter_spec.js
  test/spec/modules/browsiBidAdapter_spec.js
  test/spec/modules/finativeBidAdapter_spec.js
  test/spec/modules/fluctBidAdapter_spec.js
  test/spec/modules/kulturemediaBidAdapter_spec.js
  test/spec/modules/livewrappedBidAdapter_spec.js
  test/spec/modules/revcontentBidAdapter_spec.js
  test/spec/modules/seedingAllianceAdapter_spec.js
  test/spec/modules/sspBCBidAdapter_spec.js
  test/spec/modules/underdogmediaBidAdapter_spec.js
  test/spec/modules/videobyteBidAdapter_spec.js
Labels: maintenance, 8.0 API Change

#9891 MgidAdapter: change user sync get parameters
  modules/mgidBidAdapter.js
  test/spec/modules/mgidBidAdapter_spec.js
Labels: maintenance

#9837 Rise Bid Adapter: support Coppa param
  modules/riseBidAdapter.js
  test/spec/modules/riseBidAdapter_spec.js
Labels: needs update, maintenance

#9609 Bidder Settings: Support for option to apply adapter bid adjustment to unknown bidder codes
  src/adapters/bidderFactory.js
  src/utils/cpm.js
  test/spec/unit/core/bidderFactory_spec.js
  test/spec/unit/utils/cpm_spec.js
Labels: feature

#9632 PBjs Core : filter bidders from config when not server-side
  modules/prebidServerBidAdapter/ortbConverter.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: maintenance

#9892 ttd bid adapter: pass on all of user/app/ortb2imp for first party data support, default imp.secure
  modules/ttdBidAdapter.js
  test/spec/modules/ttdBidAdapter_spec.js
Labels: maintenance

#9895 YieldlabBidAdapter updated native asset mapping
  modules/yieldlabBidAdapter.js
  test/spec/modules/yieldlabBidAdapter_spec.js
Labels: maintenance

#9913 Prebid Server adapter: change gpp sid sync formatting
  modules/prebidServerBidAdapter/index.js
Labels: bugfix

#9912 PubmaticAnalyticsAdapter - Passing GPT slot name for "au" field.
  modules/pubmaticAnalyticsAdapter.js
  test/spec/modules/pubmaticAnalyticsAdapter_spec.js
Labels: maintenance

#9909 Prebid 8: No mas mass
  integrationExamples/mass/index.html
  modules/mass.js
  modules/mass.md
  test/spec/modules/mass_spec.js
Labels: 8.0 API Change

#9824 Retailspot Bid Adapter : initial release
  modules/retailspotBidAdapter .md
  modules/retailspotBidAdapter.js
  test/spec/modules/retailspotBidAdapter_spec.js
Labels: feature

#9918 Prebid 8: Delete emx
  modules/emx_digitalBidAdapter.js
  modules/emx_digitalBidAdapter.md
  test/spec/modules/emx_digitalBidAdapter_spec.js
Labels: 8.0 API Change

#9910 Vidazoo Bid Adapter: allow all id systems
  modules/vidazooBidAdapter.js
  test/spec/modules/vidazooBidAdapter_spec.js
Labels: maintenance

#9931 Admixer Bid Adapter: add alias handlers
  README.md
  modules/admixerBidAdapter.js
  test/spec/modules/admixerBidAdapter_spec.js
Labels: maintenance

#9932 Remove Rubicon Analytics for Prebid 8
  modules/rubiconAnalyticsAdapter.js
  test/spec/modules/rubiconAnalyticsAdapter_spec.js
  test/spec/modules/rubiconAnalyticsSchema.json
Labels: maintenance, 8.0 API Change

#9920 IX Bid Adapter : fix missing IX First Party Data
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: bugfix

#9938 Nexx360 Bid Adapter : aliases list update
  modules/nexx360BidAdapter.js
Labels: maintenance

#9926 KueezRtb Bid Adapter: added support for all user id systems.
  modules/kueezRtbBidAdapter.js
  test/spec/modules/kueezRtbBidAdapter_spec.js
Labels: maintenance

#9919 Prebid 8: do not call bidder methods (`onBidWon`, `onBidBillable`, ...) for S2S bids
  src/adapterManager.js
  test/spec/unit/core/adapterManager_spec.js
Labels: bugfix

#9927 MinuteMediaPlus Bid Adapter: added support for all user id systems.
  modules/minutemediaplusBidAdapter.js
  test/spec/modules/minutemediaplusBidAdapter_spec.js
Labels: maintenance

#9771 [Video Module] Include a type property in all events
  libraries/video/shared/helpers.js
  modules/videoModule/adQueue.js
  modules/videoModule/index.js
  test/spec/modules/videoModule/shared/helpers_spec.js
Labels: video, bugfix

#9944 Appnexus Bid Adapter: added projectagora as an alias
  modules/appnexusBidAdapter.js
Labels: maintenance

#9941 TheMediaGrid Bid Adapter : added video.plcmt support
  modules/gridBidAdapter.js
  test/spec/modules/gridBidAdapter_spec.js
Labels: maintenance

#9939 MASS module: fix tests
  test/spec/modules/mass_spec.js
Labels: maintenance

#9929 Rubicon Bid Adapter: fix outstream renderer
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: bugfix

#9940 Rubicon Bid Adapter : access x_source.tid from ortb2 object
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: maintenance

#9930 Criteo Bid Adapter: add mapping for bid.meta.networkName
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: maintenance

#9937 Video Module: warn when plcmt is not set
  modules/videoModule/index.js
Labels: video, maintenance

#9949 Criteo Bid Adapter: add eids to bid request sent to bidder
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: maintenance

#9628 Permutive RTD Module: migrate ozone to ortb2
  modules/permutiveRtdProvider.js
  test/spec/modules/permutiveRtdProvider_spec.js
Labels: maintenance

#9953 Revert "Rubicon Bid Adapter : access x_source.tid from ortb2 object"
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: maintenance

#9921 Yahoo SSP adapter support for extra site publisher info.
  modules/yahoosspBidAdapter.js
  modules/yahoosspBidAdapter.md
  test/spec/modules/yahoosspBidAdapter_spec.js
Labels: needs docs, maintenance

#9964 Criteo Bid Adapter: add support for imp.rwdd
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: maintenance

#9950 confiant Rtd Provider : add message type check
  modules/confiantRtdProvider.js
  test/spec/modules/confiantRtdProvider_spec.js
Labels: maintenance

#9958 33across Bid Adapter : send mobile client hint in request
  modules/33acrossBidAdapter.js
  test/spec/modules/33acrossBidAdapter_spec.js
Labels: maintenance

#9961 Conversant Bid Adapter: add in Epsilon alias
  modules/conversantAnalyticsAdapter.js
  modules/conversantBidAdapter.js
  test/spec/modules/conversantBidAdapter_spec.js
Labels: maintenance

#9826 Underdog Media Bid Adapter: Update ttl & referer information
  modules/underdogmediaBidAdapter.js
  test/spec/modules/underdogmediaBidAdapter_spec.js
Labels: maintenance

#9963 LiveIntent UserId module: add support for distributorId configuration parameter
  modules/liveIntentIdSystem.js
  test/spec/modules/liveIntentIdMinimalSystem_spec.js
  test/spec/modules/liveIntentIdSystem_spec.js
Labels: maintenance

#9934 Docs Integration Examples : add Events UI page for Video Module
  integrationExamples/videoModule/eventsUI/eventsUI.css
  integrationExamples/videoModule/eventsUI/eventsUI.js
  integrationExamples/videoModule/jwplayer/eventsUI.html
  integrationExamples/videoModule/videojs/eventsUI.html
Labels: feature, video, documentation

#9924 GumGum Bid Adapter : Id5 integration suppress link type for ttd
  modules/gumgumBidAdapter.js
  test/spec/modules/gumgumBidAdapter_spec.js
Labels: maintenance

#9804 PBS Bid Adapter: add context to emitted seatnonbid event
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: feature

#9955 Criteo bid adapter: add video outstream renderer
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: feature

#9972 Adtelligent Bid Adapter : add Copper6 alias adapter
  modules/adtelligentBidAdapter.js
  test/spec/modules/adtelligentBidAdapter_spec.js
Labels: feature

#9975 Criteo Bid Adapter: add support for video.plcmt
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: maintenance

#9979 PubMatic Bid Adapter: Added support for video.plcmt
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: maintenance

#9943 Adnuntius Bid Adaptor: handling deals better
  modules/adnuntiusBidAdapter.js
  modules/adnuntiusBidAdapter.md
  test/spec/modules/adnuntiusBidAdapter_spec.js
Labels: maintenance

#9899 Prebid 8: use `prebid.floors.floorMin` instead of `prebid.floorMin`
  modules/priceFloors.js
  test/spec/modules/priceFloors_spec.js
Labels: maintenance, major, 8.0 API Change

#9977 Prebid 8: remove shutdown company from appnexus aliases
  modules/appnexusBidAdapter.js
Labels: maintenance, 8.0 API Change

#9847 Prebid 8: add bidResponse before emitting the event BID_RESPONSE
  src/auction.js
  test/spec/auctionmanager_spec.js
Labels: bugfix, 8.0 API Change

#9923 Core: fix `aspect_ratios` in ortb -> legacy native asset conversion
  src/native.js
  test/spec/native_spec.js
Labels: bugfix

#9986 RTB House Bid Adapter: docs update - FLEDGE support
  modules/rtbhouseBidAdapter.md
Labels: maintenance

#9870 AdHash Bid Adapter: changes to support preroll videos
  modules/adhashBidAdapter.js
  test/spec/modules/adhashBidAdapter_spec.js
Labels: maintenance

#9966 Prebid 8: removing coding project documentation for epsilon
  modules/conversantAnalyticsAdapter.js
  modules/conversantAnalyticsAdapter.md
  modules/conversantBidAdapter.js
  modules/conversantBidAdapter.md
Labels: maintenance

#9996 Rise Bid Adapter: support sua and plcmt params.
  modules/riseBidAdapter.js
  test/spec/modules/riseBidAdapter_spec.js
Labels: maintenance

#9917 Prebid 8: pick keywords from FPD in addition to bid params
  libraries/appnexusKeywords/anKeywords.js
  libraries/keywords/keywords.js
  modules/adprimeBidAdapter.js
  modules/adrelevantisBidAdapter.js
  modules/appnexusBidAdapter.js
  modules/beopBidAdapter.js
  modules/craftBidAdapter.js
  modules/displayioBidAdapter.js
  modules/goldbachBidAdapter.js
  modules/mediafuseBidAdapter.js
  modules/pixfutureBidAdapter.js
  modules/prismaBidAdapter.js
  modules/rasBidAdapter.js
  modules/richaudienceBidAdapter.js
  modules/rubiconBidAdapter.js
  modules/sonobiBidAdapter.js
  modules/winrBidAdapter.js
  src/utils.js
  test/spec/appnexusKeywords_spec.js
  test/spec/keywords_spec.js
  test/spec/modules/appnexusBidAdapter_spec.js
  test/spec/utils_spec.js
Labels: bugfix, 8.0 API Change

#9967 Adman Adapter: remove useless parameter
  modules/admanBidAdapter.js
  test/spec/modules/admanBidAdapter_spec.js
Labels: bugfix

#9893 Prebid 8: support sizeMapping for video; extract it into a module
  modules/sizeMapping.js
  src/adapterManager.js
  test/spec/modules/sizeMapping_spec.js
  test/spec/sizeMapping_spec.js
  test/spec/unit/core/adapterManager_spec.js
Labels: feature, 8.0 API Change

#9993 Adrino Bid Adapter: pass adUnitCode to adserver
  modules/adrinoBidAdapter.js
  test/spec/modules/adrinoBidAdapter_spec.js
Labels: maintenance

#9946 Adquery Bid Adapter : added bid request: version and bidPageUrl
  modules/adqueryBidAdapter.js
  test/spec/modules/adqueryBidAdapter_spec.js
Labels: LGTM, maintenance

#9933 Magnite Analytics Adapter : do not rely on BID_RESPONSE 0cpm rejected bids
  modules/magniteAnalyticsAdapter.js
  test/spec/modules/magniteAnalyticsAdapter_spec.js
Labels: needs update, maintenance

#10002 Appnexus Bid Adapter: added uol as an alias
  modules/appnexusBidAdapter.js
Labels: maintenance

#9998 Pair Id System: less noisy errors
  modules/pairIdSystem.js
  test/spec/modules/pairIdSystem_spec.js
Labels: maintenance

#10009 Zeta Global SSP Bid Adapter: Added support for video.plcmt
  modules/zeta_global_sspBidAdapter.js
  test/spec/modules/zeta_global_sspBidAdapter_spec.js
Labels: maintenance

#10013 Criteo Bid Adapter: add support of bcat/badv/bapp
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: maintenance

#10004 Smartadserver Bid Adapter: support GPID
  modules/smartadserverBidAdapter.js
  test/spec/modules/smartadserverBidAdapter_spec.js
Labels: maintenance

#9948 IX Bid Adapter: change default video.placement value
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance

#10011 ShareThrough Bid Adapter : fix playerSize
  modules/sharethroughBidAdapter.js
  test/spec/modules/sharethroughBidAdapter_spec.js
Labels: bugfix

#9852 GrowthCode RTD : initial release
  integrationExamples/gpt/growthcode.html
  modules/growthCodeRtdProvider.js
  modules/growthCodeRtdProvider.md
  test/spec/modules/growthCodeRtdProvider_spec.js
Labels: feature

#10019 GrowthCode RTD : fix module type
  modules/growthCodeRtdProvider.js
Labels: bugfix
