Repository prebid/Prebid.js, pull requests merged in 2023-07, with the labels that each got.

#10160 Cadent Aperture MX Bid Adapter: change contact email address
  modules/cadentApertureMXBidAdapter.md
  test/spec/modules/cadentApertureMXBidAdapter_spec.js
Labels: maintenance

#10180 Livewrapped Analytics Adapter : collect the same data for timeouts and responses
  modules/livewrappedAnalyticsAdapter.js
Labels: maintenance

#10166 IX Bid Adapter: Multiformat Support
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance

#10182 IX Bid Adapter: add 33Across to EID allowlist
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance

#10168 Adagio Bid Adapter : add new boolean params
  modules/adagioBidAdapter.js
  test/spec/modules/adagioBidAdapter_spec.js
Labels: maintenance

#10153 Holid Bid Adapter: add new fields to bid request, fix auctionId leak, add new usersync
  modules/holidBidAdapter.js
  test/spec/modules/holidBidAdapter_spec.js
Labels: maintenance

#10151 Mediago / Discovery Bid Adapter : update param tagid
  modules/discoveryBidAdapter.js
  modules/mediagoBidAdapter.js
Labels: bugfix

#10183 SharedId: use `sharedId` instead of `pubCommonId` for accessing storage
  modules/sharedIdSystem.js
Labels: bugfix

#10178 Oxxion Rtd Module: add bid filtering
  modules/oxxionRtdProvider.js
  test/spec/modules/oxxionRtdProvider_spec.js
Labels: maintenance

#10109 Vox Bid Addapter: add schain, floors, userid support
  modules/voxBidAdapter.js
  test/spec/modules/voxBidAdapter_spec.js
Labels: maintenance

#10177 PulsePoint Bid Adapter: deals support and refactoring to use ortbConverter
  modules/pulsepointBidAdapter.js
  modules/pulsepointBidAdapter.md
  test/spec/modules/pulsepointBidAdapter_spec.js
Labels: maintenance

#10172 userId Module: update GAM APIs for Eids
  modules/userId/index.js
Labels: bugfix

#10198 Sovrn Bid adapter: add GPP support for user sync
  modules/sovrnBidAdapter.js
  test/spec/modules/sovrnBidAdapter_spec.js
Labels: maintenance

#10125 Yahoo Bid Adapter: Rebrand from to Yahoo Advertising
  modules/yahoosspBidAdapter.js
  modules/yahoosspBidAdapter.md
  test/spec/modules/yahoosspBidAdapter_spec.js
Labels: needs update, maintenance

#10165 PubMatic Bid Adapter : add GPP support
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: maintenance

#10195 MinuteMedia Bid Adapter: support missing params and tests
  modules/minutemediaBidAdapter.js
  test/spec/modules/minutemediaBidAdapter_spec.js
Labels: maintenance

#10095 TheMediaGrid: support on data deletion request
  modules/gridBidAdapter.js
  test/spec/modules/gridBidAdapter_spec.js
Labels: maintenance

#10207 Adagio Bid Adapter: remove useless field in adRequest
  modules/adagioBidAdapter.js
  test/spec/modules/adagioBidAdapter_spec.js
Labels: maintenance

#10199 gpdrEnforcement : add purpose 4 check for `transmitUfpd`
  modules/gdprEnforcement.js
  src/activities/redactor.js
  test/spec/modules/gdprEnforcement_spec.js
Labels: feature

#10206 StroeerCore Bid Adapter : use a random UUID for the request id
  modules/stroeerCoreBidAdapter.js
  test/spec/modules/stroeerCoreBidAdapter_spec.js
Labels: bugfix

#10148 Brandmetrics RTD Module: support billable event
  modules/brandmetricsRtdProvider.js
  modules/brandmetricsRtdProvider.md
  test/spec/modules/brandmetricsRtdProvider_spec.js
Labels: maintenance

#10218 Doccumentation : delete inskin_example.html
  integrationExamples/gpt/inskin_example.html
Labels: maintenance

#10204 Adman Bid Adapter : additional content object handle
  modules/admanBidAdapter.js
Labels: maintenance

#10220 AdagioBidAdapter: bug: fix endpoint
  modules/adagioBidAdapter.js
Labels: bugfix

#10217 IX Bid Adapter: add LiveIntent to EID allowlist
  modules/ixBidAdapter.js
Labels: maintenance

#10202 Kargo Bid Adapter: Forward `schain` in the request
  modules/kargoBidAdapter.js
  test/spec/modules/kargoBidAdapter_spec.js
Labels: needs unit tests, bugfix

#10167 Core: Fix sua low entropy check for empty objects
  src/fpd/sua.js
  test/spec/fpd/enrichment_spec.js
  test/spec/fpd/sua_spec.js
Labels: bugfix

#10158 Ogury Bid Adapter: init new user sync iframe
  modules/oguryBidAdapter.js
  test/spec/modules/oguryBidAdapter_spec.js
Labels: maintenance

#10216 Prebid Core : add optional targeting keys CRID and DSP
  src/auction.js
  src/constants.json
  test/spec/auctionmanager_spec.js
Labels: feature

#10221 Teads bid adapter: Support video.plcmt
  modules/teadsBidAdapter.js
  test/spec/modules/teadsBidAdapter_spec.js
Labels: needs update, maintenance

#10173 33Across Bid Adapter & UIM: Add GPP & COPPA support
  modules/33acrossBidAdapter.js
  modules/33acrossIdSystem.js
  test/spec/modules/33acrossBidAdapter_spec.js
  test/spec/modules/33acrossIdSystem_spec.js
Labels: maintenance

#10219 gdprEnforcement: check for purpose 4 on `enrichUfpd` as well as `transmitUfpd`
  modules/gdprEnforcement.js
  test/spec/modules/gdprEnforcement_spec.js
Labels: maintenance

#10152 Yandex Bid Adapter: add adServerCurrency support
  modules/yandexBidAdapter.js
  test/spec/modules/yandexBidAdapter_spec.js
Labels: maintenance

#10231 IX Bid Adapter: add 33Across and LiveIntent to EID allowlist
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance

#10229 userID: break out EID configuration to individual submodules
  modules/33acrossIdSystem.js
  modules/admixerIdSystem.js
  modules/adqueryIdSystem.js
  modules/adtelligentIdSystem.js
  modules/amxIdSystem.js
  modules/britepoolIdSystem.js
  modules/connectIdSystem.js
  modules/criteoIdSystem.js
  modules/czechAdIdSystem.js
  modules/dacIdSystem.js
  modules/deepintentDpesIdSystem.js
  modules/dmdIdSystem.js
  modules/euidIdSystem.js
  modules/fabrickIdSystem.js
  modules/ftrackIdSystem.js
  modules/gravitoIdSystem.js
  modules/growthCodeIdSystem.js
  modules/hadronIdSystem.js
  modules/id5IdSystem.js
  modules/identityLinkIdSystem.js
  modules/idxIdSystem.js
  modules/imuIdSystem.js
  modules/intentIqIdSystem.js
  modules/justIdSystem.js
  modules/kinessoIdSystem.js
  modules/liveIntentIdSystem.js
  modules/lotamePanoramaIdSystem.js
  modules/merkleIdSystem.js
  modules/mwOpenLinkIdSystem.js
  modules/naveggIdSystem.js
  modules/netIdSystem.js
  modules/novatiqIdSystem.js
  modules/oneKeyIdSystem.js
  modules/pairIdSystem.js
  modules/parrableIdSystem.js
  modules/publinkIdSystem.js
  modules/quantcastIdSystem.js
  modules/sharedIdSystem.js
  modules/tapadIdSystem.js
  modules/tncIdSystem.js
  modules/uid2IdSystem.js
  modules/unifiedIdSystem.js
  modules/userId/eids.js
  modules/userId/index.js
  modules/utiqSystem.js
  modules/verizonMediaIdSystem.js
  modules/zeotapIdPlusIdSystem.js
  test/spec/modules/freewheel-sspBidAdapter_spec.js
  test/spec/modules/ixBidAdapter_spec.js
  test/spec/modules/outbrainBidAdapter_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/pubmaticBidAdapter_spec.js
  test/spec/modules/rubiconBidAdapter_spec.js
  test/spec/modules/smaatoBidAdapter_spec.js
  test/spec/modules/userId_spec.js
  test/spec/modules/vrtcalBidAdapter_spec.js
  test/spec/modules/xeBidAdapter_spec.js
  test/spec/modules/yahoosspBidAdapter_spec.js
Labels: feature

#10017 Invibes Bid Adapter : change referrer formatting
  modules/invibesBidAdapter.js
  test/spec/modules/invibesBidAdapter_spec.js
Labels: maintenance

#10194 Optidigital Bid Adapter : update getUserSync method (legacy)
  modules/optidigitalBidAdapter.js
  test/spec/modules/optidigitalBidAdapter_spec.js
Labels: maintenance

#10232 Adnuntius Bid Adaptor: re-enable alias use
  modules/adnuntiusBidAdapter.js
  test/spec/modules/adnuntiusBidAdapter_spec.js
Labels: maintenance

#10228 Adkernel Bid Adapter: support GPP
  modules/adkernelBidAdapter.js
  test/spec/modules/adkernelBidAdapter_spec.js
Labels: maintenance

#10237 AdkernelAdn Bid Adapter: add adpluto_dsp alias
  modules/adkernelAdnBidAdapter.js
  test/spec/modules/adkernelAdnBidAdapter_spec.js
Labels: maintenance

#10227 Beachfront Bid Adapter : GPP support
  modules/beachfrontBidAdapter.js
  test/spec/modules/beachfrontBidAdapter_spec.js
Labels: maintenance

#10235 Adkernel Bid Adapter: add adpluto alias
  modules/adkernelBidAdapter.js
Labels: maintenance

#10222 sspBC Bid Adapter: remove dependence on auctionId, improve notifications
  modules/sspBCBidAdapter.js
  test/spec/modules/sspBCBidAdapter_spec.js
Labels: bugfix

#10171 SSMas Bid adapter : Initial release
  modules/ssmasBidAdapter.js
  modules/ssmasBidAdapter.md
  test/spec/modules/ssmasBidAdapter_spec.js
Labels: feature

#10248 Documentation: Remove outdated video example
  integrationExamples/gpt/pbjs_video_adUnit.html
Labels: maintenance

#10250 consentManagementGPP: do not cancel auctions when CMP is not version 1.0 (7.54.x-legacy backport)
  modules/consentManagementGpp.js
  test/spec/modules/consentManagementGpp_spec.js
Labels: maintenance

#10244 Snigel Bid Adapter: GPP support for Prebid.js 7
  modules/snigelBidAdapter.js
  modules/snigelBidAdapter.md
  test/spec/modules/snigelBidAdapter_spec.js
Labels: maintenance

#10252 Vrtcal Bid Adapter: add gvlid; add fields to ortb2 payload
  modules/vrtcalBidAdapter.js
  test/spec/modules/vrtcalBidAdapter_spec.js
Labels: maintenance

#10238 Ozone Bid Adapter : updates 2.9.0 and tid
  modules/ozoneBidAdapter.js
  modules/ozoneBidAdapter.md
  test/spec/modules/ozoneBidAdapter_spec.js
Labels: bugfix

#10012 Geolocation RTD module: initial release
  modules/geolocationRtdProvider.js
  test/spec/modules/geolocationRtdProvider_spec.js
Labels: feature, needs 2nd review

#10223 Medianet Bid Adapter: Added test cases for GPP
  test/spec/modules/medianetBidAdapter_spec.js
Labels: maintenance

#10141 A1Media RTD module : initial release
  modules/.submodules.json
  modules/a1MediaRtdProvider.js
  modules/a1MediaRtdProvider.md
  src/adloader.js
  test/spec/modules/a1MediaRtdProvider_spec.js
Labels: feature

#10233 ID5 User Id module - accept partner in a string format
  modules/id5IdSystem.js
  test/spec/modules/id5IdSystem_spec.js
Labels: maintenance

#10211 Adf Bid Adapter getFloor update
  modules/adfBidAdapter.js
  test/spec/modules/adfBidAdapter_spec.js
Labels: bugfix

#10150 iMDS Bid Adapter: support gpp
  modules/imdsBidAdapter.js
  test/spec/modules/imdsBidAdapter_spec.js
Labels: maintenance

#10102 Adyoulike Bid Adapter: fix eids retrieve
  modules/adyoulikeBidAdapter.js
  test/spec/modules/adyoulikeBidAdapter_spec.js
Labels: bugfix

#10258 Greenbids Rtd Provider : fix GreenbidsRtdProvider endpoint
  modules/greenbidsRtdProvider.js
  test/spec/modules/greenbidsRtdProvider_spec.js
Labels: bugfix

#10257 priceFloors: fix bug where floors are not set when TIDs are disabled
  integrationExamples/gpt/adUnitFloors.html
  src/adapters/bidderFactory.js
  test/spec/modules/priceFloors_spec.js
  test/spec/unit/core/bidderFactory_spec.js
Labels: needs 2nd review, bugfix

#10262 Core: disregard `transactionId`/`auctionId` set by bid adapters
  src/adapters/bidderFactory.js
  test/spec/unit/core/bidderFactory_spec.js
Labels: bugfix

#10261 LiveIntent UserId module: add magnite id support to legacy branch
  modules/liveIntentIdSystem.js
  modules/userId/eids.js
  modules/userId/eids.md
  test/spec/modules/eids_spec.js
  test/spec/modules/liveIntentIdMinimalSystem_spec.js
  test/spec/modules/liveIntentIdSystem_spec.js
Labels: maintenance

#10267 SSMAS Bid Adapter : change to https
  modules/ssmasBidAdapter.js
Labels: maintenance

#10149 Viant Bid Adapter: Initial Release
  modules/viantOrtbBidAdapter.js
  modules/viantOrtbBidAdapter.md
  test/spec/modules/viantOrtbBidAdapter_spec.js
Labels: feature

#10236 Criteo Bid Adapter: add onDataDeletionRequest method
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: maintenance

#10274 Vidazoo Bid Adapter: pass gpp to user sync
  modules/vidazooBidAdapter.js
Labels: maintenance

#10241 Core (gppControl_usnat) : update default rules for usnat consent interpretation
  libraries/mspa/activityControls.js
  test/spec/libraries/mspa/activityControls_spec.js
Labels: bugfix

#10272 C Wire Bid Adapter: add support for user-syncs
  modules/cwireBidAdapter.js
  test/spec/modules/cwireBidAdapter_spec.js
Labels: maintenance

#10254 NewspassId Bid Adapter: tid logic change and GPID Module Support
  modules/newspassid.md
  modules/newspassidBidAdapter.js
  test/spec/modules/newspassidBidAdapter_spec.js
Labels: bugfix

#10263 Appnexus Bid Adapter : update gpid logic
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: maintenance

#10201 topicsFpdModule: replace ad-hoc GDPR logic with `transmitUfpd` acitivity check; check for topics support before loading frames
  modules/topicsFpdModule.js
  test/spec/modules/topicsFpdModule_spec.js
Labels: feature, needs 2nd review

#10278 GrowthCode Analytics : nobid fix
  modules/growthCodeAnalyticsAdapter.js
Labels: bugfix

#9907 Tappx Bid Adapter: accept ortb2 country
  modules/tappxBidAdapter.js
  modules/tappxBidAdapter.md
Labels: needs unit tests, maintenance

#10281 AdsInteractive Bid Adapter : update sync url
  modules/adsinteractiveBidAdapter.js
Labels: maintenance

#10192 pubCircle Bid Adapter : initial release
  modules/pubCircleBidAdapter.js
  modules/pubCircleBidAdapter.md
  test/spec/modules/pubCircleBidAdapter_spec.js
Labels: feature

#10181 Automatad Analytics Adapter: Initial Release
  modules/automatadAnalyticsAdapter.js
  modules/automatadAnalyticsAdapter.md
  test/spec/modules/automatadAnalyticsAdapter_spec.js
Labels: feature
