Repository prebid/Prebid.js, pull requests merged in 2024-07, with the labels that each got.

#11863 Core: add location method for cross-frame creatives and update creatives
  creative/constants.js
  creative/crossDomain.js
  integrationExamples/gpt/x-domain/creative.html
  libraries/creative-renderer-display/renderer.js
  libraries/creative-renderer-native/renderer.js
  src/adRendering.js
  src/constants.js
  src/prebid.js
  test/spec/creative/crossDomainCreative_spec.js
  test/spec/unit/pbjs_api_spec.js
Labels: feature

#11799 Outbrain adapter: send placement and plcmt fields separately
  modules/adfBidAdapter.js
  modules/codefuelBidAdapter.js
  modules/deltaprojectsBidAdapter.js
  modules/dianomiBidAdapter.js
  modules/finativeBidAdapter.js
  modules/mgidBidAdapter.js
  modules/outbrainBidAdapter.js
  src/utils.js
  test/spec/modules/outbrainBidAdapter_spec.js
Labels: needs update, maintenance

#11748 Outbrain bid adapter add ortb2 device
  modules/outbrainBidAdapter.js
  test/spec/modules/outbrainBidAdapter_spec.js
Labels: maintenance

#11895 Adagio Bid Adapter: fix typo
  modules/adagioBidAdapter.js
Labels: maintenance

#11902 Mobian RTD module: ensure object to modify exists
  modules/mobianRtdProvider.js
  test/spec/modules/mobianRtdProvider_spec.js
Labels: bugfix

#11908 Utils: Fix typo for GDPR/GPDR
  modules/adtrgtmeBidAdapter.js
  modules/apacdexBidAdapter.js
  modules/appnexusBidAdapter.js
  modules/concertBidAdapter.js
  modules/craftBidAdapter.js
  modules/criteoBidAdapter.js
  modules/cwireBidAdapter.js
  modules/goldbachBidAdapter.js
  modules/improvedigitalBidAdapter.js
  modules/jwplayerBidAdapter.js
  modules/mediafuseBidAdapter.js
  modules/nobidBidAdapter.js
  modules/optoutBidAdapter.js
  modules/prebidServerBidAdapter/index.js
  modules/programmaticaBidAdapter.js
  modules/richaudienceBidAdapter.js
  modules/snigelBidAdapter.js
  modules/winrBidAdapter.js
  modules/yahooAdsBidAdapter.js
  src/utils/gdpr.js
  test/pages/consent_mgt_gdpr.html
  test/spec/fpd/gdpr_spec.js
  test/spec/modules/adxcgBidAdapter_spec.js
  test/spec/modules/consentManagement_spec.js
  test/spec/modules/proxistoreBidAdapter_spec.js
  test/spec/modules/pulsepointBidAdapter_spec.js
Labels: bugfix

#11907 Adkernel Bid Adapter: add globalsun alias
  modules/adkernelBidAdapter.js
Labels: feature

#11905 Admixer Bid Adapter: change admixerwl to rtbstack alias
  modules/admixerBidAdapter.js
  modules/admixerBidAdapter.md
  test/spec/modules/admixerBidAdapter_spec.js
Labels: maintenance

#11901 [JW Player Video Provider][Video JS Video Provider]: Add missing typedefs
  modules/jwplayerVideoProvider.js
  modules/videojsVideoProvider.js
Labels: maintenance

#11913 GumGum Bid Adapter: Send ae parameter in the request
  modules/gumgumBidAdapter.js
  test/spec/modules/gumgumBidAdapter_spec.js
Labels: maintenance

#11900 symitriDapRtdProvider : initial release and update akamaiDapRTD to import from symitri
  modules/.submodules.json
  modules/akamaiDapRtdProvider.js
  modules/symitriDapRtdProvider.js
  modules/symitriDapRtdProvider.md
  package-lock.json
  package.json
  src/adloader.js
  test/spec/modules/symitriDapRtdProvider_spec.js
Labels: feature, needs update

#11882 yandex ID: Use error-prone reference to crypto module
  modules/yandexIdSystem.js
  test/spec/modules/yandexIdSystem_spec.js
Labels: bugfix

#11916 mgidBidAdapter: Add gpid value to bid request's imp[].ext
  modules/mgidBidAdapter.js
  test/spec/modules/mgidBidAdapter_spec.js
Labels: maintenance

#11186 JW Player RTD Module : fallback to lone player on page
  modules/jwplayerRtdProvider.js
  test/spec/modules/jwplayerRtdProvider_spec.js
Labels: maintenance

#11919 Anonymised RTD: Added Global Vendor List ID
  modules/anonymisedRtdProvider.js
  modules/anonymisedRtdProvider.md
Labels: maintenance

#11910 permutiveRtd : transform integers to strings
  modules/permutiveRtdProvider.js
  test/spec/modules/permutiveRtdProvider_spec.js
Labels: bugfix

#11923 Visx bid adapter: added currencies: CHF and SEK
  modules/visxBidAdapter.js
Labels: maintenance

#11922 Reduce log spamming
  modules/utiqIdSystem.js
Labels: maintenance

#11425 PubxAi Analytics Adapter : code cleanup and additional data collection
  libraries/userAgentUtils/index.js
  libraries/userAgentUtils/userAgentTypes.enums.js
  modules/pubxaiAnalyticsAdapter.js
  src/ajax.js
  test/spec/ajax_spec.js
  test/spec/libraries/userAgentUtils_spec.js
  test/spec/modules/pubxaiAnalyticsAdapter_spec.js
Labels: needs update, maintenance

#11884 Linter checks: dom manipulation, network traffic, and direct storage access && bugfixes: unauthorized storage access
  .eslintrc.js
  .github/workflows/jscpd.yml
  .github/workflows/linter.yml
  modules/33acrossAnalyticsAdapter.js
  modules/adlooxAnalyticsAdapter.js
  modules/automatadAnalyticsAdapter.js
  modules/cleanioRtdProvider.js
  modules/connectIdSystem.js
  modules/contxtfulRtdProvider.js
  modules/cwireBidAdapter.js
  modules/debugging/debugging.js
  modules/dgkeywordRtdProvider.js
  modules/fintezaAnalyticsAdapter.js
  modules/growthCodeAnalyticsAdapter.js
  modules/growthCodeRtdProvider.js
  modules/relevatehealthBidAdapter.js
  modules/sirdataRtdProvider.js
  modules/sonobiBidAdapter.js
  plugins/eslint/index.js
  src/ajax.js
  src/debugging.js
  src/storageManager.js
  src/utils.js
  test/spec/modules/contxtfulRtdProvider_spec.js
Labels: bugfix

#11877 Discovery Bid Adapter : add ext params
  libraries/currencyUtils/floor.js
  libraries/fpdUtils/deviceInfo.js
  libraries/fpdUtils/pageInfo.js
  libraries/sizeUtils/tranformSize.js
  modules/discoveryBidAdapter.js
  modules/mediagoBidAdapter.js
  modules/winrBidAdapter.js
  test/spec/modules/discoveryBidAdapter_spec.js
  test/spec/modules/mediagoBidAdapter_spec.js
Labels: do not merge, maintenance

#11925 AdmixerBidAdapter: rtbstack change endpointId to tagId
  modules/admixerBidAdapter.js
  modules/admixerBidAdapter.md
  test/spec/modules/admixerBidAdapter_spec.js
Labels: maintenance

#11924 Medianet Bid Adapter: passing uidsAsEids in adapter and log refactor
  modules/medianetBidAdapter.js
  src/utils.js
  test/spec/modules/medianetBidAdapter_spec.js
  test/spec/utils_spec.js
Labels: maintenance

#11935 Adagio Rtd Provider: enrich adg_rtd.session signal
  modules/adagioRtdProvider.js
  test/spec/modules/adagioRtdProvider_spec.js
Labels: maintenance

#11933 Connatix Bid Adapter: Support For Video Media Type
  modules/connatixBidAdapter.js
  test/spec/modules/connatixBidAdapter_spec.js
Labels: feature

#11775 AzerionEdge RTD Module: Compatibility with GDPR/USP Privacy Modules
  modules/azerionedgeRtdProvider.js
  modules/azerionedgeRtdProvider.md
  test/spec/modules/azerionedgeRtdProvider_spec.js
Labels: maintenance

#11939 Playdigo: add user sync
  modules/playdigoBidAdapter.js
Labels: maintenance

#11940 GitHub Action: Update jscpd.yml pr comment language
  .github/workflows/jscpd.yml
Labels: maintenance

#11804 SmileWanted Bid Adapter: support schain
  libraries/schainSerializer/schainSerializer.js
  modules/smilewantedBidAdapter.js
  test/spec/modules/smilewantedBidAdapter_spec.js
  test/spec/schainSerializer/schainSerializer_spec.js
Labels: maintenance

#11926 CORE: check if the body is available before adding the locator iframe
  src/adRendering.js
  test/pages/banner_sync.html
  test/spec/e2e/banner/basic_banner_ad.spec.js
Labels: bugfix

#11945 CI: make linter check workflow less aggressive
  .github/workflows/linter.yml
Labels: maintenance

#11941 DSPx Bid Adapter: add ortb2 content, topics support
  modules/dspxBidAdapter.js
  test/spec/modules/dspxBidAdapter_spec.js
Labels: maintenance

#11930 IntentIQ Analytics Adapter: initial release
  modules/intentIqAnalyticsAdapter.js
  modules/intentIqAnalyticsAdapter.md
  modules/intentIqIdSystem.md
  test/spec/modules/intentIqAnalyticsAdapter_spec.js
Labels: feature

#11947 UA utils: fix tests
  test/spec/libraries/userAgentUtils_spec.js
Labels: maintenance

#11928 Core: Add Session Storage Manager & Contxtful RTD Provider: use session storage
  modules/contxtfulRtdProvider.js
  modules/contxtfulRtdProvider.md
  src/storageManager.js
  test/spec/unit/core/storageManager_spec.js
Labels: maintenance

#11932 Smaato Bid Adapter: Add UserSyncs
  modules/smaatoBidAdapter.js
  test/spec/modules/smaatoBidAdapter_spec.js
Labels: maintenance

#11952 Validation module: jsdoc fixes
  modules/rtdModule/index.js
  modules/userId/eids.js
  modules/validationFpdModule/index.js
Labels: maintenance

#11703 AdvRed Analytics Adapter : initial release
  modules/advRedAnalyticsAdapter.js
  modules/advRedAnalyticsAdapter.md
  test/spec/modules/advRedAnalyticsAdapter_spec.js
Labels: feature

#11950 Dailymotion Bid Adapter: add consent enforcement to read the advertising cookie
  modules/dailymotionBidAdapter.js
  test/spec/modules/dailymotionBidAdapter_spec.js
Labels: maintenance

#11867 TargetVideo Bid Adapter : add video support
  libraries/targetVideoUtils/bidderUtils.js
  libraries/targetVideoUtils/constants.js
  modules/bridBidAdapter.js
  modules/nextMillenniumBidAdapter.js
  modules/targetVideoBidAdapter.js
  modules/targetVideoBidAdapter.md
  test/spec/modules/targetVideoBidAdapter_spec.js
Labels: feature

#11956 Dynamic creatives: fix exception on rendering
  creative/crossDomain.js
  integrationExamples/gpt/x-domain/creative.html
  libraries/creative-renderer-display/renderer.js
  libraries/creative-renderer-native/renderer.js
  test/spec/creative/crossDomainCreative_spec.js
Labels: bugfix

#11788 Appnexus bid adapter add ortb2 device
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: maintenance

#11944 EightPod Bid Adapter + EightPod Analytic Adapter - Support multiple adUnit, updated event tracking, added UserId support
  modules/eightPodAnalyticsAdapter.js
  modules/eightPodBidAdapter.js
  test/spec/modules/eightPodAnalyticsAdapter_spec.js
Labels: needs update, maintenance

#11920 sizeMapping: do not require configuration
  modules/sizeMapping.js
Labels: bugfix

#11960 Core: Remove default value for unused timeoutBuffer config
  src/config.js
Labels: maintenance

#11899 PAAPI: fix bug where configuration is not picked up correctly by the PBS adapter
  modules/paapi.js
  modules/prebidServerBidAdapter/index.js
  modules/prebidServerBidAdapter/ortbConverter.js
  test/spec/modules/paapi_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: bugfix

#11962 eightPodAnalyticsAdapter.js: fix bug on eventListener
  modules/eightPodAnalyticsAdapter.js
Labels: maintenance

#11946 gptPreAuction: pass publisher provided signals to GPT
  libraries/dfpUtils/dfpUtils.js
  libraries/gptUtils/gptUtils.js
  modules/dfpAdServerVideo.js
  modules/dfpAdpod.js
  modules/gptPreAuction.js
  src/targeting.js
  test/spec/modules/gptPreAuction_spec.js
Labels: feature

#11958 Adagio Bid Adapter|Analytics Adapter: use rtd uid as auctionid
  modules/adagioAnalyticsAdapter.js
  modules/adagioBidAdapter.js
  test/spec/modules/adagioAnalyticsAdapter_spec.js
  test/spec/modules/adagioBidAdapter_spec.js
Labels: maintenance

#11968 Kargo Bid Adapter: removes need for multiple iframe syncs
  modules/kargoBidAdapter.js
  test/spec/modules/kargoBidAdapter_spec.js
Labels: maintenance

#11971 Adagio Bid Adapter: GPP remove useless logic
  modules/adagioBidAdapter.js
  test/spec/modules/adagioBidAdapter_spec.js
Labels: maintenance

#11957 Core & fledgeForGpt: backport customSlotMatching
  modules/fledgeForGpt.js
  src/targeting.js
  test/spec/modules/fledgeForGpt_spec.js
  test/spec/unit/core/targeting_spec.js
Labels: feature

#11961 AdagioAnalyticsAdapter: send PBA for all auctions
  modules/adagioAnalyticsAdapter.js
  modules/adagioAnalyticsAdapter.md
  test/spec/modules/adagioAnalyticsAdapter_spec.js
Labels: maintenance

#11912 Core: Add global clearAllAuctions method
  src/prebid.js
  test/spec/unit/pbjs_api_spec.js
Labels: feature, needs 2nd review

#11964 ConnectIdSystem.js: fix storage bypass
  modules/connectIdSystem.js
  test/spec/modules/connectIdSystem_spec.js
Labels: needs update, bugfix

#11874 Smarthub bid adapter: alias vimayx
  libraries/teqblazeUtils/bidderUtils.js
  modules/smarthubBidAdapter.js
  test/spec/modules/smarthubBidAdapter_spec.js
Labels: feature

#11969 uid2IdSystem_shared.js : better logging messages
  modules/uid2IdSystem_shared.js
Labels: maintenance

#11951 Rise utils: initial commit
  libraries/riseUtils/index.js
  modules/minutemediaBidAdapter.js
  modules/openwebBidAdapter.js
  modules/publirBidAdapter.js
  modules/riseBidAdapter.js
  modules/shinezBidAdapter.js
  modules/stnBidAdapter.js
  modules/telariaBidAdapter.js
Labels: maintenance

#11983 adkernelBidAdapter.js: revert alias with existing adapter
  modules/adkernelBidAdapter.js
Labels: bugfix

#11984 Nexx360 Bid Adapter: 1accord alias added
  modules/nexx360BidAdapter.js
  test/spec/modules/nexx360BidAdapter_spec.js
Labels: feature

#11985 Update resetdigitalBidAdapter.md: Details in documentation and New examples
  modules/resetdigitalBidAdapter.md
Labels: maintenance

#11987 AIDEM Bid Adapter: Added gvlid param for Europe GDPR compliance
  modules/aidemBidAdapter.js
Labels: maintenance

#11986 Adkernel Bid Adapter: add global_sun alias
  modules/adkernelBidAdapter.js
Labels: maintenance

#11981 kimberliteBidAdapter: video media type support
  modules/kimberliteBidAdapter.js
  modules/kimberliteBidAdapter.md
  test/spec/modules/kimberliteBidAdapter_spec.js
Labels: feature

#11989 PBS Adapter: backport 11878
  modules/prebidServerBidAdapter/index.js
Labels: bugfix

#11976 Prebid Core: Adding idImportLibrary to activity controls
  modules/idImportLibrary.js
  test/spec/modules/idImportLibrary_spec.js
Labels: bugfix

#11891 CleanmedianetBidAdapter.js: bug fix on plcmt
  modules/cleanmedianetBidAdapter.js
  modules/gamoshiBidAdapter.js
  test/spec/modules/cleanmedianetBidAdapter_spec.js
  test/spec/modules/gamoshiBidAdapter_spec.js
Labels: video, bugfix

#11995 Revert "Appnexus Bid Adapter: parse the currency from the bid if specified"
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: bugfix

#12002 viantOrtbBidAdapter: geo balanaced endpoint for prebid
  modules/viantOrtbBidAdapter.js
Labels: maintenance

#12012 Rise Utils: Bugfixes
  libraries/riseUtils/index.js
Labels: bugfix

#12013 51degreesRtdProvider: update doc
  modules/51DegreesRtdProvider.md
Labels: maintenance

#11975 Dailymotion Bid Adapter: send user sync status in request
  modules/dailymotionBidAdapter.js
  test/spec/modules/dailymotionBidAdapter_spec.js
Labels: feature

#11785 Sharethrough bid adapter add ortb2 device
  modules/sharethroughBidAdapter.js
  test/spec/modules/sharethroughBidAdapter_spec.js
Labels: maintenance

#12014 Mobian RTD Module: remove reference to garm in output of mobian brand-safety
  modules/mobianRtdProvider.js
  test/spec/modules/mobianRtdProvider_spec.js
Labels: maintenance

#12019 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: maintenance

#12020 PubMaticBidAdapter - Support ortb2Imp for pmp property.
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: maintenance

#11965 ID5 UserId module : use userId storage mechanism to store request number
  modules/id5IdSystem.js
  test/spec/modules/id5IdSystem_spec.js
Labels: maintenance

#12031 Readme : fix broken link to docs
  README.md
Labels: maintenance

#11970 Core: ORTB video params validation (work on dupe)
  libraries/ortbConverter/processors/video.js
  modules/adagioBidAdapter.js
  src/prebid.js
  src/video.js
  test/spec/modules/adagioBidAdapter_spec.js
  test/spec/video_spec.js
Labels: maintenance

#12037 Greenbids RTD provider: debug flag
  modules/greenbidsAnalyticsAdapter.js
  modules/greenbidsRtdProvider.js
Labels: maintenance

#12022 Release Drafter : add default of maintenance for categories
  .github/release-drafter.yml
Labels: maintenance

#12041 Update release-drafter.yml
  .github/release-drafter.yml
Labels: maintenance

#11840 WURFL RTD submodule: initial version
  integrationExamples/gpt/wurflRtdProvider_example.html
  modules/.submodules.json
  modules/wurflRtdProvider.js
  modules/wurflRtdProvider.md
  src/adloader.js
  test/spec/modules/wurflRtdProvider_spec.js
Labels: feature

#12004 ttd bid adapter: configurable endpoint
  libraries/connectionInfo/connectionUtils.js
  modules/prismaBidAdapter.js
  modules/ttdBidAdapter.js
  test/spec/modules/ttdBidAdapter_spec.js
Labels: maintenance

#12039 Rubicon Bid Adapter: fix hb_size undefined value for native media type
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: needs unit tests, bugfix

#12048 Update omsBidAdapter.js: allow aliases
  modules/omsBidAdapter.js
Labels: bugfix

#12058 Rise Utils: Fix field name
  libraries/riseUtils/index.js
Labels: maintenance

#12059 CORE: prevent unbound growth of suspendedTimeouts and possible NaN values
  src/utils/focusTimeout.js
  src/utils/ttlCollection.js
  test/spec/unit/utils/focusTimeout_spec.js
Labels: bugfix

#12050 IX Bid Adapter: propagate atype in uids
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance

#12063 Pubxai Analytics Adapter: add additional event listener to collect bidRejected data
  modules/pubxaiAnalyticsAdapter.js
  test/spec/modules/pubxaiAnalyticsAdapter_spec.js
Labels: maintenance

#12057 mgid bid adapters: refactoring for trimmer code
  libraries/mgidUtils/mgidUtils.js
  modules/mgidBidAdapter.js
  modules/mgidXBidAdapter.js
  modules/redtramBidAdapter.js
  modules/undertoneBidAdapter.js
  src/utils.js
Labels: maintenance

#12068 Dailymotion bid adapter: add player name
  modules/dailymotionBidAdapter.js
  modules/dailymotionBidAdapter.md
  test/spec/modules/dailymotionBidAdapter_spec.js
Labels: maintenance

#12066 Cwire Bid Adapter support domainId and deprecate placementId
  modules/cwireBidAdapter.js
  modules/cwireBidAdapter.md
Labels: maintenance

#12055 Ccx bid adapter: Protected Audence, add request param imp.ext.ae
  modules/ccxBidAdapter.js
  test/spec/modules/ccxBidAdapter_spec.js
Labels: maintenance

#12064 PubxAI Rtd module update: Make the endpoint call optional; read from local storage.
  modules/pubxaiRtdProvider.js
  modules/pubxaiRtdProvider.md
  test/spec/modules/pubxaiRtdProvider_spec.js
Labels: maintenance
