Repository prebid/Prebid.js, pull requests merged in 2024-12, with the labels that each got.

#12389 Mobian Bid Adapter : push context data to GAM
  libraries/gptUtils/gptUtils.js
  modules/browsiRtdProvider.js
  modules/mobianRtdProvider.js
  modules/mobianRtdProvider.md
  test/spec/modules/mobianRtdProvider_spec.js
Labels: feature

#12524 IntentIq ID & Analytics Modules : Include additional parameters in the analytical reporting request.
  libraries/intentIqConstants/intentIqConstants.js
  modules/intentIqAnalyticsAdapter.js
  modules/intentIqIdSystem.js
Labels: maintenance

#12517 Craft Bid Adapter : refactor adapter
  libraries/interpretResponseUtils/index.js
  modules/craftBidAdapter.js
Labels: maintenance

#12515 Qortex RTD module : code removal & cleanup
  modules/qortexRtdProvider.js
  test/spec/modules/qortexRtdProvider_spec.js
Labels: maintenance

#12526 Medianet Analytics Adapter: ADD bid properties in logs and small fix in bidTimeoutHandler
  modules/medianetAnalyticsAdapter.js
  test/spec/modules/medianetAnalyticsAdapter_spec.js
Labels: bugfix

#12530 Core: fix bug where adRenderSucceeded event payloads are sometimes missing adId
  src/adRendering.js
  test/spec/unit/pbjs_api_spec.js
Labels: bugfix

#12531 Adtarget Bid Adapter: add gvlid
  modules/adtargetBidAdapter.js
Labels: maintenance

#12364 Currency Module: Adding auction delay handling
  libraries/timeoutQueue/timeoutQueue.js
  modules/currency.js
  modules/priceFloors.js
  test/spec/modules/currency_spec.js
Labels: feature, needs review

#12528 Core: fix bug where queue is processed before processQueue is called
  src/prebid.js
  test/spec/unit/pbjs_api_spec.js
Labels: bugfix

#12532 Prebid Core: Added TTL validation for suppressing expired ads
  src/adRendering.js
  src/config.js
  src/constants.js
  test/spec/config_spec.js
  test/spec/unit/adRendering_spec.js
Labels: feature

#12514 Equativ Bid Adapter: add support for video media type
  modules/equativBidAdapter.js
  test/spec/modules/equativBidAdapter_spec.js
Labels: maintenance

#12535 Core: remove individual bids from cache when minBidCacheTTL is set
  src/auction.js
  src/auctionManager.js
  src/bidTTL.js
  src/targeting.js
  test/spec/auctionmanager_spec.js
Labels: feature

#12541 Bidmatic Bid Adapter: add syncing
  modules/bidmaticBidAdapter.js
  modules/bidmaticBidAdapter.md
  test/spec/modules/bidmaticBidAdapter_spec.js
Labels: maintenance

#12542 Core: support adAuctionHeaders
  src/ajax.js
  test/spec/unit/core/ajax_spec.js
Labels: feature

#12550 Goldfish Ads RTD Adapter: Fix Description Typo
  modules/goldfishAdsRtdProvider.md
Labels: maintenance

#12544 Core & multiple modules: replace `deepAccess` with optional chaining
  libraries/appnexusUtils/anKeywords.js
  libraries/fpdUtils/pageInfo.js
  libraries/ortbConverter/processors/banner.js
  libraries/ortbConverter/processors/video.js
  modules/criteoBidAdapter.js
  modules/dfpAdServerVideo.js
  modules/prebidServerBidAdapter/index.js
  modules/prebidServerBidAdapter/ortbConverter.js
  modules/taboolaBidAdapter.js
  modules/teadsBidAdapter.js
  modules/userId/index.js
  src/Renderer.js
  src/adRendering.js
  src/adapterManager.js
  src/auction.js
  src/native.js
  src/prebid.js
  src/utils/gdpr.js
  src/video.js
  test/spec/unit/core/bidderSettings_spec.js
Labels: maintenance

#12518 Prebid Core: targeting keys issue when enableSendAllBids and alwaysIncludeDeals is true
  src/targeting.js
  test/spec/unit/core/targeting_spec.js
Labels: bugfix

#12548 Yandex Metrica Analytics : update links to the interface
  modules/yandexAnalyticsAdapter.md
Labels: maintenance

#12547 sspBC Bid Adapter : added support for transactionID and update tests
  modules/sspBCBidAdapter.js
  test/spec/modules/sspBCBidAdapter_spec.js
Labels: maintenance

#12558 PBjs : fix master import
  src/prebid.js
Labels: bugfix

#12536 craft Bid Adapter: fix netRevenue
  modules/craftBidAdapter.js
  test/spec/modules/craftBidAdapter_spec.js
Labels: maintenance

#12509 Unicorn Bid Adapter : fix net revenue
  modules/unicornBidAdapter.js
  test/spec/modules/unicornBidAdapter_spec.js
Labels: bugfix

#12565 AdMatic Bid Adapter: adt sync url updated
  modules/admaticBidAdapter.js
Labels: maintenance

#12297 Nexverse Bid Adapter : initial relese
  integrationExamples/gpt/nexverse.html
  libraries/nexverseUtils/index.js
  modules/nexverseBidAdapter.js
  modules/nexverseBidAdapter.md
  test/spec/modules/nexverseBidAdapter_spec.js
Labels: feature

#12568 Livewrapped adapter: Ensure correct winning bid is stored when multiple bids are submitted
  modules/livewrappedAnalyticsAdapter.js
  test/spec/modules/livewrappedAnalyticsAdapter_spec.js
Labels: maintenance

#12563 Adagio rtd provider: fix traffic going outside the ab test
  modules/adagioRtdProvider.js
  test/spec/modules/adagioRtdProvider_spec.js
Labels: maintenance

#12566 Equativ Bid Adapter: support native bid requests
  modules/equativBidAdapter.js
  test/spec/modules/equativBidAdapter_spec.js
Labels: feature

#12557 Feature : Auctions counter at Adslot level
  modules/medianetBidAdapter.js
  src/adUnits.js
  src/adapterManager.js
  test/fixtures/fixtures.js
  test/spec/modules/medianetBidAdapter_spec.js
  test/spec/unit/adUnits_spec.js
  test/spec/unit/core/adapterManager_spec.js
Labels: feature

#12572 Core: fix bug where FPD enrichments can modify bidder configuration
  src/prebid.js
  test/spec/unit/pbjs_api_spec.js
Labels: bugfix

#12017 Rise Bid Adapter: Add ORTB2 device data to request payload
  libraries/riseUtils/index.js
  test/spec/modules/riseBidAdapter_spec.js
Labels: maintenance

#12573 Adnuntius Bid Adapter: use advertiserDomains from ad response to populate meta.advertiserDomains
  modules/adnuntiusBidAdapter.js
  test/spec/modules/adnuntiusBidAdapter_spec.js
Labels: maintenance

#12571 PBS Adapter: fix inconsistency in how bidderconfig is merged, with a special case for EIDs
  modules/prebidServerBidAdapter/bidderConfig.js
  modules/prebidServerBidAdapter/ortbConverter.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: maintenance

#12576 Mobian RTD Module: Docs Update
  modules/mobianRtdProvider.md
Labels: maintenance

#12545 Lasso Bid Adapter : add npi support
  modules/lassoBidAdapter.js
  test/spec/modules/lassoBidAdapter_spec.js
Labels: maintenance

#12549 Bridgeupp Bidder Adapter : initial release
  modules/bridgeuppBidAdapter.js
  modules/bridgeuppBidAdapter.md
  test/spec/modules/bridgeuppBidAdapter_spec.js
Labels: feature

#12581 AcuityAds Bid Adapter: add gvlid
  modules/acuityadsBidAdapter.js
Labels: maintenance

#12579 Aniview Bid Adapter : use credentials in requests
  modules/aniviewBidAdapter.js
Labels: maintenance

#12553 Adnuntius Bid Adapter: add screen and viewport dimensions to ad request
  modules/adnuntiusBidAdapter.js
  test/spec/modules/adnuntiusBidAdapter_spec.js
Labels: maintenance

#12503 KueezRtb Bid Adapter : add first-party data handling
  modules/kueezRtbBidAdapter.js
  test/spec/modules/kueezRtbBidAdapter_spec.js
Labels: maintenance

#12538 AdGeneration Bid Adapter : change endpoint and add ortb converter
  modules/adgenerationBidAdapter.js
  test/spec/modules/adgenerationBidAdapter_spec.js
Labels: maintenance

#12510 Greenbids Bidder Adapter
  libraries/pageInfosUtils/pageInfosUtils.js
  libraries/timeToFirstBytesUtils/timeToFirstBytesUtils.js
  modules/greenbidsBidAdapter.js
  modules/greenbidsBidAdapter.md
  test/spec/libraries/pageInfosUtils.js
  test/spec/libraries/timeToFirstBytesUtils.js
  test/spec/modules/greenbidsBidAdapter_specs.js
Labels: feature

#12413 Brainx Bid Adapter : initial release
  integrationExamples/gpt/hello_world.html
  modules/brainxBidAdapter.js
  modules/brainxBidAdapter.md
  test/spec/modules/brainxBidAdapter_spec.js
Labels: feature

#12590 dfpAdServerVideo: set vconp (continuous playblack on) when playbackmethod contains 7
  modules/dfpAdServerVideo.js
  test/spec/modules/dfpAdServerVideo_spec.js
Labels: bugfix

#12594 PBS Adapter: only include known bidders in eidpermissions
  modules/prebidServerBidAdapter/bidderConfig.js
  modules/prebidServerBidAdapter/ortbConverter.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: maintenance

#12587 Bug fix: Export getProperties method
  src/auction.js
Labels: bugfix

#12582 Adf Bid Adapter: use common ortb2 data
  modules/adfBidAdapter.js
  test/spec/modules/adfBidAdapter_spec.js
Labels: maintenance

#12529 33across ID System: Include hashed email from storage
  modules/33acrossIdSystem.js
  modules/33acrossIdSystem.md
  test/spec/modules/33acrossIdSystem_spec.js
Labels: maintenance

#12601 Smarthub Bid Adapter : set skipPbsAliasing to false
  modules/smarthubBidAdapter.js
Labels: maintenance

#12588 AdMatic Bid Adapter : add yobee alias
  modules/admaticBidAdapter.js
Labels: feature

#12577 Integration example: Create id_lift_measurement.html
  integrationExamples/gpt/id_lift_measurement.html
Labels: feature

#12593 AdPlayerPro Video Module : add PLCMT
  integrationExamples/videoModule/adPlayerPro/bidRequestScheduling.html
  integrationExamples/videoModule/adPlayerPro/eventListeners.html
  modules/adplayerproVideoProvider.js
  test/spec/modules/videoModule/submodules/adplayerproVideoProvider_spec.js
Labels: maintenance

#12559 adtelligent bid adapter: add new allias
  libraries/adtelligentUtils/adtelligentUtils.js
  modules/adtargetBidAdapter.js
  modules/adtelligentBidAdapter.js
  modules/viewdeosDXBidAdapter.js
  test/spec/modules/adtelligentBidAdapter_spec.js
  test/spec/modules/viewdeosDXBidAdapter_spec.js
Labels: maintenance

#12578 Doceree AdManager Bid Adapter : maintainence
  modules/docereeAdManagerBidAdapter.js
  test/spec/modules/docereeAdManagerBidAdapter_spec.js
Labels: maintenance

#12595 PBS Adapter: handle edge case with duplicated EID permissions
  modules/prebidServerBidAdapter/bidderConfig.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: maintenance

#12603 Autoplay detection update: ignore NotSupportedError exceptions
  libraries/autoplayDetection/autoplay.js
Labels: maintenance

#11750 Taboola bid adapter add ortb2 device
  modules/taboolaBidAdapter.js
  test/spec/modules/taboolaBidAdapter_spec.js
Labels: maintenance, Needs contributor

#12006 Adagio Bid Adapter: Add full ORTB2 device data to request payload
  modules/adagioBidAdapter.js
  test/spec/modules/adagioBidAdapter_spec.js
Labels: maintenance

#12074 Vidazoo lib and associated bid adapters: Add ORTB2 device data to request payload
  libraries/vidazooUtils/bidderUtils.js
  test/spec/modules/illuminBidAdapter_spec.js
  test/spec/modules/kueezRtbBidAdapter_spec.js
  test/spec/modules/shinezRtbBidAdapter_spec.js
  test/spec/modules/tagorasBidAdapter_spec.js
  test/spec/modules/twistDigitalBidAdapter_spec.js
  test/spec/modules/vidazooBidAdapter_spec.js
Labels: maintenance

#12475 ImRtdProvider: add imuid param
  modules/imRtdProvider.js
Labels: maintenance

#12527 TNC Id Module : user input url validation and optimizations
  modules/tncIdSystem.js
  modules/tncIdSystem.md
  test/spec/modules/tncIdSystem_spec.js
Labels: maintenance

#12540 Goldbach Bid Adapter: connecting to new backend, reduced bid parameters
  modules/goldbachBidAdapter.js
  modules/goldbachBidAdapter.md
  test/spec/modules/goldbachBidAdapter_spec.js
Labels: maintenance

#12591 Yield one bid adapter: Conditionally stop sending push_sync requests
  modules/yieldoneBidAdapter.js
  test/spec/modules/yieldoneBidAdapter_spec.js
Labels: maintenance

#12592 Aniview: send `format` and `w`/`h` with banner request + refactoring and small fixes
  modules/aniviewBidAdapter.js
  test/spec/modules/aniviewBidAdapter_spec.js
Labels: maintenance

#12600 Lasso Bid AdapteR: Update with testing params
  modules/lassoBidAdapter.js
  test/spec/modules/lassoBidAdapter_spec.js
Labels: maintenance

#12606 nextMillenniumBidAdapter: Added support `imp.video.pos` and `imp.banner.pos`
  modules/nextMillenniumBidAdapter.js
  test/spec/modules/nextMillenniumBidAdapter_spec.js
Labels: maintenance

#12602 Retailspot bidAdapter : Endpoint update
  modules/retailspotBidAdapter.js
  modules/retailspotBidAdapter.md
  test/spec/modules/retailspotBidAdapter_spec.js
Labels: maintenance

#12604 LuponMedia BidAdapter: Add adomain to bidResponse
  modules/luponmediaBidAdapter.js
  test/spec/modules/luponmediaBidAdapter_spec.js
Labels: maintenance

#12583 Akcelo bid adapter : initial release
  modules/akceloBidAdapter.js
  modules/akceloBidAdapter.md
  test/spec/modules/akceloBidAdapter_spec.js
Labels: feature

#12597 Analytics adapters: attach arbitrary labels to analytics events
  libraries/analyticsAdapter/AnalyticsAdapter.js
  test/spec/AnalyticsAdapter_spec.js
  test/spec/modules/genericAnalyticsAdapter_spec.js
Labels: feature

#12596 Mobian RTD Provider: Adds prefix to ortb data as per config
  modules/mobianRtdProvider.js
  test/spec/modules/mobianRtdProvider_spec.js
Labels: maintenance

#12608 Mobian RTD Module: Documentation update
  modules/mobianRtdProvider.md
Labels: maintenance

#12609 Attekmi add new alias artechnology
  modules/smarthubBidAdapter.js
Labels: maintenance
