Repository prebid/Prebid.js, pull requests merged in 2024-01, with the labels that each got.

#10848 Mygaru Id System: Initial release
  modules/.submodules.json
  modules/mygaruIdSystem.js
  modules/mygaruIdSystem.md
  modules/userId/eids.md
  modules/userId/userId.md
  test/spec/modules/mygaruIdSystem_spec.js
Labels: feature, LGTM

#10888 viantOrtb Bid Adapter : add test case for native
  test/spec/modules/viantOrtbBidAdapter_spec.js
Labels: maintenance

#10849 Stv Bid Adapter: added user id support, adaptation of schain support
  modules/stvBidAdapter.js
  test/spec/modules/stvBidAdapter_spec.js
Labels: maintenance

#10894 LiveIntent ID Module: Update live-connect version
  package-lock.json
  package.json
  test/spec/modules/liveIntentIdMinimalSystem_spec.js
  test/spec/modules/liveIntentIdSystem_spec.js
Labels: maintenance

#10895 Rubicon Bid Adapter: Do not require API for video requests
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: maintenance

#10872 Price Floors: Failure to Account for 'data.skipRate'
  modules/priceFloors.js
  test/spec/modules/priceFloors_spec.js
Labels: bugfix

#10800 Discovery Bid Adapter : update buyerId，add ssppid & pmguid, add getUserSyncs
  modules/discoveryBidAdapter.js
  test/spec/modules/discoveryBidAdapter_spec.js
Labels: LGTM, maintenance

#10899 ID5 User Id module - pass gpp string and sid in getId request
  modules/id5IdSystem.js
  test/spec/modules/id5IdSystem_spec.js
Labels: maintenance

#10890 Adnuntius Bid Adapter : bugfix void au ids
  modules/adnuntiusBidAdapter.js
  test/spec/modules/adnuntiusBidAdapter_spec.js
Labels: bugfix

#10792 GreenbidsAnalyticsAdapter and GreenbidsRtdProvider: Rework greenbids sampling and improve transparency
  modules/greenbidsAnalyticsAdapter.js
  modules/greenbidsAnalyticsAdapter.md
  modules/greenbidsRtdProvider.js
  modules/greenbidsRtdProvider.md
  test/spec/modules/greenbidsAnalyticsAdapter_spec.js
  test/spec/modules/greenbidsRtdProvider_spec.js
Labels: maintenance

#10912 Criteo Bid Adapter: remove checks on video context
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: bugfix

#10900 Discovery Bid Adapter : add title, description, keywords
  modules/discoveryBidAdapter.js
  test/spec/modules/discoveryBidAdapter_spec.js
Labels: maintenance

#10883 Ampliffy Bid Adapter: initial commit
  modules/ampliffyBidAdapter.js
  modules/ampliffyBidAdapter.md
  test/spec/modules/ampliffyBidAdapter_spec.js
Labels: feature

#10865 Utils.js (Warning in Integration Tests): add back getWindowFromDocument
  modules/tpmnBidAdapter.js
Labels: bugfix

#10919 Rubicon Bid Adapter : remove transformBidParams function
  modules/rubiconBidAdapter.js
Labels: maintenance

#10921 Sharethrough Bid Adapter : add support for cdep
  modules/sharethroughBidAdapter.js
  test/spec/modules/sharethroughBidAdapter_spec.js
Labels: maintenance

#10918 Adkernel Bid Adapter: multiformat imp splitting
  modules/adkernelBidAdapter.js
  test/spec/modules/adkernelBidAdapter_spec.js
Labels: maintenance

#10911 Geodge RTD module: update preload mechanism
  modules/geoedgeRtdProvider.js
  test/spec/modules/geoedgeRtdProvider_spec.js
Labels: maintenance

#10867 Price Floors: Add option for no signal bidders
  modules/priceFloors.js
  test/spec/modules/priceFloors_spec.js
Labels: feature, needs docs, needs 2nd review

#10926 Criteo bid adapter: add device object to backend request
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: maintenance

#10931 Geolocation RTD provider: make module 'vendorless' for the purposes of TCF
  modules/geolocationRtdProvider.js
Labels: bugfix

#10920 LiveConnect Bid Adapter : add prebid version to liveConnect
  modules/liveIntentIdSystem.js
  package-lock.json
  package.json
  test/spec/modules/liveIntentIdSystem_spec.js
Labels: maintenance

#10903 Insticator Bid Adaptor : add support for playerSize, plcmt, vastXML, & vastURL
  modules/insticatorBidAdapter.js
  test/spec/modules/insticatorBidAdapter_spec.js
Labels: maintenance

#10906 Seedtag Bid Adapter : add geom to bidRequest
  modules/seedtagBidAdapter.js
  test/spec/modules/seedtagBidAdapter_spec.js
Labels: maintenance

#10834 dsp_geniee Bid Adapter : initial release
  modules/dsp_genieeBidAdapter.js
  modules/dsp_genieeBidAdapter.md
  test/spec/modules/dsp_genieeBidAdapter_spec.js
Labels: feature

#10550 Contxtful RTD Provider: Initial Release
  integrationExamples/gpt/contxtfulRtdProvider_example.html
  modules/contxtfulRtdProvider.js
  modules/contxtfulRtdProvider.md
  src/adloader.js
  test/spec/modules/contxtfulRtdProvider_spec.js
Labels: feature

#10877 Ad2iction Bid Adapter: initial release
  modules/ad2ictionBidAdapter.js
  modules/ad2ictionBidAdapter.md
  test/spec/modules/ad2ictionBidAdapter_spec.js
Labels: feature

#10815 Smartadserver Bid Adapter: support additional video parameters
  modules/smartadserverBidAdapter.js
  test/spec/modules/smartadserverBidAdapter_spec.js
Labels: maintenance

#10941 Jsdoc Lint : fix warnings from eslint-plugin
  libraries/cmp/cmpClient.js
  modules/ixBidAdapter.js
  modules/neuwoRtdProvider.js
  modules/prebidServerBidAdapter/index.js
  modules/pubxBidAdapter.js
  modules/rtbhouseBidAdapter.js
  modules/rtdModule/index.js
  modules/rubiconBidAdapter.js
  modules/sspBCBidAdapter.js
  modules/timeoutRtdProvider.js
  modules/yahoosspBidAdapter.js
  src/adRendering.js
  src/adServerManager.js
  src/adloader.js
  src/auction.js
  src/auctionIndex.js
  src/auctionManager.js
  src/config.js
  src/mediaTypes.js
  src/userSync.js
  src/utils.js
  test/spec/modules/sovrnAnalyticsAdapter_spec.js
Labels: maintenance

#10891 Richaudience Bid Adapter : add function onTimeout
  modules/richaudienceBidAdapter.js
  test/spec/modules/richaudienceBidAdapter_spec.js
Labels: needs update, maintenance

#10943 PubMatic Bid Adapter : add support to read and pass badv to adserver
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: maintenance

#10910 Taboola Bid Adapter : refactor using ortb conversion library
  modules/taboolaBidAdapter.js
  test/spec/modules/taboolaBidAdapter_spec.js
Labels: maintenance

#10948 Criteo Bid Adapter : support Fledge seller signals per imp
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: maintenance

#10949 Adman Bid Adapter : add GVLID
  modules/admanBidAdapter.js
Labels: maintenance

#10947 Unicorn Bid Adapter : support id5
  modules/unicornBidAdapter.js
  test/spec/modules/unicornBidAdapter_spec.js
Labels: maintenance

#10885 EUID Id Module : add support for client side token generation
  modules/euidIdSystem.js
  modules/euidIdSystem.md
  modules/uid2IdSystem.js
  modules/uid2IdSystem_shared.js
  test/spec/modules/euidIdSystem_spec.js
  test/spec/modules/uid2IdSystem_spec.js
Labels: feature

#10956 Rise Bid Adapter: add alias support
  modules/riseBidAdapter.js
  test/spec/modules/riseBidAdapter_spec.js
Labels: feature

#10963 Richaudience Bid Adapter): change url tracking
  modules/contxtfulRtdProvider.js
  modules/dsp_genieeBidAdapter.js
  modules/richaudienceBidAdapter.js
  package-lock.json
  test/spec/modules/richaudienceBidAdapter_spec.js
Labels: bugfix

#10961 Sonobi Bid Adapter: Send experian rtid in the bid request payload
  modules/sonobiBidAdapter.js
  test/spec/modules/sonobiBidAdapter_spec.js
Labels: maintenance

#10826 Tagoras Bid Adapter : Initial release
  modules/tagorasBidAdapter.js
  modules/tagorasBidAdapter.md
  test/spec/modules/tagorasBidAdapter_spec.js
Labels: feature

#10969 Insticator Bid Adapter: support optional video params
  modules/insticatorBidAdapter.js
  test/spec/modules/insticatorBidAdapter_spec.js
Labels: maintenance

#10959 Prebid Core: pass document instance to custom renderer
  libraries/creativeRender/direct.js
  src/adRendering.js
Labels: bugfix

#10955 Oxxion Rtd Module: tracking time to run
  modules/oxxionRtdProvider.js
Labels: maintenance

#10952 IQX Bid Adapter : initial release
  modules/iqxBidAdapter.js
  modules/iqxBidAdapter.md
  test/spec/modules/iqxBidAdapter_spec.js
Labels: feature

#10945 AJA Bid Adapter: add Global Placement ID support, remove native/video ad support
  modules/ajaBidAdapter.js
  modules/ajaBidAdapter.md
  test/spec/modules/ajaBidAdapter_spec.js
Labels: maintenance

#10938 AdFusion Bid Adapter : currency support
  modules/adfusionBidAdapter.js
  test/spec/modules/adfusionBidAdapter_spec.js
Labels: maintenance

#10975 Adot Bid Adapter : add gvlid
  modules/adotBidAdapter.js
Labels: maintenance

#10968 Agma Analytics Module : fix getting global config data
  modules/agmaAnalyticsAdapter.js
Labels: bugfix

#10742 ID5 ID Module : ID5 will be able to optionally delegate its logic to an external module
  modules/id5IdSystem.js
  modules/id5IdSystem.md
  src/adloader.js
  test/spec/modules/id5IdSystem_spec.js
Labels: feature

#10972 JSdoc Lint Fixes for Multiple ID Modules
  modules/33acrossIdSystem.js
  modules/admixerIdSystem.js
  modules/adqueryIdSystem.js
  modules/adriverIdSystem.js
  modules/adtelligentIdSystem.js
  modules/britepoolIdSystem.js
  modules/connectIdSystem.js
  modules/criteoIdSystem.js
  modules/czechAdIdSystem.js
  modules/deepintentDpesIdSystem.js
  modules/dmdIdSystem.js
  modules/euidIdSystem.js
  modules/fabrickIdSystem.js
  modules/ftrackIdSystem.js
  modules/growthCodeIdSystem.js
  modules/hadronIdSystem.js
  modules/id5IdSystem.js
  modules/identityLinkIdSystem.js
  modules/idxIdSystem.js
  modules/imuIdSystem.js
  modules/intentIqIdSystem.js
  modules/justIdSystem.js
  modules/kinessoIdSystem.js
  modules/liveIntentIdSystem.js
  modules/lotamePanoramaIdSystem.js
  modules/merkleIdSystem.js
  modules/mwOpenLinkIdSystem.js
  modules/mygaruIdSystem.js
  modules/naveggIdSystem.js
  modules/netIdSystem.js
  modules/novatiqIdSystem.js
  modules/oneKeyIdSystem.js
  modules/operaadsIdSystem.js
  modules/pairIdSystem.js
  modules/parrableIdSystem.js
  modules/pubProvidedIdSystem.js
  modules/publinkIdSystem.js
  modules/quantcastIdSystem.js
  modules/sharedIdSystem.js
  modules/teadsIdSystem.js
  modules/uid2IdSystem.js
  modules/unifiedIdSystem.js
  modules/verizonMediaIdSystem.js
  modules/zeotapIdPlusIdSystem.js
  src/targeting.js
  src/userSync.js
Labels: maintenance

#10973 JSdoc Linting Fixes for Multiiple RTD Modules
  modules/a1MediaRtdProvider.js
  modules/adnuntiusRtdProvider.js
  modules/airgridRtdProvider.js
  modules/arcspanRtdProvider.js
  modules/blueconicRtdProvider.js
  modules/brandmetricsRtdProvider.js
  modules/browsiRtdProvider.js
  modules/cleanioRtdProvider.js
  modules/dgkeywordRtdProvider.js
  modules/experianRtdProvider.js
  modules/geoedgeRtdProvider.js
  modules/goldfishAdsRtdProvider.js
  modules/hadronRtdProvider.js
  modules/idWardRtdProvider.js
  modules/imRtdProvider.js
  modules/jwplayerRtdProvider.js
  modules/mgidRtdProvider.js
  modules/oneKeyRtdProvider.js
  modules/optimeraRtdProvider.js
  modules/oxxionRtdProvider.js
  modules/permutiveRtdProvider.js
  modules/reconciliationRtdProvider.js
  modules/timeoutRtdProvider.js
Labels: maintenance

#10976 Insticator Bid Adaptor: add support for bidder video params
  modules/insticatorBidAdapter.js
  test/spec/modules/insticatorBidAdapter_spec.js
Labels: maintenance

#10913 Conversant Bid Adapter : use ortbConverter to handle requests and responses
  modules/conversantBidAdapter.js
  test/spec/modules/conversantBidAdapter_spec.js
Labels: feature

#10881 zMaticoo Bid Adapter : Initial Release
  modules/zmaticooBidAdapter.js
  modules/zmaticooBidAdapter.md
  test/spec/modules/zmaticooBidAdapter_spec.js
Labels: feature

#10923 MediaGo Bid Adapter : add pmguid, title, description, keywords and synchronize mguid from third party cookie to first party cookie.
  modules/mediagoBidAdapter.js
  test/spec/modules/mediagoBidAdapter_spec.js
Labels: maintenance

#10965 Discovery Bid Adapter : not filter params
  modules/discoveryBidAdapter.js
  test/spec/modules/discoveryBidAdapter_spec.js
Labels: maintenance

#10971 appnexus Bid Adapter : add DSA support
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: feature

#10871 NextMillennium Bid Adapter : currency support in request
  modules/nextMillenniumBidAdapter.js
  test/spec/modules/nextMillenniumBidAdapter_spec.js
Labels: maintenance

#10779 Core & PBS adapter: fix race condition between network timeout and auction timeout
  modules/prebidServerBidAdapter/index.js
  src/adapterManager.js
  src/adapters/bidderFactory.js
  src/ajax.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/unit/core/adapterManager_spec.js
  test/spec/unit/core/ajax_spec.js
  test/spec/unit/core/bidderFactory_spec.js
Labels: bugfix

#10927 Discovery Bid Adapter : synchronize mguid from third party cookie to first party cookie
  modules/discoveryBidAdapter.js
  test/spec/modules/discoveryBidAdapter_spec.js
Labels: maintenance

#10992 Sovrn Bid Adapter : change maintainer mail
  modules/sovrnAnalyticsAdapter.md
  modules/sovrnBidAdapter.md
Labels: maintenance

#10995 Grid Bid Adapter : do not send topics along requests to the backend
  modules/gridBidAdapter.js
Labels: maintenance

#10977 dfpAdServerVideo: add several parameters do DFP URLs
  modules/dfpAdServerVideo.js
  test/spec/modules/dfpAdServerVideo_spec.js
Labels: video

#10996 Smilewanted Bid Adapter : support video instream, video outstream and native
  modules/smilewantedBidAdapter.js
  test/spec/modules/smilewantedBidAdapter_spec.js
Labels: maintenance

#11004 GrowthCode User ID Module: Simplify Code base, added custom EID option
  modules/growthCodeIdSystem.js
  modules/growthCodeIdSystem.md
  test/spec/modules/growthCodeIdSystem_spec.js
Labels: maintenance

#10990 E2E testing: Remove @wdio/sync and update @wdio/* to the latest
  .circleci/config.yml
  README.md
  gulpfile.js
  package-lock.json
  package.json
  test/helpers/testing-utils.js
  test/spec/e2e/banner/basic_banner_ad.spec.js
  test/spec/e2e/instream/basic_instream_video_ad.spec.js
  test/spec/e2e/longform/basic_w_bidderSettings.spec.js
  test/spec/e2e/longform/basic_w_custom_adserver_translation.spec.js
  test/spec/e2e/longform/basic_w_priceGran.spec.js
  test/spec/e2e/longform/basic_w_requireExactDuration.spec.js
  test/spec/e2e/longform/basic_wo_brandCategoryExclusion.spec.js
  test/spec/e2e/longform/basic_wo_requireExactDuration.spec.js
  test/spec/e2e/modules/e2e_bidderSettings.spec.js
  test/spec/e2e/modules/e2e_currency.spec.js
  test/spec/e2e/multi-bidder/e2e_multiple_bidders.spec.js
  test/spec/e2e/native/basic_native_ad.spec.js
  test/spec/e2e/outstream/basic_outstream_video_ad.spec.js
  wdio.conf.js
  wdio.local.conf.js
  wdio.shared.conf.js
Labels: maintenance

#10876 Yandex Analytics Adapter: initial release
  modules/yandexAnalyticsAdapter.js
  modules/yandexAnalyticsAdapter.md
  test/spec/modules/yandexAnalyticsAdapter_spec.js
Labels: feature

#10612 MgidX Bid Adapter: add optional region param
  modules/mgidXBidAdapter.js
  test/spec/modules/mgidXBidAdapter_spec.js
Labels: maintenance

#10664 Video module: log error when adUnit provides unknown player div ID
  modules/videoModule/coreVideo.js
  modules/videoModule/index.js
  test/spec/modules/videoModule/pbVideo_spec.js
Labels: bugfix

#10882 ZetaGlobalSsp BidAdapter : provide params not only from first entry
  modules/zeta_global_sspBidAdapter.js
Labels: needs unit tests, bugfix

#10892 Yieldmo Bid Adapter : send topics in the Bid Request
  modules/yieldmoBidAdapter.js
  test/spec/modules/yieldmoBidAdapter_spec.js
Labels: maintenance

#10896 SilverMob Bid adapter: initial commit
  modules/silvermobBidAdapter.js
  modules/silvermobBidAdapter.md
  test/spec/modules/silvermobBidAdapter_spec.js
Labels: feature

#11009 AppNexus Bid Adapter: stop suppressing user syncs on any gpp string with section > 5
  modules/appnexusBidAdapter.js
Labels: maintenance

#11013 Topics fpd module : fix for intermitent failing test
  modules/topicsFpdModule.js
  test/spec/modules/topicsFpdModule_spec.js
Labels: bugfix

#11027 Appnexus Bid Adapter: Update DSA field names
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: maintenance
