Repository prebid/Prebid.js, pull requests merged in 2024-05, with the labels that each got.

#11300 Pubx.ai RTD Provider - Initial Release
  integrationExamples/gpt/pubxaiRtdProvider_example.html
  modules/.submodules.json
  modules/pubxaiRtdProvider.js
  modules/pubxaiRtdProvider.md
  test/spec/modules/pubxaiRtdProvider_spec.js
Labels: feature

#11159 lockr AIM user module: initial release
  modules/.submodules.json
  modules/lockrAIMIdSystem.js
  modules/lockrAIMIdSystem.md
  test/spec/modules/lockrAIMIdSystem_spec.js
Labels: feature, needs docs

#11430 OpenWeb Bid Adapter : remove multi currency support
  modules/openwebBidAdapter.js
  modules/openwebBidAdapter.md
  test/spec/modules/openwebBidAdapter_spec.js
Labels: maintenance

#11406 Prebid 9.0: oolo analytics id leak fix
  modules/ooloAnalyticsAdapter.js
Labels: bugfix

#11428 MinuteMedia Bid Adapter: remove multi currency support
  modules/minutemediaBidAdapter.js
  modules/minutemediaBidAdapter.md
  test/spec/modules/minutemediaBidAdapter_spec.js
Labels: maintenance

#11427 Rise Bid Adapter : remove multi currency support
  modules/riseBidAdapter.js
  modules/riseBidAdapter.md
  test/spec/modules/riseBidAdapter_spec.js
Labels: maintenance

#11405 PB9: Delete integrationExamples/gpt/creative_rendering.html
  integrationExamples/gpt/creative_rendering.html
Labels: maintenance

#11431 lmpIdSystem: Add initial userId submodule
  modules/.submodules.json
  modules/lmpIdSystem.js
  modules/lmpIdSystem.md
  modules/userId/userId.md
  test/spec/modules/lmpIdSystem_spec.js
Labels: feature

#11284 EXADS Bid Adapter: initial release
  modules/exadsBidAdapter.js
  modules/exadsBidAdapter.md
  test/spec/modules/exadsBidAdapter_spec.js
Labels: feature

#11260 Eight Pod Bid / Analytics Adapter : initial release
  modules/eightPodAnalyticsAdapter.js
  modules/eightPodAnalyticsAdapter.md
  modules/eightPodBidAdapter.js
  modules/eightPodBidAdapter.md
  test/spec/modules/eightPodAnalyticsAdapter_spec.js
  test/spec/modules/eightPodBidAdapter_spec.js
Labels: feature

#11436 Limelight Digital Bid Adapter: fix page field filling
  modules/limelightDigitalBidAdapter.js
  test/spec/modules/limelightDigitalBidAdapter_spec.js
Labels: bugfix

#11441 Conversant Bid Adapter: remove transformBidParams
  modules/conversantBidAdapter.js
Labels: maintenance

#11433 Smaato Bid Adapter: Migrating to ortbConverter requests build process
  modules/smaatoBidAdapter.js
  test/spec/modules/smaatoBidAdapter_spec.js
Labels: feature

#11424 ID5 ID System : update call with credentials
  modules/id5IdSystem.js
  test/spec/modules/id5IdSystem_spec.js
Labels: maintenance

#11401 Prebid 9.0: delete empty file
  modules/33acrossAnalyticsAdapter.md
  modules/enrichmentFpdModule.js
  modules/fpdModule/index.md
  test/spec/modules/BTBidAdapter_spec.js
Labels: maintenance

#11383 DeepIntent Id Module : fix user ids not being passed on page reload due to getValue func miss
  modules/deepintentDpesIdSystem.js
  test/spec/modules/deepintentDpesIdsystem_spec.js
Labels: bugfix

#11380 Discovery Bid Adapter : get UTM tag data
  modules/discoveryBidAdapter.js
  test/spec/modules/discoveryBidAdapter_spec.js
Labels: maintenance

#11147 Sovrn Bid Adapter: Remove Sovrn Analytics Adapter
  modules/sovrnAnalyticsAdapter.js
  modules/sovrnAnalyticsAdapter.md
  test/spec/modules/sovrnAnalyticsAdapter_spec.js
Labels: maintenance, 9.0 API Change

#11448 README: note about build-bundle-dev
  README.md
Labels: maintenance

#11440 HadronId System: adding the domain name when calling home
  modules/hadronIdSystem.js
Labels: maintenance

#11449 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: maintenance

#11366 Dailymotion Bid Adapter: accept ortb2 field
  modules/dailymotionBidAdapter.js
  modules/dailymotionBidAdapter.md
  test/spec/modules/dailymotionBidAdapter_spec.js
Labels: maintenance

#11453 Module: Remove Adomik
  modules/adomikAnalyticsAdapter.js
  test/spec/modules/adomikAnalyticsAdapter_spec.js
Labels: 9.0 API Change

#11447 Mabidder Bid Adapter : use ortbConverter facility to pass ortb2
  modules/mabidderBidAdapter.js
Labels: maintenance

#11451 Sharethrough Bid Adapter: update gpid determination logic
  modules/sharethroughBidAdapter.js
Labels: maintenance

#11452 AJA Bid Adapter : fix multiple media type request issue
  modules/ajaBidAdapter.js
Labels: bugfix

#11456 EXADS bid adapter: replace broken logic with merely bad logic
  modules/exadsBidAdapter.js
Labels: bugfix

#11460 Sonobi Bid Adapter : look for gpid in the ortb2Imp.ext.gpid
  modules/sonobiBidAdapter.js
  test/spec/modules/sonobiBidAdapter_spec.js
Labels: maintenance

#11325 Performax Bid Adapter: New bidder adapter
  modules/performaxBidAdapter.js
  modules/performaxBidAdapter.md
  test/spec/modules/performaxBidAdapter_spec.js
Labels: feature

#11418 PBjs Utils: Faster Deep Clone
  allowedModules.js
  modules/browsiRtdProvider.js
  package-lock.json
  package.json
  src/utils.js
Labels: maintenance

#11407 Prebid 9: remove USP consent string from consent metadata
  src/consentHandler.js
  test/spec/modules/consentManagementUsp_spec.js
Labels: maintenance

#11463 LiveIntent User ID Module: Stabilize Tests
  test/spec/modules/liveIntentIdSystem_spec.js
Labels: maintenance

#11458 OpenX Bid Adapter: remove transformBidParams
  modules/openxBidAdapter.js
Labels: maintenance

#11450 Smaato Bid Adapter : change server response type
  modules/smaatoBidAdapter.js
  test/spec/modules/smaatoBidAdapter_spec.js
Labels: maintenance

#11464 EXADS Bid Adapter : update bidder code before adapter is published
  modules/exadsBidAdapter.js
  modules/exadsBidAdapter.md
  test/spec/modules/exadsBidAdapter_spec.js
Labels: bugfix

#11378 Playdigo: new adapter
  modules/playdigoBidAdapter.js
  modules/playdigoBidAdapter.md
  test/spec/modules/playdigoBidAdapter_spec.js
Labels: feature

#11370 Twist Digital Bid Adapter: initial release
  modules/twistDigitalBidAdapter.js
  modules/twistDigitalBidAdapter.md
  test/spec/modules/twistDigitalBidAdapter_spec.js
Labels: feature

#11471 Telaria Bid Adapter : fixed small typo
  modules/telariaBidAdapter.md
Labels: maintenance

#11468 IX Bid Adapter : code cleanup and refactor
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance

#11473 PulsePoint bid adapter: Removing deprecated method
  modules/pulsepointBidAdapter.js
Labels: maintenance

#11469 Various Bid Adapters: removing hardcoded tmax/timeout values
  modules/advangelistsBidAdapter.js
  modules/axonixBidAdapter.js
  modules/bluebillywigBidAdapter.js
  modules/brightMountainMediaBidAdapter.js
  modules/lkqdBidAdapter.js
  modules/mgidXBidAdapter.js
  modules/oguryBidAdapter.js
  modules/rhythmoneBidAdapter.js
  modules/visxBidAdapter.js
  test/spec/modules/advangelistsBidAdapter_spec.js
  test/spec/modules/bluebillywigBidAdapter_spec.js
  test/spec/modules/lkqdBidAdapter_spec.js
  test/spec/modules/mgidXBidAdapter_spec.js
  test/spec/modules/oguryBidAdapter_spec.js
Labels: maintenance

#11402 Various Adapters: Delete s2s transform bid params for adapters with no server equivalent
  modules/adagioBidAdapter.js
  modules/adrelevantisBidAdapter.js
  modules/big-richmediaBidAdapter.js
  modules/craftBidAdapter.js
  modules/goldbachBidAdapter.js
  modules/vibrantmediaBidAdapter.js
  modules/winrBidAdapter.js
  test/spec/modules/adagioBidAdapter_spec.js
  test/spec/modules/big-richmediaBidAdapter_spec.js
  test/spec/modules/vibrantmediaBidAdapter_spec.js
Labels: maintenance

#11480 Kargo Bid Adapter : adds support for PAAPI module
  modules/kargoBidAdapter.js
  test/spec/modules/kargoBidAdapter_spec.js
Labels: maintenance

#11474 Prebid 9: export only public interface for NPM consumers
  package.json
  src/prebid.public.js
Labels: maintenance

#11435 Criteo Bid Adapter : remove references to fast bid
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: maintenance

#11369 33Across User ID Module: Enable 1PID addressability by default
  modules/33acrossIdSystem.js
  modules/33acrossIdSystem.md
  test/spec/modules/33acrossIdSystem_spec.js
Labels: 9.0 API Change

#11465 Adnuntius Bid Adapter: site Ext Data sent as key values
  modules/adnuntiusBidAdapter.js
  test/spec/modules/adnuntiusBidAdapter_spec.js
Labels: maintenance

#11475 PB9: fix yukta analytics methods
  modules/yuktamediaAnalyticsAdapter.js
Labels: maintenance

#11484 Waardex Bid Adapter : remove Prebid email
  modules/waardexBidAdapter.md
Labels: maintenance

#11487 Adagio Bid Adapter: validate `plcmt` video param
  modules/adagioBidAdapter.js
  test/spec/modules/adagioBidAdapter_spec.js
Labels: bugfix

#11483 AdsYield Bid Adapter: move to limelight
  modules/admixerBidAdapter.js
  modules/limelightDigitalBidAdapter.js
  test/spec/modules/admixerBidAdapter_spec.js
Labels: maintenance

#11491 Vidazoo Bid Adapter : rector gpid value assignment
  modules/vidazooBidAdapter.js
Labels: maintenance

#11481 Prebid 9: Deprecate native sendTargetingKeys/types, validate asset IDs
  src/prebid.js
  test/spec/unit/pbjs_api_spec.js
Labels: 9.0 API Change

#11492 KueezRTB Bid Adapter : refactor gpid extraction logic
  modules/kueezRtbBidAdapter.js
Labels: maintenance

#11490 Seedtag Bid Adapter : allows sending bcat and badv ortb2 params in request payload
  modules/seedtagBidAdapter.js
  test/spec/modules/seedtagBidAdapter_spec.js
Labels: maintenance

#11477 Invibes Bid Adapter : reading page referer and cookie handlid
  modules/invibesBidAdapter.js
  test/spec/modules/invibesBidAdapter_spec.js
Labels: maintenance

#11502 Brid Bid Adapter: switching to plcmt
  modules/bridBidAdapter.js
Labels: maintenance

#11504 Tappx Bid Adapter : change to plcmt
  modules/tappxBidAdapter.js
  modules/tappxBidAdapter.md
  test/spec/modules/tappxBidAdapter_spec.js
Labels: maintenance

#11496 OpenX Bid Adapter: remove use of deprecated video.placement
  modules/openxBidAdapter.js
  test/spec/modules/openxBidAdapter_spec.js
Labels: maintenance

#11498 Prebid 9: change auctionDelay default to 500
  modules/userId/index.js
  src/userSync.js
  test/spec/modules/id5IdSystem_spec.js
  test/spec/modules/userId_spec.js
Labels: maintenance

#11343 Core: include dynamic renderer in native messages
  src/native.js
  test/spec/native_spec.js
Labels: feature

#11414 51Degrees RTD submodule: initial commit
  integrationExamples/gpt/51DegreesRtdProvider_example.html
  modules/51DegreesRtdProvider.js
  modules/51DegreesRtdProvider.md
  src/adloader.js
  test/spec/modules/51DegreesRtdProvider_spec.js
Labels: feature

#11513 Sharethrough Analytics Adapter: Provide documentation
  modules/sharethroughAnalyticsAdapter.md
Labels: LGTM

#11514 Improve Digital Bid Adapter : remove parsing of addtlConsent
  modules/improvedigitalBidAdapter.js
  test/spec/modules/improvedigitalBidAdapter_spec.js
Labels: maintenance

#11518 pirIdSystem: Module delete
  modules/openxBidAdapter.js
  modules/pirIdSystem.js
  modules/pirIdSystem.md
  test/spec/modules/openxBidAdapter_spec.js
  test/spec/modules/pirIdSystem_spec.js
Labels: feature

#11517 Appnexus Bid Adapter : add new GVL ID for Adzymic alias
  modules/appnexusBidAdapter.js
Labels: maintenance

#11507 Yieldmo Bid Adapter: adding Prebid 9 compatibility
  modules/yieldmoBidAdapter.js
  test/spec/modules/yieldmoBidAdapter_spec.js
Labels: maintenance

#11489 pb9: Organize adloader.js
  src/adloader.js
  test/spec/adloader_spec.js
Labels: maintenance

#11454 Driftpixel Bid Adapter : initial release
  modules/driftpixelBidAdapter.js
  modules/driftpixelBidAdapter.md
  test/spec/modules/driftpixelBidAdapter_spec.js
Labels: feature

#11520 optimera Rtd Module : hotfix for handling score file URIs
  modules/optimeraRtdProvider.js
  test/spec/modules/optimeraRtdProvider_spec.js
Labels: bugfix

#11523 Adxcg Bid Adapter : remove transformBidParams function
  modules/adxcgBidAdapter.js
  test/spec/modules/adxcgBidAdapter_spec.js
Labels: maintenance

#11493 1plusX Rtd Provider : add First Party Cookie ID option
  modules/1plusXRtdProvider.js
  modules/1plusXRtdProvider.md
  test/spec/modules/1plusXRtdProvider_spec.js
Labels: feature

#11485 Adagio Bid Adapter: preparation for new Rtd module and Prebid.js 9
  modules/adagioBidAdapter.js
  src/utils.js
  test/spec/modules/adagioBidAdapter_spec.js
  test/spec/utils_spec.js
Labels: maintenance

#11525 Rename yahoosspBidAdapter to yahooAdsBidAdapter for Prebid 9
  modules/yahooAdsBidAdapter.js
  modules/yahooAdsBidAdapter.md
  test/spec/modules/yahooAdsBidAdapter_spec.js
Labels: feature

#11521 Prebid 9: rename GDPR modules
  modules/33acrossAnalyticsAdapter.md
  modules/consentManagementTcf.js
  modules/tcfControl.js
  src/prebid.js
  test/spec/fpd/gdpr_spec.js
  test/spec/modules/BTBidAdapter_spec.js
  test/spec/modules/asoBidAdapter_spec.js
  test/spec/modules/bizzclickBidAdapter_spec.js
  test/spec/modules/consentManagement_spec.js
  test/spec/modules/conversantBidAdapter_spec.js
  test/spec/modules/euidIdSystem_spec.js
  test/spec/modules/id5AnalyticsAdapter_spec.js
  test/spec/modules/improvedigitalBidAdapter_spec.js
  test/spec/modules/openxBidAdapter_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/prismaBidAdapter_spec.js
  test/spec/modules/rubiconBidAdapter_spec.js
  test/spec/modules/silvermobBidAdapter_spec.js
  test/spec/modules/smaatoBidAdapter_spec.js
  test/spec/modules/tcfControl_spec.js
  test/spec/modules/tpmnBidAdapter_spec.js
  test/spec/modules/trafficgateBidAdapter_spec.js
  test/spec/modules/uid2IdSystem_helpers.js
  test/spec/modules/uid2IdSystem_spec.js
  test/spec/modules/userId_spec.js
  test/spec/ortbConverter/gdpr_spec.js
Labels: maintenance

#11411 Smarthub Bid Adapter : update convertOrtbToNative
  modules/smarthubBidAdapter.js
  test/spec/modules/smarthubBidAdapter_spec.js
Labels: maintenance

#11486 Criteo Bid Adapter: converted adapter to oRTB 2.5
  libraries/ortb2.5Translator/translator.js
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: feature

#11479 ZetaGlobalSsp Analytics Adapter: refactoring
  modules/zeta_global_sspAnalyticsAdapter.js
  test/spec/modules/zeta_global_sspAnalyticsAdapter_spec.js
Labels: maintenance

#11532 FreeWheel Bid Adapter: remove .innerText for PrebidJS 9.0
  modules/freewheel-sspBidAdapter.js
Labels: maintenance

#11534 Mediafuse Bid Adapter : remove transformBidParams function
  modules/mediafuseBidAdapter.js
Labels: maintenance

#11510 cee Id System : initial ID module release
  modules/ceeIdSystem.js
  modules/ceeIdSystem.md
  test/spec/modules/ceeIdSystem_spec.js
Labels: feature

#11445 Browsi RTD : add split key
  modules/browsiRtdProvider.js
  test/spec/modules/browsiRtdProvider_spec.js
Labels: maintenance

#11535 Teads Bid Adapter : add GPP support
  modules/teadsBidAdapter.js
  test/spec/modules/teadsBidAdapter_spec.js
Labels: maintenance

#11537 Prebid 9: add deprecation warning for pbadslot
  modules/gptPreAuction.js
Labels: maintenance

#11539 Onetag Bid Adapter: add reading of ortb2Imp field
  modules/onetagBidAdapter.js
  test/spec/modules/onetagBidAdapter_spec.js
Labels: maintenance

#11508 Adnuntius Bid Adapter : merge targeting from multiple sources
  modules/adnuntiusBidAdapter.js
  test/spec/modules/adnuntiusBidAdapter_spec.js
Labels: bugfix

#11512 Bizzclick Bid Adapter : rename bizzclick to blasto
  modules/blastoBidAdapter.js
  modules/blastoBidAdapter.md
  test/spec/modules/blastoBidAdapter_spec.js
Labels: feature

#11461 Prebid 9: remove support for GPP 1.0
  modules/consentManagementGpp.js
  test/spec/modules/consentManagementGpp_spec.js
Labels: 9.0 API Change

#11531 Prebid 9: Removing innerText & adding eslint rule
  .eslintrc.js
  modules/adhashBidAdapter.js
  modules/idImportLibrary.js
  plugins/eslint/index.js
  plugins/eslint/package.json
  plugins/eslint/validateImports.js
  test/spec/modules/adhashBidAdapter_spec.js
Labels: feature

#11530 PubMatic Bid Adapter : start sending displaymanager & displaymanagerver
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: maintenance

#11527 Livewrapped Analytics Adapter : forward extended parameters
  modules/livewrappedAnalyticsAdapter.js
  test/spec/modules/livewrappedAnalyticsAdapter_spec.js
Labels: maintenance

#11522 Prebid 9: stop supporting top level app/site/device FPD config
  src/fpd/enrichment.js
  test/spec/fpd/enrichment_spec.js
  test/spec/fpd/oneClient_spec.js
  test/spec/modules/improvedigitalBidAdapter_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: maintenance

#11499 Prebid 9: stop using transformBidParams
  libraries/pbsExtensions/processors/params.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/ortbConverter/pbsExtensions/params_spec.js
Labels: 9.0 API Change

#11437 LiveIntent Identity Module: Introduce First Party ID
  modules/liveIntentIdSystem.js
  modules/userId/eids.md
  package-lock.json
  package.json
  test/spec/modules/eids_spec.js
  test/spec/modules/liveIntentIdSystem_spec.js
Labels: feature

#11543 Eskimi Bid Adapter: switching to plcmt
  modules/eskimiBidAdapter.js
  test/spec/modules/eskimiBidAdapter_spec.js
Labels: maintenance

#11478 Colombia Bid Adapter : initial release
  modules/colombiaBidAdapter.js
  modules/colombiaBidAdapter.md
  package-lock.json
  test/spec/modules/colombiaBidAdapter_spec.js
Labels: feature

#11472 Insticator Bid Adapter: Add support for BidFloors
  modules/insticatorBidAdapter.js
  test/spec/modules/insticatorBidAdapter_spec.js
Labels: feature

#11482 User id module: Ability to store user IDs in cookie and localStorage simultaneously
  modules/userId/index.js
  test/spec/modules/userId_spec.js
Labels: maintenance

#11545 Taboola Bid Adapter: support DChain
  modules/taboolaBidAdapter.js
  test/spec/modules/taboolaBidAdapter_spec.js
Labels: maintenance

#11559 Kobler adapter: Fix to avoid bidding with third-party creatives requiring consent or legitimate interest.
  modules/koblerBidAdapter.js
  test/spec/modules/koblerBidAdapter_spec.js
Labels: maintenance

#11565 MinuteMedia Bid Adapter : respond with the correct creativeId
  modules/minutemediaBidAdapter.js
  test/spec/modules/minutemediaBidAdapter_spec.js
Labels: bugfix

#11564 Rise Bid Adapter : respond with the correct creativeId
  modules/riseBidAdapter.js
  test/spec/modules/riseBidAdapter_spec.js
Labels: bugfix

#11566 STN Bid Adapter : respond with the correct creativeId
  modules/stnBidAdapter.js
  test/spec/modules/stnBidAdapter_spec.js
Labels: bugfix

#11544 Adkernel Bid Adapter: add hyperbrainz alias
  modules/adkernelBidAdapter.js
Labels: maintenance

#11519 Prebid Core: Configurable maxbid
  src/auction.js
  src/config.js
  src/constants.js
  test/spec/auctionmanager_spec.js
Labels: maintenance

#11573 Datawrkz bid adapter : removed use of deprecated video.placement
  modules/datawrkzBidAdapter.js
Labels: maintenance

#11576 ZetaGlobalSppAdapter: remove onTimeout
  modules/zeta_global_sspBidAdapter.js
  test/spec/modules/zeta_global_sspBidAdapter_spec.js
Labels: maintenance

#11574 OpenWeb Bid Adapter : fix use of requestId content as creativeId in its responses
  modules/openwebBidAdapter.js
  test/spec/modules/openwebBidAdapter_spec.js
Labels: maintenance

#11558 Beachfront Bid Adapter : add plcmt support
  modules/beachfrontBidAdapter.js
  test/spec/modules/beachfrontBidAdapter_spec.js
Labels: maintenance

#11161 Preciso Bid Adapter : update on valid request checks
  integrationExamples/gpt/precisoExample.html
  modules/precisoBidAdapter.js
  test/spec/modules/precisoBidAdapter_spec.js
Labels: maintenance

#11578 Revert "Preciso Bid Adapter : update on valid request checks"
  integrationExamples/gpt/precisoExample.html
  modules/precisoBidAdapter.js
  test/spec/modules/precisoBidAdapter_spec.js
Labels: maintenance

#11575 AIDEM Bid Adapter : fixed getConfig cleanup of consent management
  modules/aidemBidAdapter.js
  test/spec/modules/aidemBidAdapter_spec.js
Labels: maintenance

#11582 Concert Bid Adapter : add dealId Property to Bid Responses
  modules/concertBidAdapter.js
  test/spec/modules/concertBidAdapter_spec.js
Labels: maintenance

#11586 Prebid 9.0: floors enforcement
  modules/ebdrBidAdapter.js
  modules/ebdrBidAdapter.md
  modules/iqmBidAdapter.js
  modules/lkqdBidAdapter.js
  modules/madvertiseBidAdapter.js
  modules/mytargetBidAdapter.md
  modules/quantcastBidAdapter.js
  modules/truereachBidAdapter.js
  modules/vdoaiBidAdapter.js
  test/spec/modules/ebdrBidAdapter_spec.js
  test/spec/modules/mytargetBidAdapter_spec.js
  test/spec/modules/truereachBidAdapter_spec.js
Labels: maintenance, 9.0 API Change

#11585 Prebid 9: Clean up remaining transformBidParams dead code
  modules/adtelligentBidAdapter.js
  modules/connectadBidAdapter.js
  modules/trafficgateBidAdapter.js
Labels: maintenance, 9.0 API Change

#11589 Prebid 9.0: del parrable
  modules/.submodules.json
  modules/illuminBidAdapter.js
  modules/microadBidAdapter.js
  modules/newspassidBidAdapter.js
  modules/ozoneBidAdapter.js
  modules/parrableIdSystem.js
  modules/shinezRtbBidAdapter.js
  modules/userId/eids.md
  modules/userId/userId.md
  modules/vidazooBidAdapter.js
  modules/yahooAdsBidAdapter.js
  test/spec/modules/eids_spec.js
  test/spec/modules/illuminBidAdapter_spec.js
  test/spec/modules/microadBidAdapter_spec.js
  test/spec/modules/parrableIdSystem_spec.js
  test/spec/modules/shinezRtbBidAdapter_spec.js
  test/spec/modules/vidazooBidAdapter_spec.js
Labels: maintenance

#11536 Prebid 9: TCF: use publisher consent for vendorless modules
  modules/tcfControl.js
  src/consentHandler.js
  test/spec/modules/tcfControl_spec.js
Labels: bugfix

#11591 Prebid 9: Drop bbw
  modules/bluebillywigBidAdapter.js
  modules/bluebillywigBidAdapter.md
  test/spec/modules/bluebillywigBidAdapter_spec.js
Labels: maintenance, 9.0 API Change

#11593 Prebid 9: rename utiqSystem to utiqIdSystem
  modules/.submodules.json
  modules/utiqIdSystem.js
  modules/utiqIdSystem.md
  test/spec/modules/utiqIdSystem_spec.js
Labels: maintenance

#11067 ImproveDigital Bid Adapter: Breaking Parameter Changes for PB9
  modules/improvedigitalBidAdapter.js
  modules/improvedigitalBidAdapter.md
  test/spec/modules/improvedigitalBidAdapter_spec.js
Labels: 9.0 API Change

#11488 Lucead Bid Adapter: Update
  modules/luceadBidAdapter.js
  modules/luceadBidAdapter.md
  src/adloader.js
  test/spec/modules/luceadBidAdapter_spec.js
Labels: maintenance

#11588 Prebid 9.0: no harvest eids
  modules/hadronRtdProvider.js
  test/spec/modules/hadronRtdProvider_spec.js
Labels: 9.0 API Change

#11598 Sirdata RTD Module : New lint rule for Prebid 9 fix
  modules/sirdataRtdProvider.js
Labels: bugfix

#11600 Insticator Bid Adapter : update adapter for deprecated placement field
  modules/insticatorBidAdapter.js
  test/spec/modules/insticatorBidAdapter_spec.js
Labels: maintenance

#11602 Smartadserver Bid Adapter : refactor gpid logic as part of Prebid 9.0
  modules/smartadserverBidAdapter.js
Labels: maintenance

#11581 Appnexus Bid Adapter: parse the currency from the bid if specified
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: maintenance

#11548 Prebid 9: Prevent from Events system import in bidders
  .eslintrc.js
  modules/holidBidAdapter.js
Labels: feature, needs 2nd review

#11605 Openweb bid adapter: Make placementId parameter mandatory
  modules/openwebBidAdapter.js
  test/spec/modules/openwebBidAdapter_spec.js
Labels: maintenance

#11606 Update PR_REVIEW.md
  PR_REVIEW.md
Labels: maintenance

#11467 PBS adapter: do not set bidder schain in source.ext.schain
  modules/prebidServerBidAdapter/ortbConverter.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: bugfix

#11466 Nexx360 Bid Adapter: Additional localStorage information
  modules/nexx360BidAdapter.js
  test/spec/modules/nexx360BidAdapter_spec.js
Labels: maintenance

#11509 Adagio Rtd Provider: initial release
  modules/adagioRtdProvider.js
  modules/adagioRtdProvider.md
  test/spec/modules/adagioRtdProvider_spec.js
Labels: feature

#11580 AdagioBidAdapter: update preparation for Rtd module and Prebid.js 9
  modules/adagioBidAdapter.js
  test/spec/modules/adagioBidAdapter_spec.js
Labels: maintenance

#11497 Contxtful RTD Provider : add ORTB2 support
  integrationExamples/gpt/contxtfulRtdProvider_example.html
  modules/contxtfulRtdProvider.js
  modules/contxtfulRtdProvider.md
  test/spec/modules/contxtfulRtdProvider_spec.js
Labels: maintenance

#11283 Topics Fpd Module: Add vidazoo bidder iframe
  modules/topicsFpdModule.js
  modules/topicsFpdModule.md
Labels: maintenance

#11611 9.0 del idward
  integrationExamples/gpt/idward_segments_example.html
  modules/idWardRtdProvider.js
  modules/idWardRtdProvider.md
  test/spec/modules/idWardRtdProvider_spec.js
Labels: 9.0 API Change

#11516 Taboola Bid Adapter: fix ortb2 user override issue
  modules/taboolaBidAdapter.js
  test/spec/modules/taboolaBidAdapter_spec.js
Labels: bugfix

#11609 Prebid 9: update PBS tmax default
  modules/prebidServerBidAdapter/config.js
  modules/prebidServerBidAdapter/index.js
  modules/prebidServerBidAdapter/ortbConverter.js
  src/adapterManager.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: 9.0 API Change

#11613 Currency module: fix bug where changing currency configs causes currency logic to run multiple times
  modules/currency.js
Labels: bugfix

#11618 Outbrain adapter: start reading plcmt video param
  modules/outbrainBidAdapter.js
  test/spec/modules/outbrainBidAdapter_spec.js
Labels: maintenance

#11616 Adform Bid Adapter: ortb2Imp first party data
  modules/adfBidAdapter.js
  test/spec/modules/adfBidAdapter_spec.js
Labels: maintenance

#11621 Prebid 9.0: del mmp
  modules/minutemediaplusBidAdapter.js
  modules/minutemediaplusBidAdapter.md
  test/spec/modules/minutemediaplusBidAdapter_spec.js
Labels: maintenance

#11622 Update autoplay.js: add developer warning
  libraries/autoplayDetection/autoplay.js
Labels: maintenance

#11623 PubmaticBidAdapter: Using plcmt instead of placement
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: maintenance

#11619 Luponmedia Bid Adapter (9.0 fixes) : remove discontinued fpd.context, remove unused onBid…
  modules/luponmediaBidAdapter.js
  test/spec/modules/luponmediaBidAdapter_spec.js
Labels: bugfix

#11590 9.0: undocumented analytics adapters
  modules/eplanningAnalyticsAdapter.js
  modules/marsmediaAnalyticsAdapter.js
  modules/sigmoidAnalyticsAdapter.js
  modules/sonobiAnalyticsAdapter.js
  modules/staqAnalyticsAdapter.js
  test/spec/modules/eplanningAnalyticsAdapter_spec.js
  test/spec/modules/sigmoidAnalyticsAdapter_spec.js
  test/spec/modules/sonobiAnalyticsAdapter_spec.js
  test/spec/modules/staqAnalyticsAdapter_spec.js
Labels: 9.0 API Change

#11529 QT Bid Adapter : initial release
  modules/qtBidAdapter.js
  modules/qtBidAdapter.md
  test/spec/modules/qtBidAdapter_spec.js
Labels: feature

#11624 9.0 : Change Prebidmanager Analytics to AsteriobidPbm
  modules/AsteriobidPbmAnalyticsAdapter.js
  modules/AsteriobidPbmAnalyticsAdapter.md
  modules/prebidmanagerAnalyticsAdapter.md
  test/spec/modules/AsteriobidPbmAnalyticsAdapter_spec.js
Labels: feature

#11583 appnexusBidAdapter 9.0 - remove transform bid params and create anPspParamsConverter module
  libraries/appnexusUtils/anUtils.js
  modules/anPspParamsConverter.js
  modules/anPspParamsConverter.md
  modules/appnexusBidAdapter.js
  test/spec/modules/anPspParamsConverter_spec.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: feature, 9.0 API Change

#11625 Prebid 9: ban outertext
  plugins/eslint/index.js
Labels: maintenance
