Repository prebid/Prebid.js, pull requests merged in 2024-10, with the labels that each got.

#12273 Prebid Core: refactor to targeting file for readability and efficiency
  src/targeting.js
  src/utils.js
  test/fixtures/fixtures.js
  test/spec/unit/core/targeting_spec.js
  test/spec/unit/pbjs_api_spec.js
  test/spec/utils_spec.js
Labels: needs 2nd review, maintenance

#12281 Adagio Analytics Adapter: add beacon data bdrs_timeout, adsrv, adsrv_empty
  libraries/gptUtils/gptUtils.js
  modules/adagioAnalyticsAdapter.js
  test/spec/modules/adagioAnalyticsAdapter_spec.js
Labels: maintenance

#12251 Ads Interactive Bid Adapter : initial release
  modules/ads_interactiveBidAdapter.js
  modules/ads_interactiveBidAdapter.md
  test/spec/modules/ads_interactiveBidAdapter_spec.js
Labels: feature

#12150 AdPlayerPro Video Module : initial module release
  integrationExamples/videoModule/adPlayerPro/bidRequestScheduling.html
  integrationExamples/videoModule/adPlayerPro/eventListeners.html
  libraries/video/constants/vendorCodes.js
  modules/.submodules.json
  modules/adplayerproVideoProvider.js
  modules/adplayerproVideoProvider.md
  test/spec/modules/videoModule/submodules/adplayerproVideoProvider_spec.js
Labels: feature, video

#12285 Digital Matter Bid Adapter: define GVLID
  modules/digitalMatterBidAdapter.js
Labels: maintenance

#12268 Smoot Bid Adapter: initial release
  modules/smootBidAdapter.js
  modules/smootBidAdapter.md
  test/spec/modules/smootBidAdapter_spec.js
Labels: feature

#12294 AdsInteractive Bid Adapter : unit test fix
  test/spec/modules/ads_interactiveBidAdapter_spec.js
Labels: maintenance

#12298 VidazooUtils : update auction timeout logic
  libraries/vidazooUtils/bidderUtils.js
Labels: maintenance

#12252 Fix: Incorrect generation of analytics impression url when bid response is a VAST URL (videoTrackers.js)
  libraries/vastTrackers/vastTrackers.js
  test/spec/libraries/vastTrackers_spec.js
Labels: video, bugfix

#12147 New Module: Bid response filter
  libraries/ortbConverter/processors/default.js
  modules/bidResponseFilter/index.js
  src/auctionIndex.js
  src/prebid.js
  test/spec/modules/bidResponseFilter_spec.js
  test/spec/modules/dsp_genieeBidAdapter_spec.js
  test/spec/ortbConverter/banner_spec.js
  test/spec/ortbConverter/native_spec.js
  test/spec/ortbConverter/video_spec.js
  test/spec/unit/core/auctionIndex_spec.js
  test/spec/unit/pbjs_api_spec.js
Labels: feature

#12301 AdMatic Bid Adapter : add admaticde and netaddiction alias
  modules/admaticBidAdapter.js
Labels: feature

#12307 Adkernel: rxnetwork alias
  modules/adkernelBidAdapter.js
Labels: feature, needs docs

#12302 51Degrees RTD submodule: small improvements and fixes
  modules/.submodules.json
  modules/51DegreesRtdProvider.js
  modules/51DegreesRtdProvider.md
  test/spec/modules/51DegreesRtdProvider_spec.js
Labels: maintenance

#12282 BeOp Bid Adapter : PSEGS are now part of BPSEGS
  modules/beopBidAdapter.js
  test/spec/modules/beopBidAdapter_spec.js
Labels: maintenance

#12286 Eskimi Bid Adapter : support string placementId and adjust user-sync logic
  modules/eskimiBidAdapter.js
Labels: bugfix

#12309 Rubicon Bid Adapter : fix jsdoc issue
  modules/rubiconBidAdapter.js
Labels: maintenance

#12310 Prebid-Server adapter: remove OpenX PBS config
  modules/prebidServerBidAdapter/config.js
Labels: maintenance

#12054 Teads Bid Adapter: Add ORTB2 device data to request payload
  modules/teadsBidAdapter.js
  test/spec/modules/teadsBidAdapter_spec.js
Labels: maintenance

#12311 SymitriDap RTD Module : segment taxonomy values changed to Symitri registered values
  modules/symitriDapRtdProvider.js
  modules/symitriDapRtdProvider.md
  test/spec/modules/akamaiDapRtdProvider_spec.js
  test/spec/modules/symitriDapRtdProvider_spec.js
Labels: needs update, bugfix

#12289 Mobian RTD module: add ap values to mobian RTD provider
  modules/mobianRtdProvider.js
  test/spec/modules/mobianRtdProvider_spec.js
Labels: maintenance

#12296 Missena Bid Adapter : send schain & uspConsent
  modules/missenaBidAdapter.js
  test/spec/modules/missenaBidAdapter_spec.js
Labels: maintenance

#12207 Core: New activity control - load external script
  modules/51DegreesRtdProvider.js
  modules/a1MediaRtdProvider.js
  modules/aaxBlockmeterRtdProvider.js
  modules/adagioRtdProvider.js
  modules/adlooxAnalyticsAdapter.js
  modules/airgridRtdProvider.js
  modules/arcspanRtdProvider.js
  modules/azerionedgeRtdProvider.js
  modules/brandmetricsRtdProvider.js
  modules/browsiRtdProvider.js
  modules/cleanioRtdProvider.js
  modules/confiantRtdProvider.js
  modules/contxtfulRtdProvider.js
  modules/dynamicAdBoostRtdProvider.js
  modules/ftrackIdSystem.js
  modules/geoedgeRtdProvider.js
  modules/hadronRtdProvider.js
  modules/id5IdSystem.js
  modules/improvedigitalBidAdapter.js
  modules/justIdSystem.js
  modules/mediafilterRtdProvider.js
  modules/medianetRtdProvider.js
  modules/qortexRtdProvider.js
  modules/showheroes-bsBidAdapter.js
  modules/symitriDapRtdProvider.js
  modules/tncIdSystem.js
  modules/wurflRtdProvider.js
  src/Renderer.js
  src/activities/activities.js
  src/adloader.js
  src/debugging.js
  test/mocks/adloaderStub.js
  test/spec/adloader_spec.js
  test/spec/modules/adlooxAnalyticsAdapter_spec.js
  test/spec/modules/cleanioRtdProvider_spec.js
  test/spec/modules/justIdSystem_spec.js
  test/spec/modules/wurflRtdProvider_spec.js
Labels: feature

#12300 Impactify Bid Adapter: Adding logger for onBidderError
  modules/impactifyBidAdapter.js
  modules/impactifyBidAdapter.md
Labels: maintenance

#12318 Humansecurity Rtd Provider : update activity control for loadExternalScript
  modules/humansecurityRtdProvider.js
  test/spec/modules/humansecurityRtdProvider_spec.js
Labels: bugfix

#12008 GumGum Bid Adapter : add ORTB2 device data to request payload
  modules/gumgumBidAdapter.js
  test/spec/modules/gumgumBidAdapter_spec.js
Labels: maintenance

#12319 Ads Interactive: fix main domain
  modules/ads_interactiveBidAdapter.js
  test/spec/modules/ads_interactiveBidAdapter_spec.js
Labels: maintenance

#12317 Exco Bid Adapter : initial release
  modules/excoBidAdapter.js
  modules/excoBidAdapter.md
  test/spec/modules/excoBidAdapter_spec.js
Labels: feature

#12322 New Bidder:tapnative
  libraries/audUtils/bidderUtils.js
  modules/tapnativeBidAdapter.js
  modules/tapnativeBidAdapter.md
  test/spec/modules/tapnativeBidAdapter_spec.js
Labels: feature

#12320 IQzone Bid Adapter : update user sync domain
  modules/iqzoneBidAdapter.js
  test/spec/modules/iqzoneBidAdapter_spec.js
Labels: maintenance

#12321 Sparteo Bid Adapter : adapt error messages following param deprecation
  modules/sparteoBidAdapter.js
Labels: maintenance

#12331 Greenbids RTD Module : add flag to disable filtering
  modules/greenbidsRtdProvider.js
Labels: maintenance

#12334 LiveIntent User ID Module: Add DEFAULT_DELAY
  libraries/liveIntentId/idSystem.js
  libraries/liveIntentId/shared.js
Labels: bugfix

#12305 Sparteo Bid Adapter: add adUnitCode
  modules/sparteoBidAdapter.js
  test/spec/modules/sparteoBidAdapter_spec.js
Labels: maintenance

#12330 Richaudience Bid Adapter : add gvlid to alias
  modules/richaudienceBidAdapter.js
  test/spec/modules/richaudienceBidAdapter_spec.js
Labels: bugfix

#12315 tnc Id System : fixes for docs and performance improvements
  modules/tncIdSystem.js
  modules/userId/userId.md
  test/spec/modules/tncIdSystem_spec.js
Labels: maintenance

#12324 Ads Interactive Bid Adpter : add gvlid
  modules/ads_interactiveBidAdapter.js
Labels: maintenance

#12338 Viqeo Bid Adapter : updated endpoint, docs and refactored sections
  modules/viqeoBidAdapter.js
  modules/viqeoBidAdapter.md
  test/spec/modules/viqeoBidAdapter_spec.js
Labels: maintenance

#12275 Aniview Bid Adapter: oRTB support; Plain banner support; Refactoring
  modules/aniviewBidAdapter.js
  modules/aniviewBidAdapter.md
  test/spec/modules/aniviewBidAdapter_spec.js
Labels: maintenance

#12329 51Degrees RTD submodule: add `crossorigin` attribute to `script` tag
  modules/51DegreesRtdProvider.js
Labels: maintenance

#12350 ads_interactiveBidAdapter: fix broken test
  test/spec/modules/ads_interactiveBidAdapter_spec.js
Labels: maintenance

#12323 Criteo bid adapter: write cookie only on TLD+1
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: maintenance

#12333 docereeAdManager Bid Adapter : updated bid adapter
  modules/docereeAdManagerBidAdapter.js
  test/spec/modules/docereeAdManagerBidAdapter_spec.js
Labels: maintenance

#12349 Core: fix missing BID_WON for some native ad units
  src/adRendering.js
  src/secureCreatives.js
  test/spec/unit/secureCreatives_spec.js
Labels: bugfix

#12356 gptPreAuction: fix missing gpid when using mcmEnabled
  modules/gptPreAuction.js
  test/spec/modules/gptPreAuction_spec.js
Labels: bugfix

#11786 Grid bid adapter add ortb2 device
  modules/gridBidAdapter.js
  test/spec/modules/gridBidAdapter_spec.js
Labels: maintenance

#12314 IntentIq ID & Analytics Modules : manual reporting, bug fixes, refactoring
  libraries/intentIqConstants/intentIqConstants.js
  modules/intentIqAnalyticsAdapter.js
  modules/intentIqAnalyticsAdapter.md
  modules/intentIqIdSystem.js
  modules/intentIqIdSystem.md
  src/events.js
  test/spec/modules/intentIqAnalyticsAdapter_spec.js
  test/spec/modules/intentIqIdSystem_spec.js
Labels: maintenance

#12205 PAAPI: parallel contextual and IG auctions
  integrationExamples/top-level-paapi/gam-contextual.html
  integrationExamples/top-level-paapi/no_adserver.html
  modules/optableBidAdapter.js
  modules/paapi.js
  src/adapters/bidderFactory.js
  src/auction.js
  test/spec/auctionmanager_spec.js
  test/spec/modules/optableBidAdapter_spec.js
  test/spec/modules/paapi_spec.js
  test/spec/modules/priceFloors_spec.js
Labels: feature

#12361 gptPreAuction: fix missing gpid when using mcmEnabled
  modules/gptPreAuction.js
  test/spec/modules/gptPreAuction_spec.js
Labels: bugfix

#12363 Paapi: log error instead of warning when auction configs are received too late
  modules/paapi.js
Labels: maintenance

#12265 Adnuntius Bid Adapter: support multi-format ads.
  integrationExamples/gpt/adnuntius_multiformat_example.html
  modules/adnuntiusBidAdapter.js
  test/spec/modules/adnuntiusBidAdapter_spec.js
Labels: feature

#12362 bidResponseFilter Module : do not run if not configured
  modules/bidResponseFilter/index.js
  test/spec/modules/bidResponseFilter_spec.js
Labels: bugfix

#12367 Nexx360 Bid Adapter: fix localStorage access errors
  modules/nexx360BidAdapter.js
Labels: bugfix

#12256 Contxtful Bid Adapter : initial release
  modules/contxtfulBidAdapter.js
  modules/contxtfulBidAdapter.md
  test/spec/modules/contxtfulBidAdapter_spec.js
Labels: feature

#12278 Preciso Bid adapter : Native implemented
  integrationExamples/gpt/precisonativeExample.html
  libraries/precisoUtils/bidNativeUtils.js
  libraries/precisoUtils/bidUtils.js
  libraries/precisoUtils/bidUtilsCommon.js
  modules/admaticBidAdapter.js
  modules/precisoBidAdapter.js
  modules/precisoBidAdapter.md
  modules/rtbhouseBidAdapter.js
  test/spec/libraries/precisoUtils/bidNativeUtils_spec.js
  test/spec/libraries/precisoUtils/bidUtils_spec.js
  test/spec/modules/precisoBidAdapter_spec.js
  test/spec/modules/rtbhouseBidAdapter_spec.js
Labels: feature

#12283 Showheroes Bid Adapter : full rework of the adapter
  modules/showheroes-bsBidAdapter.js
  modules/showheroes-bsBidAdapter.md
  test/spec/modules/showheroes-bsBidAdapter_spec.js
Labels: maintenance

#12173 QortexRtdProvider: Supports new Qortex bid enrichment process
  modules/qortexRtdProvider.js
  modules/qortexRtdProvider.md
  test/spec/modules/qortexRtdProvider_spec.js
Labels: maintenance

#12345 AppNexus Bid Adapter: Add support for 'video' in custom Native fields
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: maintenance

#12371 Rubicon Bid Adapter : add more sizes
  modules/rubiconBidAdapter.js
Labels: maintenance

#12374 LiveIntent UserId Module : add support for sharethrough, sonobi, vidazoo IDs
  libraries/liveIntentId/shared.js
  test/spec/modules/liveIntentExternalIdSystem_spec.js
  test/spec/modules/liveIntentIdMinimalSystem_spec.js
  test/spec/modules/liveIntentIdSystem_spec.js
Labels: maintenance

#12326 Equativ Bid Adapter: initial release, Smartadserver Bid Adapter: take lowest floor to send to endpoint
  libraries/equativUtils/equativUtils.js
  modules/equativBidAdapter.js
  modules/equativBidAdapter.md
  modules/smartadserverBidAdapter.js
  test/spec/modules/equativBidAdapter_spec.js
  test/spec/modules/smartadserverBidAdapter_spec.js
Labels: feature

#12380 Ats Analytics Module : change caching of sampling rate cookie
  modules/atsAnalyticsAdapter.js
Labels: maintenance

#12372 Qortex Rtd Provider : implements rate limiting options for qortex enrichment and analytics
  modules/qortexRtdProvider.js
  test/spec/modules/qortexRtdProvider_spec.js
Labels: maintenance

#12387 Kargo Bid Adapter: replaces triggerPixel with fetch
  modules/kargoBidAdapter.js
  test/spec/modules/kargoBidAdapter_spec.js
Labels: maintenance

#12391 Core: allow renderAd on main document for bids with a renderer
  src/adRendering.js
  test/spec/unit/adRendering_spec.js
Labels: bugfix

#12328 rubicon Bid Adapter : add support for twin ad units
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: maintenance

#12383 Adagio Analytics Adapter : track relevant ad-units only
  modules/adagioAnalyticsAdapter.js
  test/spec/modules/adagioAnalyticsAdapter_spec.js
Labels: bugfix

#12352 Missena Bid Adapter : send coppa and autoplay
  modules/missenaBidAdapter.js
  test/spec/modules/missenaBidAdapter_spec.js
Labels: maintenance

#12358 Snigel Bid Adapter: add placement counter and adapter version field
  modules/snigelBidAdapter.js
  test/spec/modules/snigelBidAdapter_spec.js
Labels: maintenance

#12386 YandexAnalyticsAdapter: Added init event with prebid version
  modules/yandexAnalyticsAdapter.js
  test/spec/modules/yandexAnalyticsAdapter_spec.js
Labels: maintenance
