Repository prebid/Prebid.js, pull requests merged in 2024-02, with the labels that each got.

#11028 Yieldmo Bid Adapter: Adding gpc in the bid request
  modules/yieldmoBidAdapter.js
  test/spec/modules/yieldmoBidAdapter_spec.js
Labels: maintenance

#11026 Livewrapped Bidder: add support for ortb2imp
  modules/livewrappedBidAdapter.js
  test/spec/modules/livewrappedBidAdapter_spec.js
Labels: maintenance

#11025 BeOp Bid Adapter: add eids support
  modules/beopBidAdapter.js
  test/spec/modules/beopBidAdapter_spec.js
Labels: maintenance

#11033 Adagio Bid Adapter: don't try to compute slot position in in circumstances
  modules/adagioBidAdapter.js
  test/spec/modules/adagioBidAdapter_spec.js
Labels: bugfix

#11037 priceFloors: do not log error on missing floor definitions
  modules/id5IdSystem.js
  modules/priceFloors.js
Labels: bugfix

#11012 OpenX Bid Adapter: add ortb2Imp to PAAPI auctionSignals
  modules/openxBidAdapter.js
  test/spec/modules/openxBidAdapter_spec.js
Labels: maintenance

#11049 ZetaGlobalSsp Bid Adapter : cleanup object
  modules/zeta_global_sspBidAdapter.js
Labels: maintenance

#11016 zmaticoo Bid Adapter : add support for video
  modules/zmaticooBidAdapter.js
  modules/zmaticooBidAdapter.md
  test/spec/modules/zmaticooBidAdapter_spec.js
Labels: feature

#11050 ZetaGlobalSsp BidAdapter : provide device.sua object
  modules/zeta_global_sspBidAdapter.js
  test/spec/modules/zeta_global_sspBidAdapter_spec.js
Labels: maintenance

#11051 Rise BidAdapter : add support for gpp
  modules/riseBidAdapter.js
  test/spec/modules/riseBidAdapter_spec.js
Labels: maintenance

#11052 MinuteMedia BidAdapter : add support for gpp
  modules/minutemediaBidAdapter.js
  test/spec/modules/minutemediaBidAdapter_spec.js
Labels: maintenance

#11043 Criteo Bid Adatper: add logic to handle dsa in bid request/response
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: maintenance

#11036 Onetag Bid Adapter: add DSA support
  modules/onetagBidAdapter.js
  test/spec/modules/onetagBidAdapter_spec.js
Labels: maintenance

#11024 PGAMSSP Bidder Adapter: add id5id
  modules/pgamsspBidAdapter.js
Labels: maintenance

#11058 Missena Bid Adapter: add session identifier
  modules/missenaBidAdapter.js
  test/spec/modules/missenaBidAdapter_spec.js
Labels: maintenance

#11042 Grid bid adapter: add logic to handle dsa in bid request/response
  modules/gridBidAdapter.js
  test/spec/modules/gridBidAdapter_spec.js
Labels: maintenance

#11048 Sharethrough Bid Adapter: support Fledge + refine video-placement req logic
  modules/sharethroughBidAdapter.js
  test/spec/modules/sharethroughBidAdapter_spec.js
Labels: maintenance

#11040 PBjs Core Floors Module: add skippedReason property to floorData.
  modules/priceFloors.js
  src/constants.json
  test/spec/modules/priceFloors_spec.js
Labels: maintenance

#11064 GumGum Bid Adapter: fix size in the bid response for multi size slot sizes
  modules/gumgumBidAdapter.js
  test/spec/modules/gumgumBidAdapter_spec.js
Labels: maintenance

#10986 Topics Module: Addition of ImproveDigital's Topics API iframe
  modules/topicsFpdModule.js
Labels: maintenance

#11054 Rayn RTD Module: initial release
  integrationExamples/gpt/raynRtdProvider_example.html
  modules/raynRtdProvider.js
  modules/raynRtdProvider.md
  test/spec/modules/raynRtdProvider_spec.js
Labels: feature

#11070 mediasquare Bid Adapter: add DSA support
  modules/mediasquareBidAdapter.js
  test/spec/modules/mediasquareBidAdapter_spec.js
Labels: maintenance

#10191 PBjs Core : add ability to inject tracking in video
  libraries/vastTrackers/vastTrackers.js
  src/videoCache.js
  test/spec/libraries/vastTrackers_spec.js
  test/spec/videoCache_spec.js
Labels: feature, video

#11066 Adform Bid Adapter: add DSA support
  modules/adfBidAdapter.js
  test/spec/modules/adfBidAdapter_spec.js
Labels: maintenance

#11019 Adquery Bid Adapter : IdSystem fix getId and decode method, added userSync with iframe type
  modules/adqueryBidAdapter.js
  modules/adqueryIdSystem.js
  test/spec/modules/adqueryBidAdapter_spec.js
  test/spec/modules/adqueryIdSystem_spec.js
Labels: maintenance

#11018 NextMillenium Bid Adapter : added support for the keywords parameter openrtb
  modules/nextMillenniumBidAdapter.js
  test/spec/modules/nextMillenniumBidAdapter_spec.js
Labels: maintenance

#11079 Contentexchange Bid Adapter: add gvlid
  modules/contentexchangeBidAdapter.js
Labels: maintenance

#11069 IX Bid Adapter: support DSA fields
  modules/ixBidAdapter.js
  test/spec/modules/ixBidAdapter_spec.js
Labels: maintenance

#10981 Yieldlab Bid Adapter: Add Digital Services Act (DSA) handling
  modules/yieldlabBidAdapter.js
  test/spec/modules/yieldlabBidAdapter_spec.js
Labels: maintenance

#11078 Yandex Analytics Adapter: post-release docs update
  modules/yandexAnalyticsAdapter.js
  modules/yandexAnalyticsAdapter.md
  modules/yandexBidAdapter.md
Labels: maintenance

#11082 Build system: add --no-lint-warnings option
  gulpfile.js
Labels: maintenance

#10982 dsaControl module: Reject bids without meta.dsa when required
  libraries/ortbConverter/processors/default.js
  modules/dsaControl.js
  src/auctionManager.js
  src/constants.json
  src/utils/ttlCollection.js
  test/spec/modules/dsaControl_spec.js
  test/spec/ortbConverter/common_spec.js
  test/spec/unit/utils/ttlCollection_spec.js
Labels: feature

#11087 NoBid Analytics Adapter: added support for flag to control bidWon and auctionEnd independently.
  modules/nobidAnalyticsAdapter.js
  test/spec/modules/nobidAnalyticsAdapter_spec.js
Labels: maintenance

#11076 Microad Bid Adapter: send gpid and other to our request.
  modules/microadBidAdapter.js
  test/spec/modules/microadBidAdapter_spec.js
Labels: maintenance

#11083 StroeerCore Bid Adapter: add DSA support
  modules/stroeerCoreBidAdapter.js
  test/spec/modules/stroeerCoreBidAdapter_spec.js
Labels: maintenance

#11080 Teads Bid Adapter: add dsa info support in bid request & response
  modules/teadsBidAdapter.js
  test/spec/modules/teadsBidAdapter_spec.js
Labels: maintenance

#11022 Richaudience Bid Adapter : add compatibility to GPP
  modules/richaudienceBidAdapter.js
  test/spec/modules/richaudienceBidAdapter_spec.js
Labels: maintenance

#11039 Topics Module: add OpenX topics iframe
  modules/topicsFpdModule.js
  modules/topicsFpdModule.md
Labels: maintenance

#11084 Criteo Bid Adapter: add sellerCurrency to fledge auction config
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: maintenance

#11100 mediasquare Bid Adapter: minor change with floors
  modules/mediasquareBidAdapter.js
  test/spec/modules/mediasquareBidAdapter_spec.js
Labels: maintenance

#10930 PAAPI/fledgeForGpt: make auction configs available independently from GPT
  integrationExamples/gpt/fledge_example.html
  modules/.submodules.json
  modules/fledgeForGpt.js
  modules/paapi.js
  test/helpers/indexStub.js
  test/spec/modules/fledgeForGpt_spec.js
  test/spec/modules/paapi_spec.js
Labels: feature

#10974 Rubicon Bid Adapter: pass DSA fields
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: maintenance

#11098 Build system: fix build
  gulpfile.js
Labels: maintenance

#11068 Lucead Bid Adapter: Add new adapter
  modules/luceadBidAdapter.js
  modules/luceadBidAdapter.md
  src/adloader.js
  test/spec/modules/luceadBidAdapter_spec.js
Labels: feature

#11029 Adnuntius Bid Adapter: Allow user ID to be passed as parameter
  modules/adnuntiusBidAdapter.js
  test/spec/modules/adnuntiusBidAdapter_spec.js
Labels: maintenance

#11096 Adagio Bid Adapter: support DSA (Digital Service Act)
  modules/adagioBidAdapter.js
  test/spec/modules/adagioBidAdapter_spec.js
Labels: maintenance

#11047 The Moneytizer Bid Adapter: initial release
  modules/themoneytizerBidAdapter.js
  modules/themoneytizerBidAdapter.md
  test/spec/modules/themoneytizerBidAdapter_spec.js
Labels: feature, LGTM

#11107 ZetaGlobalSsp Analytics Adapter: keep only needed fields in event
  modules/zeta_global_sspAnalyticsAdapter.js
  test/spec/modules/zeta_global_sspAnalyticsAdapter_spec.js
Labels: maintenance

#11104 Greenbids Analytics Adapter: define split between exploratory and non exploratory sides of the sampling
  modules/greenbidsAnalyticsAdapter.js
  test/spec/modules/greenbidsAnalyticsAdapter_spec.js
Labels: maintenance

#11109 Taboola Bid Adapter: fix cookie look up logic and gpp extracting
  modules/taboolaBidAdapter.js
  test/spec/modules/taboolaBidAdapter_spec.js
Labels: bugfix

#11111 AJA Bid Adapter: add Supply Chain Object Module support
  modules/ajaBidAdapter.js
  test/spec/modules/ajaBidAdapter_spec.js
Labels: maintenance

#11120 Readpeak Bid Adapter : remove click url encoding
  modules/readpeakBidAdapter.js
  test/spec/modules/readpeakBidAdapter_spec.js
Labels: maintenance

#11092 Zeta Global Ssp Adapter: remove null values from payload
  modules/zeta_global_sspBidAdapter.js
  test/spec/modules/zeta_global_sspBidAdapter_spec.js
Labels: needs unit tests, maintenance

#11032 Kimberlite Bidder Adapter: initial commit
  modules/kimberliteBidAdapter.js
  modules/kimberliteBidAdapter.md
  test/spec/modules/kimberliteBidAdapter_spec.js
Labels: feature

#11119 LiveIntent UserId module: Add support for openpath
  modules/liveIntentIdSystem.js
  modules/userId/eids.md
  test/spec/modules/eids_spec.js
  test/spec/modules/liveIntentIdMinimalSystem_spec.js
  test/spec/modules/liveIntentIdSystem_spec.js
Labels: maintenance

#11075 Euid id module: cstg opt out enforcement
  integrationExamples/gpt/cstg_example.html
  modules/euidIdSystem.js
  modules/euidIdSystem.md
  modules/uid2IdSystem_shared.js
  test/spec/modules/euidIdSystem_spec.js
Labels: feature

#10819 Core: rendering logic overhaul, PUC-less native rendering
  .eslintrc.js
  allowedModules.js
  creative/README.md
  creative/constants.js
  creative/crossDomain.js
  creative/renderers/display/constants.js
  creative/renderers/display/renderer.js
  creative/renderers/native/constants.js
  creative/renderers/native/renderer.js
  gulpfile.js
  integrationExamples/gpt/x-domain/creative.html
  integrationExamples/noadserver/native_noadserver.html
  integrationExamples/noadserver/native_renderer/custom_renderer.html
  integrationExamples/noadserver/native_renderer/renderer.js
  libraries/creative-renderer-display/renderer.js
  libraries/creative-renderer-native/renderer.js
  libraries/creativeRender/constants.js
  libraries/creativeRender/crossDomain.js
  libraries/creativeRender/direct.js
  libraries/creativeRender/writer.js
  modules/nativeRendering.js
  modules/videoModule/index.js
  package-lock.json
  package.json
  plugins/eslint/validateImports.js
  src/adRendering.js
  src/auction.js
  src/constants.json
  src/creativeRenderers.js
  src/native.js
  src/prebid.js
  src/secureCreatives.js
  src/utils.js
  test/spec/creative/crossDomainCreative_spec.js
  test/spec/creative/displayRenderer_spec.js
  test/spec/creative/nativeRenderer_spec.js
  test/spec/native_spec.js
  test/spec/unit/adRendering_spec.js
  test/spec/unit/pbjs_api_spec.js
  test/spec/unit/secureCreatives_spec.js
  webpack.creative.js
Labels: feature, needs docs

#10714 33Across User ID sub-module: Introduce first-party ID support
  modules/33acrossIdSystem.js
  modules/33acrossIdSystem.md
  test/spec/modules/33acrossIdSystem_spec.js
Labels: feature

#11035 New bidder adapter : RixEngine
  modules/rixengineBidAdapter.js
  modules/rixengineBidAdapter.md
  test/spec/modules/rixengineBidAdapter_spec.js
Labels: feature

#11127 adstir Bid Adapter : add reference about the version requirement
  modules/adstirBidAdapter.md
Labels: maintenance

#11129 Consent Management : cleanup references to allowAuctionWithoutConsent
  integrationExamples/gpt/gdpr_hello_world.html
  modules/consentManagement.js
  modules/consentManagementGpp.js
  modules/consentManagementUsp.js
  test/pages/consent_mgt_gdpr.html
  test/spec/modules/gdprEnforcement_spec.js
Labels: maintenance

#11128 Insticator Bid Adapter: Fix bid validation for non-video requests
  modules/insticatorBidAdapter.js
  test/spec/modules/insticatorBidAdapter_spec.js
Labels: bugfix

#11126 Reset Digital Bid Adapter: updating users syncs
  modules/resetdigitalBidAdapter.js
Labels: maintenance

#11093 Alkimi Bid Adapter: add custom user object
  modules/alkimiBidAdapter.js
Labels: needs unit tests, maintenance

#11105 Unified ID 2.0 Module: Update documentation
  modules/uid2IdSystem.md
Labels: maintenance, documentation

#10985 Rubicon Bid Adapter: Pass on carbon segtaxes
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: maintenance

#10870 Blockthrough Bid Adapter: initial release
  modules/BTBidAdapter.js
  modules/BTBidAdapter.md
  test/spec/modules/BTBidAdapter_spec.js
Labels: feature

#10924 OMS Adapter: add new adapter
  libraries/percentInView/percentInView.js
  modules/omsBidAdapter.js
  modules/omsBidAdapter.md
  test/spec/modules/omsBidAdapter_spec.js
Labels: feature

#11056 zMaticoo Bid Adapter : add onBidWon function
  modules/zmaticooBidAdapter.js
  modules/zmaticooBidAdapter.md
  test/spec/modules/zmaticooBidAdapter_spec.js
Labels: bugfix

#11138 Reset Digital Bid Adapter: usersync url
  modules/resetdigitalBidAdapter.js
Labels: maintenance

#11110 Yandex: use ortb2 info & Core: add webdriver flag
  modules/yandexBidAdapter.js
  src/auction.js
  src/fpd/enrichment.js
  src/types/ortb2.d.ts
  test/spec/fpd/enrichment_spec.js
  test/spec/modules/yandexBidAdapter_spec.js
Labels: maintenance

#11123 Logicad Bid Adapter: Add paapi support
  modules/logicadBidAdapter.js
  test/spec/modules/logicadBidAdapter_spec.js
Labels: feature

#10928 Magnite Analytics: Check if prebid cache was called for video tracking
  modules/magniteAnalyticsAdapter.js
  test/spec/modules/magniteAnalyticsAdapter_spec.js
Labels: feature, on hold

#11139 Taboola Bid Adapter - support topics handling
  modules/taboolaBidAdapter.js
  modules/topicsFpdModule.js
  modules/topicsFpdModule.md
  test/spec/modules/taboolaBidAdapter_spec.js
Labels: maintenance

#11144 Adagio Bid Adapter: fix oRTB delivery video param validation
  modules/adagioBidAdapter.js
Labels: maintenance

#11103 JsDoc Lint Fix : multiple adapters and modules
  libraries/appnexusUtils/anKeywords.js
  libraries/keywords/keywords.js
  libraries/objectGuard/objectGuard.js
  libraries/objectGuard/ortbGuard.js
  libraries/video/shared/parentModule.js
  modules/adotBidAdapter.js
  modules/adriverIdSystem.js
  modules/adtelligentBidAdapter.js
  modules/adyoulikeBidAdapter.js
  modules/airgridRtdProvider.js
  modules/akamaiDapRtdProvider.js
  modules/apacdexBidAdapter.js
  modules/appierBidAdapter.js
  modules/astraoneBidAdapter.js
  modules/beopBidAdapter.js
  modules/betweenBidAdapter.js
  modules/bidglassBidAdapter.js
  modules/bliinkBidAdapter.js
  modules/blueconicRtdProvider.js
  modules/brandmetricsRtdProvider.js
  modules/britepoolIdSystem.js
  modules/browsiRtdProvider.js
  modules/buzzoolaBidAdapter.js
  modules/codefuelBidAdapter.js
  modules/dsp_genieeBidAdapter.js
  modules/dspxBidAdapter.js
  modules/dxkultureBidAdapter.js
  modules/dynamicAdBoostRtdProvider.js
  modules/feedadBidAdapter.js
  modules/flippBidAdapter.js
  modules/fluctBidAdapter.js
  modules/freewheel-sspBidAdapter.js
  modules/geoedgeRtdProvider.js
  modules/getintentBidAdapter.js
  modules/gjirafaBidAdapter.js
  modules/gmosspBidAdapter.js
  modules/gnetBidAdapter.js
  modules/growthCodeIdSystem.js
  modules/pilotxBidAdapter.js
  modules/prismaBidAdapter.js
  modules/pubmaticBidAdapter.js
  modules/pubwiseBidAdapter.js
  modules/rtdModule/index.js
  modules/smilewantedBidAdapter.js
  modules/yieldmoBidAdapter.js
  modules/zetaBidAdapter.js
  modules/zeta_global_sspBidAdapter.js
  modules/zmaticooBidAdapter.js
  test/fake-server/fake-responder.js
  test/spec/auctionmanager_spec.js
  test/spec/modules/cointrafficBidAdapter_spec.js
  test/spec/modules/rubiconBidAdapter_spec.js
  test/spec/modules/sovrnAnalyticsAdapter_spec.js
Labels: maintenance

#11099 Mediaimpact Bid Adapter: initial release
  modules/mediaimpactBidAdapter.js
  modules/mediaimpactBidAdapter.md
  test/spec/modules/mediaimpactBidAdapter_spec.js
Labels: feature

#11143 Lucead Adapter: update
  modules/luceadBidAdapter.js
  modules/luceadBidAdapter.md
  test/spec/modules/luceadBidAdapter_spec.js
Labels: maintenance

#11150 ZetaGlobalSsp Bid Adapter: provide dspId into bid
  modules/zeta_global_sspBidAdapter.js
  test/spec/modules/zeta_global_sspBidAdapter_spec.js
Labels: maintenance

#11151 Hadron ID system: fix module name for TCF checks
  modules/hadronIdSystem.js
Labels: bugfix

#11152 Criteo bid adapter: increase default Fledge timeout
  modules/criteoBidAdapter.js
  test/spec/modules/criteoBidAdapter_spec.js
Labels: maintenance

#11085 Stn Bid Adapter: initial release
  modules/stnBidAdapter.js
  modules/stnBidAdapter.md
  test/spec/modules/stnBidAdapter_spec.js
Labels: feature, LGTM
