Repository prebid/Prebid.js, pull requests merged in 2025-02, with the labels that each got.

#12722 Medianet Analytics Adapter : add video placement logic
  modules/medianetAnalyticsAdapter.js
  test/spec/modules/medianetAnalyticsAdapter_spec.js
Labels: feature

#12719 Update ttdBidAdapter.js: hang pmp off imp
  modules/ttdBidAdapter.js
  test/spec/modules/ttdBidAdapter_spec.js
Labels: bugfix

#12728 Aso Bid Adapter: add cordless alias
  modules/asoBidAdapter.js
Labels: maintenance

#12727 Prebid Server adapter: fix bug with disabling some of multiple instances
  modules/prebidServerBidAdapter/index.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: bugfix

#12704 Connatix Bid Adapter : fix consent query params & refactor post message events for user ids
  modules/connatixBidAdapter.js
  test/spec/modules/connatixBidAdapter_spec.js
Labels: bugfix

#12736 Missena Bid Adapter : send viewport and add getViewportSize to viewport library
  libraries/viewport/viewport.js
  modules/missenaBidAdapter.js
  test/spec/modules/missenaBidAdapter_spec.js
Labels: feature

#12737 Hadron Rtd Provider : fix missing param to hadronId JS snippet load
  modules/hadronRtdProvider.js
Labels: bugfix

#12649 Nodals AI RTD Module : initial release
  modules/nodalsAiRtdProvider.js
  modules/nodalsAiRtdProvider.md
  src/adloader.js
  test/spec/modules/nodalsAiRtdProvider_spec.js
Labels: feature

#12555 R2B2 Analytic Adapter : initial release
  modules/r2b2AnalyticsAdapter.js
  modules/r2b2AnalyticsAdapter.md
  test/spec/modules/r2b2AnalytiscAdapter_spec.js
Labels: feature, LGTM

#12740 Rubicon Bid Adapter: Fix client Hints full ver
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: maintenance

#12716 Prebid Core: Fix wrong targeting being applied when multibid module is included
  src/targeting.js
  test/spec/unit/core/targeting_spec.js
Labels: needs 2nd review, bugfix

#12745 Id5Id: Provisioning EIDs from server-side response
  modules/id5IdSystem.js
  test/spec/modules/id5IdSystem_spec.js
Labels: maintenance

#12643 CondorX Bid Adapter : initial release
  modules/condorxBidAdapter.js
  modules/condorxBidAdapter.md
  test/spec/modules/condorxBidAdapter_spec.js
Labels: feature

#12755 Vidazoo bidder: pass coppa flag on syncs
  libraries/vidazooUtils/bidderUtils.js
  test/spec/modules/excoBidAdapter_spec.js
  test/spec/modules/illuminBidAdapter_spec.js
  test/spec/modules/kueezRtbBidAdapter_spec.js
  test/spec/modules/shinezRtbBidAdapter_spec.js
  test/spec/modules/tagorasBidAdapter_spec.js
  test/spec/modules/twistDigitalBidAdapter_spec.js
  test/spec/modules/vidazooBidAdapter_spec.js
Labels: maintenance

#12721 wurfl Rtd Provider : fix invalid types for pxratio and js in ORTB2 device data
  modules/wurflRtdProvider.js
  test/spec/modules/wurflRtdProvider_spec.js
Labels: bugfix

#12742 Adnuntius Bid Adapter: pass on native ad request sizes to ad server.
  modules/adnuntiusBidAdapter.js
  test/spec/modules/adnuntiusBidAdapter_spec.js
Labels: bugfix

#12735 PubMatic Analytics Adapter: Sending 'ds' in tracker
  modules/pubmaticAnalyticsAdapter.js
  test/spec/modules/pubmaticAnalyticsAdapter_spec.js
Labels: maintenance

#12718 Core: mild mergedeep speedup
  src/utils.js
Labels: maintenance

#12751 Sonobi Bid Adapter: change HTTP method to POST
  modules/sonobiBidAdapter.js
  test/spec/modules/sonobiBidAdapter_spec.js
Labels: maintenance

#12753 Mediago Bid Adapter : add param publisherid
  libraries/cookieSync/cookieSync.js
  modules/discoveryBidAdapter.js
  modules/mediagoBidAdapter.js
  test/spec/modules/mediagoBidAdapter_spec.js
Labels: maintenance

#12770 Appnexus Bid Adapter : fix issue with start delay
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: maintenance

#12769 LiveIntent ID Module : add support for zetassp id
  libraries/liveIntentId/shared.js
  test/spec/modules/liveIntentExternalIdSystem_spec.js
  test/spec/modules/liveIntentIdMinimalSystem_spec.js
  test/spec/modules/liveIntentIdSystem_spec.js
Labels: maintenance

#12765 GumGum Bid Adapter : send transaction Id (tId)
  modules/gumgumBidAdapter.js
  test/spec/modules/gumgumBidAdapter_spec.js
Labels: maintenance

#12759 SeedingAlliance Bid Adapter: fix wrong cur value
  modules/seedingAllianceBidAdapter.js
Labels: bugfix

#12756 LimelightDigital Bid Adapter : add new aliases
  modules/limelightDigitalBidAdapter.js
Labels: feature

#12507 Michao Bid Adapter: Initial release
  modules/michaoBidAdapter.js
  modules/michaoBidAdapter.md
  test/spec/modules/michaoBidAdapter_spec.js
Labels: feature

#12778 Agma Analytics : allow config of ortb2 data for anayltics adapter during runtime
  modules/agmaAnalyticsAdapter.js
  test/spec/modules/agmaAnalyticsAdapter_spec.js
Labels: maintenance

#12750 Alkimi Bid Adapter : added support for Imp extention object
  modules/alkimiBidAdapter.js
  test/spec/modules/alkimiBidAdapter_spec.js
Labels: maintenance

#12754 Attekmi Bid Adapter : add Jambojar alias
  modules/smarthubBidAdapter.js
Labels: feature

#12782 Core: improve some error messages
  src/Renderer.js
  src/adapters/bidderFactory.js
Labels: maintenance

#12761 Holid Bid Adapter : enhance logic for regs.ext and updated docs
  modules/holidBidAdapter.js
  modules/holidBidAdapter.md
  test/spec/modules/holidBidAdapter_spec.js
Labels: maintenance

#12789 Rixengine Bid Adapter : add "algorix" as an alias
  modules/rixengineBidAdapter.js
Labels: feature

#12786 Ttd Bid Adapter : add integration type header
  modules/ttdBidAdapter.js
  test/spec/modules/ttdBidAdapter_spec.js
Labels: maintenance

#12771 Qortex Rtd Provider : implements code version and adjusts for new expected data structure of API responses
  modules/qortexRtdProvider.js
  modules/qortexRtdProvider.md
  test/spec/modules/qortexRtdProvider_spec.js
Labels: maintenance

#12777 Improve Digital Bid Adapter: Added support for MultiBid
  modules/improvedigitalBidAdapter.js
  modules/improvedigitalBidAdapter.md
  test/spec/modules/improvedigitalBidAdapter_spec.js
Labels: maintenance

#12783 UserId & multiple userId modules: pass all consent, not just TCF, to ID modules
  modules/33acrossIdSystem.js
  modules/admixerIdSystem.js
  modules/adtelligentIdSystem.js
  modules/amxIdSystem.js
  modules/connectIdSystem.js
  modules/euidIdSystem.js
  modules/fabrickIdSystem.js
  modules/ftrackIdSystem.js
  modules/id5IdSystem.js
  modules/identityLinkIdSystem.js
  modules/justIdSystem.js
  modules/kinessoIdSystem.js
  modules/lockrAIMIdSystem.js
  modules/lotamePanoramaIdSystem.js
  modules/merkleIdSystem.js
  modules/mygaruIdSystem.js
  modules/publinkIdSystem.js
  modules/sharedIdSystem.js
  modules/tapadIdSystem.js
  modules/teadsIdSystem.js
  modules/tncIdSystem.js
  modules/uid2IdSystem.js
  modules/userId/index.js
  modules/verizonMediaIdSystem.js
  test/spec/modules/33acrossIdSystem_spec.js
  test/spec/modules/admixerIdSystem_spec.js
  test/spec/modules/connectIdSystem_spec.js
  test/spec/modules/ftrackIdSystem_spec.js
  test/spec/modules/id5IdSystem_spec.js
  test/spec/modules/identityLinkIdSystem_spec.js
  test/spec/modules/justIdSystem_spec.js
  test/spec/modules/lotamePanoramaIdSystem_spec.js
  test/spec/modules/merkleIdSystem_spec.js
  test/spec/modules/mygaruIdSystem_spec.js
  test/spec/modules/publinkIdSystem_spec.js
  test/spec/modules/sharedIdSystem_spec.js
  test/spec/modules/teadsIdSystem_spec.js
  test/spec/modules/tncIdSystem_spec.js
  test/spec/modules/uid2IdSystem_spec.js
  test/spec/modules/userId_spec.js
  test/spec/modules/verizonMediaIdSystem_spec.js
Labels: feature

#12780 Targeting.js: Fixed Slot Targeting Bug when RTD is Enabled
  src/targeting.js
  test/spec/unit/core/targeting_spec.js
Labels: bugfix

#12711 Core & PBS Adapter: support `eventtrackers`, and normalize `burl` / `ext.prebid.events.win` into it
  libraries/ortbConverter/processors/default.js
  libraries/pbsExtensions/processors/eventTrackers.js
  libraries/pbsExtensions/processors/pbs.js
  modules/prebidServerBidAdapter/index.js
  src/adRendering.js
  src/adapterManager.js
  src/eventTrackers.js
  src/native.js
  src/prebid.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/ortbConverter/pbsExtensions/trackers_spec.js
  test/spec/unit/adRendering_spec.js
  test/spec/unit/core/adapterManager_spec.js
  test/spec/unit/core/eventTrackers_spec.js
  test/spec/unit/pbjs_api_spec.js
Labels: feature

#12739 PubMatic Analytics Adapter : sending 'ffs' floors param in tracker and optional chaining in logger and tracker
  modules/pubmaticAnalyticsAdapter.js
  test/spec/modules/pubmaticAnalyticsAdapter_spec.js
Labels: maintenance

#12647 Mobkoi Bidder Adapter: Initial Release
  modules/mobkoiBidAdapter.js
  modules/mobkoiBidAdapter.md
  test/spec/modules/mobkoiBidAdapter_spec.js
Labels: feature

#12733 Mobkoi User ID module: Initial Release
  modules/.submodules.json
  modules/mobkoiIdSystem.js
  modules/mobkoiIdSystem.md
  test/spec/modules/mobkoiIdSystem_spec.js
Labels: feature

#12734 GumGum Bid Adapter: bug fix to handle site.content.data.name undefined values
  modules/gumgumBidAdapter.js
Labels: bugfix

#12785 IntentIq ID & Analytics Modules: GAM reporting
  libraries/intentIqConstants/intentIqConstants.js
  libraries/intentIqUtils/detectBrowserUtils.js
  modules/intentIqIdSystem.js
  modules/intentIqIdSystem.md
  test/spec/modules/intentIqIdSystem_spec.js
Labels: maintenance

#12720 Debugging Module: Bid responses for various media types (+ TestBidder)
  integrationExamples/testBidder/testBidderBannerExample.html
  integrationExamples/testBidder/testBidderNativeExample.html
  integrationExamples/testBidder/testBidderVideoExample.html
  modules/debugging/bidInterceptor.js
  modules/debugging/responses.js
  src/prebid.js
Labels: feature

#12749 Lane4 Bid Adapter : initial release
  libraries/audUtils/bidderUtils.js
  modules/lane4BidAdapter.js
  modules/lane4BidAdapter.md
  test/spec/modules/lane4BidAdapter_spec.js
Labels: feature

#12680 Ozone Bid Adapter : support for multi-size adUnits
  modules/ozoneBidAdapter.js
  test/spec/modules/ozoneBidAdapter_spec.js
Labels: maintenance

#12741 GumGum Bid Adapter: Send content url and additional vid params
  modules/gumgumBidAdapter.js
  test/spec/modules/gumgumBidAdapter_spec.js
Labels: needs unit tests, maintenance

#12795 IntentIq ID Module: Bugfix for GAM cmd
  modules/intentIqIdSystem.js
Labels: bugfix

#12763 Core: suspend auctions during prerendering
  src/prebid.js
  src/utils/prerendering.js
  test/spec/unit/pbjs_api_spec.js
  test/spec/utils/prerendering_spec.js
Labels: feature

#12668 SemantIQ RTD Provider: initial release
  modules/.submodules.json
  modules/semantiqRtdProvider.js
  modules/semantiqRtdProvider.md
  test/spec/modules/semantiqRtdProvider_spec.js
Labels: feature

#12800 TTD Bid Adapter : revert integration type header due to CORS error
  modules/ttdBidAdapter.js
  test/spec/modules/ttdBidAdapter_spec.js
Labels: bugfix

#12648 Mobkoi Analystics Adapter: Initial Release
  modules/mobkoiAnalyticsAdapter.js
  modules/mobkoiAnalyticsAdapter.md
  test/spec/modules/mobkoiAnalyticsAdapter_spec.js
Labels: feature

#12621 BMS Bid Adapter : initial release
  modules/bmsBidAdapter.js
  modules/bmsBidAdapter.md
  test/spec/modules/bmsBidAdapter_spec.js
Labels: feature

#12496 Adnuntius Analytics Adapter: initial release
  modules/adnuntiusAnalyticsAdapter.js
  modules/adnuntiusAnalyticsAdapter.md
  test/spec/modules/adnuntiusAnalyticsAdapter_spec.js
Labels: feature

#12802 Teads Bid Adapter: add extra information to request payload
  modules/teadsBidAdapter.js
  test/spec/modules/teadsBidAdapter_spec.js
Labels: maintenance

#12812 Setupad Bid Adapter : fix gdprConsent undefined error
  modules/setupadBidAdapter.js
Labels: bugfix

#12804 Debugging module: make mock creatives respect requested sizes
  integrationExamples/testBidder/testBidderVideoExample.html
  modules/debugging/bidInterceptor.js
  modules/debugging/pbsInterceptor.js
  modules/debugging/responses.js
Labels: maintenance

#12806 Ssp_geniee Bid Adapter : add support for GPID and pbadslot
  modules/ssp_genieeBidAdapter.js
  test/spec/modules/ssp_genieeBidAdapter_spec.js
Labels: maintenance

#12808 Yieldmo Bid Adapter : add tagid, divid and allow video.api greater than 0
  modules/yieldmoBidAdapter.js
Labels: maintenance

#12810 Aniview Bid Adapter : pass replacements and s2s winning ad source in bid meta
  modules/aniviewBidAdapter.js
  test/spec/modules/aniviewBidAdapter_spec.js
Labels: maintenance

#12818 TTD Bid Adapter : add x-integration-type
  modules/ttdBidAdapter.js
  test/spec/modules/ttdBidAdapter_spec.js
Labels: maintenance

#12798 RediAds Bid Adapter : added params and bugfixes to backend
  modules/rediadsBidAdapter.js
  modules/rediadsBidAdapter.md
  test/spec/modules/rediadsBidAdapter_spec.js
Labels: maintenance

#12809 Codepath alerts
  .github/workflows/code-path-changes.yml
  .github/workflows/scripts/codepath-notification
  .github/workflows/scripts/send-notification-on-change.js
Labels: feature

#12781 EXCO Bid Adapter: Support of new `publisherId`, `accountId` and `tagId` parameters.
  modules/excoBidAdapter.js
  modules/excoBidAdapter.md
  test/spec/modules/excoBidAdapter_spec.js
Labels: maintenance
