Repository prebid/Prebid.js, pull requests merged in 2025-03, with the labels that each got.

#12819 BMS bid adapter: use triggerPixel for bid won notifications and enable withCredentials for requests
  modules/bmsBidAdapter.js
Labels: maintenance

#12025 Core: start yielding control of the main thread
  features.json
  gulpfile.js
  libraries/cmp/cmpClient.js
  libraries/consentManagement/cmUtils.js
  libraries/greedy/greedyPromise.js
  modules/consentManagementGpp.js
  modules/consentManagementTcf.js
  modules/fpdModule/index.js
  modules/id5IdSystem.js
  modules/topLevelPaapi.js
  modules/topicsFpdModule.js
  modules/userId/index.js
  src/adRendering.js
  src/auction.js
  src/consentHandler.js
  src/creativeRenderers.js
  src/debugging.js
  src/fpd/enrichment.js
  src/fpd/sua.js
  src/prebid.js
  src/utils.js
  src/utils/promise.js
  src/utils/ttlCollection.js
  test/helpers/consentData.js
  test/helpers/fpd.js
  test/mocks/xhr.js
  test/spec/auctionmanager_spec.js
  test/spec/libraries/cmUtils_spec.js
  test/spec/libraries/greedy/greedyPromise_spec.js
  test/spec/modules/adxcgBidAdapter_spec.js
  test/spec/modules/asoBidAdapter_spec.js
  test/spec/modules/blastoBidAdapter_spec.js
  test/spec/modules/bridgeuppBidAdapter_spec.js
  test/spec/modules/ccxBidAdapter_spec.js
  test/spec/modules/consentManagementGpp_spec.js
  test/spec/modules/consentManagement_spec.js
  test/spec/modules/criteoBidAdapter_spec.js
  test/spec/modules/escalaxBidAdapter_spec.js
  test/spec/modules/euidIdSystem_spec.js
  test/spec/modules/ftrackIdSystem_spec.js
  test/spec/modules/geolocationRtdProvider_spec.js
  test/spec/modules/id5IdSystem_spec.js
  test/spec/modules/improvedigitalBidAdapter_spec.js
  test/spec/modules/inmobiBidAdapter_spec.js
  test/spec/modules/lmpIdSystem_spec.js
  test/spec/modules/openxBidAdapter_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/pubxaiAnalyticsAdapter_spec.js
  test/spec/modules/pulsepointBidAdapter_spec.js
  test/spec/modules/rubiconBidAdapter_spec.js
  test/spec/modules/sharedIdSystem_spec.js
  test/spec/modules/showheroes-bsBidAdapter_spec.js
  test/spec/modules/silvermobBidAdapter_spec.js
  test/spec/modules/tpmnBidAdapter_spec.js
  test/spec/modules/trafficgateBidAdapter_spec.js
  test/spec/modules/uid2IdSystem_spec.js
  test/spec/modules/userId_spec.js
  test/spec/unit/core/events_spec.js
  test/spec/unit/pbjs_api_spec.js
  test/spec/unit/utils/promise_spec.js
Labels: feature

#12738 IntentIq ID & Analytics Modules: GDPR support and update documentation
  libraries/intentIqConstants/intentIqConstants.js
  libraries/intentIqUtils/getCmpData.js
  libraries/intentIqUtils/getGppValue.js
  libraries/intentIqUtils/storageUtils.js
  modules/intentIqAnalyticsAdapter.js
  modules/intentIqIdSystem.js
  modules/intentIqIdSystem.md
  test/spec/modules/intentIqAnalyticsAdapter_spec.js
  test/spec/modules/intentIqIdSystem_spec.js
Labels: maintenance

#12823 ExcoAdapter: Unit tests according to latest ortb converter changes
  test/spec/modules/excoBidAdapter_spec.js
Labels: maintenance

#12821 TargetVideo and Brid Adapter: Fixing schain
  modules/bridBidAdapter.js
  modules/targetVideoBidAdapter.js
  test/spec/modules/bridBidAdapter_spec.js
  test/spec/modules/targetVideoBidAdapter_spec.js
Labels: maintenance

#12837 Adagio Rtd Provider: fix apntag event callback
  modules/adagioRtdProvider.js
Labels: maintenance

#12841 Revert TTD integration type header due to flaky bidding
  modules/ttdBidAdapter.js
  test/spec/modules/ttdBidAdapter_spec.js
Labels: bugfix

#12714 Adgrid Bid Adapter: support userSync feature
  modules/adgridBidAdapter.js
  test/spec/modules/adgridBidAdapter_spec.js
Labels: needs unit tests, maintenance

#12834 Sonobi Bid Adapter - add new video params
  modules/sonobiBidAdapter.js
  test/spec/modules/sonobiBidAdapter_spec.js
Labels: maintenance

#12379 Core: support for expandable / flex slots
  creative/renderers/display/renderer.js
  integrationExamples/gpt/x-domain/creative.html
  libraries/creative-renderer-display/renderer.js
  libraries/ortbConverter/processors/banner.js
  libraries/ortbConverter/processors/default.js
  modules/debugging/responses.js
  src/adapters/bidderFactory.js
  src/prebid.js
  test/spec/creative/displayRenderer_spec.js
  test/spec/ortbConverter/banner_spec.js
  test/spec/unit/core/bidderFactory_spec.js
  test/spec/unit/pbjs_api_spec.js
Labels: feature

#12817 Bridgeupp Bid Adapter: include auction start on all requests
  modules/bridgeuppBidAdapter.js
  modules/bridgeuppBidAdapter.md
  test/spec/modules/bridgeuppBidAdapter_spec.js
Labels: maintenance

#12854 Pubmatic Analytics Adapter : added display manager "dm" and "dmv" keys to logger and tracker
  modules/pubmaticAnalyticsAdapter.js
  test/spec/modules/pubmaticAnalyticsAdapter_spec.js
Labels: maintenance

#12852 UserID: improve handling of IDs coming from multiple alternate sources but having conflicting bidder restrictions
  modules/userId/eids.js
  modules/userId/index.js
  test/spec/modules/userId_spec.js
Labels: maintenance

#12855 OpenX Bid Adapter: mtype cleanup
  modules/openxBidAdapter.js
  test/spec/modules/openxBidAdapter_spec.js
Labels: maintenance

#12145 EClickAds: rename bidder from EClickAds to eClick
  modules/eclickBidAdapter.js
  modules/eclickBidAdapter.md
  test/spec/modules/eclickBidAdapter_spec.js
Labels: 10.0 API Change

#12843 PAAPI: automatically enable adAuctionHeaders when PAAPI is enabled
  modules/paapi.js
  test/spec/modules/paapi_spec.js
Labels: maintenance

#12878 Change imds adapter name to advertising
  modules/advertisingBidAdapter.js
  modules/advertisingBidAdapter.md
  test/spec/modules/advertisingBidAdapter_spec.js
Labels: 10.0 API Change

#12870 Prebid 10: Delete modules/cleanmedianetBidAdapter.js
  modules/cleanmedianetBidAdapter.js
  modules/cleanmedianetBidAdapter.md
  test/spec/modules/cleanmedianetBidAdapter_spec.js
Labels: 10.0 API Change

#12868 Prebid 10: Delete modules/telariaBidAdapter.js
  modules/telariaBidAdapter.js
  modules/telariaBidAdapter.md
Labels: 10.0 API Change

#12864 Prebid 10: EMX Digital, alias of Cadent
  libraries/appnexusUtils/anUtils.js
  modules/cadentApertureMXBidAdapter.js
Labels: 10.0 API Change

#12874 Prebid 10: Delete adsinteractiveBidAdapter_spec.js
  modules/adsinteractiveBidAdapter.js
  modules/adsinteractiveBidAdapter.md
  test/spec/modules/adsinteractiveBidAdapter_spec.js
Labels: 10.0 API Change

#12869 Prebid 10: Delete modules/kueezBidAdapter.js
  modules/kueezBidAdapter.js
  modules/kueezBidAdapter.md
  test/spec/modules/kueezBidAdapter_spec.js
Labels: 10.0 API Change

#12863 Prebid 10: Delete modules/saambaaBidAdapter.js
  modules/saambaaBidAdapter.js
Labels: 10.0 API Change

#12857 paapiForGpt.js: code comment for reference
  modules/paapiForGpt.js
Labels: maintenance

#12873 Prebid 10: Delete modules/bidwatchAnalyticsAdapter.js
  modules/bidwatchAnalyticsAdapter.js
  modules/bidwatchAnalyticsAdapter.md
  test/spec/modules/bidwatchAnalyticsAdapter_spec.js
Labels: 10.0 API Change

#12860 RichAudience Bid Adapter : remove deprecated params for video player
  modules/richaudienceBidAdapter.js
Labels: maintenance

#12838 IncrementX Bid Adapter : a instream video
  modules/incrxBidAdapter.js
  modules/incrxBidAdapter.md
  test/spec/modules/incrxBidAdapter_spec.js
Labels: feature

#12842 Smarthub Bid Adapter : add UserSyncs
  modules/smarthubBidAdapter.js
  test/spec/modules/smarthubBidAdapter_spec.js
Labels: maintenance

#12811 Vidoomy Bid Adapter: include widths and heights on requests
  modules/vidoomyBidAdapter.js
  test/spec/modules/vidoomyBidAdapter_spec.js
Labels: maintenance

#12807 Nexx360 Bid Adapter: prismassp alias added
  modules/nexx360BidAdapter.js
  test/spec/modules/nexx360BidAdapter_spec.js
Labels: maintenance

#12848 getBoundingClientRect and percent Inview library: replace layout calculations in various adapters
  .eslintrc.js
  libraries/boundingClientRect/boundingClientRect.js
  libraries/percentInView/percentInView.js
  modules/33acrossBidAdapter.js
  modules/adagioRtdProvider.js
  modules/concertBidAdapter.js
  modules/eplanningBidAdapter.js
  modules/h12mediaBidAdapter.js
  modules/mantisBidAdapter.js
  modules/marsmediaBidAdapter.js
  modules/medianetBidAdapter.js
  modules/onetagBidAdapter.js
  modules/onomagicBidAdapter.js
  modules/seedtagBidAdapter.js
  modules/stroeerCoreBidAdapter.js
  modules/underdogmediaBidAdapter.js
  modules/widespaceBidAdapter.js
  test/spec/libraries/boundingClientRect_spec.js
  test/spec/modules/h12mediaBidAdapter_spec.js
Labels: feature

#12861 Gamoshi Bid Adapter : update alias - adding alias of cleanmedianet
  modules/gamoshiBidAdapter.js
Labels: feature

#12885 Various modules: fix jsdoc linter warnings
  libraries/consentManagement/cmUtils.js
  modules/adagioAnalyticsAdapter.js
Labels: maintenance

#12882 anonymisedRtdProvider: can load Anonymised Marketing Tag external script
  integrationExamples/gpt/anonymised_segments_example.html
  modules/anonymisedRtdProvider.js
  modules/anonymisedRtdProvider.md
  src/adloader.js
  test/spec/modules/anonymisedRtdProvider_spec.js
Labels: needs update, maintenance

#12859 Limelight bid adapter: update gvl ids
  modules/limelightDigitalBidAdapter.js
Labels: maintenance

#12888 Oubtrain Bid Adapter : netRevenue simplification
  modules/outbrainBidAdapter.js
  test/spec/modules/outbrainBidAdapter_spec.js
Labels: maintenance

#12893 Adnuntius Bid Adapter: fix bugs on legacy native bid requests and converting ortb adserver responses to legacy responses
  modules/adnuntiusBidAdapter.js
  test/spec/modules/adnuntiusBidAdapter_spec.js
Labels: bugfix

#12762 Equativ Bid Adapter: implement Multi-Impressions Objects (MIO) logic
  modules/equativBidAdapter.js
  test/spec/modules/equativBidAdapter_spec.js
Labels: feature

#12858 Onetag Bid Adapter: add native support
  modules/onetagBidAdapter.js
  test/spec/modules/onetagBidAdapter_spec.js
Labels: feature

#12905 Mobkoi Bid Adapter : remove code responsible for macro replacement
  modules/mobkoiBidAdapter.js
  test/spec/modules/mobkoiBidAdapter_spec.js
Labels: maintenance

#12891 Teads Bid Adapter : send outbrain id
  modules/teadsBidAdapter.js
  test/spec/modules/teadsBidAdapter_spec.js
Labels: maintenance

#12910 Rubicon Bid Adapter : add 710(600x250) and 712(340x430) sizes
  modules/rubiconBidAdapter.js
Labels: maintenance

#12909 ResetDigital Bid Adapter: keywords params validation
  modules/resetdigitalBidAdapter.js
Labels: bugfix

#12815 Browsi RTD & Analytics Adapters : improvements
  libraries/browsiUtils/browsiUtils.js
  modules/browsiAnalyticsAdapter.js
  modules/browsiAnalyticsAdapter.md
  modules/browsiRtdProvider.js
  modules/rtdModule/index.js
  src/constants.js
  test/spec/modules/browsiAnalyticsAdapter_spec.js
  test/spec/modules/browsiRtdProvider_spec.js
Labels: maintenance

#12915 Revert "Goldbach Bid Adapter : switching to ortb endpoint, added uid when consent is granted"
  modules/goldbachBidAdapter.js
  test/spec/modules/goldbachBidAdapter_spec.js
Labels: maintenance

#12906 PubMatic Bid Adapter : analyse bid adjustment patterns
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: maintenance

#12846 UNIQUEST Bid Adapter: initial release
  modules/uniquestAnalyticsAdapter.js
  modules/uniquestAnalyticsAdapter.md
  modules/uniquestBidAdapter.js
  modules/uniquestBidAdapter.md
  test/spec/modules/uniquestAnalyticsAdapter_spec.js
  test/spec/modules/uniquestBidAdapter_spec.js
Labels: feature

#12598 Core: Local cache for video bids
  integrationExamples/gpt/localCacheGam.html
  integrationExamples/videoModule/adPlayerPro/localVideoCache.html
  integrationExamples/videoModule/jwplayer/bidsBackHandlerOverride.html
  integrationExamples/videoModule/jwplayer/gamAdServerMediation.html
  integrationExamples/videoModule/jwplayer/localVideoCache.html
  integrationExamples/videoModule/videojs/bidsBackHandlerOverride.html
  integrationExamples/videoModule/videojs/localVideoCache.html
  libraries/video/shared/vastXmlEditor.js
  libraries/xmlUtils/xmlUtils.js
  modules/adplayerproVideoProvider.js
  modules/dfpAdServerVideo.js
  modules/jwplayerVideoProvider.js
  modules/videoModule/adQueue.js
  modules/videoModule/coreVideo.js
  modules/videoModule/gamAdServerSubmodule.js
  modules/videoModule/index.js
  modules/videojsVideoProvider.js
  src/auction.js
  src/video.js
  src/videoCache.js
  test/spec/modules/dfpAdServerVideo_spec.js
  test/spec/modules/videoModule/adQueue_spec.js
  test/spec/modules/videoModule/shared/vastXmlEditor_spec.js
  test/spec/videoCache_spec.js
Labels: feature

#12920 Preciso Bid Adapter : endpoint update
  modules/precisoBidAdapter.js
  test/spec/modules/precisoBidAdapter_spec.js
Labels: maintenance

#12921 PubxAI RTD Module : update docs
  modules/pubxaiRtdProvider.md
Labels: maintenance

#12792 Contxtful Rtd Provider : add ad unit positions
  modules/contxtfulRtdProvider.js
  modules/contxtfulRtdProvider.md
  test/spec/modules/contxtfulRtdProvider_spec.js
Labels: maintenance

#12913 Medianet: added medianet in codepath-notification
  .github/workflows/scripts/codepath-notification
Labels: on hold

#12911 Core: Custom Targeting Controls
  src/targeting.js
  test/spec/unit/core/targeting_spec.js
Labels: feature, pmc-review

#12732 PubMatic RTD Provider - Initial Release
  modules/.submodules.json
  modules/pubmaticAnalyticsAdapter.js
  modules/pubmaticRtdProvider.js
  modules/pubmaticRtdProvider.md
  test/spec/modules/pubmaticRtdProvider_spec.js
Labels: feature

#12912 NodalsAi Rtd Module : integrate with major version 1 of Nodals' JS Library
  modules/nodalsAiRtdProvider.js
  test/spec/modules/nodalsAiRtdProvider_spec.js
Labels: maintenance

#12599 PAIR: Support for Generic TechLab Version #12146
  modules/.submodules.json
  modules/openPairIdSystem.js
  test/spec/modules/openPairIdSystem_spec.js
Labels: feature, needs update, do not merge

#12901 Adgrid Bid Adapter : add new param placement
  modules/adgridBidAdapter.js
  modules/adgridBidAdapter.md
  test/spec/modules/adgridBidAdapter_spec.js
Labels: maintenance

#12797 Robusta Bid Adapter: New bid adapter
  modules/robustaBidAdapter.js
  modules/robustaBidAdapter.md
  test/spec/modules/robustaBidAdapter_spec.js
Labels: feature

#12922 consentManagementTcf: do not require CMP API to be available when Prebid loads
  libraries/consentManagement/cmUtils.js
  test/spec/libraries/cmUtils_spec.js
  test/spec/modules/consentManagement_spec.js
Labels: bugfix

#12856 LiveIntent User ID Module And Analytics Adapter: Built-in Treatment/Holdout Mechanism And Auction Events Collection Improvements
  libraries/liveIntentId/externalIdSystem.js
  libraries/liveIntentId/idSystem.js
  libraries/liveIntentId/shared.js
  modules/liveIntentAnalyticsAdapter.js
  test/fixtures/liveIntentAuctionEvents.js
  test/spec/modules/liveIntentAnalyticsAdapter_spec.js
  test/spec/modules/liveIntentExternalIdSystem_spec.js
  test/spec/modules/liveIntentIdSystem_spec.js
Labels: feature

#12929 Update adloader.js: remove showheroes after refactor
  src/adloader.js
Labels: maintenance

#12889 PBS Bid Adapter : add BEFORE_PBS_HTTP event
  modules/prebidServerBidAdapter/index.js
  src/constants.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: feature

#12936 Ozone Bid Adapter : support vastURL & vastXML
  modules/ozoneBidAdapter.js
Labels: maintenance

#12850 New RTD submodule: optableRtdProvider
  integrationExamples/gpt/optableRtdProvider_example.html
  modules/.submodules.json
  modules/optableRtdProvider.js
  modules/optableRtdProvider.md
  src/adloader.js
  test/spec/modules/optableRtdProvider_spec.js
Labels: feature

#12924 Smaato Bid Adapter: Add iframe UserSyncs
  modules/smaatoBidAdapter.js
  test/spec/modules/smaatoBidAdapter_spec.js
Labels: maintenance
