Repository prebid/Prebid.js, pull requests merged in 2025-08, with the labels that each got.

#13717 Aso Bid Adapter: add adklip alias
  modules/asoBidAdapter.js
Labels: feature

#13714 PubMatic RTD Module Optimisation - 9.x
  modules/pubmaticRtdProvider.js
  test/spec/modules/pubmaticRtdProvider_spec.js
Labels: legacy

#13716 PubMatic Analytics Adapter Optimization - 9.x
  modules/pubmaticAnalyticsAdapter.js
  test/spec/modules/pubmaticAnalyticsAdapter_spec.js
Labels: legacy

#13734 Rubicon Bid Adapter : allow multiple user syncs per prebid load
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: maintenance

#13665 Debugging: remove all imports
  eslint.config.js
  modules/debugging/WARNING.md
  modules/debugging/bidInterceptor.js
  modules/debugging/debugging.js
  modules/debugging/index.js
  modules/debugging/pbsInterceptor.js
  modules/debugging/responses.js
  plugins/eslint/validateImports.js
  src/debugging.js
  test/spec/modules/debugging_mod_spec.js
Labels: bugfix

#13729 Sevio Bid Adapter : send only the data needed by the backend
  modules/sevioBidAdapter.js
Labels: maintenance

#13735 userId: reintroduce userIdAsEids into adUnit bids
  modules/userId/index.ts
  src/auction.ts
  test/spec/modules/userId_spec.js
Labels: bugfix

#13751 FWSSP Adapter: use ad unit durations
  modules/fwsspBidAdapter.js
  modules/fwsspBidAdapter.md
  test/spec/modules/fwsspBidAdapter_spec.js
Labels: maintenance

#13701 Core: Fixing anchor ads rendering issue
  src/secureCreatives.js
  test/spec/unit/secureCreatives_spec.js
Labels: bugfix

#13722 Core: temporary lock on targeting
  src/targeting.ts
  src/targeting/lock.ts
  src/utils/ttlCollection.ts
  test/spec/unit/core/targetingLock_spec.js
  test/spec/unit/utils/ttlCollection_spec.js
Labels: feature

#13673 appStockSSP Bid Adapter : initial release
  modules/appStockSSPBidAdapter.js
  modules/appStockSSPBidAdapter.md
  test/spec/modules/appStockSSPBidAdapter_spec.js
Labels: feature

#13469 Core: timeoutQueue to TS
  libraries/timeoutQueue/timeoutQueue.js
  libraries/timeoutQueue/timeoutQueue.ts
  test/spec/libraries/timeoutQueue_spec.js
Labels: maintenance

#13794 nextMillennium Bid Adapter : fix typos end changed test endpoint
  modules/nextMillenniumBidAdapter.js
Labels: maintenance

#13800 Core: make transaction IDs bidder-specific
  src/adapterManager.ts
  src/adapters/bidderFactory.ts
  src/prebid.ts
  test/fixtures/fixtures.js
  test/spec/modules/paapi_spec.js
  test/spec/unit/core/adapterManager_spec.js
  test/spec/unit/core/bidderFactory_spec.js
  test/spec/unit/pbjs_api_spec.js
Labels: feature

#13808 Nexx360 Bid Adapter : revnew alias added
  modules/nexx360BidAdapter.js
  test/spec/modules/nexx360BidAdapter_spec.js
Labels: feature

#13821 Build system: add schema-utils dependency
  package-lock.json
  package.json
Labels: dependencies
