Repository prebid/Prebid.js, pull requests merged in 2025-06, with the labels that each got.

#13219 Adverxo Bid Adapter : allow adUnitId to be a string
  modules/adverxoBidAdapter.js
  test/spec/modules/adverxoBidAdapter_spec.js
Labels: maintenance

#13188 Blue BMS Adapters : move shared code to a utility
  libraries/blueUtils/bidderUtils.js
  modules/blueBidAdapter.js
  modules/bmsBidAdapter.js
Labels: maintenance

#13240 mediasquare Bid Adapter - ortb and userIdAsEids
  modules/mediasquareBidAdapter.js
  test/spec/modules/mediasquareBidAdapter_spec.js
Labels: maintenance

#13236 pubmatic Rtd Provider: relax unit test condition
  test/spec/modules/pubmaticRtdProvider_spec.js
Labels: maintenance

#13210 Cwire Bid Adapter: Add network bandwidth to bid payload
  modules/cwireBidAdapter.js
Labels: maintenance

#13228 Xe util library: remove findindex polyfill import
  libraries/xeUtils/bidderUtils.js
Labels: maintenance

#13198 Conversant Adapter: remove use of bidRequest.{}.userid
  modules/conversantBidAdapter.js
  test/spec/modules/conversantBidAdapter_spec.js
Labels: maintenance

#13249 PBS Adapter: ensure tmax is an integer
  modules/prebidServerBidAdapter/ortbConverter.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: bugfix

#13242 Gulp script: replace gutil with plugin-error and fancy-log
  gulpHelpers.js
  gulpfile.js
  package-lock.json
  package.json
Labels: maintenance

#13257 Various modules: remove additional polyfill.js imports
  libraries/advangUtils/index.js
  libraries/browsiUtils/browsiUtils.js
  libraries/gptUtils/gptUtils.js
  modules/microadBidAdapter.js
  modules/onetagBidAdapter.js
  modules/videoModule/index.js
  modules/videoModule/videoImpressionVerifier.js
  modules/yieldlabBidAdapter.js
Labels: maintenance

#13250 Util tests: ensure target always there
  test/spec/utils_spec.js
Labels: maintenance

#13246 Update karma.conf.maker.js: del es5-shim
  karma.conf.maker.js
  package-lock.json
  package.json
Labels: maintenance

#13261 Bliink bid adapter: fix intermittent test failure
  test/spec/modules/bliinkBidAdapter_spec.js
Labels: maintenance

#13262 kargo and bliink bid adapter: remaining intermittent test failure on safari
  test/spec/modules/bliinkBidAdapter_spec.js
  test/spec/modules/kargoBidAdapter_spec.js
Labels: maintenance

#13164 Documentation: guidelines for robots to only submit to forks
  AGENTS.md
  CLAUDE.md
Labels: maintenance

#13020 Luponmedia Bid Adapter: improve fallback bid alignment and dynamic server resolution
  modules/dynamicAdBoostRtdProvider.js
  modules/dynamicAdBoostRtdProvider.md
  modules/luponmediaBidAdapter.js
  modules/luponmediaBidAdapter.md
  test/spec/modules/dynamicAdBoostRtdProvider_spec.js
  test/spec/modules/luponmediaBidAdapter_spec.js
Labels: maintenance

#13268 stvAdapter: change userId handling to bidRequest.userIdAsEids, process userIds from euid.eu
  modules/stvBidAdapter.js
  test/spec/modules/stvBidAdapter_spec.js
Labels: maintenance

#13148 CodeQL: warn on json request content type
  .github/codeql/queries/jsonRequestContentType.ql
Labels: maintenance

#13279 Test suite: enforce no-absolute-path in tests
  eslint.config.js
  test/spec/modules/displayioBidAdapter_spec.js
  test/spec/modules/topLevelPaapi_spec.js
Labels: maintenance

#13282 Gulpfile: replace gulp shell with gulp execa
  gulpfile.js
  package-lock.json
  package.json
Labels: maintenance

#13296 HypelabBidAdapter: fixing spec file
  test/spec/modules/hypelabBidAdapter_spec.js
Labels: bugfix

#13275 Eslint: enforce no-array-constructor in test files
  eslint.config.js
  test/helpers/index_adapter_utils.js
  test/spec/modules/yieldmoBidAdapter_spec.js
  test/spec/unit/core/targeting_spec.js
Labels: maintenance

#13271 Eslint: re-enable no trailing spaces rules in test files
  eslint.config.js
  test/fake-server/README.md
  test/helpers/testing-utils.js
  test/spec/fpd/enrichment_spec.js
  test/spec/libraries/greedy/greedyPromise_spec.js
  test/spec/modules/adfBidAdapter_spec.js
  test/spec/modules/contxtfulBidAdapter_spec.js
  test/spec/modules/cwireBidAdapter_spec.js
  test/spec/modules/enrichmentLiftMeasurement_spec.js
  test/spec/modules/iasRtdProvider_spec.js
  test/spec/modules/id5IdSystem_spec.js
  test/spec/modules/intentIqAnalyticsAdapter_spec.js
  test/spec/modules/intentIqIdSystem_spec.js
  test/spec/modules/lockrAIMIdSystem_spec.js
  test/spec/modules/luceadBidAdapter_spec.js
  test/spec/modules/mediaeyesBidAdapter_spec.js
  test/spec/modules/missenaBidAdapter_spec.js
  test/spec/modules/nexx360BidAdapter_spec.js
  test/spec/modules/oguryBidAdapter_spec.js
  test/spec/modules/omsBidAdapter_spec.js
  test/spec/modules/onomagicBidAdapter_spec.js
  test/spec/modules/overtoneRtdProvider_spec.mjs
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/modules/previousAuctionInfo_spec.js
  test/spec/modules/pubmaticAnalyticsAdapter_spec.js
  test/spec/modules/pubmaticBidAdapter_spec.js
  test/spec/modules/pubmaticRtdProvider_spec.js
  test/spec/modules/pubwiseAnalyticsAdapter_spec.js
  test/spec/modules/sizeMappingV2_spec.js
  test/spec/modules/tpmnBidAdapter_spec.js
  test/spec/modules/ttdBidAdapter_spec.js
  test/spec/modules/userId_spec.js
  test/spec/modules/vibrantmediaBidAdapter_spec.js
  test/spec/unit/pbjs_api_spec.js
  test/spec/utils_spec.js
  test/test_deps.js
Labels: maintenance

#13277 Permutive RTD modules: ensure window.permutive cleanup in test runs
  test/spec/modules/permutiveIdentityManagerIdSystem_spec.js
Labels: maintenance

#13214 RTB House Bid Adapter: pause active PAAPI support
  modules/rtbhouseBidAdapter.js
  test/spec/modules/rtbhouseBidAdapter_spec.js
Labels: maintenance

#13300 AdtrgtmeBidAdapter: set source.schain and regs for openRTB2.6
  modules/adtrgtmeBidAdapter.js
  test/spec/modules/adtrgtmeBidAdapter_spec.js
Labels: maintenance

#13285 Dependencies : bump fsextra and babel
  gulpHelpers.js
  package-lock.json
  package.json
Labels: build process, maintenance

#13284 Gulpfile: eliminate gulp connect dependency
  gulpfile.js
  integrationExamples/gpt/amp/gulpfile.js
  package-lock.json
  package.json
Labels: maintenance

#12979 OneId System : initial release
  modules/.submodules.json
  modules/modules/oneIdIdSystem.md
  modules/oneIdIdSystem.js
  modules/oneIdIdSystem.md
  package-lock.json
  package.json
  test/helpers/testing-utils.js
  test/spec/modules/oneIdIdSystem_spec.js
Labels: feature

#13322 Automatad adapter: use storage manager
  modules/automatadAnalyticsAdapter.js
Labels: maintenance

#13317 Improve Digital Bid Adapter: Added compression support for outgoing requests
  modules/improvedigitalBidAdapter.js
  test/spec/modules/improvedigitalBidAdapter_spec.js
Labels: maintenance

#13318 Lemmadigital Bid Adapter: update bid request URL and fixed video player size reading issue
  integrationExamples/gpt/lemma_sample.html
  modules/lemmaDigitalBidAdapter.js
  test/spec/modules/lemmaDigitalBidAdapter_spec.js
Labels: maintenance

#13335 GumGum Bid Adapter : Added id property to eids for uid2
  modules/gumgumBidAdapter.js
  test/spec/modules/gumgumBidAdapter_spec.js
Labels: maintenance

#13331 DSPx Bid Adapter: Update for Prebid.js v10 - userIdAsEids migration, ortb2 categories, schain enhancements
  libraries/dspxUtils/bidderUtils.js
  modules/dspxBidAdapter.js
  test/spec/modules/dspxBidAdapter_spec.js
Labels: maintenance

#13310 Condorx Bid Adapter : add support to bidfloor and support open RTB requests and responses
  modules/condorxBidAdapter.js
  modules/condorxBidAdapter.md
  test/spec/modules/condorxBidAdapter_spec.js
Labels: maintenance

#13329 Bliink bid adapter: try to stabilize test
  test/spec/modules/bliinkBidAdapter_spec.js
Labels: maintenance

#13316 StroeerCore Bid Adapter: use bid's meta as-is from server response
  modules/stroeerCoreBidAdapter.js
  test/spec/modules/stroeerCoreBidAdapter_spec.js
Labels: maintenance

#13339 New Adapter: RocketLab
  modules/rocketlabBidAdapter.js
  modules/rocketlabBidAdapter.md
  test/spec/modules/rocketlabBidAdapter_spec.js
Labels: feature

#13326 Permutive RTD Module: fix duplicate ortb2 keywords
  modules/permutiveRtdProvider.js
  test/spec/modules/permutiveCombined_spec.js
  test/spec/modules/permutiveIdentityManagerIdSystem_spec.js
Labels: maintenance

#13324 Adrino Bid Adapter: userIdsAsEids(bidderRequest) for Prebid 10 compatibility
  modules/adrinoBidAdapter.js
  test/spec/modules/adrinoBidAdapter_spec.js
Labels: maintenance

#13348 Update package.json: remove documentation dep
  package-lock.json
  package.json
Labels: maintenance

#13346 Attekmi: update user syncs
  modules/smarthubBidAdapter.js
  test/spec/modules/smarthubBidAdapter_spec.js
Labels: maintenance

#13313 kinesso id system: improve test coverage
  test/spec/modules/kinessoIdSystem_spec.js
Labels: maintenance

#13305 Adtrue bid adapter: improve test coverage
  test/spec/modules/adtrueBidAdapter_spec.js
Labels: maintenance

#13344 Core: sync rtd and id submodules lists
  modules/.submodules.json
Labels: maintenance

#13092 PubMatic Bid Adapter : send viewability percentage of slots
  libraries/percentInView/percentInView.js
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: maintenance

#13359 Pubmatic RTD: fix null check for auctionDelay
  modules/pubmaticRtdProvider.js
Labels: bugfix

#13358 PubMatic RTD Module : support for partners in dynamic floors
  modules/pubmaticRtdProvider.js
  test/spec/modules/pubmaticRtdProvider_spec.js
Labels: maintenance

#13362 360playvid Bid Adapter : initial release
  modules/360playvidBidAdapter.js
  modules/360playvidBidAdapter.md
  test/spec/modules/360playvidBidAdapter_spec.js
Labels: feature

#13366 Asteriobid Analytics Adapters : fix 2 blank lines linting
  modules/AsteriobidPbmAnalyticsAdapter.js
  modules/asteriobidAnalyticsAdapter.js
Labels: maintenance

#13369 Vidoomy Bid Adapter: support multiple bid response
  modules/vidoomyBidAdapter.js
  test/spec/modules/vidoomyBidAdapter_spec.js
Labels: maintenance

#13377 Ogury Bid Adapter: Replace Deprecated bidderRequest.{}.userId
  modules/oguryBidAdapter.js
  test/spec/modules/oguryBidAdapter_spec.js
Labels: maintenance

#13374 TargetVideo Bid Adapter: Send user eids/data; changing load_cookie.html URL
  libraries/targetVideoUtils/constants.js
  modules/targetVideoBidAdapter.js
  test/spec/modules/targetVideoBidAdapter_spec.js
Labels: maintenance

#13272 Mobilefuse Bid Adapter: Add support for iframe sync flag in bid request
  modules/mobilefuseBidAdapter.js
  test/spec/modules/mobilefuseBidAdapter_spec.js
Labels: maintenance

#13303 Adlane Real Time Data Provider Module: release
  modules/.submodules.json
  modules/adlaneRtdProvider.js
  modules/adlaneRtdProvider.md
  test/spec/modules/adlaneRtdProvider_spec.js
Labels: feature

#13304 Adtelligent Bid Adapter: Add support for age verification flag
  modules/adtelligentBidAdapter.js
  test/spec/modules/adtelligentBidAdapter_spec.js
Labels: needs unit tests, maintenance

#13373 Missena Bid Adapter: forward GPID from ortb2Imp to ortb2.ext
  modules/missenaBidAdapter.js
  test/spec/modules/missenaBidAdapter_spec.js
Labels: maintenance

#13391 Adot Bid Adapter - Prebid.js v10 support
  modules/adotBidAdapter.js
  test/spec/modules/adotBidAdapter_spec.js
Labels: maintenance

#13397 MobkoiBidAdapter MobkoiIdSystem update: Replace bidRequest.{}.userId with userIdAdEids for 10.0 Compliance
  modules/mobkoiBidAdapter.js
  modules/mobkoiIdSystem.js
  test/spec/modules/mobkoiAnalyticsAdapter_spec.js
  test/spec/modules/mobkoiIdSystem_spec.js
Labels: maintenance

#13395 Underdog Media Adapter Update: Switch to userIdAsEids for 10.0 Compliance
  modules/underdogmediaBidAdapter.js
  test/spec/modules/underdogmediaBidAdapter_spec.js
Labels: maintenance

#13405 Video module: do not attempt to render winning bid if there are none
  modules/videoModule/index.js
  test/spec/modules/videoModule/pbVideo_spec.js
Labels: bugfix

#13387 Adwmg adapters: share user agent parsing
  libraries/userAgentUtils/detailed.js
  modules/adWMGAnalyticsAdapter.js
  modules/adWMGBidAdapter.js
  modules/byDataAnalyticsAdapter.js
Labels: maintenance

#13396 TTD Bid Adapter: accept 64 character publisher id
  modules/ttdBidAdapter.js
  test/spec/modules/ttdBidAdapter_spec.js
Labels: maintenance

#13404 Liveintent id module: no more id cookies.
  libraries/liveIntentId/externalIdSystem.js
  libraries/liveIntentId/idSystem.js
  libraries/liveIntentId/shared.js
  test/spec/modules/liveIntentExternalIdSystem_spec.js
  test/spec/modules/liveIntentIdMinimalSystem_spec.js
  test/spec/modules/liveIntentIdSystem_spec.js
Labels: maintenance

#13287 Liveramp ID Submodule: add try catch for atob in identitylink module
  modules/identityLinkIdSystem.js
  test/spec/modules/identityLinkIdSystem_spec.js
Labels: maintenance

#13407 Magnite Analytics Adapter: fix falsy meta.mediaType overriding valid mediaType
  modules/magniteAnalyticsAdapter.js
Labels: bugfix

#13361 Core: suppress topics enrollment warning unless debugging
  src/adapters/bidderFactory.js
  src/ajax.js
  test/spec/unit/core/bidderFactory_spec.js
Labels: maintenance

#13415 Onetag Bid Adapter: fix the priceFloor size field format
  modules/onetagBidAdapter.js
  test/spec/modules/onetagBidAdapter_spec.js
Labels: maintenance

#13094 Prebid 10: access request credentials check
  modules/tcfControl.ts
  src/activities/activities.js
  src/ajax.ts
  src/storageManager.ts
  test/spec/modules/tcfControl_spec.js
Labels: 10.0 API Change

#13108 Ssp_geniee Bid Adapter : Add support for iframe-based cookie sync in BidAdapter and Fix the default value of the ib parameter
  modules/ssp_genieeBidAdapter.js
  test/spec/modules/ssp_genieeBidAdapter_spec.js
Labels: needs update, maintenance

#13421 Mobkoi Analytics Adapter : reinstate test block
  test/spec/modules/mobkoiAnalyticsAdapter_spec.js
Labels: maintenance

#13379 Prebid 10: Various bid adapters: align filename with bidder code
  modules/adbutlerBidAdapter.js
  modules/blockthroughBidAdapter.js
  modules/blockthroughBidAdapter.md
  modules/bmtmBidAdapter.js
  modules/bmtmBidAdapter.md
  modules/cadent_aperture_mxBidAdapter.js
  modules/cadent_aperture_mxBidAdapter.md
  modules/epom_dspBidAdapter.js
  modules/epom_dspBidAdapter.md
  modules/growadsBidAdapter.js
  modules/growadsBidAdapter.md
  modules/incrementxBidAdapter.js
  modules/incrementxBidAdapter.md
  modules/pwbidBidAdapter.js
  modules/pwbidBidAdapter.md
  modules/sonaradsBidAdapter.js
  modules/sonaradsBidAdapter.md
  modules/viantBidAdapter.js
  modules/viantBidAdapter.md
  modules/zeta_globalBidAdapter.js
  modules/zeta_globalBidAdapter.md
  test/spec/modules/blockthroughBidAdapter_spec.js
  test/spec/modules/bmtmBidAdapter_spec.js
  test/spec/modules/cadent_aperture_mxBidAdapter_spec.js
  test/spec/modules/epom_dspBidAdapter_spec.js
  test/spec/modules/growadsBidAdapter_spec.js
  test/spec/modules/incrementxBidAdapter_spec.js
  test/spec/modules/pwbidBidAdapter_spec.js
  test/spec/modules/sonaradsBidAdapter_spec.js
  test/spec/modules/viantBidAdapter_spec.js
  test/spec/modules/zeta_globalBidAdapter_spec.js
Labels: 10.0 API Change

#13298 Circleci: setup persistent babel cache for tests
  .circleci/config.yml
  wdio.shared.conf.js
Labels: build process, maintenance

#13414 Teads Bid Adapter: prefer eids to form userids
  modules/teadsBidAdapter.js
  modules/teadsIdSystem.js
  test/spec/modules/teadsBidAdapter_spec.js
Labels: maintenance

#13429 Bidmatic Bid Adapter: update API
  modules/bidmaticBidAdapter.js
  test/spec/modules/bidmaticBidAdapter_spec.js
Labels: maintenance

#13276 Cwire Bid Adapter : add floor price in the bid request
  modules/cwireBidAdapter.js
  test/spec/modules/cwireBidAdapter_spec.js
Labels: maintenance

#13354 core enrichments: convert documentLang
  src/fpd/enrichment.js
  test/spec/fpd/enrichment_spec.js
Labels: maintenance

#13442 Rubicon Bid Adapter: remove fallback value for rp_maxbids
  modules/rubiconBidAdapter.js
  test/spec/modules/rubiconBidAdapter_spec.js
Labels: maintenance

#13368 Prebid 10: Add yield helper and disable greedy by default
  README.md
  gulpHelpers.js
  src/prebid.ts
  src/prebidGlobal.ts
  src/utils/yield.ts
Labels: 10.0 API Change

#13440 PubMatic analytics adapter throwing an error when there is no s2sConfig present.
  modules/pubmaticAnalyticsAdapter.js
Labels: bugfix

#12952 Core: Error Detection for Autoplay Detection
  libraries/autoplayDetection/autoplay.js
  test/spec/libraries/autoplayDetection_spec.js
Labels: needs update, bugfix

#13372 Prebid 10: Introducing enforceStorageType
  modules/userId/index.ts
  src/storageManager.ts
  test/spec/modules/userId_spec.js
Labels: 10.0 API Change

#13082 New Module added: jixieIdSystem
  modules/jixieIdSystem.js
  test/spec/modules/jixieIdSystem_spec.js
Labels: feature

#13286 ChromeAi Rtd Provider: Initial Release
  integrationExamples/chromeai/japanese.html
  modules/.submodules.json
  modules/chromeAiRtdProvider.js
  modules/chromeAiRtdProvider.md
  test/spec/modules/chromeAiRtdProvider_spec.js
Labels: feature

#13457 Build system: serialize test runs
  .circleci/config.yml
Labels: maintenance

#13454 Circleci: bail in e2e, lower disconnect tolerance
  karma.conf.maker.js
  wdio.shared.conf.js
Labels: maintenance

#13170 Update crossDomain.js: wait for onload
  creative/crossDomain.js
Labels: bugfix

#13464 Test suite: eliminate real time waits
  test/spec/libraries/cmUtils_spec.js
  test/spec/modules/dgkeywordRtdProvider_spec.js
  test/spec/modules/instreamTracking_spec.js
  test/spec/modules/yieldoneAnalyticsAdapter_spec.js
Labels: maintenance

#13445 Aniview Bid Adapter : filter bids without `adm` or `nurl`; Use only `vastXml` OR `vastUrl`
  modules/aniviewBidAdapter.js
  test/spec/modules/aniviewBidAdapter_spec.js
Labels: bugfix
