Repository prebid/Prebid.js, pull requests merged in 2025-05, with the labels that each got.

#12903 IntentIq ID & Analytics Modules: Updates for adType, placementId and sync request
  libraries/intentIqConstants/intentIqConstants.js
  libraries/intentIqUtils/getRefferer.js
  libraries/intentIqUtils/getSyncKey.js
  modules/intentIqAnalyticsAdapter.js
  modules/intentIqAnalyticsAdapter.md
  modules/intentIqIdSystem.js
  modules/intentIqIdSystem.md
  test/spec/modules/intentIqAnalyticsAdapter_spec.js
  test/spec/modules/intentIqIdSystem_spec.js
Labels: maintenance

#13057 IntentIQ ID System : fix for window.innerHeight and Width with util function
  modules/intentIqIdSystem.js
Labels: bugfix

#13010 OpaMarketplace Bid Adapter : initial release
  modules/opaMarketplaceBidAdapter.js
  modules/opaMarketplaceBidAdapter.md
  test/spec/modules/opaMarketplaceBidAdapter_spec.js
Labels: feature

#12790 blue Bid Adapter : implement onBidWon pixel triggers
  modules/blueBidAdapter.js
  test/spec/modules/blueBidAdapter_spec.js
Labels: maintenance

#13050 Omnidex Bid Adapter : initial release
  modules/omnidexBidAdapter.js
  modules/omnidexBidAdapter.md
  test/spec/modules/omnidexBidAdapter_spec.js
Labels: feature

#13064 sspBC Bid Adapter : fix floor price currency
  modules/sspBCBidAdapter.js
Labels: bugfix

#13061 Core: allow for splitting bid requests on pbsHost
  modules/prebidServerBidAdapter/index.js
  modules/prebidServerBidAdapter/ortbConverter.js
  modules/s2sTesting.js
  src/adapterManager.js
  src/prebid.js
  src/utils.js
  test/spec/modules/prebidServerBidAdapter_spec.js
  test/spec/unit/core/adapterManager_spec.js
Labels: feature

#13059 IAS RTD Module: allow iasRtdProvider to store fetched data
  modules/iasRtdProvider.js
  test/spec/modules/iasRtdProvider_spec.js
Labels: bugfix

#13080 Ogury Bid Adapter: reintroduce previous BID_WON logic to avoid some discrepancies
  modules/oguryBidAdapter.js
  test/spec/modules/oguryBidAdapter_spec.js
Labels: bugfix

#13077 Logicad Bid Adapter : add schain support
  modules/logicadBidAdapter.js
  test/spec/modules/logicadBidAdapter_spec.js
Labels: maintenance

#13078 Goldbach Bid Adapter : added gdpr signals to cookiesync
  modules/goldbachBidAdapter.js
  test/spec/modules/goldbachBidAdapter_spec.js
Labels: bugfix

#13067 Nexx360 Bid Adapter: bidstailamedia alias added
  modules/nexx360BidAdapter.js
Labels: feature

#13085 ttd Bid Adapter : remove imp.video overwrite
  modules/ttdBidAdapter.js
Labels: bugfix

#13089 Build system: wait for DOM to load before starting tests
  test/test_deps.js
Labels: build process, maintenance

#13093 Taboola User Id Sub-Module: release
  modules/taboolaIdSystem.js
  modules/taboolaIdSystem.md
  test/spec/modules/taboolaIdSystem_spec.js
Labels: feature

#13091 Bidglass Bid Adapter : remove params.adUnitId numeric requirement
  modules/bidglassBidAdapter.js
Labels: maintenance

#13096 Yandex Bid Adapter : Bid handler changed
  modules/yandexBidAdapter.js
  test/spec/modules/yandexBidAdapter_spec.js
Labels: maintenance

#13102 Nexx360 Bid Adapter : add scoremedia alias
  modules/nexx360BidAdapter.js
Labels: feature

#13101 Mediaforce Bid Adapter: add video support and extended test coverage
  modules/mediaforceBidAdapter.js
  modules/mediaforceBidAdapter.md
  test/spec/modules/mediaforceBidAdapter_spec.js
Labels: maintenance

#13090 Limelight adapter: update user sync headers
  modules/limelightDigitalBidAdapter.js
  test/spec/modules/limelightDigitalBidAdapter_spec.js
Labels: maintenance

#13097 Bid Glass Bid Adapter : add consent data to requests
  modules/bidglassBidAdapter.js
  test/spec/modules/bidglassAdapter_spec.js
Labels: maintenance

#13084 Onetag Bid Adapter : added native legacy support
  modules/onetagBidAdapter.js
  test/spec/modules/onetagBidAdapter_spec.js
Labels: maintenance

#13105 Prebid 10: Removing default s2s vendor config
  modules/prebidServerBidAdapter/config.js
  modules/prebidServerBidAdapter/index.js
  test/spec/auctionmanager_spec.js
  test/spec/modules/prebidServerBidAdapter_spec.js
Labels: 10.0 API Change

#13028 Equativ Bid Adapter: benefit from Previous Auction Info module
  modules/equativBidAdapter.js
  test/spec/modules/equativBidAdapter_spec.js
Labels: maintenance

#13079 Adkernel Bid Adapter: vast/nurl changes
  modules/adkernelBidAdapter.js
  test/spec/modules/adkernelBidAdapter_spec.js
Labels: maintenance

#13111 PB10: Delete conversantAnalyticsAdapter
  modules/conversantAnalyticsAdapter.js
  test/spec/modules/conversantAnalyticsAdapter_spec.js
Labels: 10.0 API Change

#13002 Adnuntius Bid Adapter: send eids to adserver
  modules/adnuntiusBidAdapter.js
  test/spec/modules/adnuntiusBidAdapter_spec.js
Labels: feature

#13068 Prebid 10: Update PR_REVIEW.md
  PR_REVIEW.md
Labels: 10.0 API Change

#13113 Update browsers.json: bump chrome legacy supported vesion
  browsers.json
Labels: 10.0 API Change

#13109 Adgrid Bid Adapter : updated withCredentials for true
  modules/adgridBidAdapter.js
Labels: maintenance

#13110 Livewrapped Bid Adapter : forward dealId and bidderCode if setting enabled
  modules/livewrappedBidAdapter.js
  test/spec/modules/livewrappedBidAdapter_spec.js
Labels: maintenance

#13045 Suim Bid Adapter : initial release
  modules/suimBidAdapter.js
  modules/suimBidAdapter.md
  test/spec/modules/suimBidAdapter_spec.js
Labels: feature

#13062 Yandex Bid Adapter : add support for video ads
  modules/yandexBidAdapter.js
  modules/yandexBidAdapter.md
  test/spec/modules/yandexBidAdapter_spec.js
Labels: maintenance

#13120 Adnuntius Bid Adapter: sends through prebid version with ad requests.
  modules/adnuntiusBidAdapter.js
  test/spec/modules/adnuntiusBidAdapter_spec.js
Labels: maintenance

#13100 MediaForce Bid Adapter: support static (bid.params.bidfloor) and dynamic (getFloor) bidfloor
  modules/mediaforceBidAdapter.js
  test/spec/modules/mediaforceBidAdapter_spec.js
Labels: maintenance

#13124 Mobian RTD module: update email address in documentation
  modules/mobianRtdProvider.md
Labels: maintenance

#13033 Core: Option to Enable Gzip Compression for Bid Requests
  modules/pubmaticBidAdapter.js
  src/adapters/bidderFactory.js
  src/utils.js
  test/spec/modules/pubmaticBidAdapter_spec.js
  test/spec/unit/core/bidderFactory_spec.js
  test/spec/utils_spec.js
Labels: feature, needs 2nd review, do not merge

#13121 Nexx360 Bid Adapter : create lib for shared adapter code
  libraries/nexx360Utils/index.js
  modules/nexx360BidAdapter.js
  test/spec/modules/nexx360BidAdapter_spec.js
Labels: maintenance

#13123 Adgrid Bid Adapter : use common code
  modules/adgridBidAdapter.js
  test/spec/modules/adgridBidAdapter_spec.js
Labels: maintenance

#12867 Prebid 10: Delete temporary apn transformer module
  modules/anPspParamsConverter.js
  modules/anPspParamsConverter.md
  test/spec/modules/anPspParamsConverter_spec.js
Labels: 10.0 API Change

#13136 Various modules: fix jsdoc warnings
  modules/debugging/bidInterceptor.js
  modules/discoveryBidAdapter.js
  modules/dmdIdSystem.js
  modules/dsp_genieeBidAdapter.js
  modules/dxkultureBidAdapter.js
  modules/fabrickIdSystem.js
  modules/feedadBidAdapter.js
  modules/gmosspBidAdapter.js
  modules/gppControl_usstates.js
  modules/hybridBidAdapter.js
  modules/identityLinkIdSystem.js
  modules/idxIdSystem.js
  modules/impactifyBidAdapter.js
  modules/improvedigitalBidAdapter.js
  modules/integr8BidAdapter.js
  modules/ivsBidAdapter.js
  modules/jixieBidAdapter.js
  modules/kinessoIdSystem.js
  modules/lemmaDigitalBidAdapter.js
  modules/limelightDigitalBidAdapter.js
  modules/lmpIdSystem.js
  modules/malltvBidAdapter.js
  modules/mediagoBidAdapter.js
  modules/medianetBidAdapter.js
  modules/mediasquareBidAdapter.js
  modules/merkleIdSystem.js
  modules/multibid/index.js
  modules/mwOpenLinkIdSystem.js
  modules/nativoBidAdapter.js
  modules/netIdSystem.js
  modules/neuwoRtdProvider.js
  modules/nextrollBidAdapter.js
  modules/nobidBidAdapter.js
  modules/novatiqIdSystem.js
  modules/oneKeyIdSystem.js
  modules/oneKeyRtdProvider.js
  modules/operaadsBidAdapter.js
  modules/optidigitalBidAdapter.js
  modules/orbidderBidAdapter.js
  modules/paapi.js
  src/prebid.js
  src/utils/focusTimeout.js
  src/utils/perfMetrics.js
  src/utils/ttlCollection.js
Labels: maintenance

#13134 Various modules: fix jsdoc warnings
  modules/1plusXRtdProvider.js
  modules/33acrossAnalyticsAdapter.js
  modules/adhashBidAdapter.js
  modules/adlooxRtdProvider.js
  modules/adplusBidAdapter.js
  modules/adpod.js
  modules/adtelligentBidAdapter.js
  modules/adyoulikeBidAdapter.js
  modules/bliinkBidAdapter.js
  modules/concertBidAdapter.js
  modules/criteoIdSystem.js
  modules/dailymotionBidAdapter.js
  modules/datawrkzBidAdapter.js
Labels: maintenance

#13143 ProgrammaticX: new adapter
  modules/programmaticXBidAdapter.js
  modules/programmaticXBidAdapter.md
  test/spec/modules/programmaticXBidAdapter_spec.js
Labels: feature

#13144 AppNexus Bid Adapter - refactor userId code for Prebid 10
  modules/appnexusBidAdapter.js
  test/spec/modules/appnexusBidAdapter_spec.js
Labels: maintenance

#13139 Mediago Bid Adapter:remove request.{}.userID
  modules/mediagoBidAdapter.js
  test/spec/modules/mediagoBidAdapter_spec.js
Labels: maintenance

#13145 Mobian Rtd Provider : add gvlid
  modules/mobianRtdProvider.js
Labels: maintenance

#13132 GumGum Bid Adapter : Add support for the sua parameter
  modules/gumgumBidAdapter.js
  test/spec/modules/gumgumBidAdapter_spec.js
Labels: maintenance

#13152 Integration Examples: Update gpt.js URLs
  integrationExamples/gpt/adloox.html
  integrationExamples/gpt/adnuntius_example.html
  integrationExamples/gpt/adnuntius_multiformat_example.html
  integrationExamples/gpt/advanced_size_mapping.html
  integrationExamples/gpt/afpGamExample.html
  integrationExamples/gpt/akamaidap_segments_example.html
  integrationExamples/gpt/azerionedgeRtdProvider_example.html
  integrationExamples/gpt/contxtfulRtdProvider_example.html
  integrationExamples/gpt/esp_example.html
  integrationExamples/gpt/gdpr_hello_world.html
  integrationExamples/gpt/gpp_us_hello_world.html
  integrationExamples/gpt/gpp_us_hello_world_iframe_subpage.html
  integrationExamples/gpt/growthcode.html
  integrationExamples/gpt/hello_world.html
  integrationExamples/gpt/imRtdProvider_example.html
  integrationExamples/gpt/liveIntentRtdProviderExample.html
  integrationExamples/gpt/neuwoRtdProvider_example.html
  integrationExamples/gpt/nexverse.html
  integrationExamples/gpt/paapi_example.html
  integrationExamples/gpt/permutiveRtdProvider_example.html
  integrationExamples/gpt/prebidServer_native_example.html
  integrationExamples/gpt/prebidServer_paapi_example.html
  integrationExamples/gpt/proxistore_example.html
  integrationExamples/gpt/publir_hello_world.html
  integrationExamples/gpt/pubxaiRtdProvider_example.html
  integrationExamples/gpt/reconciliationRtdProvider_example.html
  integrationExamples/gpt/revcontent_example_banner.html
  integrationExamples/gpt/revcontent_example_native.html
  integrationExamples/gpt/symitridap_segments_example.html
  integrationExamples/gpt/tpmn_example.html
  integrationExamples/gpt/wurflRtdProvider_example.html
  modules/afpBidAdapter.md
  modules/astraoneBidAdapter.md
  modules/hybridBidAdapter.md
  modules/pixfutureBidAdapter.md
  modules/voxBidAdapter.md
  modules/winrBidAdapter.md
Labels: maintenance, documentation

#13122 IntentIq ID & Analytics Modules: Supports additional configuration parameters
  libraries/intentIqConstants/intentIqConstants.js
  libraries/intentIqUtils/handleAdditionalParams.js
  libraries/intentIqUtils/intentIqConfig.js
  libraries/intentIqUtils/storageUtils.js
  libraries/intentIqUtils/urlUtils.js
  modules/intentIqAnalyticsAdapter.js
  modules/intentIqIdSystem.js
  modules/intentIqIdSystem.md
  test/spec/modules/intentIqAnalyticsAdapter_spec.js
  test/spec/modules/intentIqIdSystem_spec.js
Labels: maintenance

#13167 Various modules: remove includes polyfill
  modules/adhashBidAdapter.js
  modules/adnowBidAdapter.js
  modules/adrelevantisBidAdapter.js
  modules/adxpremiumAnalyticsAdapter.js
  modules/afpBidAdapter.js
  modules/appnexusBidAdapter.js
  modules/betweenBidAdapter.js
  modules/browsiRtdProvider.js
  modules/cadentApertureMXBidAdapter.js
  modules/cleanmedianetBidAdapter.js
  modules/connectIdSystem.js
  modules/craftBidAdapter.js
  modules/dchain.js
  modules/dspxBidAdapter.js
  modules/gamoshiBidAdapter.js
  modules/gumgumBidAdapter.js
  modules/imdsBidAdapter.js
  modules/intersectionRtdProvider.js
  modules/justIdSystem.js
  modules/mediafuseBidAdapter.js
  modules/medianetRtdProvider.js
  modules/permutiveRtdProvider.js
  modules/pixfutureBidAdapter.js
  modules/prebidServerBidAdapter/index.js
  modules/relevadRtdProvider.js
  modules/roxotAnalyticsAdapter.js
  modules/rtbhouseBidAdapter.js
  modules/sirdataRtdProvider.js
  modules/sizeMapping.js
  modules/sizeMappingV2.js
  modules/sspBCBidAdapter.js
  modules/stvBidAdapter.js
  modules/topicsFpdModule.js
  modules/verizonMediaIdSystem.js
  modules/viewdeosDXBidAdapter.js
  modules/widespaceBidAdapter.js
  modules/winrBidAdapter.js
  modules/yieldmoBidAdapter.js
  modules/yuktamediaAnalyticsAdapter.js
  src/adapterManager.js
  src/adapters/bidderFactory.js
  src/adloader.js
  src/auction.js
  src/config.js
  src/native.js
  src/prebid.js
  src/secureCreatives.js
  src/targeting.js
  src/userSync.js
  src/utils.js
  test/spec/e2e/longform/basic_w_bidderSettings.spec.js
  test/spec/e2e/longform/basic_w_custom_adserver_translation.spec.js
  test/spec/e2e/longform/basic_w_priceGran.spec.js
  test/spec/e2e/longform/basic_w_requireExactDuration.spec.js
  test/spec/e2e/longform/basic_wo_brandCategoryExclusion.spec.js
  test/spec/e2e/longform/basic_wo_requireExactDuration.spec.js
  test/spec/modules/afpBidAdapter_spec.js
  test/spec/modules/fintezaAnalyticsAdapter_spec.js
  test/spec/modules/widespaceBidAdapter_spec.js
Labels: maintenance

#13173 Prebid 10: add logInfo to public API methods
  src/prebid.js
Labels: 10.0 API Change

#13147 Weborama RTD Module : check gdpr consent data
  integrationExamples/gpt/weboramaRtdProvider_example.html
  modules/weboramaRtdProvider.js
  modules/weboramaRtdProvider.md
  test/spec/modules/weboramaRtdProvider_spec.js
Labels: maintenance

#13149 Integration examples: fix failsafe logic
  integrationExamples/gpt/1plusXRtdProviderExample.html
  integrationExamples/gpt/51DegreesRtdProvider_example.html
  integrationExamples/gpt/adUnitFloors.html
  integrationExamples/gpt/adloox.html
  integrationExamples/gpt/adnuntius_example.html
  integrationExamples/gpt/adnuntius_multiformat_example.html
  integrationExamples/gpt/advanced_size_mapping.html
  integrationExamples/gpt/airgridRtdProvider_example.html
  integrationExamples/gpt/akamaidap_segments_example.html
  integrationExamples/gpt/anonymised_segments_example.html
  integrationExamples/gpt/azerionedgeRtdProvider_example.html
  integrationExamples/gpt/blueconicRtdProvider_example.html
  integrationExamples/gpt/contxtfulRtdProvider_example.html
  integrationExamples/gpt/esp_example.html
  integrationExamples/gpt/gdpr_hello_world.html
  integrationExamples/gpt/gpp_us_hello_world.html
  integrationExamples/gpt/gpp_us_hello_world_iframe_subpage.html
  integrationExamples/gpt/growthcode.html
  integrationExamples/gpt/hadronRtdProvider_example.html
  integrationExamples/gpt/hello_world.html
  integrationExamples/gpt/idImportLibrary_example.html
  integrationExamples/gpt/id_lift_measurement.html
  integrationExamples/gpt/imRtdProvider_example.html
  integrationExamples/gpt/ixMultiFormat.html
  integrationExamples/gpt/liveIntentRtdProviderExample.html
  integrationExamples/gpt/mgidRtdProvider_example.html
  integrationExamples/gpt/neuwoRtdProvider_example.html
  integrationExamples/gpt/nexverse.html
  integrationExamples/gpt/optableRtdProvider_example.html
  integrationExamples/gpt/optimeraRtdProvider_example.html
  integrationExamples/gpt/paapi_example.html
  integrationExamples/gpt/permutiveRtdProvider_example.html
  integrationExamples/gpt/prebidServer_paapi_example.html
  integrationExamples/gpt/precisoExample.html
  integrationExamples/gpt/proxistore_example.html
  integrationExamples/gpt/publir_hello_world.html
  integrationExamples/gpt/raveltechRtdProvider_example.html
  integrationExamples/gpt/raynRtdProvider_example.html
  integrationExamples/gpt/reconciliationRtdProvider_example.html
  integrationExamples/gpt/relevadRtdProvider_example.html
  integrationExamples/gpt/revcontent_example_banner.html
  integrationExamples/gpt/revcontent_example_native.html
  integrationExamples/gpt/rewardedInterestIdSystem_example.html
  integrationExamples/gpt/sirdataRtdProvider_example.html
  integrationExamples/gpt/symitridap_segments_example.html
  integrationExamples/gpt/userId_example.html
  integrationExamples/gpt/weboramaRtdProvider_example.html
  integrationExamples/gpt/wurflRtdProvider_example.html
  integrationExamples/top-level-paapi/gam-contextual.html
Labels: maintenance

#13180 Nexx360 Bid Adapter - Aliases added
  modules/nexx360BidAdapter.js
  test/spec/modules/nexx360BidAdapter_spec.js
Labels: maintenance

#13160 Core: remove find polyfills
  modules/adkernelBidAdapter.js
  modules/adlooxAnalyticsAdapter.js
  modules/admixerBidAdapter.js
  modules/adotBidAdapter.js
  modules/adpod.js
  modules/adrelevantisBidAdapter.js
  modules/adtargetBidAdapter.js
  modules/adtelligentBidAdapter.js
  modules/adyoulikeBidAdapter.js
  modules/appnexusBidAdapter.js
  modules/beachfrontBidAdapter.js
  modules/bidViewability.js
  modules/bridgewellBidAdapter.js
  modules/cadentApertureMXBidAdapter.js
  modules/craftBidAdapter.js
  modules/dailyhuntBidAdapter.js
  modules/glomexBidAdapter.js
  modules/gptPreAuction.js
  modules/hybridBidAdapter.js
  modules/insticatorBidAdapter.js
  modules/ixBidAdapter.js
  modules/jwplayerRtdProvider.js
  modules/livewrappedBidAdapter.js
  modules/mediafuseBidAdapter.js
  modules/mediakeysBidAdapter.js
  modules/microadBidAdapter.js
  modules/nextrollBidAdapter.js
  modules/onetagBidAdapter.js
  modules/pixfutureBidAdapter.js
  modules/priceFloors.js
  modules/quantcastBidAdapter.js
  modules/reconciliationRtdProvider.js
  modules/relevadRtdProvider.js
  modules/rtdModule/index.js
  modules/s2sTesting.js
  modules/sirdataRtdProvider.js
  modules/smaatoBidAdapter.js
  modules/smarticoBidAdapter.js
  modules/stroeerCoreBidAdapter.js
  modules/userId/index.js
  modules/ventesBidAdapter.js
  modules/videoModule/index.js
  modules/videoModule/videoImpressionVerifier.js
  modules/viewdeosDXBidAdapter.js
  modules/viouslyBidAdapter.js
  modules/voxBidAdapter.js
  modules/waardexBidAdapter.js
  modules/widespaceBidAdapter.js
  modules/winrBidAdapter.js
  modules/yieldlabBidAdapter.js
  modules/yieldmoBidAdapter.js
Labels: maintenance

#13184 Adspirit Bid Adapter : lint fix
  test/spec/modules/adspiritBidAdapter_spec.js
Labels: maintenance

#13178 CWire Bid Adapter: update get user sync function url with gdpr consent
  modules/cwireBidAdapter.js
  test/spec/modules/cwireBidAdapter_spec.js
Labels: maintenance

#13104 Dvgroup bid adapter: added ssid
  modules/dvgroupBidAdapter.js
  modules/dvgroupBidAdapter.md
  test/spec/modules/dvgroupBidAdapter_spec.js
Labels: maintenance

#13138 Various modules: reuse viewport utilities
  modules/concertBidAdapter.js
  modules/cwireBidAdapter.js
  modules/h12mediaBidAdapter.js
  modules/nexx360BidAdapter.js
  modules/seedtagBidAdapter.js
  modules/undertoneBidAdapter.js
  test/spec/modules/cwireBidAdapter_spec.js
  test/spec/modules/nexx360BidAdapter_spec.js
  test/spec/modules/undertoneBidAdapter_spec.js
Labels: maintenance

#13187 Various Adapters : apply failsafe logic to remaining integration examples (Jules Bot)
  integrationExamples/gpt/afpGamExample.html
  integrationExamples/gpt/prebidServer_example.html
  integrationExamples/gpt/prebidServer_native_example.html
  integrationExamples/gpt/pubxaiRtdProvider_example.html
Labels: do not merge, maintenance

#13189 Docs: pubxaiRtdProvider example refactor
  integrationExamples/gpt/pubxaiRtdProvider_example.html
Labels: maintenance

#13135 ELM Module: decrease module invocations in test
  modules/enrichmentLiftMeasurement/index.js
  test/spec/modules/enrichmentLiftMeasurement_spec.js
Labels: maintenance

#13202 Distroscale Bid Adapter: remove reference to bidderRequest.{}.userId
  modules/distroscaleBidAdapter.js
Labels: maintenance

#13048 Start.io Bid Adapter : initial release
  modules/startioBidAdapter.js
  modules/startioBidAdapter.md
  test/spec/modules/startioBidAdapter_spec.js
Labels: feature

#13206 Relaido Bid Adapter: remove use of bidRequest.{}.userid
  modules/relaidoBidAdapter.js
  test/spec/modules/relaidoBidAdapter_spec.js
Labels: maintenance

#13190 Adnuntius Bid Adapter: send through eids always to adserver
  modules/adnuntiusBidAdapter.js
  test/spec/modules/adnuntiusBidAdapter_spec.js
Labels: maintenance

#13186 Adrelevantis, winr, pixfuture bid adapters: refactor common code into libraries
  libraries/adrelevantisUtils/bidderUtils.js
  modules/adrelevantisBidAdapter.js
  modules/pixfutureBidAdapter.js
  modules/ventesBidAdapter.js
  modules/winrBidAdapter.js
Labels: maintenance

#13209 Cwire Bid Adapter: refine user sync url
  modules/cwireBidAdapter.js
  test/spec/modules/cwireBidAdapter_spec.js
Labels: maintenance

#13047 EX.CO Adapter: viewability measurement, sync, bid won and timeout pixels support
  modules/excoBidAdapter.js
  test/spec/modules/excoBidAdapter_spec.js
Labels: maintenance

#13212 Gulp: consolidate gulp run command into gulp shell
  gulpfile.js
  package-lock.json
  package.json
Labels: maintenance

#13217 Adnuntius Bid Adapter: Better test failure messages
  test/spec/modules/adnuntiusBidAdapter_spec.js
Labels: bugfix

#13218 auction.js : getPrimaryCatId must return a string or the first value of the array
  src/auction.js
Labels: bugfix

#13197 UID1 Eids: support inserter and matcher
  libraries/liveIntentId/shared.js
  modules/unifiedIdSystem.js
  modules/userId/eids.js
  test/spec/modules/liveIntentIdSystem_spec.js
  test/spec/modules/unifiedIdSystem_spec.js
Labels: maintenance

#13220 PubMatic Bid Adapter : get benefits from previous auction info module
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: maintenance

#13233 Aduntius Bid Adapter : test failures on safari 15.6
  test/spec/modules/adnuntiusBidAdapter_spec.js
Labels: maintenance

#13239 Pubmatic Bid Adapter : prev auction info
  modules/pubmaticBidAdapter.js
  test/spec/modules/pubmaticBidAdapter_spec.js
Labels: maintenance
